### ISSUE TITLE
Git Pull this morning blew me out of the water...

### ISSUE THREAD

**Issue by KnobleSavage** [invoke-ai/InvokeAI#1072]
So I've been running the lstein fork almost from the beginning.  I frequently do a git pull and enjoy the benefits of continued upgrades.... until this morning which totally blew me up.  I made a post about this in the disccusions forum, which was probably the wrong place.  Apologies. [Link To that Post](https://github.com/invoke-ai/InvokeAI/discussions/1069)

So now I'm trying to follow the install instructions and not having any luck.  Here's where I am:

```(base) C:\WINDOWS\system32>cd\

(base) C:\>git clone https://github.com/invoke-ai/InvokeAI.git
Cloning into 'InvokeAI'...
remote: Enumerating objects: 9061, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 9061 (delta 15), reused 35 (delta 15), pack-reused 9023
Receiving objects: 100% (9061/9061), 80.83 MiB | 13.03 MiB/s, done.
Resolving deltas: 100% (5666/5666), done.

(base) C:\>cd InvokeAI

(base) C:\InvokeAI>conda env create

CondaValueError: prefix already exists: C:\Users\thepe\anaconda3\envs\invokeai


(base) C:\InvokeAI>conda activate invokeai

(invokeai) C:\InvokeAI>python scripts\preload_models.py
Traceback (most recent call last):
  File "C:\InvokeAI\scripts\preload_models.py", line 6, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
ModuleNotFoundError: No module named 'transformers'

(invokeai) C:\InvokeAI>`
(base) C:\WINDOWS\system32>cd\

(base) C:\>git clone https://github.com/invoke-ai/InvokeAI.git
Cloning into 'InvokeAI'...
remote: Enumerating objects: 9061, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 9061 (delta 15), reused 35 (delta 15), pack-reused 9023
Receiving objects: 100% (9061/9061), 80.83 MiB | 13.03 MiB/s, done.
Resolving deltas: 100% (5666/5666), done.

(base) C:\>cd InvokeAI

(base) C:\InvokeAI>conda env create

CondaValueError: prefix already exists: C:\Users\thepe\anaconda3\envs\invokeai


(base) C:\InvokeAI>conda activate invokeai

(invokeai) C:\InvokeAI>python scripts\preload_models.py
Traceback (most recent call last):
  File "C:\InvokeAI\scripts\preload_models.py", line 6, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
ModuleNotFoundError: No module named 'transformers'

(invokeai) C:\InvokeAI>

```

**Describe your environment**
- GPU: [cuda/amd/mps/cpu] NVidia GeForce RTX 2070 Super
- VRAM: [if known] 8g
- CPU arch: [x86/arm] 
- OS: [Linux/Windows/macOS] Windows
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)] anaconda
- Branch: [if `git status` says anything other than "On branch main" paste it here]
- Commit: [run `git show` and paste the line that starts with "Merge" here]
(invokeai) C:\InvokeAI>git show
commit ca6385e6fa3e2b53239bc68f19762ce566b60de6 (HEAD -> main, origin/main, origin/HEAD)
Author: mauwii <Mauwii@outlook.de>
Date:   Tue Oct 11 22:39:35 2022 +0200

    fix TEXTUAL_INVERSION.md emoji

diff --git a/docs/features/TEXTUAL_INVERSION.md b/docs/features/TEXTUAL_INVERSION.md
index 180ae6b..7ce0f41 100644
--- a/docs/features/TEXTUAL_INVERSION.md
+++ b/docs/features/TEXTUAL_INVERSION.md
@@ -1,8 +1,8 @@
 ---
-title: Textual Inversion
+title: Textual-Inversion
 ---

-# :material-file-document-plus-outline: Textual Inversion
+# :material-file-document: Textual Inversion

 ## **Personalizing Text-to-Image Generation**

**Describe the bug**
Can't seem to install this latest version.  (See above)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by KnobleSavage** [comment]
Okay, I think I'm running okay again.  I had to issue the following three commands manually.  The only way I knew to do this was by simply reading the error messages as they came up.  This was sort of frustrating and I'll now be sort of scared to do git pull in the future.
`
pip install eventlet
pip install flask
pip install flask_socketio
`
