### ISSUE TITLE
legacy_api.py fails on requests

### ISSUE THREAD

**Issue by ArtemKo7v** [invoke-ai/InvokeAI#1087]
legacy_api.py --web starts normally, but fails on request:

```
(invokeai) user@server:~/sd$ python3 scripts/legacy_api.py --web --port 9000
* Initializing, be patient...

>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using faster float16 precision
>> Model loaded in 14.10s
>> Max VRAM used to load the model: 2.17G
>> Current VRAM usage:2.17G
>> Setting Sampler to k_lms

* Initialization done! Awaiting your command (-h for help, 'q' to quit)

* --web was specified, starting web server...
>> Started Stable Diffusion dream server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9000.
127.0.0.1 - - [13/Oct/2022 16:24:51] "GET / HTTP/1.0" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 43354)
Traceback (most recent call last):
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/http/server.py", line 425, in handle
    self.handle_one_request()
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/http/server.py", line 413, in handle_one_request
    method()
  File "/home/gfx/sd/ldm/invoke/server_legacy.py", line 74, in do_GET
    from ldm.gfpgan.gfpgan_tools import gfpgan_model_exists
ModuleNotFoundError: No module named 'ldm.gfpgan'
```

**Comment by lstein** [comment]
Hey, @CapableWeb here's a bug report regarding the legacy API...

**Comment by CapableWeb** [comment]
I think I know what's happening and seems relatively easy to fix.

@ArtemKo7v  But before I confirm any fixes, could you share the request you're making as a cURL command? For reproducibility.

**Comment by ArtemKo7v** [comment]
> But before I confirm any fixes, could you share the request you're making as a cURL command? For reproducibility.

The exception was firing when I opened web interface in browser.
For some reason, I can't reproduce the issue anymore (maybe because I updated from git, I dunno).
Web interface still broken, but another exception on backend:
```
Exception occurred during processing of request from ('127.0.0.1', 59708)
Traceback (most recent call last):
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/http/server.py", line 425, in handle
    self.handle_one_request()
  File "/home/gfx/anaconda3/envs/invokeai/lib/python3.9/http/server.py", line 413, in handle_one_request
    method()
  File "/home/gfx/sd/ldm/invoke/server_legacy.py", line 74, in do_GET
    from ldm.gfpgan.gfpgan_tools import gfpgan_model_exists
  File "/home/gfx/sd2/ldm/gfpgan/gfpgan_tools.py", line 8, in <module>
    from scripts.dream import create_argv_parser
ImportError: cannot import name 'create_argv_parser' from 'scripts.dream' (/home/gfx/sd/scripts/dream.py)
```
But API calls are now working, so I'm fine with it.

**Comment by lstein** [comment]
Ok. Feel free to open a new issue when the problem recurs.
