### ISSUE TITLE
Can't load embedding model on MacBookPro(Intel CPU+ eGPU)

### ISSUE THREAD

**Issue by FreeBlues** [invoke-ai/InvokeAI#1157]
**Describe your environment**
- GPU: [cuda/amd/mps/cpu] eGPU( Radeon RX6600 XT)
- VRAM: [if known] 8G
- CPU arch: [x86/arm] x86
- OS: [Linux/Windows/macOS] macOS Monterey 12.6
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)] miniconda
- Branch: [if `git status` says anything other than "On branch main" paste it here]
```
 (base) ppt@pptdeMacBook-Pro InvokeAI % git status                                
On branch main
Your branch is up to date with 'origin/main'.
- Commit: [run `git show` and paste the line that starts with "Merge" here]
```

**Describe the bug**
I tried to use a .bin file form [lofa](https://huggingface.co/sd-concepts-library/lofa) as the embedding model, use the command `python scripts/invoke.py --embedding_path embedding/lofa/learned_embeds.bin` to load it, but return error.

The code(ldm/generate.py line:724) is below:
```
        seed_everything(random.randrange(0, np.iinfo(np.uint32).max))
        if self.embedding_path is not None:
            model.embedding_manager.load(
                self.embedding_path, self.precision == 'float32' or self.precision == 'autocast'
            )
```

I thought maybe it should be `self.modell.embedding_manager.load`, so I modified it, and run it, then got the 2nd error.

**Additional context**

### the 1st error log

```
(ldm) ppt@pptdeMacBook-Pro InvokeAI % python scripts/invoke.py --embedding_path embedding/lofa/learned_embeds.bin
* Initializing, be patient...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type mps
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
>> Model loaded in 14.36s
Traceback (most recent call last):
  File "/Users/ppt/Github/InvokeAI/scripts/invoke.py", line 708, in <module>
    main()
  File "/Users/ppt/Github/InvokeAI/scripts/invoke.py", line 86, in main
    gen.load_model()
  File "/Users/ppt/Github/InvokeAI/ldm/generate.py", line 699, in load_model
    self.set_model(self.model_name)
  File "/Users/ppt/Github/InvokeAI/ldm/generate.py", line 724, in set_model
    model.embedding_manager.load(
NameError: name 'model' is not defined
(ldm) ppt@pptdeMacBook-Pro InvokeAI %
```

### the 2nd error log

```
(ldm) ppt@pptdeMacBook-Pro InvokeAI % python scripts/invoke.py --embedding_path embedding/lofa/learned_embeds.bin
* Initializing, be patient...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type mps
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
>> Model loaded in 14.49s
Traceback (most recent call last):
  File "/Users/ppt/Github/InvokeAI/scripts/invoke.py", line 708, in <module>
    main()
  File "/Users/ppt/Github/InvokeAI/scripts/invoke.py", line 86, in main
    gen.load_model()
  File "/Users/ppt/Github/InvokeAI/ldm/generate.py", line 699, in load_model
    self.set_model(self.model_name)
  File "/Users/ppt/Github/InvokeAI/ldm/generate.py", line 724, in set_model
    self.model.embedding_manager.load(
  File "/Users/ppt/Github/InvokeAI/ldm/modules/embedding_manager.py", line 227, in load
    ckpt = torch.load(ckpt_path, map_location='cpu')
  File "/Users/ppt/miniconda/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/ppt/miniconda/envs/ldm/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
(ldm) ppt@pptdeMacBook-Pro InvokeAI % 
```

**Comment by skurovec** [comment]
first error was fixed in https://github.com/invoke-ai/InvokeAI/pull/1164

second could be https://github.com/invoke-ai/InvokeAI/issues/887

**Comment by FreeBlues** [comment]
@skurovec Thanks for the info! I got the reason: The huggingface repo is using LFS format to store the .bin model file, we need to install the git-lfs first, otherwise we will get the below clone(not correct):

```
(base) ppt@pptdeMacBook-Pro lofa % ls -al
total 40
drwxr-xr-x   9 ppt  staff   288 10 19 03:16 .
drwxr-xr-x   3 ppt  staff    96 10 19 03:16 ..
drwxr-xr-x  12 ppt  staff   384 10 19 03:16 .git
-rw-r--r--   1 ppt  staff  1384 10 19 03:16 .gitattributes
-rw-r--r--   1 ppt  staff  1087 10 19 03:16 README.md
drwxr-xr-x   7 ppt  staff   224 10 19 03:16 concept_images
-rw-r--r--   1 ppt  staff   129 10 19 03:16 learned_embeds.bin
-rw-r--r--   1 ppt  staff     6 10 19 03:16 token_identifier.txt
-rw-r--r--   1 ppt  staff     6 10 19 03:16 type_of_concept.txt
(base) ppt@pptdeMacBook-Pro lofa % 
```

We can see the .bin file `learned_embeds.bin` only 139 bytes.

So, we need to install the git-lfs in macOS first, here is the steps:

```
brew install git-lfs
git lfs install
git clone https://huggingface.co/sd-concepts-library/lofa
```

Now the .bin file `learned_embeds.bin` is 3819( I don't know if it is correct, but now the file can be loaded!)

All the logs:

-    Install git-lfs, clone lofa

```
(ldm) ppt@pptdeMacBook-Pro lofa % brew install git-lfs
fatal: not in a git directory
Warning: No remote 'origin' in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/git-lfs-3.2.0.monterey.bottle.tar.gz
######################################################################## 100.0%
==> Pouring git-lfs-3.2.0.monterey.bottle.tar.gz
==> Caveats
Update your git config to finish installation:

  # Update global git config
  $ git lfs install

  # Update system git config
  $ git lfs install --system
==> Summary
🍺  /usr/local/Cellar/git-lfs/3.2.0: 3 files, 11.2MB
==> Running `brew cleanup git-lfs`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
(ldm) ppt@pptdeMacBook-Pro lofa % git lfs install
Updated Git hooks.
Git LFS initialized.
(ldm) ppt@pptdeMacBook-Pro lofa % git lfs install --system
warning: current user is not root/admin, system install is likely to fail.
warning: error running /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git 'config' '--includes' '--system' '--replace-all' 'filter.lfs.clean' 'git-lfs clean -- %f': 'error: could not lock config file /etc/gitconfig: Permission denied' 'exit status 255'
Run `git lfs install --force` to reset Git configuration.
(ldm) ppt@pptdeMacBook-Pro lofa % cd ..
(ldm) ppt@pptdeMacBook-Pro embedding % rm -rf lofa
(ldm) ppt@pptdeMacBook-Pro embedding % git clone https://huggingface.co/sd-concepts-library/lofa
Cloning into 'lofa'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 17 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), 145.18 KiB | 62.00 KiB/s, done.
(ldm) ppt@pptdeMacBook-Pro embedding % cd lofa
(ldm) ppt@pptdeMacBook-Pro lofa % ls -al
total 40
drwxr-xr-x   9 ppt  staff   288 10 19 22:13 .
drwxr-xr-x   3 ppt  staff    96 10 19 22:13 ..
drwxr-xr-x  13 ppt  staff   416 10 19 22:13 .git
-rw-r--r--   1 ppt  staff  1384 10 19 22:13 .gitattributes
-rw-r--r--   1 ppt  staff  1087 10 19 22:13 README.md
drwxr-xr-x   7 ppt  staff   224 10 19 22:13 concept_images
-rw-r--r--   1 ppt  staff  3819 10 19 22:13 learned_embeds.bin
-rw-r--r--   1 ppt  staff     6 10 19 22:13 token_identifier.txt
-rw-r--r--   1 ppt  staff     6 10 19 22:13 type_of_concept.txt
(ldm) ppt@pptdeMacBook-Pro lofa % 
```

-    Load the .bin file to InvokeAI:
    -    Command line only:

```
(ldm) ppt@pptdeMacBook-Pro InvokeAI % python scripts/invoke.py --embedding_path embedding/lofa/learned_embeds.bin
* Initializing, be patient...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type mps
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
>> Model loaded in 16.51s
Added terms: *, <lofa>
>> Setting Sampler to k_lms

* Initialization done! Awaiting your command (-h for help, 'q' to quit)
invoke> q
goodbye!
```

    -Webui:

```
(ldm) ppt@pptdeMacBook-Pro InvokeAI % python scripts/invoke.py --web --host 0.0.0.0 --embedding_path embedding/lofa/learned_embeds.bin
* Initializing, be patient...
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type mps
>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
>> Model loaded in 14.75s
Added terms: *, <lofa>
>> Setting Sampler to k_lms

* --web was specified, starting web server...
>> Started Invoke AI Web Server!
Point your browser at http://localhost:9090 or use the host's DNS name or IP address.
```

-    Generate with the embedding model(I need to confirm if the prompt is using correct)

```
>> Image generation requested: {'prompt': 'a photo of lofa', 'iterations': 3, 'steps': 20, 'cfg_scale': 12, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'ddim', 'seed': 826354115, 'seamless': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
>> Setting Sampler to ddim
/Users/ppt/Github/InvokeAI/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/miniforge3/conda-bld/pytorch-recipe_1660136156773/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:26<00:00,  4.34s/it]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001128.826354115.png"████████████████████████| 20/20 [01:26<00:00,  4.78s/it]
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:31<00:00,  4.56s/it]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001129.4064272353.png"███████████████████████| 20/20 [01:31<00:00,  4.85s/it]
DDIMSampler: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [01:35<00:00,  4.78s/it]
>> Image generated: "/Users/ppt/Github/InvokeAI/outputs/img-samples/001130.4199904679.png"███████████████████████| 20/20 [01:35<00:00,  4.84s/it]
Generating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [04:36<00:00, 92.13s/it]
>> Usage stats:
>>   3 image(s) generated in 277.72s
```
