### ISSUE TITLE
after textual inversion and using new learn embeddings.pt Ive got error

### ISSUE THREAD

**Issue by wasyleque** [invoke-ai/InvokeAI#1215]
python3 ./scripts/invoke.py --embedding_path logs/something2022-10-21T17-33-30_something/checkpoints/embeddings.pt

>> Loading stable-diffusion-1.4 from models/ldm/stable-diffusion-v1/model.ckpt
** model stable-diffusion-1.4 could not be loaded: [Errno 2] No such file or directory: 'models/ldm/stable-diffusion-v1/model.ckpt'
** restoring None
** "None" is not a known model name. Please check your models.yaml file
** Model switch failed **
Traceback (most recent call last):
  File "/home/piotr/Documents/v2/InvokeAI/./scripts/invoke.py", line 708, in <module>
    main()
  File "/home/piotr/Documents/v2/InvokeAI/./scripts/invoke.py", line 99, in main
    main_loop(gen, opt, infile)
  File "/home/piotr/Documents/v2/InvokeAI/./scripts/invoke.py", line 303, in main_loop
    gen.prompt2image(
  File "/home/piotr/Documents/InvokeAI/ldm/generate.py", line 351, in prompt2image
    for m in model.modules():
AttributeError: 'NoneType' object has no attribute 'modules'

**Comment by ngundotra** [comment]
@wasyleque what was the fix?

**Comment by ngundotra** [comment]
For me I had failed to properly symlink my model.

This helped me debug: https://stackoverflow.com/questions/37214892/python-cant-open-symlinked-file
