### ISSUE TITLE
Safety checker error

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#1277]
I'd appreciate if someone could check if they can repro this issue.
` miranda kerr nude`
```
>> Ksampler using model noise schedule (steps > 29)
>> Sampling with k_lms starting at step 0 of 50 (50 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:27<00:00,  1.84it/s]
Generating:   0%|                                        
Traceback (most recent call last):
  File "/Users/me/Downloads/stable-diffusion/ldm/generate.py", line 455, in prompt2image
    results = generator.generate(
  File "/Users/me/Downloads/stable-diffusion/ldm/invoke/generator/base.py", line 93, in generate
    image = self.safety_check(image)
  File "/Users/me/Downloads/stable-diffusion/ldm/invoke/generator/base.py", line 206, in safety_check
    checked_image, has_nsfw_concept = checker(images=x_image, clip_input=features.pixel_values)
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/safety_checker.py", line 38, in forward
    pooled_output = self.vision_model(clip_input)[1]  # pooled_output
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 840, in forward
    return self.vision_model(
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 771, in forward
    hidden_states = self.embeddings(pixel_values)
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/opt/anaconda3/envs/do_not_touch-osx-arm64-stable-diffusion/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 137, in forward
    embeddings = torch.cat([class_embeds, patch_embeds], dim=1)
RuntimeError: torch.cat(): all input tensors must be on the same device. Received mps:0 and cpu
```

**Comment by insanityfarm** [comment]
I'm reproing it. If I run Invoke with the `--safety_checker` flag I get this error for _every_ gen, regardless of prompt. Doesn't seem to be caused by NSFW content, it's just broken for everything.

**Comment by lstein** [comment]
I'll find and fix that bug today.

**Comment by lstein** [comment]
Could you try applying this patch to `ldm/generate.py`?

```
diff --git a/ldm/generate.py b/ldm/generate.py
index 6c45c02..cd54581 100644
--- a/ldm/generate.py
+++ b/ldm/generate.py
@@ -217,6 +217,7 @@ class Generate:
                 safety_model_id = "CompVis/stable-diffusion-safety-checker"
                 self.safety_checker = StableDiffusionSafetyChecker.from_pretrained(safety_model_id, local_files_only=True)
                 self.safety_feature_extractor = AutoFeatureExtractor.from_pretrained(safety_model_id, local_files_only=True)
+                self.safety_feature_extractor.to(self.device)
             except Exception:
                 print('** An error was encountered while installing the safety checker:')
                 print(traceback.format_exc())
```

**Comment by Any-Winter-4079** [comment]
AttributeError: 'CLIPFeatureExtractor' object has no attribute 'to'

**Comment by lstein** [comment]
That's weird. The same line works fine on a CUDA system.

**Comment by lstein** [comment]
Remove the previous patch and try this one:
```
diff --git a/ldm/invoke/generator/base.py b/ldm/invoke/generator/base.py
index 77b92d6..0a27485 100644
--- a/ldm/invoke/generator/base.py
+++ b/ldm/invoke/generator/base.py
@@ -114,6 +114,10 @@ class Generator():
         x_sample = 255.0 * rearrange(
             x_samples[0].cpu().numpy(), 'c h w -> h w c'
         )
+
+        if self.safety_checker is not None:
+            self.safety_checker['last_image'] = x_sample
+            
         return Image.fromarray(x_sample.astype(np.uint8))
 
     def generate_initial_noise(self, seed, width, height):
@@ -196,11 +200,13 @@ class Generator():
 
         checker = self.safety_checker['checker']
         extractor = self.safety_checker['extractor']
-        features = extractor([image], return_tensors="pt")
-
+        last_image = self.safety_checker['last_image']
+        features = extractor(self.numpy_to_pil(last_image), return_tensors="pt")
+        x_image  = last_image
+        # features = extractor([image], return_tensors="pt")
         # unfortunately checker requires the numpy version, so we have to convert back
-        x_image = np.array(image).astype(np.float32) / 255.0
-        x_image = x_image[None].transpose(0, 3, 1, 2)
+        # x_image = np.array(image).astype(np.float32) / 255.0
+        # x_image = x_image[None].transpose(0, 3, 1, 2)
 
         diffusers.logging.set_verbosity_error()
         checked_image, has_nsfw_concept = checker(images=x_image, clip_input=features.pixel_values)
@@ -220,6 +226,17 @@ class Generator():
             pass
         return blurry
 
+    def numpy_to_pil(self,images:list):
+        """
+        Convert a numpy image or a batch of images to a PIL image.
+        """
+        if images.ndim == 3:
+            images = images[None, ...]
+        images = (images * 255).round().astype("uint8")
+        pil_images = [Image.fromarray(image) for image in images]
+
+        return pil_images
+
     # this is a handy routine for debugging use. Given a generated sample,
     # convert it into a PNG image and store it at the indicated path
     def save_sample(self, sample, filepath):

```

**Comment by Any-Winter-4079** [comment]
Hmm, same error.
I found `features.pixel_values` is on cpu (`print(features.pixel_values.device)`).
I'll try to find what is on mps.

**Comment by Any-Winter-4079** [comment]
Okay, I think the issue has been found.
```
checker.to('mps')
features.to('mps')
```
runs.

**Comment by Any-Winter-4079** [comment]
Although this is not unsafe
<img width="218" alt="Screenshot 2022-10-30 at 17 53 02" src="https://user-images.githubusercontent.com/50542132/198891022-ec63dc29-a10a-47c4-9c72-70a4bab82c11.png">

**Comment by lstein** [comment]
> 

Interesting. I previously tried `checker.to(self.model.device)` and `features.to(self.model.device)` and it caused exceptions on my CUDA machine. I'll try your solution

**Comment by lstein** [comment]
The following did not trigger the filter:
- windmill
- puppy
- river and moutains
The following did:
- sandra bullock nude

**Comment by Any-Winter-4079** [comment]
> Interesting. I previously tried checker.to(self.model.device) and features.to(self.model.device) and it caused exceptions on my CUDA machine. I'll try your solution

That's basically what I'm running, because `self.model.device` returns mps.

**Comment by lstein** [comment]
> Okay, I think the issue has been found. This would be a potential solution.
> 
> ```
> if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():
>     checker.to('mps')
>     features.to('mps')
> ```

I'd rather put this code into the place where the safety checker is initialized. Could you check if this works?

```
diff --git a/ldm/generate.py b/ldm/generate.py
index 6c45c02..43f4ab2 100644
--- a/ldm/generate.py
+++ b/ldm/generate.py
@@ -217,6 +217,9 @@ class Generate:
                 safety_model_id = "CompVis/stable-diffusion-safety-checker"
                 self.safety_checker = StableDiffusionSafetyChecker.from_pretrained(safety_model_id, local_files_only=True)
                 self.safety_feature_extractor = AutoFeatureExtractor.from_pretrained(safety_model_id, local_files_only=True)
+                if hasattr(torch.backends,'mps') and torch.backends.mps.is_availabile():
+                    self.safety_checker.to('mps')
+                    self.safety_feature_extractor.to('mps')
             except Exception:
                 print('** An error was encountered while installing the safety checker:')
                 print(traceback.format_exc())
```

**Comment by Any-Winter-4079** [comment]
No, I can't run it with self.
```
self.safety_checker.to('mps')
AttributeError: 'dict' object has no attribute 'to'
```

**Comment by Any-Winter-4079** [comment]
I also updated my dev branch.

**Comment by Any-Winter-4079** [comment]
But one thing I'll add, the filter doesn't work very well, e.g.
```
invoke> nature
>> Parsed prompt to FlattenedPrompt:[Fragment:'nature'@1.0]
Generating:   0%|                                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]>> Ksampler using model noise schedule (steps >= 30)
>> Sampling with k_lms starting at step 0 of 50 (50 new sampling steps)
100%|| 50/50 [00:27<00:00,  1.84it/s]
100%|| 50/50 [00:27<00:00,  1.87it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
```


But since sometimes it does work, I guess it's diffusers issue and not ours, though.

**Comment by Any-Winter-4079** [comment]
Okay, actually, I'm starting to think something is wrong.

**Comment by lstein** [comment]
That does seem excessive. Could you send me the prompts you used and I'll test from here?

**Comment by lstein** [comment]
> There is a typo `is_availabile` -> `is_available`. Fixing it I get:
> 
> ```
> self.safety_feature_extractor.to('mps')
> AttributeError: 'CLIPFeatureExtractor' object has no attribute 'to'
> ```
> 
> And eventually results in `Received mps:0 and cpu`

Yeah, I got the same AttributeError, which is why I thought this wouldn't work. I'll just go with your recipe, then.

**Comment by Any-Winter-4079** [comment]
Third time's a charm! That last solution does work!

**Comment by psychedelicious** [comment]
@lstein Did the fix make it into dev/main?
