### ISSUE TITLE
[bug]: bug Pytorch M1 Mac?

### ISSUE THREAD

**Issue by enzyme69** [invoke-ai/InvokeAI#1313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

Last night was my first time using InvokeAI, the interface is pretty sleek actually. Comparing it with WebUI which is a bit more techy. But I love both.

Anyways, I was testing different model, I am using "web" version of InvokeAI currently. I tried rendering 100 batch last night and getting few errors:

```
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000033.2756651360.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [06:16<00:00, 18.82s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000034.505673138.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:36<00:00, 16.84s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000035.2172538832.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:53<00:00, 17.69s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000036.1190997283.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:55<00:00, 17.78s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000037.354811650.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:22<00:00, 16.11s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000038.1790876031.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:51<00:00, 17.56s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000039.1363867037.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [06:06<00:00, 18.32s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000040.3546692084.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:20<00:00, 16.04s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000041.3239782626.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:23<00:00, 16.16s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000042.3463870009.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:49<00:00, 17.50s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000043.3549931962.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:37<00:00, 16.88s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000044.4206525246.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:21<00:00, 16.09s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000045.1392588635.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:54<00:00, 17.72s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000046.1324650350.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:47<00:00, 17.40s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000047.1124466880.png"
DDIMSampler: 100%|███████████████████████████████████| 20/20 [05:39<00:00, 16.97s/it]
>> Image generated: "/Users/blendersushi/Documents/InvokeAI/outputs/img-samples/000048.3117484370.png"
DDIMSampler:  45%|████████████████▏                   | 9/20 [02:54<03:33, 19.39s/it]
Generating:  40%|████████████                  | 40/100 [4:11:03<6:16:35, 376.59s/it]
Traceback (most recent call last):
  File "/Users/blendersushi/Documents/InvokeAI/ldm/generate.py", line 426, in prompt2image
    results = generator.generate(
  File "/Users/blendersushi/Documents/InvokeAI/ldm/invoke/generator/base.py", line 79, in generate
    image = make_image(x_T)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/invoke/generator/txt2img.py", line 37, in make_image
    samples, _ = sampler.sample(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/models/diffusion/sampler.py", line 174, in sample
    samples, intermediates = self.do_sampling(
  File "/Users/blendersushi/Documents/InvokeAI/ldm/models/diffusion/sampler.py", line 262, in do_sampling
    outs = self.p_sample(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/models/diffusion/ddim.py", line 45, in p_sample
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/models/diffusion/ddpm.py", line 1440, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/models/diffusion/ddpm.py", line 2148, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/modules/diffusionmodules/openaimodel.py", line 811, in forward
    h = module(h, emb, context)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/modules/diffusionmodules/openaimodel.py", line 88, in forward
    x = layer(x, context)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/modules/attention.py", line 314, in forward
    x = block(x, context=context)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/modules/attention.py", line 264, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/modules/diffusionmodules/util.py", line 158, in checkpoint
    return func(*inputs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/modules/attention.py", line 270, in _forward
    x += self.ff(self.norm3(x.clone()))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/modules/attention.py", line 65, in forward
    return self.net(x)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/invokeai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/Documents/InvokeAI/ldm/modules/attention.py", line 45, in forward
    return x * F.gelu(gate)
RuntimeError: current_allocated_size() >= m_low_watermark_limit INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666646703877/work/aten/src/ATen/mps/MPSAllocator.mm":389, please report a bug to PyTorch. 

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 15064.28s

```

### Additional context

I tested using custom waifu model.

### Contact Details

twitter jimmygunawanapp

**Comment by psychedelicious** [comment]
Hi @enzyme69 , apologies for the late response here. At the end of the error, it says it is a PyTorch error. Not sure we can do much here. Haven't seen this myself. Have you had further issues / are you willing to take this to PyTorch?
