### ISSUE TITLE
[bug]: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by eeeclipse** [invoke-ai/InvokeAI#1358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

TypeError: 'type' object is not subscriptable occured while training with new images.

```
$ python main.py \
--base ./configs/stable-diffusion/v1-finetune.yaml     \
-t     \
--actual_resume ./models/ldm/stable-diffusion-v1/sd-v1-4-full-ema.ckpt     \
-n my_key     \
--gpus 0     \
--data_root ./training_data/key_t1m1/


Global seed set to 23
Running on GPUs 0
Loading model from ./models/ldm/stable-diffusion-v1/sd-v1-4-full-ema.ckpt

Traceback (most recent call last):
  File "main.py", line 736, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main.py", line 52, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/stable/InvokeAI/ldm/util.py", line 90, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/stable/InvokeAI/ldm/util.py", line 100, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/home/stable/anaconda3/envs/stable-lab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/stable/InvokeAI/ldm/models/diffusion/ddpm.py", line 50, in <module>
    from ldm.models.diffusion.ddim import DDIMSampler
  File "/home/stable/InvokeAI/ldm/models/diffusion/ddim.py", line 4, in <module>
    from ldm.models.diffusion.shared_invokeai_diffusion import InvokeAIDiffuserComponent
  File "/home/stable/InvokeAI/ldm/models/diffusion/shared_invokeai_diffusion.py", line 6, in <module>
    from ldm.models.diffusion.cross_attention_control import CrossAttentionControl
  File "/home/stable/InvokeAI/ldm/models/diffusion/cross_attention_control.py", line 8, in <module>
    class CrossAttentionControl:
  File "/home/stable/InvokeAI/ldm/models/diffusion/cross_attention_control.py", line 10, in CrossAttentionControl
    class Arguments:
  File "/home/stable/InvokeAI/ldm/models/diffusion/cross_attention_control.py", line 11, in Arguments
    def __init__(self, edited_conditioning: torch.Tensor, edit_opcodes: list[tuple], edit_options: dict):
TypeError: 'type' object is not subscriptable
```

### Contact Details

eeeclipse.genesis@gmail.com

**Comment by lstein** [comment]
Thanks for the report. I’ll look into it.

**Comment by Mitchnoff** [comment]
Can Confirm I an getting the same error:

`(ldm) allenm@dh-dgx1-1:~/stablediffusion/InvokeAI$ python main.py --base ./configs/stable-diffusion/v1-finetune.yaml --actual_resume ./models/ldm/stable-diffusion-v1/model.ckpt -n MORDECAI --gpus 1, --data_root ../textual_inversion/DATA/mordecai/
Global seed set to 23
Running on GPUs 1,
Loading model from ./models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "main.py", line 735, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main.py", line 51, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/allenm/stablediffusion/InvokeAI/ldm/util.py", line 90, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/allenm/stablediffusion/InvokeAI/ldm/util.py", line 100, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/home/allenm/.conda/envs/ldm/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/allenm/stablediffusion/InvokeAI/ldm/models/diffusion/ddpm.py", line 40, in <module>
    from ldm.models.autoencoder import (
  File "/home/allenm/stablediffusion/InvokeAI/ldm/models/autoencoder.py", line 8, in <module>
    from ldm.modules.diffusionmodules.model import Encoder, Decoder
  File "/home/allenm/stablediffusion/InvokeAI/ldm/modules/diffusionmodules/model.py", line 11, in <module>
    from ldm.modules.attention import LinearAttention
  File "/home/allenm/stablediffusion/InvokeAI/ldm/modules/attention.py", line 167, in <module>
    class CrossAttention(nn.Module):
  File "/home/allenm/stablediffusion/InvokeAI/ldm/modules/attention.py", line 206, in CrossAttention
    def set_slicing_strategy_getter(self, getter: Optional[Callable[[nn.Module], tuple[int,int]]]):
TypeError: 'type' object is not subscriptable`
