### ISSUE TITLE
[bug]: ddim sampler not working in development branch with itterations set to 10

### ISSUE THREAD

**Issue by mauwii** [invoke-ai/InvokeAI#1398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

Stated the web interface (python scripts/invoke.py --web), wanted to create a picture with sampler set to ddim and 10 iterations, which resulted in this error:

```shell
(invokeai)  ~/git/mauwii/stable-diffusion   development  python scripts/invoke.py --web                   
* Initializing, be patient...
NOTE: Redirects are currently not supported in Windows or MacOs.
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type mps
>> Current VRAM usage:  0.00G
>> Loading stable-diffusion-1.5 from ./models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
   | Loading VAE weights from: ./models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
>> Model loaded in 13.28s
>> Setting Sampler to k_lms

* --web was specified, starting web server...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090
>> System config requested
>> System config requested
>> Image generation requested: {'prompt': 'gorgeous atompunk diner waitress, normaln rockwell, boris vallejo', 'iterations': 1, 'steps': 10, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'ddim', 'seed': 4180139166, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
>> Setting Sampler to ddim
>> Parsed prompt to FlattenedPrompt:[Fragment:'gorgeous atompunk diner waitress, normaln rockwell, boris vallejo'@1.0]
/Users/mauwii/git/mauwii/stable-diffusion/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484611838/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
DDIMSampler:   0%|                                                                                                                  | 0/10 [00:03<?, ?it/s]
Generating:   0%|                                                                                                                    | 0/1 [00:03<?, ?it/s]
index 9 is out of bounds for dimension 0 with size 9


Traceback (most recent call last):
  File "/Users/mauwii/git/mauwii/stable-diffusion/backend/invoke_ai_web_server.py", line 832, in generate_images
    self.generate.prompt2image(
  File "/Users/mauwii/git/mauwii/stable-diffusion/ldm/generate.py", line 467, in prompt2image
    results = generator.generate(
  File "/Users/mauwii/git/mauwii/stable-diffusion/ldm/invoke/generator/base.py", line 90, in generate
    image = make_image(x_T)
  File "/Users/mauwii/.pyenv/versions/miniconda3-latest/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/mauwii/git/mauwii/stable-diffusion/ldm/invoke/generator/txt2img.py", line 39, in make_image
    samples, _ = sampler.sample(
  File "/Users/mauwii/.pyenv/versions/miniconda3-latest/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/mauwii/git/mauwii/stable-diffusion/ldm/models/diffusion/sampler.py", line 188, in sample
    samples, intermediates = self.do_sampling(
  File "/Users/mauwii/.pyenv/versions/miniconda3-latest/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/mauwii/git/mauwii/stable-diffusion/ldm/models/diffusion/sampler.py", line 278, in do_sampling
    outs = self.p_sample(
  File "/Users/mauwii/.pyenv/versions/miniconda3-latest/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/mauwii/git/mauwii/stable-diffusion/ldm/models/diffusion/ddim.py", line 91, in p_sample
    a_t = torch.full((b, 1, 1, 1), alphas[index], device=device)
IndexError: index 9 is out of bounds for dimension 0 with size 9
```

### Additional context

when setting iterations >10 it is working

**Comment by mauwii** [comment]
ok, strange, not sure which number of iterations work and which don't...

11 iterations is working, 15 is working, 20 isn't 🙈

**Comment by lstein** [comment]
The PR which changed the ddim sampler has been backed out as of yesterday. Could you check that the problem is resolved?
