### ISSUE TITLE
[bug]: 2.1.3-rc5 pip-based install not functional on Amazon Deep Learning AMI (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ebr** [invoke-ai/InvokeAI#1447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What happened?

Both the web interface and CLI crash with `RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)` (full stack trace below). It seems there might be missing packages or incorrect versions.

### Environment:

- AWS Deep Learning AMI
- ubuntu20.04
- python 3.9.5 (NOTE: has to be installed separately; the AMI comes with 3.8.x)
- nvidia-headless-510-server
- nvidia-utils-510-server
- NVIDIA-SMI: 510.85.02 - Driver Version: 510.85.02 - CUDA Version: 11.6
- NVIDIA Tesla T4 (g4dn.xlarge instance)
- release-candidate-2-1-3 branch; followed manual install instructions for Linux.

### Stack trace

The error is identical whether running web UI or CLI. The application loads, but crashes when trying to generate.

<details>

```
 --web was specified, starting web server...
>> Initialization file /home/ubuntu/.invokeai not found. Applying default settings...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090
>> System config requested
>> Image generation requested: {'prompt': 'lemonade', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 
'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 2483636514, 'progress_images': False, 'progress_latents': True, 'save_inter
mediates': 5, 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
Traceback (most recent call last): 
  File "/home/ubuntu/InvokeAI/ldm/generate.py", line 437, in prompt2image
    uc, c, extra_conditioning_info = get_uc_and_c_and_ec(
  File "/home/ubuntu/InvokeAI/ldm/invoke/conditioning.py", line 129, in get_uc_and_c_and_ec
    conditioning, _ = build_embeddings_and_tokens_for_flattened_prompt(model,
  File "/home/ubuntu/InvokeAI/ldm/invoke/conditioning.py", line 163, in build_embeddings_and_tokens_for_flattened_prompt
    embeddings, tokens = model.get_learned_conditioning([fragments], return_tokens=True, fragment_weights=[weights])
  File "/home/ubuntu/InvokeAI/ldm/models/diffusion/ddpm.py", line 829, in get_learned_conditioning
    c = self.cond_stage_model.encode(
  File "/home/ubuntu/InvokeAI/ldm/modules/encoders/modules.py", line 457, in encode
    return self(text, **kwargs)
  File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/InvokeAI/ldm/modules/encoders/modules.py", line 503, in forward
    base_embedding = self.build_weighted_embedding_tensor(tokens, per_token_weights, **kwargs)
  File "/home/ubuntu/InvokeAI/ldm/modules/encoders/modules.py", line 645, in build_weighted_embedding_tensor
    z = self.transformer(input_ids=tokens.unsqueeze(0), **kwargs)
  File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/InvokeAI/ldm/modules/encoders/modules.py", line 422, in transformer_forward
    return self.text_model(
  File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/InvokeAI/ldm/modules/encoders/modules.py", line 395, in text_encoder_forward
    last_hidden_state = self.encoder(
  File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/InvokeAI/ldm/modules/encoders/modules.py", line 322, in encoder_forward
    layer_outputs = encoder_layer( 
  File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 321, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 220, in forward
    attn_weights = torch.bmm(query_states, key_states.transpose(1, 2))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 48.94s
>>   Max VRAM used for this generation: 2.17G. Current VRAM utilization: 2.17G
>>   Max VRAM used since script start:  2.17G

```

</details>

Same prompt runs fine in a conda-managed environment (installed with `micromamba`)

### Additional context

1. Installing with `pip` produces errors. It eventually completes but it's likely this is related:

<details>

```
Building wheels for collected packages: test-tube, clip, k-diffusion, clipseg, basicsr, antlr4-python3-runtime, urwid, future, jsonmerge, filterpy, pathtools, promise
  Building wheel for test-tube (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/test-tube/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/test-tube/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-r9mlry36
       cwd: /tmp/pip-install-w34e4hil/test-tube/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for test-tube
  Running setup.py clean for test-tube
  Building wheel for clip (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/clip/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/clip/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6dom45me
       cwd: /tmp/pip-install-w34e4hil/clip/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for clip
  Running setup.py clean for clip
  Building wheel for k-diffusion (PEP 517) ... done
  Created wheel for k-diffusion: filename=k_diffusion-0.0.1-py3-none-any.whl size=24943 sha256=a386d385f7742e1bc3722c6e9c6ccf9cc4510f1248738f56b51d61fc6b510159
  Stored in directory: /tmp/pip-ephem-wheel-cache-59hfk4yp/wheels/ef/65/9d/fcfe32849129f2180acecbc336d580f9dbf429c19841ff01cc
  Building wheel for clipseg (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/clipseg/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/clipseg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mskjxtmk
       cwd: /tmp/pip-install-w34e4hil/clipseg/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for clipseg
  Running setup.py clean for clipseg
  Building wheel for basicsr (setup.py) ... done
  Created wheel for basicsr: filename=basicsr-1.4.2-py3-none-any.whl size=214830 sha256=728ec6079c2de169d4f3e8574343022e1a37e87e710c898c98f1a1aff662bbe5
  Stored in directory: /home/ubuntu/.cache/pip/wheels/42/d6/3d/6d8c4b8fabeb93dd442eb255f133e8928c75d903fe20e9472c
  Building wheel for antlr4-python3-runtime (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/antlr4-python3-runtime/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/antlr4-python3-runtime/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zrqj9mu4
       cwd: /tmp/pip-install-w34e4hil/antlr4-python3-runtime/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for antlr4-python3-runtime
  Running setup.py clean for antlr4-python3-runtime
  Building wheel for urwid (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/urwid/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/urwid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yzr5vqmo
       cwd: /tmp/pip-install-w34e4hil/urwid/
  Complete output (46 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.9/distutils/dist.py", line 539, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/setuptools/dist.py", line 837, in get_command_class
      return _Distribution.get_command_class(self, command)
    File "/usr/lib/python3.9/distutils/dist.py", line 843, in get_command_class
      raise DistutilsModuleError("invalid command '%s'" % command)
  distutils.errors.DistutilsModuleError: invalid command 'bdist_wheel'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib/python3.9/distutils/core.py", line 134, in setup
      ok = dist.parse_command_line()
    File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/setuptools/dist.py", line 707, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib/python3.9/distutils/dist.py", line 483, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/setuptools/dist.py", line 1014, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib/python3.9/distutils/dist.py", line 541, in _parse_command_opts
      raise DistutilsArgError(msg)
  distutils.errors.DistutilsArgError: invalid command 'bdist_wheel'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-w34e4hil/urwid/setup.py", line 82, in <module>
      setup(**setup_d)
    File "/home/ubuntu/InvokeAI/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 136, in setup
      raise SystemExit(gen_usage(dist.script_name) + "\nerror: %s" % msg)
  SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  Couldn't build the extension module, trying without it...
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for urwid
  Running setup.py clean for urwid
  Building wheel for future (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6cgonqt9
       cwd: /tmp/pip-install-w34e4hil/future/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for future
  Running setup.py clean for future
  Building wheel for jsonmerge (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/jsonmerge/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/jsonmerge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bi3qetj0
       cwd: /tmp/pip-install-w34e4hil/jsonmerge/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for jsonmerge
  Running setup.py clean for jsonmerge
  Building wheel for filterpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/filterpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/filterpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fga1j15h
       cwd: /tmp/pip-install-w34e4hil/filterpy/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for filterpy
  Running setup.py clean for filterpy
  Building wheel for pathtools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/pathtools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/pathtools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3ws8une6
       cwd: /tmp/pip-install-w34e4hil/pathtools/
  Complete output (8 lines):
  /tmp/pip-install-w34e4hil/pathtools/setup.py:25: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pathtools
  Running setup.py clean for pathtools
  Building wheel for promise (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/InvokeAI/.venv/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w34e4hil/promise/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w34e4hil/promise/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-171491vv
       cwd: /tmp/pip-install-w34e4hil/promise/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for promise
  Running setup.py clean for promise
Successfully built k-diffusion basicsr
Failed to build test-tube clip clipseg antlr4-python3-runtime urwid future jsonmerge filterpy pathtools promise
ERROR: clean-fid 0.1.34 has requirement requests==2.25.1, but you'll have requests 2.28.1 which is incompatible.

```
</details>

2. In the pip environment, `preload_models.py` does not seem to load CLIP models. The following is printed when using Conda, but NOT printed when using pip:

```
** DOWNLOADING SUPPORT MODELS **
......
Loading CLIP model (ignore deprecation errors)......success
/home/ubuntu/conda-env/envs/invokeai/lib/python3.10/site-packages/basicsr/metrics/niqe.py:5: DeprecationWarning: Please use `convolve` fr
om the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import convolve
Installing models from RealESRGAN and facexlib  (ignore deprecation errors)...Downloading: "https://github.com/xinntao/Real-ESRGAN/releas
es/download/v0.2.5.0/realesr-general-x4v3.pth" to /home/ubuntu/conda-env/envs/invokeai/lib/python3.10/site-packages/weights/realesr-gener
al-x4v3.pth
``` 

3. Package lists:

Conda:

<details>

```
List of packages in environment: "/home/ubuntu/conda-env/envs/invokeai"

  Name                Version    Build                         Channel
────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex       0.1        conda_forge                   conda-forge
  _openmp_mutex       4.5        2_gnu                         conda-forge
  blas                1.0        mkl                           conda-forge
  brotlipy            0.7.0      py310h5764c6d_1005            conda-forge
  bzip2               1.0.8      h7f98852_4                    conda-forge
  ca-certificates     2022.9.24  ha878542_0                    conda-forge
  certifi             2022.9.24  pyhd8ed1ab_0                  conda-forge
  cffi                1.15.1     py310h255011f_2               conda-forge
  charset-normalizer  2.1.1      pyhd8ed1ab_0                  conda-forge
  cryptography        38.0.3     py310h600f1e7_0               conda-forge
  cudatoolkit         11.6.0     hecad31d_10                   conda-forge
  ffmpeg              4.3        hf484d3e_0                    pytorch
  freetype            2.12.1     hca18f0e_0                    conda-forge
  gmp                 6.2.1      h58526e2_0                    conda-forge
  gnutls              3.6.13     h85f3911_1                    conda-forge
  idna                3.4        pyhd8ed1ab_0                  conda-forge
  intel-openmp        2022.1.0   h9e868ea_3769
  jpeg                9e         h166bdaf_2                    conda-forge
  lame                3.100      h166bdaf_1003                 conda-forge
  lcms2               2.14       h6ed2654_0                    conda-forge
  ld_impl_linux-64    2.39       hc81fddc_0                    conda-forge
  lerc                4.0.0      h27087fc_0                    conda-forge
  libblas             3.9.0      16_linux64_mkl                conda-forge
  libcblas            3.9.0      16_linux64_mkl                conda-forge
  libdeflate          1.14       h166bdaf_0                    conda-forge
  libffi              3.4.2      h7f98852_5                    conda-forge
  libgcc-ng           12.2.0     h65d4601_19                   conda-forge
  libgomp             12.2.0     h65d4601_19                   conda-forge
  libiconv            1.17       h166bdaf_0                    conda-forge
  liblapack           3.9.0      16_linux64_mkl                conda-forge
  libnsl              2.0.0      h7f98852_0                    conda-forge
  libpng              1.6.38     h753d276_0                    conda-forge
  libsqlite           3.39.4     h753d276_0                    conda-forge
  libstdcxx-ng        12.2.0     h46fd767_19                   conda-forge
  libtiff             4.4.0      h55922b4_4                    conda-forge
  libuuid             2.32.1     h7f98852_1000                 conda-forge
  libwebp-base        1.2.4      h166bdaf_0                    conda-forge
  libxcb              1.13       h7f98852_1004                 conda-forge
  libzlib             1.2.13     h166bdaf_4                    conda-forge
  mkl                 2022.1.0   hc2b9512_224
  ncurses             6.3        h27087fc_1                    conda-forge
  nettle              3.6        he412f7d_0                    conda-forge
  numpy               1.23.3     py310h53a5b5f_0               conda-forge
  openh264            2.1.1      h780b84a_0                    conda-forge
  openjpeg            2.5.0      h7d73246_1                    conda-forge
  openssl             3.0.7      h166bdaf_0                    conda-forge
  pillow              9.2.0      py310h454ad03_3               conda-forge
  pip                 22.2.2     pyhd8ed1ab_0                  conda-forge
  pthread-stubs       0.4        h36c2ea0_1001                 conda-forge
  pycparser           2.21       pyhd8ed1ab_0                  conda-forge
  pyopenssl           22.1.0     pyhd8ed1ab_0                  conda-forge
  pysocks             1.7.1      pyha2e5f31_6                  conda-forge
  python              3.10.6     ha86cf86_0_cpython            conda-forge
  python_abi          3.10       2_cp310                       conda-forge
  pytorch             1.12.1     py3.10_cuda11.6_cudnn8.3.2_0  pytorch
  pytorch-mutex       1.0        cuda                          pytorch
  readline            8.1.2      h0f457ee_0                    conda-forge
  requests            2.28.1     pyhd8ed1ab_1                  conda-forge
  setuptools          65.5.1     pyhd8ed1ab_0                  conda-forge
  tk                  8.6.12     h27826a3_0                    conda-forge
  torchaudio          0.12.1     py310_cu116                   pytorch
  torchvision         0.13.1     py310_cu116                   pytorch
  typing_extensions   4.4.0      pyha770c72_0                  conda-forge
  tzdata              2022f      h191b570_0                    conda-forge
  urllib3             1.26.11    pyhd8ed1ab_0                  conda-forge
  wheel               0.38.4     pyhd8ed1ab_0                  conda-forge
  xorg-libxau         1.0.9      h7f98852_0                    conda-forge
  xorg-libxdmcp       1.1.3      h7f98852_0                    conda-forge
  xz                  5.2.6      h166bdaf_0                    conda-forge
  zlib                1.2.13     h166bdaf_4                    conda-forge
  zstd                1.5.2      h6239696_4                    conda-forge

```

</details>

pip:

<details>

```
absl-py==1.3.0
accelerate==0.14.0
addict==2.4.0
aiohttp==3.8.3
aiosignal==1.3.1
albumentations==1.3.0
altair==4.2.0
antlr4-python3-runtime==4.9.3
async-timeout==4.0.2
attrs==22.1.0
basicsr==1.4.2
bidict==0.22.0
blinker==1.5
boltons==21.0.0
cachetools==5.2.0
certifi==2022.9.24
chardet==4.0.0
charset-normalizer==2.1.1
clean-fid==0.1.34
click==8.1.3
clip @ git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
clipseg @ git+https://github.com/invoke-ai/clipseg.git@1f754751c85d7d4255fa681f4491ff5711c1c288
commonmark==0.9.1
contourpy==1.0.6
cycler==0.11.0
decorator==5.1.1
dependency-injector==4.40.0
diffusers==0.7.2
dnspython==2.2.1
docker-pycreds==0.4.0
einops==0.6.0
entrypoints==0.4
eventlet==0.33.1
facexlib==0.2.5
filelock==3.8.0
filterpy==1.4.5
Flask==2.1.3
Flask-Cors==3.0.10
Flask-SocketIO==5.3.0
flaskwebgui==0.3.7
fonttools==4.38.0
frozenlist==1.3.3
fsspec==2022.11.0
ftfy==6.1.1
future==0.18.2
getpass-asterisk==1.0.1
gfpgan==1.3.8
gitdb==4.0.9
GitPython==3.1.29
google-auth==2.14.1
google-auth-oauthlib==0.4.6
greenlet==2.0.1
grpcio==1.50.0
huggingface-hub==0.10.1
idna==2.10
imageio==2.22.4
imageio-ffmpeg==0.4.7
importlib-metadata==5.0.0
-e git+https://github.com/invoke-ai/InvokeAI.git@201eb22d7650b00f55249c2646fa4f47ac3e0ec2#egg=invoke_ai
itsdangerous==2.1.2
Jinja2==3.1.2
joblib==1.2.0
jsonmerge==1.9.0
jsonschema==4.17.0
k-diffusion @ git+https://github.com/Birch-san/k-diffusion.git@9bfd658ba7190f6e1403d8c77f6c8e26a4a9a7dc
kiwisolver==1.4.4
kornia==0.6.8
llvmlite==0.39.1
lmdb==1.3.0
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
multidict==6.0.2
networkx==2.8.8
numba==0.56.4
numpy==1.23.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
omegaconf==2.2.3
opencv-python==4.6.0.66
opencv-python-headless==4.6.0.66
packaging==21.3
pandas==1.5.1
pathtools==0.1.2
Pillow==9.3.0
pkg_resources==0.0.0
promise==2.3
protobuf==3.20.3
psutil==5.9.4
pudb==2014.1
pyarrow==10.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydeck==0.8.0
pyDeprecate==0.3.2
Pygments==2.13.0
Pympler==1.0.1
pyparsing==3.0.9
pyreadline3==3.4.1
pyrsistent==0.19.2
python-dateutil==2.8.2
python-engineio==4.3.4
python-socketio==5.7.2
pytorch-lightning==1.7.7
pytz==2022.6
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.4.1
PyYAML==6.0
qudida==0.0.4
realesrgan==0.3.0
regex==2022.10.31
requests==2.25.1
requests-oauthlib==1.3.1
resize-right==0.0.2
rich==12.6.0
rsa==4.9
scikit-image==0.19.3
scikit-learn==1.1.3
scipy==1.9.3
semver==2.13.0
Send2Trash==1.8.0
sentry-sdk==1.10.1
setproctitle==1.3.2
shortuuid==1.0.10
six==1.16.0
smmap==5.0.0
streamlit==1.14.0
taming-transformers-rom1504==0.0.6
tb-nightly==2.12.0a20221110
tensorboard==2.11.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
test-tube==0.7.5
threadpoolctl==3.1.0
tifffile==2022.10.10
tokenizers==0.12.1
toml==0.10.2
toolz==0.12.0
torch==1.13.0
torch-fidelity==0.3.0
torchdiffeq==0.2.3
torchmetrics==0.10.2
torchsde==0.2.5
torchvision==0.14.0
tornado==6.2
tqdm==4.64.1
trampoline==0.1.2
transformers==4.21.3
typing_extensions==4.4.0
tzdata==2022.6
tzlocal==4.2
urllib3==1.26.12
urwid==2.1.2
validators==0.18.2
wandb==0.13.5
watchdog==2.1.9
wcwidth==0.2.5
Werkzeug==2.2.2
whichcraft==0.6.1
yapf==0.32.0
yarl==1.8.1
zipp==3.10.0
```

</details>

Since they are installed from different sources, it is hard to pinpoint true version discrepancies.

This is not a blocker for me at the moment and I haven't looked too deeply into it, but wanted to raise the issue in case anyone runs into this on AWS.

### Contact Details

discord: brodsky

**Comment by ebr** [comment]
no longer relevant as 2.1.3 was released and this edge case doesn't need attention
