### ISSUE TITLE
[bug]: Conflicting dependencies when installing

### ISSUE THREAD

**Issue by bamarillo** [invoke-ai/InvokeAI#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10GB

### What happened?

Just found this repo and wanted to download the dev version to start using it and contribute in the future but had a problem installing.

`ERROR: Cannot install -r D:\invokeAI\condaenv.y01kibl2.requirements.txt (line 20), basicsr==1.4.1 and realesrgan==0.3.0 because these package versions have conflicting dependencies.`

Tried doing the manual install and the Source code installer and both had the same error.

### Screenshots

![Captura de pantalla 2022-11-14 225304](https://user-images.githubusercontent.com/8331071/201807144-8054a585-5f2e-4e88-8b83-2e0fac6a3efe.png)

**Comment by djasil** [comment]
I'm also getting this error trying to install from the development branch:

````
Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\XXXXXXXXXX\AppData\Local\Temp\pip-install-fd9tyec4\clip_4826b07a35514ba1a32df6ef64aa667a'
  Running command git clone --filter=blob:none --quiet https://github.com/Birch-san/k-diffusion.git 'C:\Users\XXXXXXXXXX\AppData\Local\Temp\pip-install-fd9tyec4\k-diffusion_af91fc4ee50a4787b9d77b39af699fb8'
  Running command git clone --filter=blob:none --quiet https://github.com/invoke-ai/clipseg.git 'C:\Users\XXXXXXXXXX\AppData\Local\Temp\pip-install-fd9tyec4\clipseg_283eeb0654e94261ab6bad0102b14b41'
  Running command git checkout -b relaxed-python-requirement --track origin/relaxed-python-requirement
  branch 'relaxed-python-requirement' set up to track 'origin/relaxed-python-requirement'.
  Switched to a new branch 'relaxed-python-requirement'
  Running command git clone --filter=blob:none --quiet https://github.com/invoke-ai/GFPGAN 'C:\Users\XXXXXXXXXX\AppData\Local\Temp\pip-install-fd9tyec4\gfpgan_464b3330bd2a4a63829196439479b55d'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  ¦ exit code: 1
  ?-> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\XXXXXXXXXX\AppData\Local\Temp\pip-install-fd9tyec4\realesrgan_8a76d3c72e424d1fbd666825ddc45c8f\setup.py", line 48, in get_hash
          from facexlib.version import __version__
      ModuleNotFoundError: No module named 'facexlib'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\XXXXXXXXXX\AppData\Local\Temp\pip-install-fd9tyec4\realesrgan_8a76d3c72e424d1fbd666825ddc45c8f\setup.py", line 89, in <module>
          write_version_py()
        File "C:\Users\XXXXXXXXXX\AppData\Local\Temp\pip-install-fd9tyec4\realesrgan_8a76d3c72e424d1fbd666825ddc45c8f\setup.py", line 65, in write_version_py
          sha = get_hash()
        File "C:\Users\XXXXXXXXXX\AppData\Local\Temp\pip-install-fd9tyec4\realesrgan_8a76d3c72e424d1fbd666825ddc45c8f\setup.py", line 51, in get_hash
          raise ImportError('Unable to get git version')
      ImportError: Unable to get git version
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
?-> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
````

**Comment by dahifi** [comment]
Getting a different error on M1, there's no basicsr in that build. 

```
The conflict is caused by:
    realesrgan 0.3.0 depends on basicsr==1.4.1
    gfpgan 1.3.8 depends on basicsr>=1.4.2
```

**Comment by dahifi** [comment]
There's no basicsr in the env file for M1, and I couldn't figure out how to install it. 

PIP based installation seems to be fine.

**Comment by simplomat** [comment]
@dahifi I am running environment-mac.yml. A quick fix until the issue is resolved is pointing the sub repo for Real-ESRGAN to the original unmodified version. (invoke-ai is currently only one commit ahead which is downgrading the version requirement)

In the pip section in environment.yml replace:
`- pip:
      - git+https://github.com/invoke-ai/Real-ESRGAN.git#egg=realesrgan
`
with
`
- pip:
      - git+https://github.com/xinntao/Real-ESRGAN.git#egg=realesrgan
`

**Comment by lstein** [comment]
We are using the `invoke-ai` fork because of `basicsr` conflicts with Windows. I have proposed a different fix in the `invoke-ai` fork of GFPGAN. If you don't mind, could you try running any of the installation methods again? The fix should apply automatically.

**Comment by bamarillo** [comment]
I pulled the repo and made the manual installation with conda and everything looked ok. Now, when I try to run the webui I get this:
```
* Initializing, be patient...
>> Initialization file C:\Users\bruno/.invokeai not found. Applying default settings...
Traceback (most recent call last):
  File "D:\invokeAI\scripts\invoke.py", line 933, in <module>
    main()
  File "D:\invokeAI\scripts\invoke.py", line 49, in main
    from ldm.generate import Generate
  File "D:\invokeAI\.\ldm\generate.py", line 15, in <module>
    import transformers
ModuleNotFoundError: No module named 'transformers'
```
