### ISSUE TITLE
[bug]: 1-Click installer on Windows 10 stops at python deps

### ISSUE THREAD

**Issue by IngwiePhoenix** [invoke-ai/InvokeAI#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

Extracted the installer to `C:\tools\invokeAI`. I use `C:\tools` a little like `/opt` on linux; a generally writeable space where I have full permissions. So the permission situation shouldn't be a problem here.

The following error occurs way after conda has downloaded a new local version of python; 3.10.7 as shown.

Now, I am not very good with python - so I really don't know where to look for a proper and precise error output...

```
Collecting basicsr==1.4.2
  Downloading basicsr-1.4.2.tar.gz (172 kB)
     ---------------------------------------- 172.5/172.5 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Ingwie Phoenix\AppData\Local\Temp\pip-install-gt2k2s5c\basicsr_1963b0a70b694a4d8bf9f0c029cd3ba0\setup.py", line 147, in <module>
          setup(
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\tools\InvokeAI\.venv\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "C:\tools\InvokeAI\.venv\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\wheel.py", line 96, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\wheel.py", line 104, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\wheel.py", line 125, in _convert_metadata
          _unpack_zipfile_obj(zf, destination_eggdir)
        File "C:\tools\InvokeAI\.venv\lib\site-packages\setuptools\archive_util.py", line 129, in _unpack_zipfile_obj
          with open(target, 'wb') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ingwie Phoenix\\AppData\\Local\\Temp\\pip-install-gt2k2s5c\\basicsr_1963b0a70b694a4d8bf9f0c029cd3ba0\\.eggs\\torch-1.13.0-py3.10-win-amd64.egg\\torch\\include\\ATen\\ops\\_test_autograd_multiple_dispatch_view_copy_compositeexplicitautogradnonfunctional_dispatch.h'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Screenshots

Hope my logs count :)

### Additional context

I ran the installer twice. After it errored the first time, I re-ran `install.bat` again to see if something would change - which did not happen, sadly.

### Contact Details

Discord IngwiePhoenix#6637 - Twitter IngwiePhoenix

**Comment by pedrovivash** [comment]
Have you tried the [manual install](https://invoke-ai.github.io/InvokeAI/installation/INSTALL_MANUAL/) method? I just updated and had to require pip via the `environment.yml` to install `basicsr==1.4.2` as your `install.bat` but also had to require `realesrgan==0.3.0`.

**Comment by Beerman2000** [comment]
Ingwie, your logs do count! Have a look at how loooooong that directory is on that FileNotFoundError line. It's over **260 characters: not a problem for Linux but a big no-no for Windows.** My identical error returned a path 6 characters shorter than yours and it was still breaking the rules! 

Not your fault — but something for devs to consider documenting for Windows people or working around it in their batch file because this is a default environment variable location.

Head to _Control Panel > System > Advanced > Environment Variables_ and change your Windows TEMP path(s) to a folder closer to the root, try again and report back.

**Comment by lstein** [comment]
There is a .bat file in `installer` called `WinLongPathsEnabled.reg`. If you double-click it, it will enable long file names in your Windows Registry. If the problem is indeed the long name, then this will fix it.

**Comment by tildebyte** [comment]
> All thats left is to learn what does what exactly, in terms of the settings on the left, and how I can possibly feed some of my own images in? If that is even possible since those seem to be checkpoints.

Join the [Discord](https://discord.gg/invokeai-the-stable-diffusion-toolkit-1020123559063990373)! Lots of help to be had in there.
