### ISSUE TITLE
[bug]: crash w cross-attention when prompt is >75 tokens

### ISSUE THREAD

**Issue by tjennings** [invoke-ai/InvokeAI#1513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24gb

### What happened?

This is Ubuntu Linux on WSL, windows 11, latest drivers. 

Commit hash: 8b47c82992647d6caffe611305f5d30049fa8146

After running many generation with a cross-attention prompt changing the attributes of a .swap to an uneven set of terms causes a crash.  For example changing  (steel sphere).swap(black hole) to (supernova).swap(black hole) caused invoke to crash simultaneously on two seperate GPUs (a 4090 and 3080, otherwise running identical software & hardware).  This is the excpetion: 

```
Traceback (most recent call last):                                                               | 0/15 [00:00<?, ?it/s]
  File "/mnt/c/Users/tyler/code/AIDreamer-Compute/ldm/generate.py", line 467, in prompt2image
    results = generator.generate(
  File "/mnt/c/Users/tyler/code/AIDreamer-Compute/ldm/invoke/generator/base.py", line 90, in generate
    image = make_image(x_T)
  File "/home/coreco/miniconda3/envs/invokeai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(args, **kwargs)
  File "/mnt/c/Users/tyler/code/AIDreamer-Compute/ldm/invoke/generator/txt2img2img.py", line 53, in makeimage
    samples,  = sampler.sample(
  File "/home/coreco/miniconda3/envs/invokeai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(args, kwargs)
  File "/mnt/c/Users/tyler/code/AIDreamer-Compute/ldm/models/diffusion/sampler.py", line 188, in sample
    samples, intermediates = self.do_sampling(
  File "/home/coreco/miniconda3/envs/invokeai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, kwargs)
  File "/mnt/c/Users/tyler/code/AIDreamer-Compute/ldm/models/diffusion/sampler.py", line 250, in do_sampling
    self.prepare_to_sample(t_enc=total_steps,all_timesteps_count=steps,**kwargs)
  File "/mnt/c/Users/tyler/code/AIDreamer-Compute/ldm/models/diffusion/ddim.py", line 22, in prepare_to_sample
    self.invokeai_diffuser.setup_cross_attention_control(extra_conditioning_info, step_count = all_timesteps_count)
  File "/mnt/c/Users/tyler/code/AIDreamer-Compute/ldm/models/diffusion/shared_invokeai_diffusion.py", line 45, in setup_cross_attention_control
    CrossAttentionControl.setup_cross_attention_control(self.model,
  File "/mnt/c/Users/tyler/code/AIDreamer-Compute/ldm/models/diffusion/cross_attention_control.py", line 68, in setup_cross_attention_control
    indices[b0:b1] = indices_target[a0:a1]
RuntimeError: The expanded size of the tensor (38) must match the existing size (39) at non-singleton dimension 0.  Target sizes: [38].  Tensor sizes: [39]
```

Repro steps: 

1. 
run roughly 30 generations with this prompt and settings: 
https://aidreamer.art/images/2576deeecfe1c6236278d9bbe8abb817

2. 
Change the prompt to the following leaving everything else the same: 

A centered (supernova).swap(black hole) exploding into colorful powder on a black background, digital Art, perfect composition, beautiful detailed intricate insanely detailed micro details octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger [grainy washed out] [sex] [furnishing decorating decoration furniture] [pizza] [sign meme label text watermark signature frame oil thousand hands dance]

### Contact Details

@coreco on discord

**Comment by damian0815** [comment]
note to self, this is happening because the prompt is too long and is being truncated
