### ISSUE TITLE
[bug]: When using the web interface from the development branch , upscaling fails realesr-general-x4v3.pth not found

### ISSUE THREAD

**Issue by Vargol** [invoke-ai/InvokeAI#1522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

8GB

### What happened?

When using the web interface from the development branch , upscaling fails.
It does not fail from the CLI.

```
>> Image generation requested: {'prompt': 'green eggs and ham', 'iterations': 10, 'steps': 2, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 1332844990, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
ESRGAN parameters: {'level': 4, 'strength': 0.75}
Facetool parameters: False
Generating:   0%|                                                                                                                        | 0/10 [00:00<?, ?it/s]>> Ksampler using karras noise schedule (steps < 30)
>> Sampling with k_lms starting at step 0 of 2 (2 new sampling steps)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:18<00:00,  9.45s/it]
>> Error loading Real-ESRGAN:█████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:18<00:00,  8.83s/it]
Traceback (most recent call last):
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/InvokeAITesting/ldm/invoke/restoration/realesrgan.py", line 50, in process
    upsampler = self.load_esrgan_bg_upsampler()
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/InvokeAITesting/ldm/invoke/restoration/realesrgan.py", line 32, in load_esrgan_bg_upsampler
    bg_upsampler = RealESRGANer(
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/lib/python3.10/site-packages/realesrgan/utils.py", line 43, in __init__
    loadnet = torch.load(model_path, map_location=torch.device('cpu'))
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/lib/python3.10/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/lib/python3.10/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/realesrgan/realesr-general-x4v3.pth'

>> Real-ESRGAN Upscaling seed:1332844990 : scale:4x
Generating:   0%|                                                                                                                        | 0/10 [00:29<?, ?it/s]
local variable 'upsampler' referenced before assignment


Traceback (most recent call last):
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/InvokeAITesting/backend/invoke_ai_web_server.py", line 836, in generate_images
    self.generate.prompt2image(
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/InvokeAITesting/ldm/generate.py", line 477, in prompt2image
    results = generator.generate(
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/InvokeAITesting/ldm/invoke/generator/base.py", line 98, in generate
    image_callback(image, seed, first_seed=first_seed)
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/InvokeAITesting/backend/invoke_ai_web_server.py", line 732, in image_done
    image = self.esrgan.process(
  File "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAIModel/InvokeAITesting/ldm/invoke/restoration/realesrgan.py", line 69, in process
    output, _ = upsampler.enhance(
UnboundLocalError: local variable 'upsampler' referenced before assignment
```

### Screenshots

N/A

### Additional context

I mentioned this in Discord...
https://discord.com/channels/1020123559063990373/1043515681703997530

..and a potential solution, it basically seems the Globals.root is '.'  and the current directory is not consistent, deriving its absolute path when set seems to fix it.

**Comment by psychedelicious** [comment]
Fixed in #1523, thanks @Vargol !
