### ISSUE TITLE
[bug]: Receiving "SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer." despite running the included WinLongPathsEnabled registry fix during install.bat

### ISSUE THREAD

**Issue by dreamofmt** [invoke-ai/InvokeAI#1699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10

### What happened?

Hello can't wait to try this but unfortunately I keep receiving the aforementioned error upon trying to run the install.bat, and I saw others had this issue and fixed it by running the registry file to fix the long word path in Windows in the folder. 

I have ran the long word fix and am still encountering the error.

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      E:\InvokeAI\InvokeAI\.venv\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      ERROR: Wheel 'torch' located at C:\Users\Nicole\AppData\Local\Temp\pip-unpack-t7hpus4r\torch-1.13.0-cp310-cp310-win_amd64.whl is invalid.
      Traceback (most recent call last):
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "E:\InvokeAI\InvokeAI\python\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['E:\\InvokeAI\\InvokeAI\\.venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Nicole\\AppData\\Local\\Temp\\tmp2fcd2m00', '--quiet', 'torch']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Nicole\AppData\Local\Temp\pip-install-h7vk1zeb\basicsr_4bb06ce0c08f4895a315939be2662ebb\setup.py", line 147, in <module>
          setup(
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "E:\InvokeAI\InvokeAI\.venv\lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['E:\\InvokeAI\\InvokeAI\\.venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Nicole\\AppData\\Local\\Temp\\tmp2fcd2m00', '--quiet', 'torch']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
----- main pip install failed -----
Press any key to continue . . .

![Screenshot (8466)_cr](https://user-images.githubusercontent.com/116125222/205246392-809d84a7-af29-4f72-89b1-c6590e0531e3.png)

I am not sure how to proceed, tried what was suggested in the forum here but continue to receive this error after rebooting even after applying the registry fix. 

Sorry for the trouble and if this is not how to post the issue I will remove it, thanks for your help.

Edit: I just read up on this error and tried to find a solution for it, I've tried multiple things now including a pip upgrade (says requirements already satisfied), updating setuptools wheel (says requirements already satisfied)

**Comment by dreamofmt** [comment]
Rebooted for a 3rd time and it finally cleared this error (not sure what) now is getting new error, making thread for that issue.

**Comment by durga-nayak** [comment]
I am getting the same issue what is the resolution for it
