### ISSUE TITLE
[bug]: no module names pathtools.patterns

### ISSUE THREAD

**Issue by daddy-drav** [invoke-ai/InvokeAI#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

when i get to the python installation with the binary install and it looks for the module pathtools.patterns it can't find it nor does it try to install it

### Screenshots

heres a ss from the start of the python install:
***** Installed invoke launcher script ******
Loading Python libraries...

Traceback (most recent call last):
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\observers\__init__.py", line 90, in <module>
    from .read_directory_changes import WindowsApiObserver as Observer
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\observers\read_directory_changes.py", line 26, in <module>
    from wandb_watchdog.events import (
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\events.py", line 91, in <module>
    from pathtools.patterns import match_any_paths
ModuleNotFoundError: No module named 'pathtools.patterns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1076, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\InvokeAI\InvokeAI\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\transformers\modeling_utils.py", line 78, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\accelerate\accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\accelerate\tracking.py", line 45, in <module>
    import wandb
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\sdk\wandb_init.py", line 31, in <module>
    from .backend.backend import Backend
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\sdk\backend\backend.py", line 19, in <module>
    from ..internal.internal import wandb_internal
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\sdk\internal\internal.py", line 34, in <module>
    from . import handler, internal_util, sender, settings_static, writer
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\sdk\internal\sender.py", line 31, in <module>
    from wandb.filesync.dir_watcher import DirWatcher
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\filesync\dir_watcher.py", line 29, in <module>
    wd_polling = util.vendor_import("wandb_watchdog.observers.polling")
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\util.py", line 329, in vendor_import
    module = import_module(name)
  File "C:\InvokeAI\InvokeAI\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\observers\__init__.py", line 92, in <module>
    from .polling import PollingObserver as Observer
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\observers\polling.py", line 50, in <module>
    from wandb_watchdog.events import (
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\events.py", line 91, in <module>
    from pathtools.patterns import match_any_paths
ModuleNotFoundError: No module named 'pathtools.patterns'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\InvokeAI\InvokeAI\scripts\configure_invokeai.py", line 22, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1067, in __getattr__
    value = getattr(module, name)
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1066, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\InvokeAI\InvokeAI\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1078, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
No module named 'pathtools.patterns'
----- model download clone failed -----
Press any key to continue . . .

**Comment by daddy-drav** [comment]
I no longer need this fixed, my solution was switching to the source install and moving the install from my c drive to a different drive.
