### ISSUE TITLE
[bug]: Site package failed to load -  transformers.models.clip.modeling_clip 

### ISSUE THREAD

**Issue by philflav** [invoke-ai/InvokeAI#1800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Site package failed to load. transformers.models.clip.modeling_clip . 'NoneType' object has no attribute 'message_types_by_name'

### Screenshots

Traceback (most recent call last):
  File "D:\StableDiffusion\invokeAI\scripts\configure_invokeai.py", line 23, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Anaconda3\envs\invokeai\lib\site-packages\transformers\utils\import_utils.py", line 993, in __getattr__
    value = getattr(module, name)
  File "D:\Anaconda3\envs\invokeai\lib\site-packages\transformers\utils\import_utils.py", line 992, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\Anaconda3\envs\invokeai\lib\site-packages\transformers\utils\import_utils.py", line 1004, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
'NoneType' object has no attribute 'message_types_by_name'
""
"The configure script crashed or was cancelled."
"InvokeAI is not ready to run. To run preload_models.py again,"
"run the command 'update.bat' in this directory."
"Press any key to continue"

**Comment by philflav** [comment]
Resolved with fresh install using latest installer.
