### ISSUE TITLE
[bug]: Running Img2img with `Display In-Progress Images: Accurate` causes it to fail

### ISSUE THREAD

**Issue by xpscyho** [invoke-ai/InvokeAI#1851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What happened?

When using the webinterface and running any image through Img2img I initially caught 3 errors:
```
Traceback (most recent call last):
  File "/mnt/Toshiba/GitHub/invokeAI/backend/invoke_ai_web_server.py", line 1367, in get_image_path_from_url
    if "init-images" in url:
TypeError: argument of type 'Image' is not iterable
```
```
Traceback (most recent call last):
  File "/mnt/Toshiba/GitHub/invokeAI/backend/invoke_ai_web_server.py", line 1212, in 
parameters_to_generated_image_metadata
    rfc_dict["orig_hash"] = calculate_init_img_hash(
  File "/mnt/Toshiba/GitHub/invokeAI/ldm/invoke/args.py", line 1182, in calculate_init_img_hash
    if image_string.startswith(prefix):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
```
Traceback (most recent call last):
  File "/mnt/Toshiba/GitHub/invokeAI/backend/invoke_ai_web_server.py", line 1104, in generate_images
    self.generate.prompt2image(
  File "/mnt/Toshiba/GitHub/invokeAI/ldm/generate.py", line 486, in prompt2image
    results = generator.generate(
  File "/mnt/Toshiba/GitHub/invokeAI/ldm/invoke/generator/base.py", line 93, in generate
    image = make_image(x_T)
  File "/mnt/Toshiba/GitHub/invokeAI/ldm/invoke/generator/img2img.py", line 52, in make_image
    samples = sampler.decode(
  File "/home/xpsyc/micromamba/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/Toshiba/GitHub/invokeAI/ldm/models/diffusion/ksampler.py", line 129, in decode
    samples,_ = self.sample(
  File "/home/xpsyc/micromamba/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/Toshiba/GitHub/invokeAI/ldm/models/diffusion/ksampler.py", line 214, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "/home/xpsyc/micromamba/envs/invokeai/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xpsyc/micromamba/envs/invokeai/lib/python3.9/site-packages/k_diffusion/sampling.py", line 273, in sample_lms
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "/mnt/Toshiba/GitHub/invokeAI/ldm/models/diffusion/ksampler.py", line 182, in route_callback
    img_callback(k_callback_values['x'],k_callback_values['i'])
  File "/mnt/Toshiba/GitHub/invokeAI/backend/invoke_ai_web_server.py", line 868, in image_progress
    command = parameters_to_command(generation_parameters)
  File "/mnt/Toshiba/GitHub/invokeAI/backend/modules/parameters.py", line 43, in parameters_to_command
    if "init_img" in params and len(params["init_img"]) > 0:
TypeError: object of type 'Image' has no len()
```

Switching `Display In-Progress Images` to `Fast` fixed it.

### Contact Details

@Xpsychonauticon#1297

**Comment by zlyfer** [comment]
I also experienced this issue with the exact same console output.
- Windows 11
- Cuda
- 12GB VRAM

At first I thought img2img didn't work at all so I search issues and found this.
Turned off `Display In-Progress Images: Accurate` and now it works. (`Fast` and `None` both work)
Additionally this is the output in the web UI (which matches with the console output):
```console
2023-03-30T13:11:54+0200: Server error: argument of type 'Image' is not iterable
2023-03-30T13:11:54+0200: Server error: 'NoneType' object has no attribute 'startswith'
2023-03-30T13:11:54+0200: Server error: object of type 'Image' has no len()
```

**Comment by PauloFDO** [comment]
> I also experienced this issue with the exact same console output.
> 
> * Windows 11
> * Cuda
> * 12GB VRAM
> 
> At first I thought img2img didn't work at all so I search issues and found this. Turned off `Display In-Progress Images: Accurate` and now it works. (`Fast` and `None` both work) Additionally this is the output in the web UI (which matches with the console output):
> 
> ```
> 2023-03-30T13:11:54+0200: Server error: argument of type 'Image' is not iterable
> 2023-03-30T13:11:54+0200: Server error: 'NoneType' object has no attribute 'startswith'
> 2023-03-30T13:11:54+0200: Server error: object of type 'Image' has no len()
> ```

I can't believe that this actually fixed it
