### ISSUE TITLE
[bug]: Installation fails at "Preparing metadata (setup.py)"

### ISSUE THREAD

**Issue by Toasterbirb** [invoke-ai/InvokeAI#2056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

I was trying to install InvokeAI with the provided `install.sh` script, but the installer quits with error code 1 and prints this error
```
Collecting basicsr>=1.4.2
  Downloading basicsr-1.4.2.tar.gz (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.5/172.5 kB 6.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      /home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1jv5lczb/basicsr_cdab16a383a747ca93d00fb420ff69eb/setup.py", line 147, in <module>
          setup(
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/wheel.py", line 139, in _convert_metadata
          _unpack_zipfile_obj(zf, destination_eggdir)
        File "/home/toasterbirb/.local/share/invokeai/.venv/lib/python3.10/site-packages/setuptools/archive_util.py", line 130, in _unpack_zipfile_obj
          f.write(data)
      OSError: [Errno 28] No space left on device
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Additional context

Some python version information in-case that matters
pip 22.2.2
Python 3.10.9

Also, I have 49G left in the partition I'm installing into, so the `OSError: [Errno 28] No space left on device` error is a bit odd

**Comment by ebr** [comment]
`OSError: [Errno 28] No space left on device` means you've run out of space on the drive where you're trying to install InvokeAI. If you have a drive with more space available, you can select that path when the installer asks you to `"Select your preferred location for the 'invokeai' directory"`.

I also see paths like `/home/toasterbirb/.local/share/invokeai/.venv/` in the log, which is strange because the `/invokeai/` directory should not end up under `~/.local/share`. Could you please verify the path you're installing to?

**Comment by Toasterbirb** [comment]
I was installing to ~/.local/share on purpose. Is there some reason why it shouldn't be put there?

I have 49 gigabytes of storage space available in the partition I'm trying to install InvokeAI into

**Comment by ebr** [comment]
> I was installing to `~/.local/share` on purpose. Is there some reason why it shouldn't be put there?

No reason - if that's intended, go for it. Just didn't expect to see that location in the logs.

To confirm, you're selecting this location when prompted by `install.sh`?

> I have 49 gigabytes of storage space available in the partition I'm trying to install InvokeAI into

That's very odd indeed, but the message clearly states that there's no space left on the device.... 

perhaps you could try to start the installation again, and run `watch df -h` in another terminal to pinpoint the device whose free space begins to dwindle?

**Comment by Toasterbirb** [comment]
Yes, I was specifying the location with the installation script. The total size of the installation directory was about 22 megabytes in size.

When installing and monitoring `df -h`, it looks like my `/tmp` gets full. I have mounted it as tmpfs and 4 gigabytes of storage. I'll try giving it temporarely a bit more space and see if that helps

**Comment by Toasterbirb** [comment]
Yup, that was the issue. Looks like you need about 6 gigabytes of space in /tmp to get trough the installation.

**Comment by ebr** [comment]
> Yup, that was the issue. Looks like you need about 6 gigabytes of space in /tmp to get trough the installation.

Thank you! we can add this to the documentation.
