### ISSUE TITLE
[bug]: ERROR when Collecting torch==1.12.1

### ISSUE THREAD

**Issue by NaughtDZ** [invoke-ai/InvokeAI#2067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24G

### What happened?

Collecting torch==1.12.1
ERROR: Exception:
Traceback (most recent call last):
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\network\download.py", line 134, in __call__
    resp = _http_get_download(self._session, link)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\network\download.py", line 117, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_internal\network\session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 48, in send
    cached_response = self.controller.cached_request(request)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 155, in cached_request
    resp = self.serializer.loads(request, cache_data, body_file)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 95, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data, body_file)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 186, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 125, in unpackb
    ret = unpacker._unpack()
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "I:\InvokeAI\invokeai\.venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 603, in _unpack
    return bytes(obj)
MemoryError

### Screenshots

![image](https://user-images.githubusercontent.com/37768911/208306788-4a7a7b8c-7351-4a1c-8131-7ebe59c46d23.png)
![image](https://user-images.githubusercontent.com/37768911/208306794-dfc03407-0a75-4aef-a8e5-26a5777c132d.png)
![Uploading image.png…]()

### Additional context

I have 2 GPU,GPU 0 is Tesla m40,GPU 1 is RTX 3070

**Comment by wywywywy** [comment]
Are you using Python 3.11? If so try 3.10. Pytorch wheel is not available for 3.11 on Windows yet.

**Comment by NaughtDZ** [comment]
> Are you using Python 3.11? If so try 3.10. Pytorch wheel is not available for 3.11 on Windows yet.

![image](https://user-images.githubusercontent.com/37768911/208694754-0b372f41-b773-4841-90c2-a2f59866fa97.png)
