### ISSUE TITLE
[bug]: Problem installing InvokeAI 2.2.4 after successfully installed and deleted InvokeAI 2.2.3

### ISSUE THREAD

**Issue by Alteregohr** [invoke-ai/InvokeAI#2124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What happened?

I have successfully installed version 2.2.3, an then decided to ty and install 2.2.4. I have manuali deleted folders of 2.2.3. Installation was located in user folder  ( I was planning to move installation to another drive because of space on drive C: ) and try to install 2.2.4. but constantly get errors. I have tried automatic installation, and manula conda installation but without success.

After installation collects all packages I get this error:

Successfully built k-diffusion pypatchmatch clip
Installing collected packages: torch, tifffile, sentry-sdk, scipy, rich, requests, PyWavelets, pytz-deprecation-shim, python-socketio, python-dateutil, pypatchmatch, pyarrow, pudb, promise, opencv-python-headless, opencv-python, omegaconf, numba, jsonschema, Jinja2, importlib-metadata, imageio, gitdb, flaskwebgui, eventlet, docker-pycreds, contourpy, click, aiosignal, tzlocal, torchvision, torchsde, torchmetrics, torchdiffeq, scikit-learn, scikit-image, requests-oauthlib, pydeck, pandas, matplotlib, kornia, jsonmerge, huggingface-hub, google-auth, gitpython, flask, aiohttp, accelerate, wandb, transformers, torch-fidelity, qudida, google-auth-oauthlib, flask_socketio, flask_cors, filterpy, diffusers, clip, clean-fid, altair, tensorboard, tb-nightly, streamlit, k-diffusion, facexlib, clipseg, albumentations, test-tube, pytorch-lightning, basicsr, taming-transformers-rom1504, gfpgan, realesrgan
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\rober\invokeai\.venv\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\rober\invokeai\.venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\rober\invokeai\.venv\lib\site-packages\pip\_internal\commands\install.py", line 494, in run
    installed = install_given_reqs(
  File "C:\Users\rober\invokeai\.venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "C:\Users\rober\invokeai\.venv\lib\site-packages\pip\_internal\req\req_install.py", line 792, in install
    install_wheel(
  File "C:\Users\rober\invokeai\.venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 729, in install_wheel
    _install_wheel(
  File "C:\Users\rober\invokeai\.venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 589, in _install_wheel
    file.save()
  File "C:\Users\rober\invokeai\.venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "C:\Python310\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Python310\lib\zipfile.py", line 925, in read
    data = self._read1(n)
  File "C:\Python310\lib\zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "C:\Python310\lib\zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/torch_cuda_cu.dll'
Requirements installation failed. See above for errors and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.
Press any key to continue . . .

**Comment by Alteregohr** [comment]
I managed to solve the problem with

pip cache purge

after that the installation went fint
