### ISSUE TITLE
[bug]: 'Combine' object has no attribute 'set_parse_action'

### ISSUE THREAD

**Issue by regstuff** [invoke-ai/InvokeAI#2171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

32

### What happened?

After inputing the prompt in the UI, I get the error on the command line:
```
'Combine' object has no attribute 'set_parse_action'

Traceback (most recent call last):
  File "/home/user/InvokeAI/backend/invoke_ai_web_server.py", line 1201, in generate_images
    self.generate.prompt2image(
  File "/home/user/InvokeAI/ldm/generate.py", line 463, in prompt2image
    uc, c, extra_conditioning_info = get_uc_and_c_and_ec(
  File "/home/user/InvokeAI/ldm/invoke/conditioning.py", line 22, in get_uc_and_c_and_ec
    prompt, negative_prompt = get_prompt_structure(prompt_string,
  File "/home/user/InvokeAI/ldm/invoke/conditioning.py", line 34, in get_prompt_structure
    prompt, negative_prompt = _parse_prompt_string(prompt_string,
  File "/home/user/InvokeAI/ldm/invoke/conditioning.py", line 68, in _parse_prompt_string
    pp = PromptParser()
  File "/home/user/InvokeAI/ldm/invoke/prompt_parser.py", line 272, in __init__
    self.conjunction, self.prompt = build_parser_syntax(attention_plus_base, attention_minus_base)
  File "/home/user/InvokeAI/ldm/invoke/prompt_parser.py", line 468, in build_parser_syntax
    pp.Combine(pp.Optional("-")+pp.Word(pp.nums)).set_parse_action(pp.token_map(float))
AttributeError: 'Combine' object has no attribute 'set_parse_action'
```
I get a similar issue when entering a prompt via the commandline.

Here's details of my prompt and the other params:
```
Image generation requested: {'prompt': 'Ultrarealistic image of a supernova with a spaceship flying away with a warp drive. [Male pilot]', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 1802727589, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
{'prompt': 'Ultrarealistic image of a supernova with a spaceship flying away with a warp drive. [Male pilot]', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 1802727589, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '', 'seamless': False, 'hires_fix': False, 'variation_amount': 0}
```

Also, when the web server was launched, I had this error. (Not sure if it's relevant to this issue.)

```
patchmatch.patch_match: INFO - Compiling and loading c extensions from "/home/user/InvokeAI/invokeai/lib/python3.10/site-packages/patchmatch".
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
>> patchmatch.patch_match: INFO - Refer to https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/INSTALL_PATCHMATCH.md for installation instructions.
```

**Comment by georgi** [comment]
You need a newer version of pyparsing.

**Comment by AlexNolasco** [comment]
> pyparsing

`pip install --upgrade pyparsing `

did work for me, thanks 
Ubuntu 22.04.1 LTS
