### ISSUE TITLE
[bug]: Unable to run Invoke AI from Mac M1 error: If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True

### ISSUE THREAD

**Issue by mansueli** [invoke-ai/InvokeAI#2234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What happened?

There's this error once I try to run the command:
```

** DOWNLOADING SUPPORT MODELS **
Installing bert tokenizer (ignore deprecation errors)...
...success
Installing CLIP model (ignore deprecation errors)...
Tokenizer...
Text model...

A problem occurred during initialization.
The error was: "Unable to load weights from pytorch checkpoint file for './models/openai/clip-vit-large-patch14/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff/pytorch_model.bin' at './models/openai/clip-vit-large-patch14/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True."
Traceback (most recent call last):
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 399, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 403, in load_state_dict
    if f.read().startswith("version"):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/model_cache.py", line 81, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/model_cache.py", line 248, in _load_model
    model = instantiate_from_config(omega_config.model)
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/ldm/util.py", line 90, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/ldm/models/diffusion/ddpm.py", line 658, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/ldm/models/diffusion/ddpm.py", line 769, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/ldm/util.py", line 90, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/encoders/modules.py", line 252, in __init__
    self.transformer = CLIPTextModel.from_pretrained(
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2230, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/Users/mansueli/invokeai/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/Users/mansueli/invokeai/models/openai/clip-vit-large-patch14/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff/pytorch_model.bin' at '/Users/mansueli/invokeai/models/openai/clip-vit-large-patch14/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

```

I've tried to call the command with args e.g `% ./invoke.sh from_tf=True` but it doesn't work:

`invoke.py: error: unrecognized arguments: from_tf=True`

I've opened the .venv directory found the file pyvenv.cfg, it didn't work to set this there either. Found these two issues:
https://github.com/UKPLab/EasyNMT/issues/46

And https://github.com/huggingface/transformers/issues/4336

I've tried to install torchvision as recommended on the second issue above. Same issue:
`pip install --upgrade torch torchvision`

### Additional context

I found this in the documentation, but doesn't seen specific to this issue:

https://invoke-ai.github.io/InvokeAI/installation/deprecated_documentation/INSTALL_MAC/?h=patch14#oserror-cant-load-tokenizer-for-openaiclip-vit-large-patch14

### Contact Details

https://twitter.com/rmansueli

**Comment by pvint** [comment]
I had the same thing on a new Windows install - I deleted `/models/openai/clip-vit-large-patch14/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff/pytorch_model.bin` and restarted and it got a new copy and is working fine.

**Comment by DjebbZ** [comment]
Same problem from a brand new Macbook Air M2. I installed python 3.10 as recommended in the installation guide.

The workaround from @pvint didn't work, the same error occurs again after deleting the `pythorch_model.bin`file.

**Comment by remixer-dec** [comment]
I had a similar issue (OSError: openai/clip-vit-large-patch14 does not appear to have a file named pytorch_model.bin but there is a file for TensorFlow weights. Use `from_tf=True` to load this model from those weights.
).

To see which files are missing, edit ~/miniconda3/lib/PYTHON_VERSION/site-packages/transformers/utils/hub.py and print the required file at the end of function `try_to_load_from_cache` add `   print(cached_file, os.path.isfile(cached_file))` before return. For the issue was that pytorch_model.bin was a symlink to a non-existing file, i relinked it to `~/.cache/huggingface/transformers/c506559a5367a918bab46c39c79af91ab88846b49c8abd9d09e699ae067505c6.6365d436cc844f2f2b4885629b559d8ff0938ac484c01a6796538b2665de96c7` and the error disappeared

**Comment by rokmr** [comment]
> There has been no activity in this issue for 14 days. If this issue is still being experienced, please reply with an updated confirmation that the issue is still being experienced with the latest release.

Still getting same error

**Comment by Volutionn** [comment]
Same error on M1.

**Comment by quartzar** [comment]
Same error on Kubuntu 22.10:

```bash
Loading EleutherAI_gpt-j-6b...
Traceback (most recent call last):
  File "/home/quartzar/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/home/quartzar/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/quartzar/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quartzar/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 446, in load_state_dict
    if f.read(7) == "version":
  File "/home/quartzar/miniconda3/envs/textgen/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quartzar/text-generation-webui/server.py", line 471, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/quartzar/text-generation-webui/modules/models.py", line 53, in load_model
    model = AutoModelForCausalLM.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16)
  File "/home/quartzar/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/quartzar/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2560, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/quartzar/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 458, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'models/EleutherAI_gpt-j-6b/pytorch_model.bin' at 'models/EleutherAI_gpt-j-6b/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

**Comment by DjebbZ** [comment]
Trying a again from scratch with the latest version as of today (2.3.4.post1) installs and runs OK. _Note :_ I installed this version using the install script and used the default models.
