### ISSUE TITLE
[bug]: Failed to install due to "No module named 'promise.pyutils'"

### ISSUE THREAD

**Issue by MalikKillian** [invoke-ai/InvokeAI#2236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

After downloading the Windows zip from the latest release (https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.5) I extracted the files, ran the registry fix, and ran the `install.bat`. I already had Python 3.9 installed as I've been running AUTOMATIC1111 and I appeared to have a few Visual C++ libraries already installed.

I used the default location for installation and mostly things worked fine but eventually I hit an error with a Traceback. Logs below (there's more before the first line but no warnings or errors):

```
Installation successful.
.\templates\rootdir\configs\INITIAL_MODELS.yaml
.\templates\rootdir\configs\models.yaml.example
.\templates\rootdir\configs\sd-concepts.txt
.\templates\rootdir\configs\stable-diffusion\v1-finetune.yaml
.\templates\rootdir\configs\stable-diffusion\v1-finetune_style.yaml
.\templates\rootdir\configs\stable-diffusion\v1-inference.yaml
.\templates\rootdir\configs\stable-diffusion\v1-inpainting-inference.yaml
.\templates\rootdir\configs\stable-diffusion\v1-m1-finetune.yaml
8 File(s) copied
Loading Python libraries...

Traceback (most recent call last):
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1093, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\transformers\modeling_utils.py", line 78, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\accelerate\accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\accelerate\tracking.py", line 45, in <module>
    import wandb
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\sdk\__init__.py", line 7, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\sdk\wandb_artifacts.py", line 33, in <module>
    from wandb.apis import InternalApi, PublicApi
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\apis\__init__.py", line 30, in <module>
    from .internal import Api as InternalApi  # noqa
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\apis\internal.py", line 1, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\sdk\internal\internal_api.py", line 31, in <module>
    from wandb_gql import Client, gql  # type: ignore
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\__init__.py", line 1, in <module>
    from .gql import gql
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\gql.py", line 1, in <module>
    from wandb_graphql.language.parser import parse
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\vendor\graphql-core-1.1\wandb_graphql\__init__.py", line 43, in <module>
    from .graphql import (
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\vendor\graphql-core-1.1\wandb_graphql\graphql.py", line 1, in <module>
    from .execution import ExecutionResult, execute
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\vendor\graphql-core-1.1\wandb_graphql\execution\__init__.py", line 21, in <module>
    from .executor import execute
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\wandb\vendor\graphql-core-1.1\wandb_graphql\execution\executor.py", line 7, in <module>
    from promise import Promise, promise_for_dict, is_thenable
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\promise\__init__.py", line 1, in <module>
    from .pyutils.version import get_version
ModuleNotFoundError: No module named 'promise.pyutils'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\johndoe\invokeai\.venv\Scripts\configure_invokeai.py", line 24, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1084, in __getattr__
    value = getattr(module, name)
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1083, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\johndoe\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1095, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
No module named 'promise.pyutils'
Configuration failed. See above for error messages and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.
Press any key to continue . . .
```

### Additional context

I was just successful in installing 2.24 on the same machine.

**Comment by EchoedForm** [comment]
I'm here because I searched this text on google, and I have the exact same issue. Just getting into Ai images, successfully installed Automatic1111 an hour ago.

**Comment by ohgamer65** [comment]
me too

**Comment by MalikKillian** [comment]
@EchoedForm @ohgamer65 
Try 2.24 so we can hopefully narrow down the issue to a recent change.

**Comment by MalikKillian** [comment]
New finding. I was able to use the standard upgrade process to get to 2.25. So there may be a change in the dependency tree or install process since the last version that makes a clean install problematic.
