### ISSUE TITLE
[bug]: Invoke Ai is not starting. Not getting the localhost URL.

### ISSUE THREAD

**Issue by Konspaul** [invoke-ai/InvokeAI#2320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

20

### What happened?

I run the InvokeAI. I chose 2 the brower UI but:

Do you want to generate images using the
command-line
browser-based UI
open the developer console
Please enter 1, 2, or 3: 2

Starting the InvokeAI browser-based UI..
Traceback (most recent call last):
  File "/Volumes/Workstation HD/invokeai/.venv/bin/invoke.py", line 8, in <module>
    import ldm.invoke.CLI
  File "/Volumes/Workstation HD/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/CLI.py", line 12, in <module>
    from ldm.generate import Generate
  File "/Volumes/Workstation HD/invokeai/.venv/lib/python3.10/site-packages/ldm/generate.py", line 19, in <module>
    import cv2
  File "/Volumes/Workstation HD/invokeai/.venv/lib/python3.10/site-packages/cv2/init.py", line 181, in <module>
    bootstrap()
  File "/Volumes/Workstation HD/invokeai/.venv/lib/python3.10/site-packages/cv2/init.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/init.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Volumes/Workstation HD/invokeai/.venv/lib/python3.10/site-packages/cv2/cv2.abi3.so, 2): Symbol not found: _VTRegisterSupplementalVideoDecoderIfAvailable
  Referenced from: /Volumes/Workstation HD/invokeai/.venv/lib/python3.10/site-packages/cv2/.dylibs/libavcodec.59.37.100.dylib (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
 in /Volumes/Workstation HD/invokeai/.venv/lib/python3.10/site-packages/cv2/.dylibs/libavcodec.59.37.100.dylib

What does this mean and why I'm not gettin the localhost url?

### Screenshots

<img width="625" alt="Screenshot_2023-01-11_at_1 53 35" src="https://user-images.githubusercontent.com/16685288/212497622-1a6d0a9c-6c1d-4665-a79a-ab0f408d949c.png">

### Additional context

This issue is being discussed on Discord https://discord.com/channels/1020123559063990373/1062518124458557520

I tried this as I was suggested to try:

cd "/Volumes/Workstation HD/invokeai"
source .venv/bin/activate
pip3 install opencv-python==4.1.2.30

But got error:

ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68)
ERROR: No matching distribution found for opencv-python==4.1.2.30

### Contact Details

discord2023@raccoonbox.com

**Comment by Konspaul** [comment]
This is issue got fixed by updating OSX from 10.5 to 11.7.
