### ISSUE TITLE
[bug]: Unable to install on windows

### ISSUE THREAD

**Issue by bfg-coding** [invoke-ai/InvokeAI#2323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

Running through the install.bat file and having it failed with the following `AttributeError: module 'dns.rdtypes' has no attribute 'ANY'` 

### Screenshots

![WindowsTerminal_7y0TZRR1m2](https://user-images.githubusercontent.com/11151592/212560065-c92c7d05-8f37-4a23-a87d-39a20a8396d8.png)

**Comment by hc20k** [comment]
I also encountered this issue, it appears that a new version of dnspython was just pushed a couple hours ago and broke it.
Fixed it by running `pip install dnspython==2.2.1`.

**Comment by fogostudio** [comment]
I get a similar error : 

`Loading Python libraries...

Traceback (most recent call last):
  File "C:\Users\das\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1093, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\das\invokeai\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "C:\Users\das\invokeai\.venv\lib\site-packages\transformers\modeling_utils.py", line 78, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Users\das\invokeai\.venv\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "C:\Users\das\invokeai\.venv\lib\site-packages\accelerate\accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\das\invokeai\.venv\lib\site-packages\accelerate\tracking.py", line 45, in <module>
    import wandb
  File "C:\Users\das\invokeai\.venv\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\Users\das\invokeai\.venv\lib\site-packages\wandb\sdk\__init__.py", line 5, in <module>
    from . import wandb_helper as helper  # noqa: F401
  File "C:\Users\das\invokeai\.venv\lib\site-packages\wandb\sdk\wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "C:\Users\das\invokeai\.venv\lib\site-packages\wandb\sdk\lib\config_util.py", line 9, in <module>
    from wandb.util import load_yaml
  File "C:\Users\das\invokeai\.venv\lib\site-packages\wandb\util.py", line 51, in <module>
    import sentry_sdk  # type: ignore
  File "C:\Users\das\invokeai\.venv\lib\site-packages\sentry_sdk\__init__.py", line 1, in <module>
    from sentry_sdk.hub import Hub, init
  File "C:\Users\das\invokeai\.venv\lib\site-packages\sentry_sdk\hub.py", line 9, in <module>
    from sentry_sdk.scope import Scope
  File "C:\Users\das\invokeai\.venv\lib\site-packages\sentry_sdk\scope.py", line 7, in <module>
    from sentry_sdk.utils import logger, capture_internal_exceptions
  File "C:\Users\das\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 966, in <module>
    HAS_REAL_CONTEXTVARS, ContextVar = _get_contextvars()
  File "C:\Users\das\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 936, in _get_contextvars
    if not _is_contextvars_broken():
  File "C:\Users\das\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 897, in _is_contextvars_broken
    from eventlet.patcher import is_monkey_patched  # type: ignore
  File "C:\Users\das\invokeai\.venv\lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "C:\Users\das\invokeai\.venv\lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "C:\Users\das\invokeai\.venv\lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "C:\Users\das\invokeai\.venv\lib\site-packages\eventlet\support\greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "C:\Users\das\invokeai\.venv\lib\site-packages\eventlet\support\greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "C:\Users\das\invokeai\.venv\lib\site-packages\eventlet\patcher.py", line 132, in import_patched
    return inject(
  File "C:\Users\das\invokeai\.venv\lib\site-packages\eventlet\patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "C:\Users\das\invokeai\.venv\lib\site-packages\dns\zone.py", line 86, in <module>
    class Zone(dns.transaction.TransactionManager):
  File "C:\Users\das\invokeai\.venv\lib\site-packages\dns\zone.py", line 757, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\das\invokeai\.venv\Scripts\configure_invokeai.py", line 24, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\das\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1084, in __getattr__
    value = getattr(module, name)
  File "C:\Users\das\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1083, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\das\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1095, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
module 'dns.rdtypes' has no attribute 'ANY'
Configuration failed. See above for error messages and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.`

Tried hc20k solution but it didn't work for me.

**Comment by bfg-coding** [comment]
So I'm also having problems and I'm not the greatest Python developer but it looks like I'm not updating the .venv version of the dependency.  How would I access that to change that to the needed version?

**Comment by divn** [comment]
@bfg-coding PS C:\Users\divn\Desktop\Projects\invokeai> .\.venv\Scripts\pip.exe install dnspython==2.2.1 as an example

**Comment by Blasstt** [comment]
First you have to remove the unwanted versions by deleting the folders "dns" and "dnspython" from `invokeai\.venv\Lib\site-packages` and only then install dnspython 2.2.1 by runing `\invokeai\.venv\Scripts\pip.exe install dnspython==2.2.1` to install it to that same directory

**Comment by fogostudio** [comment]
tyvm @blastewe  !!! Followed your instructions and it worked!!

**Comment by LeGitHubDeTai** [comment]
hello / good evening I probably have the same problem but the pip command does not change anything
`Loading Python libraries...

Traceback (most recent call last):
  File "F:\IAImages\invokeAI\scripts\configure_invokeai.py", line 24, in <module>
    from diffusers import StableDiffusionPipeline, AutoencoderKL
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\diffusers\__init__.py", line 27, in <module>
    from .modeling_utils import ModelMixin
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\diffusers\modeling_utils.py", line 52, in <module>
    import accelerate
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\accelerate\accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\accelerate\tracking.py", line 45, in <module>
    import wandb
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\wandb\sdk\__init__.py", line 5, in <module>
    from . import wandb_helper as helper  # noqa: F401
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\wandb\sdk\wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\wandb\sdk\lib\config_util.py", line 9, in <module>
    from wandb.util import load_yaml
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\wandb\util.py", line 51, in <module>
    import sentry_sdk  # type: ignore
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\sentry_sdk\__init__.py", line 1, in <module>
    from sentry_sdk.hub import Hub, init
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\sentry_sdk\hub.py", line 9, in <module>
    from sentry_sdk.scope import Scope
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\sentry_sdk\scope.py", line 7, in <module>
    from sentry_sdk.utils import logger, capture_internal_exceptions
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\sentry_sdk\utils.py", line 966, in <module>
    HAS_REAL_CONTEXTVARS, ContextVar = _get_contextvars()
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\sentry_sdk\utils.py", line 936, in _get_contextvars
    if not _is_contextvars_broken():
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\sentry_sdk\utils.py", line 897, in _is_contextvars_broken
    from eventlet.patcher import is_monkey_patched  # type: ignore
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\eventlet\support\greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\eventlet\support\greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\eventlet\patcher.py", line 132, in import_patched
    return inject(
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\eventlet\patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\dns\zone.py", line 86, in <module>
    class Zone(dns.transaction.TransactionManager):
  File "F:\IAImages\invokeAI\installer_files\env\envs\invokeai\lib\site-packages\dns\zone.py", line 757, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'
""
"The configure script crashed or was cancelled."
"InvokeAI is not ready to run. To run preload_models.py again,"
"run the command 'update.bat' in this directory."
"Press any key to continue"
Appuyez sur une touche pour continuer...`

**Comment by haejoochang** [comment]
having same issue

and even when i remove the dns & dnspython and install dnspython==2.2.1

there's still no invoke.bat file; just missing :{

**Comment by pedrovenancio72** [comment]
> invokeai\.venv\Scripts\pip.exe install dnspython==2.2.1

How amazing i have done it, ufaaaaaa thanks all ok and work 100%

**Comment by pitneyw** [comment]
Would someone please write out a step by step I can follow to, "remove the dns & dnspython and install dnspython==2.2.1"?

I'm having this problem on my Mac OS and this SOUNDS good but I need help doing that^
(I've followed tutorials on how to instal a zsh shell, python 3.10 and added it to a PATH variable - hopefully, all thats left is this!)

**Comment by haejoochang** [comment]
> > having same issue
> > and even when i remove the dns & dnspython and install dnspython==2.2.1
> > there's still no invoke.bat file; just missing :{
> 
> this seems unrelated to this issue. try pulling the repo and rerunning the install script

how so? i'm getting those exact lines 1084, 1083 and 1095 failed to import transformers.models.clip.modeling_clip module dns.rdtypes has no attribute any errors AND i've tried reinstalling the script more than 5x last night using the auto installer

**Comment by lllusionJ** [comment]
> Would someone please write out a step by step I can follow to, "remove the dns & dnspython and install dnspython==2.2.1"?
> 
> I'm having this problem on my Mac OS and this SOUNDS good but I need help doing that^ (I've followed tutorials on how to instal a zsh shell, python 3.10 and added it to a PATH variable - hopefully, all thats left is this!)

@pitneyw I was having the same issue with my MAC OS too. But its fine now after following the instructions!
1. To remove the dns file, copy the file name of the error message file location from your Terminal (eg. /User/.... ) 
 Then type in "rm" followed by *space* and paste the copied error msg file (eg. rm /User/...) and hit Enter. The file should be removed.
2. Next run "pip install dnspython==2.2.1"
3. Close and reopen Terminal and drag the "install.sh" file into the Terminal from the InvokeAI-Installer and carry on your installation.

Hope this helps!

**Comment by pitneyw** [comment]
> > Would someone please write out a step by step I can follow to, "remove the dns & dnspython and install dnspython==2.2.1"?
> > I'm having this problem on my Mac OS and this SOUNDS good but I need help doing that^ (I've followed tutorials on how to instal a zsh shell, python 3.10 and added it to a PATH variable - hopefully, all thats left is this!)
> 
> @pitneyw I was having the same issue with my MAC OS too. But its fine now after following the instructions!
> 
> 1. To remove the dns file, copy the file name of the error message file location from your Terminal (eg. /User/.... )
>    Then type in "rm" followed by _space_ and paste the copied error msg file (eg. rm /User/...) and hit Enter. The file should be removed.
> 2. Next run "pip install dnspython==2.2.1"
> 3. Close and reopen Terminal and drag the "install.sh" file into the Terminal from the InvokeAI-Installer and carry on your installation.
> 
> Hope this helps!

Thank you for the help!
I now know about rm !
