### ISSUE TITLE
[bug]: Instalation problem

### ISSUE THREAD

**Issue by lucasthomasbecher** [invoke-ai/InvokeAI#2334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

12

### What happened?

during the installation of invoke AI 2.2.5p1 I got this error message (could you help me, please? I have no coding knowledge):

AttributeError: module 'dns.rdtypes' has no attribute 'ANY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\IA\invokeai\.venv\Scripts\configure_invokeai.py", line 24, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\IA\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1084, in __getattr__
    value = getattr(module, name)
  File "D:\IA\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1083, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\IA\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1095, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
module 'dns.rdtypes' has no attribute 'ANY'

### Contact Details

lucasthomasbecher@outlook.com

**Comment by divn** [comment]
#2323

**Comment by RebornZA** [comment]
`Traceback (most recent call last):
  File "A:\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1093, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "A:\Program Files\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\invokeai\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "A:\invokeai\.venv\lib\site-packages\transformers\modeling_utils.py", line 78, in <module>
    from accelerate import __version__ as accelerate_version
  File "A:\invokeai\.venv\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "A:\invokeai\.venv\lib\site-packages\accelerate\accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "A:\invokeai\.venv\lib\site-packages\accelerate\tracking.py", line 45, in <module>
    import wandb
  File "A:\invokeai\.venv\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "A:\invokeai\.venv\lib\site-packages\wandb\sdk\__init__.py", line 5, in <module>
    from . import wandb_helper as helper  # noqa: F401
  File "A:\invokeai\.venv\lib\site-packages\wandb\sdk\wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "A:\invokeai\.venv\lib\site-packages\wandb\sdk\lib\config_util.py", line 9, in <module>
    from wandb.util import load_yaml
  File "A:\invokeai\.venv\lib\site-packages\wandb\util.py", line 51, in <module>
    import sentry_sdk  # type: ignore
  File "A:\invokeai\.venv\lib\site-packages\sentry_sdk\__init__.py", line 1, in <module>
    from sentry_sdk.hub import Hub, init
  File "A:\invokeai\.venv\lib\site-packages\sentry_sdk\hub.py", line 9, in <module>
    from sentry_sdk.scope import Scope
  File "A:\invokeai\.venv\lib\site-packages\sentry_sdk\scope.py", line 7, in <module>
    from sentry_sdk.utils import logger, capture_internal_exceptions
  File "A:\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 966, in <module>
    HAS_REAL_CONTEXTVARS, ContextVar = _get_contextvars()
  File "A:\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 936, in _get_contextvars
    if not _is_contextvars_broken():
  File "A:\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 897, in _is_contextvars_broken
    from eventlet.patcher import is_monkey_patched  # type: ignore
  File "A:\invokeai\.venv\lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "A:\invokeai\.venv\lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "A:\invokeai\.venv\lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "A:\invokeai\.venv\lib\site-packages\eventlet\support\greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "A:\invokeai\.venv\lib\site-packages\eventlet\support\greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "A:\invokeai\.venv\lib\site-packages\eventlet\patcher.py", line 132, in import_patched
    return inject(
  File "A:\invokeai\.venv\lib\site-packages\eventlet\patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "A:\invokeai\.venv\lib\site-packages\dns\zone.py", line 86, in <module>
    class Zone(dns.transaction.TransactionManager):
  File "A:\invokeai\.venv\lib\site-packages\dns\zone.py", line 757, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "A:\invokeai\.venv\Scripts\configure_invokeai.py", line 24, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "A:\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1084, in __getattr__
    value = getattr(module, name)
  File "A:\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1083, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "A:\invokeai\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1095, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
module 'dns.rdtypes' has no attribute 'ANY'
Configuration failed. See above for error messages and check https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/#troubleshooting for potential solutions.
The installer will exit now.`

Was working until latest update. Even complete fresh install same errors.

**Comment by EuroCluddy** [comment]
I'm having the same issue as lucasthomasbecher, only I'm installing on a Mac OS.

Any help would be much appreciated. I have no coding knowledge either, sadly.

Thanks in advance.

---

  File "/Users/ME/invokeai/.venv/lib/python3.10/site-packages/dns/zone.py", line 757, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ME/invokeai/./.venv/bin/configure_invokeai.py", line 23, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/Users/ME/invokeai/.venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1084, in __getattr__
    value = getattr(module, name)
  File "/Users/ME/invokeai/.venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1083, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/ME/invokeai/.venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1095, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
module 'dns.rdtypes' has no attribute 'ANY'**

---

**Comment by MSDNAndi** [comment]
Same on Windows, both with install.bat script and with manual conda install.

**Comment by lucasthomasbecher** [comment]
> #2323

Thank you divn! now i have other problem, do you know how to solve it?

 
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "D:\IA\invokeai\.venv\Scripts\python.exe"
  * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by fogostudio** [comment]
Same problem

**Comment by VerifiedStoic** [comment]
I'm having the same problem. [This solution did not work.](https://github.com/invoke-ai/InvokeAI/issues/2323)

**Comment by kvsft** [comment]
> I'm having the same problem. [This solution did not work.](https://github.com/invoke-ai/InvokeAI/issues/2323)

don't forget to use -t option
pip3 install dnspython==2.2.1 --upgrade -t c:\invokeai\.venv\lib\site-packages

**Comment by haejoochang** [comment]
same issue

and also missing invoke.bat file 

despite 

"
Successfully built InvokeAI
Installing collected packages: InvokeAI
Successfully installed InvokeAI-2.2.5
Installation successful.
"

**Comment by MSDNAndi** [comment]
Did you get it via git clone or did you download the release zip? Use the release zip unless you want to contribute to development

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Njordy** [comment]
Guys, I have metered connection with only 50Gb/month. I don't wanna screw up. The installation is failed exactly like that. 
My install directory is "E:\InvokeAI\invokeai\".

I've did this: 
```
E:\InvokeAI>pip3 install dnspython==2.2.1 --upgrade -t E:\InvokeAI\invokeai\.venv\Lib\site-packages
Collecting dnspython==2.2.1
  Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
     |████████████████████████████████| 269 kB 544 kB/s
Installing collected packages: dnspython
Successfully installed dnspython-2.2.1
```

Is this correct? Should I re-install from the same .bat file, and it will work? I really can't afford failed installs/downloads once again...

**Comment by Titukas22** [comment]
i have the same issue after the error, i deleted the DNS folder (D:\invokeai\.venv\Lib\site-packages\dns)  and run install again, then was ok

**Comment by haejoochang** [comment]
> Did you get it via git clone or did you download the release zip? Use the release zip unless you want to contribute to development Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: haejoochang ***@***.***> Sent: Monday, January 16, 2023 9:53:28 AM To: invoke-ai/InvokeAI ***@***.***> Cc: Andreas Erben ***@***.***>; Comment ***@***.***> Subject: Re: [invoke-ai/InvokeAI] [bug]: Instalation problem (Issue #2334) same issue and also missing invoke.bat file despite " Successfully built InvokeAI Installing collected packages: InvokeAI Successfully installed InvokeAI-2.2.5 Installation successful. " — Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finvoke-ai%2FInvokeAI%2Fissues%2F2334%23issuecomment-1384242530&data=05%7C01%7C%7C0b389547157d4daace3f08daf7d9cf7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638094812102228626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wQ0dN7M6Q7rpGgFfGwIakoGgfAj4PAiojWC5zoVxgGQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABTOSD3NGLFC4BTSQ3FGF33WSVVHRANCNFSM6AAAAAAT4DSWGA&data=05%7C01%7C%7C0b389547157d4daace3f08daf7d9cf7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638094812102228626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oD1WZQZrVXRIhEHj3gabOdyAkkJO2b%2BIyH0JbR0cTMc%3D&reserved=0>. You are receiving this because you commented.Message ID: ***@***.***>

i used the released zip :[

**Comment by Njordy** [comment]
.zip

**Comment by livecleo** [comment]
Im also getting this type of error! :( have been on this for hours. 
If anyone can help id realy love it!


Displaying command line help...
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
Traceback (most recent call last):
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC3\invokeai\.venv\Scripts\invokeai.exe\__main__.py", line 4, in <module>
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\ldm\invoke\CLI.py", line 15, in <module>
    from ldm.generate import Generate
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\ldm\generate.py", line 15, in <module>
    import cv2
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\cv2\__init__.py", line 11, in <module>
    import numpy
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\Users\PC3\invokeai\.venv\Lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Users\PC3\invokeai\.venv\Scripts\python.exe"
  * The NumPy version is: "1.23.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
