### ISSUE TITLE
[bug]: img2img crashes when strength is too low

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#2337]
When img2img strength is set too low, the diffusers pipeline fails with this traceback:

<details>
<summary>IndexError: index 0 is out of bounds for dimension 0 with size 0</summary>

Traceback (most recent call last):
  File "InvokeAI/backend/invoke_ai_web_server.py", line 1216, in generate_images
    self.generate.prompt2image(
  File "InvokeAI/ldm/generate.py", line 498, in prompt2image
    results = generator.generate(
  File "InvokeAI/ldm/invoke/generator/base.py", line 108, in generate
    image = make_image(x_T)
  File "InvokeAI/ldm/invoke/generator/img2img.py", line 45, in make_image
    pipeline_output = pipeline.img2img_from_embeddings(
  File "InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 485, in img2img_from_embeddings
    return self.img2img_from_latents_and_embeddings(initial_latents, num_inference_steps,
  File "InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 500, in img2img_from_latents_and_embeddings
    result_latents, result_attention_maps = self.latents_from_embeddings(
  File "InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 356, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 186, in __call__
    for result in self.generator_method(*args, **kwargs):
  File "InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 388, in generate_latents_from_embeddings
    batched_t = torch.full((batch_size,), timesteps[0],
IndexError: index 0 is out of bounds for dimension 0 with size 0

</details>

### Additional context

It's breaking because the strength is so low that it concluded it should run zero timesteps, and there's code that doesn't work well with running zero timesteps. We should fix it so it always does one, at a minimum. (Or maybe a minimum of `scheduler.order` steps?)

Our diffusers pipeline code is _significantly_ reshuffled from the upstream [StableDiffusionImg2ImgPipeline](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py), but I'm curious how it avoids this problem, or if the bug exists there too. At a glance I don't see anything in its `get_timesteps` method that would guard against this.

**Comment by i3oc9i** [comment]
img2img also raise the following exception on Mac 

```
>> using provided input image of size 768x768
'<' not supported between instances of 'int' and 'str'


Traceback (most recent call last):
  File "/Users/ivano/Code/Ai/invokeai/backend/invoke_ai_web_server.py", line 1216, in generate_images
    self.generate.prompt2image(
  File "/Users/ivano/Code/Ai/invokeai/ldm/generate.py", line 475, in prompt2image
    init_image, mask_image = self._make_images(
  File "/Users/ivano/Code/Ai/invokeai/ldm/generate.py", line 752, in _make_images
    if image.width < self.width and image.height < self.height:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by i3oc9i** [comment]
@keturn this patch will solve the issue I was reporting, but I don't know if it is better to fix it in the `model_manager.py`

```
diff --git a/ldm/generate.py b/ldm/generate.py
index 63eaf79b..a87f258b 100644
--- a/ldm/generate.py
+++ b/ldm/generate.py
@@ -853,8 +853,8 @@ class Generate:
             model_name = previous_model_name

         self.model = model_data['model']
-        self.width = model_data['width']
-        self.height= model_data['height']
+        self.width = int(model_data['width'])
+        self.height= int(model_data['height'])
         self.model_hash = model_data['hash']

         # uncache generators so they pick up new models
```

**Comment by Fortyseven** [comment]
Keep running into this one, myself. Glad to see it's already been reported. :beers:

**Comment by Fortyseven** [comment]
Aaand there's the culprit. :stuck_out_tongue_closed_eyes: 

![image](https://user-images.githubusercontent.com/156409/215313413-1d55579f-509d-4584-8a22-d8493d206351.png)
