### ISSUE TITLE
AttributeError: 'PNDMScheduler' object has no attribute 'make_schedule'

### ISSUE THREAD

**Issue by gateway** [invoke-ai/InvokeAI#2344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What happened?

When Im trying out image to image I keep getting these types of errors..

```AttributeError: 'PNDMScheduler' object has no attribute 'make_schedule'```

Basically seems to happen with every sampler ? thoughts? I have the latest GIT version as of Jan 16th 2022.. It worked prior to me updating :(

thoughts?

```>> Setting Sampler to plms (PNDMScheduler)
c:\users\evil\desktop\work\invokeai\ldm\invoke\generator\diffusers_pipeline.py:609: DeprecationWarning: legacy compatibility layer
  warnings.warn("legacy compatibility layer", DeprecationWarning)
c:\users\evil\desktop\work\invokeai\ldm\invoke\generator\diffusers_pipeline.py:609: DeprecationWarning: legacy compatibility layer
  warnings.warn("legacy compatibility layer", DeprecationWarning)
>> using provided input image of size 512x768
>> This input is larger than your defaults. If you run out of memory, please use a smaller image.
>> image will be resized to fit inside a box 768x512 in size.
>> after adjusting image dimensions to be multiples of 64, init image is 320x512
'PNDMScheduler' object has no attribute 'make_schedule'


Traceback (most recent call last):
  File "c:\users\evil\desktop\work\invokeai\backend\invoke_ai_web_server.py", line 1216, in generate_images
    self.generate.prompt2image(
  File "c:\users\evil\desktop\work\invokeai\ldm\generate.py", line 498, in prompt2image
    results = generator.generate(
  File "c:\users\evil\desktop\work\invokeai\ldm\invoke\ckpt_generator\base.py", line 64, in generate
    make_image = self.get_make_image(
  File "c:\users\evil\desktop\work\invokeai\ldm\invoke\ckpt_generator\img2img.py", line 28, in get_make_image
    sampler.make_schedule(
AttributeError: 'PNDMScheduler' object has no attribute 'make_schedule'
```

**Comment by gateway** [comment]
When I switch models the console spits out this..

```>> Model change requested: stable-diffusion-1.4
>> Current VRAM usage:  0.00G
>> Offloading stable-diffusion-1.5 to CPU
c:\users\evil\desktop\work\invokeai\ldm\invoke\generator\diffusers_pipeline.py:609: DeprecationWarning: legacy compatibility layer
  warnings.warn("legacy compatibility layer", DeprecationWarning)
c:\users\evil\desktop\work\invokeai\ldm\invoke\generator\diffusers_pipeline.py:609: DeprecationWarning: legacy compatibility layer
  warnings.warn("legacy compatibility layer", DeprecationWarning)
>> Loading diffusers model from CompVis/stable-diffusion-v1-4
  | Using more accurate float32 precision
  | Loading diffusers VAE from stabilityai/sd-vae-ft-mse
  | Using more accurate float32 precision
Fetching 16 files: 100%|█████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 1229.66it/s]
  | Calculating sha256 hash of model files
  | sha256 = 8afccccccaf60d9b59d1e2630616436da569c07b2567a76c78f71ac7270868fd (33 files hashed in 8.66s)
  | Default image dimensions = 512 x 512
>> Model loaded in 14.46s
>> Textual inversions available:
>> Setting Sampler to ddim (DDIMScheduler)```
