### ISSUE TITLE
[bug]: "subprocess-exited-with-error" during execution of install.sh

### ISSUE THREAD

**Issue by Bit-ForceLtd** [invoke-ai/InvokeAI#2364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

Hello,

I was executing install.sh when the installation was interrupted with the following error. Now I am stuck. I can't uninstall, I can't proceed with the installation. What can I do please?
(The code formatting is not working properly for some reason).

Collecting basicsr>=1.4.2
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [114 lines of output]
      /home/ernest/invokeai/.venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      ERROR: Exception:
      Traceback (most recent call last):
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
          yield
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
          data = self._fp_read(amt) if not fp_closed else b""
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 526, in _fp_read
          return self._fp.read(amt) if amt is not None else self._fp.read()
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
          data = self.__fp.read(amt)
        File "/usr/lib/python3.10/http/client.py", line 465, in read
          s = self.fp.read(amt)
        File "/usr/lib/python3.10/socket.py", line 705, in readinto
          return self._sock.recv_into(b)
        File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
          return self.read(nbytes, buffer)
        File "/usr/lib/python3.10/ssl.py", line 1130, in read
          return self._sslobj.read(len, buffer)
      TimeoutError: The read operation timed out
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
          status = run_func(*args)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
          return func(self, options, args)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/commands/wheel.py", line 170, in run
          requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
          result = self._result = resolver.resolve(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
          if not criterion.candidates:
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
          return bool(self._sequence)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
          super().__init__(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
          self.dist = self._prepare()
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
          dist = self._prepare_distribution()
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
          local_file = unpack_url(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
          file = get_http_url(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
          from_path, content_type = download(link, temp_dir.path)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
          for chunk in chunks:
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
          for chunk in response.raw.stream(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 621, in stream
          data = self.read(amt=amt, decode_content=decode_content)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 559, in read
          with self._error_catcher():
        File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
          self.gen.throw(typ, value, traceback)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 442, in _error_catcher
          raise ReadTimeoutError(self._pool, None, "Read timed out.")
      pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
      Traceback (most recent call last):
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/ernest/invokeai/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp5nuj9tss', '--quiet', 'nvidia-cudnn-cu11==8.5.0.96']' returned non-zero exit status 2.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7_pmfkkf/basicsr_64d9fbad37964234be4314447a00a2e4/setup.py", line 147, in <module>
          setup(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 771, in resolve
          dist = best[req.key] = env.best_match(
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1056, in best_match
          return self.obtain(req, installer)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1068, in obtain
          return installer(requirement)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 883, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/home/ernest/invokeai/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/ernest/invokeai/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp5nuj9tss', '--quiet', 'nvidia-cudnn-cu11==8.5.0.96']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Contact Details

ernesto.pozzoni@gmail.com

**Comment by gogurtenjoyer** [comment]
Hello,
The error makes it look as though there was a network issue preventing one of the required packages from downloading. If possible, I'd try to think about anything that could cause network issues (bad wifi reception, VPN, firewall, etc), and disable/fix them before trying again.
If you'd like to completely restart the install, you should just be able to delete the 'invokeai' folder from your home folder - the installer won't see anything there and consider it a fresh install at that point.

**Comment by UglyStupidHonest** [comment]
I have the same exact issue too . Also on linux and cuda .

I can't find any issues with my network everything works as it should . Could there be another reason? Thank you so much!

**Comment by Bit-ForceLtd** [comment]
The issue was in the network. Many thanks for your help.

**Comment by UglyStupidHonest** [comment]
Maybe I should check again haha :)

**Comment by UglyStupidHonest** [comment]
It was disk space for me :)

**Comment by kaitakww** [comment]
I had the same problem while downloading pytorch and it was about network issue but the thing is I can't fix the network problem because of the place I live with restriction and so. Is there any way to manually download the torch .whl file and make it a cached file for the installer so the installer doesn't need to download it using "pip" (but install it from the cache) ?!

**Comment by wolfmanyoda** [comment]
Same issue, I paused my vpn and the install ran great.
