### ISSUE TITLE
Cannot install Invoke version 2.3.0. Installer closes with out completing the installation[bug]: 

### ISSUE THREAD

**Issue by BigBlueGX** [invoke-ai/InvokeAI#2503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24 GB

### What happened?

Cannot install Invoke version 2.3.0.

The automated installer closes without completing the installation procedure.
I had 2.2.5 without any issues

### Screenshots

** DOWNLOADING WEIGHTS **
stable-diffusion-1.5...
safety_checker\model.safetensors not found
Fetching 15 files: 100%|█████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 1905.06it/s]

A problem occurred during initialization.
The error was: "torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU "
Traceback (most recent call last):
  File "C:\SD\invokeai\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 995, in main
    errors.add(download_weights(opt))
  File "C:\SD\invokeai\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 767, in download_weights
    successfully_downloaded = download_weight_datasets(
  File "C:\SD\invokeai\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 381, in download_weight_datasets
    successful[mod] = _download_repo_or_file(
  File "C:\SD\invokeai\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 394, in _download_repo_or_file
    path = _download_diffusion_weights(mconfig, access_token, precision=precision)
  File "C:\SD\invokeai\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 427, in _download_diffusion_weights
    path = download_from_hf(
  File "C:\SD\invokeai\.venv\Lib\site-packages\ldm\invoke\config\configure_invokeai.py", line 638, in download_from_hf
    model = model_class.from_pretrained(
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 760, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "C:\SD\invokeai\.venv\Lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 305, in __init__
    self._enable_memory_efficient_attention()
  File "C:\SD\invokeai\.venv\Lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 313, in _enable_memory_efficient_attention
    self.enable_xformers_memory_efficient_attention()
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 875, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 900, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 891, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 208, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 204, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 204, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 204, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 201, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\SD\invokeai\.venv\Lib\site-packages\diffusers\models\attention.py", line 104, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

= was unexpected at this time.

### Additional context

There is a warning during the installation that is maybe related to this:

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+cpu)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
** DOWNLOADING DIFFUSION WEIGHTS **

Then the installer closes abruptly

**Comment by BigBlueGX** [comment]
I also tried the following

> `for Anyone having the issue "xformers pytorch 1.13.1+cpu instead 1.13.1+cu117" after installing 2.3.0rcx.x or suddenly invoke is using the cpu (WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for: PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+cpu))
> 
> Start invoke and choose "Developer Console" (number 6)
> 
> paste these comands: pip uninstall torch (uninstalls pytorch cpu version)
> 
> pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117 (this can take a few minutes)
> 
> after that close the Terminal and restart Invoke
> 
> There will be a new error "Triton not found" or similar (triton is just optimization ~ 5-10% i think, but not available on pip for windows, only linux) it should still work fine `
> 
> found on discord by user Dschogo#0604

This helped me solve the problem but the web UI is loading a blank screen now

**Comment by BigBlueGX** [comment]
I found a thread that mentions this. I'll close this and post it there

**Comment by Dok11** [comment]
> I found a thread that mentions this. I'll close this and post it there

@BigBlueGX could you share the link to this tread?
