### ISSUE TITLE
[bug]:Encountered error while trying to install package -grpcio

### ISSUE THREAD

**Issue by bingling00** [invoke-ai/InvokeAI#2604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

32GB

### What happened?

'   Traceback (most recent call last):
        File "/private/var/folders/r9/mgm6pz615vl2vnd2spp8jvb00000gn/T/pip-install-9pboxpve/grpcio_eb4acc48441547f99b9ddf6465ac64f0/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/ziang/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/Users/ziang/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/ziang/miniconda3/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/ziang/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
          objects = self.compiler.compile(
        File "/private/var/folders/r9/mgm6pz615vl2vnd2spp8jvb00000gn/T/pip-install-9pboxpve/grpcio_eb4acc48441547f99b9ddf6465ac64f0/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Users/ziang/miniconda3/lib/python3.10/multiprocessing/pool.py", line 367, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Users/ziang/miniconda3/lib/python3.10/multiprocessing/pool.py", line 774, in get
          raise self._value
        File "/Users/ziang/miniconda3/lib/python3.10/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Users/ziang/miniconda3/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/r9/mgm6pz615vl2vnd2spp8jvb00000gn/T/pip-install-9pboxpve/grpcio_eb4acc48441547f99b9ddf6465ac64f0/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/r9/mgm6pz615vl2vnd2spp8jvb00000gn/T/pip-install-9pboxpve/grpcio_eb4acc48441547f99b9ddf6465ac64f0/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/ziang/miniconda3/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.  '

### Screenshots

![image](https://user-images.githubusercontent.com/61322616/217843128-1da190f9-5779-4eba-8a20-a93dc78520da.png)

**Comment by bingling00** [comment]
![image](https://user-images.githubusercontent.com/61322616/217848756-74db2fba-6555-4c78-8385-7c48921c6168.png)
      [end of output]
  
'  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Successfully built k-diffusion clip
Failed to build grpcio
Installing collected packages: grpcio, gitdb, flaskwebgui, eventlet, docker-pycreds, contourpy, aiosignal, tzlocal, torchvision, torchsde, torchmetrics, torchdiffeq, scikit-learn, scikit-image, rich, requests-oauthlib, pydeck, pandas, matplotlib, kornia, jsonmerge, huggingface-hub, google-auth, gitpython, flask, aiohttp, accelerate, wandb, transformers, torch-fidelity, qudida, google-auth-oauthlib, flask_socketio, flask_cors, filterpy, diffusers, clip, clean-fid, altair, tensorboard, tb-nightly, streamlit, k-diffusion, facexlib, clipseg, albumentations, test-tube, pytorch-lightning, basicsr, taming-transformers-rom1504, gfpgan, realesrgan
  Running setup.py install for grpcio ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for grpcio did not run successfully.
  │ exit code: 1
  ╰─> [2636 lines of output]'

**Comment by mauwii** [comment]
We deprecated support for Conda quite a while ago, please use the [automated installer](https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/)
