### ISSUE TITLE
[bug]: embiggen on 2.3.0-rc7 MacOS, KeyError: 'clear_cuda_cache'

### ISSUE THREAD

**Issue by nelsonre** [invoke-ai/InvokeAI#2605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64

### What happened?

Attempted to use embiggen like this:
!fix outputs/005560.de14622b.1079278388.png --embiggen 2.0

Got this error:

```
Starting 1 of 15 tiles
100%|████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:14<00:00,  1.35it/s]
Generating:   0%|                                                                                          | 0/1 [00:16<?, ?it/s]
Generating:   0%|                                                                                          | 0/1 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "/Users/nelsonre/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/CLI.py", line 885, in do_postprocess
    gen.apply_postprocessor(
  File "/Users/nelsonre/invokeai/.venv/lib/python3.10/site-packages/ldm/generate.py", line 718, in apply_postprocessor
    generator.generate(
  File "/Users/nelsonre/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/generator/embiggen.py", line 36, in generate
    image = make_image()
  File "/Users/nelsonre/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/generator/embiggen.py", line 350, in make_image
    tile_results = gen_img2img.generate(
  File "/Users/nelsonre/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/generator/base.py", line 126, in generate
    clear_cuda_cache = kwargs['clear_cuda_cache'] or None
KeyError: 'clear_cuda_cache'
```

**Comment by Periton-Media** [comment]
Had the same issue and just went into the code to comment out those 3 lines in the base.py file.

Did it work? Yes.
Is this a good fix? Probably not.
