### ISSUE TITLE
[bug]:  Crash during updating to 2.3 while installing pytorch

### ISSUE THREAD

**Issue by thertemis** [invoke-ai/InvokeAI#2612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

The install of the 2.3.0 over the 2.2.5 crashed when trying ton install pytorch :

------------------------------------------------------------------------------------

`This script will install InvokeAI and its dependencies.

BEFORE YOU START PLEASE MAKE SURE TO DO THE FOLLOWING
1. Install python 3.9 or 3.10. Python version 3.11 and above are
   not supported at the moment.
2. Double-click on the file WinLongPathsEnabled.reg in order to
   enable long path support on your system.
3. Install the Visual C++ core libraries.
   Please download and install the libraries from:
   https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

See https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/ for more details.

Appuyez sur une touche pour continuer...
***** Checking and Updating Python *****
Initializing the installer. This may take a minute - please wait...

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Scripts\python.exe -m pip install --upgrade pip
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
╔═════════════════════════════════════════ Welcome to the InvokeAI Installer ══════════════════════════════════════════╗
║                                                                                                                      ║
║  Windows Users!                                                                                                      ║
║                                                                                                                      ║
║  Before you start, please do the following:                                                                          ║
║    1. Double-click on the file WinLongPathsEnabled.reg in order to                                                   ║
║       enable long path support on your system.                                                                       ║
║    2. Make sure you have the Visual C++ core libraries installed. If not, install from                               ║
║       https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170                         ║
║                                                                                                                      ║
║  Some of the installation steps take a long time to run. Please be patient. If the script appears to hang for more   ║
║                             than 10 minutes, please interrupt with Control-C and retry.                              ║
║                                                                                                                      ║
╚═══════════════════════════════════════════════════ Windows-AMD64 ════════════════════════════════════════════════════╝

❗ Directory C:\Users\Utilisateur\invokeai already exists ❗
🛑 Are you sure you want to (re)install in this location? [y/n] (n): y

───────────────────────────────────────── 👾 GPU (Graphics Card) selection 👾 ──────────────────────────────────────────

  Detected the Windows-AMD64 platform

  See https://invoke-ai.github.io/InvokeAI/#system to ensure your system meets the minimum requirements.

  🠶  Your GPU drivers must be correctly installed before using InvokeAI! 🠴

  Please select the type of GPU installed in your computer.

    1 🢒 an NVIDIA GPU (using CUDA™)

    2 🢒 no compatible GPU, or specifically prefer to use the CPU

    3 🢒 I'm not sure what to choose

Please make your selection: 1
──────────────────────────────────────────────── Installing PyTorch 🔥 ─────────────────────────────────────────────────
Traceback (most recent call last):
  File "D:\DLCHROME\InvokeAI-installer-v2.3.0\InvokeAI-Installer\lib\main.py", line 50, in <module>
    inst.install(**args.__dict__)
  File "D:\DLCHROME\InvokeAI-installer-v2.3.0\InvokeAI-Installer\lib\installer.py", line 179, in install
    self.instance.install(
  File "D:\DLCHROME\InvokeAI-installer-v2.3.0\InvokeAI-Installer\lib\installer.py", line 232, in install
    self.install_torch(extra_index_url, find_links)
  File "D:\DLCHROME\InvokeAI-installer-v2.3.0\InvokeAI-Installer\lib\installer.py", line 247, in install_torch
    pip[
  File "C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Lib\site-packages\plumbum\commands\base.py", line 251, in run
    with self.bgrun(args, **kwargs) as p:
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Lib\site-packages\plumbum\commands\base.py", line 207, in bgrun
    p = self.popen(args, **kwargs)
  File "C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Lib\site-packages\plumbum\commands\base.py", line 332, in popen
    return self.cmd.popen(self.args + list(args), **kwargs)
  File "C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Lib\site-packages\plumbum\machines\local.py", line 115, in popen
    return self.machine._popen(
  File "C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Lib\site-packages\plumbum\machines\local.py", line 295, in _popen
    proc = PlumbumLocalPopen(
  File "C:\Users\Utilisateur\AppData\Local\Temp\invokeai-installer-tmpeuwmhgx9\Lib\site-packages\plumbum\machines\local.py", line 29, in __init__
    self._proc = Popen(*args, **kwargs)  # pylint: disable=consider-using-with
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
= était inattendu.`

-------------------------------------------------------------------------------------
I checked the pre-requisites:
python 3.10.10 install with PATH
update Visual C++
update CUDA
Run the reg file
restart the system.

i tried to install pytorch from the official website and it worked without an issue.

I don'r know what to do

**Comment by thirstyhouseplant** [comment]
It looks like the installer is on a different volume than your main C: drive. Where are you attempting to install to? You might try placing the installer in the same directory you intend to install \invokeai\ to. Curious about anything else you might have tried.
