### ISSUE TITLE
[bug]: textual inversion - `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#2621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What happened?

First time trying TI. The rest of invokeai works fine, and `xformers` works during generation. 

```
(.venv) bat@batbox:~/invokeai$ invokeai-ti --gui
DEBUG: args = {'model': 'stable-diffusion-2.1-768', 'resolution': 768, 'lr_scheduler': 'constant', 'mixed_precision': 'bf16', 'learnable_property': 'object', 'initializer_token': '*', 'placeholder_token': '<terence>', 'train_data_dir': '/home/bat/invokeai/text-inversion-training-data/terence', 'output_dir': '/home/bat/invokeai/text-inversion-output/terence', 'scale_lr': True, 'center_crop': False, 'enable_xformers_memory_efficient_attention': True, 'train_batch_size': 12, 'gradient_accumulation_steps': 4, 'num_train_epochs': 100, 'max_train_steps': 3000, 'lr_warmup_steps': 0, 'learning_rate': 0.0005, 'resume_from_checkpoint': 'latest', 'only_save_embeds': True}
/home/bat/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py:231: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
02/11/2023 10:34:04 - INFO - ldm.invoke.training.textual_inversion_training - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Mixed precision type: bf16

** An exception occurred during training. The exception was:
Expecting value: line 1 column 1 (char 0)
** DETAILS:
Traceback (most recent call last):
  File "/home/bat/Documents/Code/InvokeAI/ldm/invoke/training/textual_inversion.py", line 425, in do_front_end
    do_textual_inversion_training(**args)
  File "/home/bat/Documents/Code/InvokeAI/ldm/invoke/training/textual_inversion_training.py", line 642, in do_textual_inversion_training
    tokenizer = CLIPTokenizer.from_pretrained(
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "/home/bat/invokeai/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1853, in _from_pretrained
    init_kwargs = json.load(tokenizer_config_handle)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by psychedelicious** [comment]
I tried again and it works now, so I suppose something changed recently.
