### ISSUE TITLE
[bug]: Textual Inversion using cpu on mac (incredibly slow)

### ISSUE THREAD

**Issue by farisalamin** [invoke-ai/InvokeAI#2705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

32GB

### What happened?

When using `invokeai-ti  --front_end` it seems to be using cpu and is running at about ~400s/it.

Below is my output for training:

```
(InvokeAI) ➜  invokeai invokeai-ti --front_end
DEBUG: args = {'model': 'diffusers-1.5+mse', 'resolution': 512, 'lr_scheduler': 'constant', 'mixed_precision': 'no', 'learnable_property': 'object', 'initializer_token': '★', 'placeholder_token': '<farisalamin>', 'train_data_dir': '/Users/Faris/invokeai/text-inversion-training-data/farisalamin', 'output_dir': '/Users/Faris/invokeai/text-inversion-output/farisalamin', 'scale_lr': True, 'center_crop': False, 'enable_xformers_memory_efficient_attention': False, 'train_batch_size': 8, 'gradient_accumulation_steps': 4, 'num_train_epochs': 100, 'max_train_steps': 3000, 'lr_warmup_steps': 0, 'learning_rate': 0.0005, 'only_save_embeds': True}
/Users/Faris/invokeai/.venv/lib/python3.9/site-packages/accelerate/accelerator.py:231: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
02/18/2023 05:28:49 - INFO - ldm.invoke.training.textual_inversion_training - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu
Mixed precision type: no

{'prediction_type', 'clip_sample_range', 'variance_type'} was not found in config. Values will be initialized to default values.
{'scaling_factor'} was not found in config. Values will be initialized to default values.
{'conv_in_kernel', 'upcast_attention', 'timestep_post_act', 'time_embedding_type', 'only_cross_attention', 'num_class_embeds', 'dual_cross_attention', 'class_embed_type', 'resnet_time_scale_shift', 'conv_out_kernel', 'time_cond_proj_dim', 'projection_class_embeddings_input_dim', 'use_linear_projection', 'mid_block_type'} was not found in config. Values will be initialized to default values.
02/18/2023 05:28:53 - INFO - ldm.invoke.training.textual_inversion_training - ***** Running training *****
02/18/2023 05:28:53 - INFO - ldm.invoke.training.textual_inversion_training -   Num examples = 1200
02/18/2023 05:28:53 - INFO - ldm.invoke.training.textual_inversion_training -   Num Epochs = 79
02/18/2023 05:28:53 - INFO - ldm.invoke.training.textual_inversion_training -   Instantaneous batch size per device = 8
02/18/2023 05:28:53 - INFO - ldm.invoke.training.textual_inversion_training -   Total train batch size (w. parallel, distributed & accumulation) = 32
02/18/2023 05:28:53 - INFO - ldm.invoke.training.textual_inversion_training -   Gradient Accumulation steps = 4
02/18/2023 05:28:53 - INFO - ldm.invoke.training.textual_inversion_training -   Total optimization steps = 3000
Steps:   0%|▏                                                                                                                                                                            | 4/3000 [32:41<343:11:12, 412.37s/it, loss=0.122, lr=0.016]
```

### Contact Details

Twyzan#5347

**Comment by psychedelicious** [comment]
Let's try setting the MPS fallback environment variable, which tells pytorch to use MPS instead of CPU, by running this:
`PYTORCH_ENABLE_MPS_FALLBACK=1 invokeai-ti --front_end`

Is that any faster?

**Comment by farisalamin** [comment]
Still uses cpu, not any faster:

```
(InvokeAI) ➜  invokeai PYTORCH_ENABLE_MPS_FALLBACK=1 invokeai-ti --front_end
DEBUG: args = {'model': 'diffusers-1.5+mse', 'resolution': 512, 'lr_scheduler': 'constant', 'mixed_precision': 'no', 'learnable_property': 'object', 'initializer_token': '★', 'placeholder_token': '<farisalamin>', 'train_data_dir': '/Users/Faris/invokeai/text-inversion-training-data/farisalamin', 'output_dir': '/Users/Faris/invokeai/text-inversion-output/farisalamin', 'scale_lr': True, 'center_crop': False, 'enable_xformers_memory_efficient_attention': False, 'train_batch_size': 8, 'gradient_accumulation_steps': 4, 'num_train_epochs': 100, 'max_train_steps': 3000, 'lr_warmup_steps': 0, 'learning_rate': 0.0005, 'resume_from_checkpoint': 'latest', 'only_save_embeds': True}
/Users/Faris/invokeai/.venv/lib/python3.9/site-packages/accelerate/accelerator.py:231: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
02/18/2023 15:23:20 - INFO - ldm.invoke.training.textual_inversion_training - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu
Mixed precision type: no

{'variance_type', 'clip_sample_range', 'prediction_type'} was not found in config. Values will be initialized to default values.
{'scaling_factor'} was not found in config. Values will be initialized to default values.
{'conv_in_kernel', 'time_cond_proj_dim', 'upcast_attention', 'timestep_post_act', 'num_class_embeds', 'resnet_time_scale_shift', 'use_linear_projection', 'conv_out_kernel', 'time_embedding_type', 'dual_cross_attention', 'only_cross_attention', 'class_embed_type', 'mid_block_type', 'projection_class_embeddings_input_dim'} was not found in config. Values will be initialized to default values.
02/18/2023 15:23:25 - INFO - ldm.invoke.training.textual_inversion_training - ***** Running training *****
02/18/2023 15:23:25 - INFO - ldm.invoke.training.textual_inversion_training -   Num examples = 1200
02/18/2023 15:23:25 - INFO - ldm.invoke.training.textual_inversion_training -   Num Epochs = 79
02/18/2023 15:23:25 - INFO - ldm.invoke.training.textual_inversion_training -   Instantaneous batch size per device = 8
02/18/2023 15:23:25 - INFO - ldm.invoke.training.textual_inversion_training -   Total train batch size (w. parallel, distributed & accumulation) = 32
02/18/2023 15:23:25 - INFO - ldm.invoke.training.textual_inversion_training -   Gradient Accumulation steps = 4
02/18/2023 15:23:25 - INFO - ldm.invoke.training.textual_inversion_training -   Total optimization steps = 3000
Checkpoint 'latest' does not exist. Starting a new training run.
Steps:   0%|                                                                                                                                                                                                                | 0/3000 [00:00<?, ?it/s]
```

**Comment by farisalamin** [comment]
Can confirm this is still being experienced on latest release.

**Comment by wescorp** [comment]
Same here, confirming from fresh github install.

**Comment by wescorp** [comment]
Can confirm also. The solution was to make the terminal screen full screen.  Then I could tell it was working.

**Comment by stoerr** [comment]
I saw that also on a Apple M1 Max MacBook on several of the 2.3.2 and 2.3.3 pre/post releases. Just creating pictures works nicely with the GPU. But when I try to start the textual inversion training from the invoke.sh script I get two kinds of errors, depending on what I select for the "Mixed precision". If I select "fp16", I get:

```
Starting Textual Inversion:
/Users/hps/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py:243: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
** An exception occurred during training. The exception was:
fp16 mixed precision requires a GPU
** DETAILS:
Traceback (most recent call last):
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/training/textual_inversion.py", line 425, in do_front_end
    do_textual_inversion_training(**args)
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/training/textual_inversion_training.py", line 582, in do_textual_inversion_training
    accelerator = Accelerator(
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 392, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
```

and if I select "bf16" I get:

```
Starting Textual Inversion:
/Users/hps/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py:243: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
03/28/2023 12:51:28 - INFO - ldm.invoke.training.textual_inversion_training - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: mps

Mixed precision type: bf16

{'clip_sample_range', 'variance_type'} was not found in config. Values will be initialized to default values.
{'scaling_factor'} was not found in config. Values will be initialized to default values.
{'mid_block_type', 'time_embedding_type', 'resnet_time_scale_shift', 'projection_class_embeddings_input_dim', 'conv_out_kernel', 'time_cond_proj_dim', 'timestep_post_act', 'class_embed_type', 'conv_in_kernel'} was not found in config. Values will be initialized to default values.
** An exception occurred during training. The exception was:
User specified autocast device_type must be 'cuda' or 'cpu'
** DETAILS:
Traceback (most recent call last):
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/training/textual_inversion.py", line 425, in do_front_end
    do_textual_inversion_training(**args)
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/training/textual_inversion_training.py", line 774, in do_textual_inversion_training
    text_encoder, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1094, in prepare
    result = tuple(
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1095, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 949, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1198, in prepare_model
    model.forward = torch.autocast(device_type=self.device.type, dtype=torch.bfloat16)(model.forward)
  File "/Users/hps/invokeai/.venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 199, in __init__
    raise RuntimeError('User specified autocast device_type must be \'cuda\' or \'cpu\'')
RuntimeError: User specified autocast device_type must be 'cuda' or 'cpu'
```


If I select "no"  for mixed precision, I get

```
Starting Textual Inversion:
/Users/hps/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py:243: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
03/28/2023 12:52:18 - INFO - ldm.invoke.training.textual_inversion_training - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: mps

Mixed precision type: no

{'clip_sample_range', 'variance_type'} was not found in config. Values will be initialized to default values.
{'scaling_factor'} was not found in config. Values will be initialized to default values.
{'conv_in_kernel', 'timestep_post_act', 'time_cond_proj_dim', 'projection_class_embeddings_input_dim', 'mid_block_type', 'time_embedding_type', 'class_embed_type', 'conv_out_kernel', 'resnet_time_scale_shift'} was not found in config. Values will be initialized to default values.
03/28/2023 12:52:31 - INFO - ldm.invoke.training.textual_inversion_training - ***** Running training *****
03/28/2023 12:52:31 - INFO - ldm.invoke.training.textual_inversion_training -   Num examples = 800
03/28/2023 12:52:31 - INFO - ldm.invoke.training.textual_inversion_training -   Num Epochs = 120
03/28/2023 12:52:31 - INFO - ldm.invoke.training.textual_inversion_training -   Instantaneous batch size per device = 8
03/28/2023 12:52:31 - INFO - ldm.invoke.training.textual_inversion_training -   Total train batch size (w. parallel, distributed & accumulation) = 32
03/28/2023 12:52:31 - INFO - ldm.invoke.training.textual_inversion_training -   Gradient Accumulation steps = 4
03/28/2023 12:52:31 - INFO - ldm.invoke.training.textual_inversion_training -   Total optimization steps = 3000
Checkpoint 'latest' does not exist. Starting a new training run.
Steps:   0%|                                                                                                                                       | 0/3000 [00:00<?, ?it/s]/AppleInternal/Library/BuildRoots/c651a45f-806e-11ed-a221-7ef33c48bc85/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:705: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: product of dimension sizes > 2**31'
fish: Job 1, 'nice -n 99 ./invoke.sh' terminated by signal SIGABRT (Abort)
/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
 ```

**Comment by immranderson** [comment]
I'm having the exact same troubles as @stoerr. Tried a few different combinations of configurations and was unsuccessful.
