### ISSUE TITLE
[bug]: When selecting the third model in the model merging TUI it crashes.

### ISSUE THREAD

**Issue by AutoAwesome** [invoke-ai/InvokeAI#2707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What happened?

When trying to merge models using the InvokeAI CLI it crashes when selecting the third model.

Please see this snippet:

```
(base) imx@willow /ml/invokeai $ ./invoke.sh 
Do you want to generate images using the
1. command-line
2. browser-based UI
3. run textual inversion training
4. merge models (diffusers type only)
5. open the developer console
6. re-run the configure script to download new models
7. command-line help 

Please enter 1, 2, 3, 4, 5, 6 or 7: [2] 4
Merging Models:


<<< HERE THE TUI OPENS AND I CAN SETUP EVERYTHING. ONCE I HIT ENTER ON THE THIRD MODEL IT CRASHES >>>>


>> An error occurred:
Traceback (most recent call last):
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/merge_diffusers.py", line 457, in main
    run_gui(args)
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/merge_diffusers.py", line 417, in run_gui
    mergeapp.run()
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/wgmultiline.py", line 581, in edit
    self.get_and_use_key_press()
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/wgwidget.py", line 612, in get_and_use_key_press
    self.when_check_value_changed()
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/npyscreen/wgwidget.py", line 670, in when_check_value_changed
    self.when_value_edited()
  File "/ml/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/merge_diffusers.py", line 327, in models_changed
    self.merged_model_name.value += f"+{models[selected_model3]}"
IndexError: list index out of range
(base) imx@willow /ml/invokeai $ 
```

If i can provide anything else let me now. :-)

**Comment by AutoAwesome** [comment]
I have found the issue and fixed in in the pull request i have submitted.
