### ISSUE TITLE
[bug]: Installer 2.3.0 crashes on macOS 13.2.1

### ISSUE THREAD

**Issue by DavidCWGA** [invoke-ai/InvokeAI#2748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

32 GB

### What happened?

install.sh crashes after choosing an install directory:

````
Traceback (most recent call last):
  File "/Volumes/MediDisk/StableDiffusion/InvokeAI-Installer/./lib/main.py", line 50, in <module>
    inst.install(**args.__dict__)
  File "/Volumes/MediDisk/StableDiffusion/InvokeAI-Installer/lib/installer.py", line 179, in install
    self.instance.install(
  File "/Volumes/MediDisk/StableDiffusion/InvokeAI-Installer/lib/installer.py", line 232, in install
    self.install_torch(extra_index_url, find_links)
  File "/Volumes/MediDisk/StableDiffusion/InvokeAI-Installer/lib/installer.py", line 247, in install_torch
    pip[
  File "/private/var/folders/yg/rrtqhmm545n7kxk12l9f_shc0000gn/T/invokeai-installer-tmpc3pky0o9/lib/python3.11/site-packages/plumbum/commands/modifiers.py", line 145, in __rand__
    cmd(
  File "/private/var/folders/yg/rrtqhmm545n7kxk12l9f_shc0000gn/T/invokeai-installer-tmpc3pky0o9/lib/python3.11/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/yg/rrtqhmm545n7kxk12l9f_shc0000gn/T/invokeai-installer-tmpc3pky0o9/lib/python3.11/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "/private/var/folders/yg/rrtqhmm545n7kxk12l9f_shc0000gn/T/invokeai-installer-tmpc3pky0o9/lib/python3.11/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/yg/rrtqhmm545n7kxk12l9f_shc0000gn/T/invokeai-installer-tmpc3pky0o9/lib/python3.11/site-packages/plumbum/commands/processes.py", line 304, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/yg/rrtqhmm545n7kxk12l9f_shc0000gn/T/invokeai-installer-tmpc3pky0o9/lib/python3.11/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/private/var/folders/yg/rrtqhmm545n7kxk12l9f_shc0000gn/T/invokeai-installer-tmpc3pky0o9/lib/python3.11/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /Volumes/MediDisk/StableDiffusion/invokeai/.venv/bin/pip install --require-virtualenv torch torchvision --force-reinstall
````

**Comment by lstein** [comment]
I believe you will need to install `XCode` tools. See https://invoke-ai.github.io/InvokeAI/installation/020_INSTALL_MANUAL/#prerequisites

**Comment by DavidCWGA** [comment]
XCode tools are installed.

I believe this might be because I have Python 3.11 installed, but not 3.10. I think it may only work with 3.10.

**Comment by i3oc9i** [comment]
yes it is, do a brew install python@3.10

**Comment by ebr** [comment]
still active
