### ISSUE TITLE
[bug]: Error downloading StabilityAI standard VAE: fp16 is not a valid git identifier

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#2768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

After Commit #2644

Installing stabilityai VAE...
Error downloading StabilityAI standard VAE: fp16 is not a valid git identifier (branch name, tag name or commit id) that exists for this model name. Check the model page at 'https://huggingface.co/stabilityai/sd-vae-ft-mse' for available revisions.
Traceback (most recent call last):
  File "/home/invokeuser/venv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 264, in hf_raise_for_status
    response.raise_for_status()
  File "/home/invokeuser/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/stabilityai/sd-vae-ft-mse/resolve/fp16/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/invokeuser/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 855, in _get_model_file
    model_file = hf_hub_download(
  File "/home/invokeuser/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/invokeuser/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1106, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/invokeuser/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/invokeuser/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1441, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/invokeuser/venv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 274, in hf_raise_for_status
    raise RevisionNotFoundError(message, response) from e
huggingface_hub.utils._errors.RevisionNotFoundError: 404 Client Error. (Request ID: Root=1-63f6c24e-4574ea5423136d056ec9a85c)

Revision Not Found for url: https://huggingface.co/stabilityai/sd-vae-ft-mse/resolve/fp16/diffusion_pytorch_model.bin.
Invalid rev id: fp16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/invokeuser/venv/lib/python3.10/site-packages/ldm/invoke/config/invokeai_configure.py", line 297, in download_vaes
    if not AutoencoderKL.from_pretrained(repo_id, **args):
  File "/home/invokeuser/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 525, in from_pretrained
    model_file = _get_model_file(
  File "/home/invokeuser/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 878, in _get_model_file
    raise EnvironmentError(
OSError: fp16 is not a valid git identifier (branch name, tag name or commit id) that exists for this model name. Check the model page at 'https://huggingface.co/stabilityai/sd-vae-ft-mse' for available revisions.

**Comment by mickr777** [comment]
Looks like its fixed
