### ISSUE TITLE
[bug]: "Accurate" intermediate images cause a render error

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#2784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What happened?

In the WebUI, when display intermediate images is set to "Accurate", all renders fail with:
```
': False, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'hires_fix': False, 'seamless': False, 'variation_amount': 0}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
  0%|                                                                                                        | 0/30 [00:00<?, ?it/s]
Generating:   0%|                                                                                             | 0/1 [00:00<?, ?it/s]
'StableDiffusionGeneratorPipeline' object has no attribute 'decode_first_stage'


Traceback (most recent call last):
  File "/home/lstein/Projects/InvokeAI/invokeai/backend/invoke_ai_web_server.py", line 1293, in generate_images
    self.generate.prompt2image(
  File "/home/lstein/Projects/InvokeAI/ldm/generate.py", line 557, in prompt2image
    results = generator.generate(
  File "/home/lstein/Projects/InvokeAI/ldm/invoke/generator/base.py", line 115, in generate
    image = make_image(x_T)
  File "/home/lstein/Projects/InvokeAI/ldm/invoke/generator/txt2img.py", line 45, in make_image
    pipeline_output = pipeline.image_from_embeddings(
  File "/home/lstein/Projects/InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 419, in image_from_embeddings
    result_latents, result_attention_map_saver = self.latents_from_embeddings(
  File "/home/lstein/Projects/InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 445, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "/home/lstein/Projects/InvokeAI/ldm/invoke/generator/diffusers_pipeline.py", line 180, in __call__
    callback(result)
  File "/home/lstein/Projects/InvokeAI/invokeai/backend/invoke_ai_web_server.py", line 1289, in diffusers_step_callback_adapter
    return image_progress(progress_state.latents, progress_state.step)
  File "/home/lstein/Projects/InvokeAI/invokeai/backend/invoke_ai_web_server.py", line 1029, in image_progress
    image = self.generate.sample_to_image(sample)
  File "/home/lstein/Projects/InvokeAI/ldm/generate.py", line 1107, in sample_to_image
    return self._make_base().sample_to_image(samples)
  File "/home/lstein/Projects/InvokeAI/ldm/invoke/generator/base.py", line 140, in sample_to_image
    x_samples = self.model.decode_first_stage(samples)
AttributeError: 'StableDiffusionGeneratorPipeline' object has no attribute 'decode_first_stage'
```
I believe this is related to the change in the step callback signature that occurred with the migration to diffusers. A quick remedy would be to disable Accurate rendering, since it is not often used.

**Comment by lstein** [comment]
I believe I fixed this on the backend. See PR #2787
