### ISSUE TITLE
[bug]: Failure loading python libraries... ModuleNotFoundError

### ISSUE THREAD

**Issue by dneesen** [invoke-ai/InvokeAI#2818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What happened?

Configuration hangs up when loading python libraries. Results in `ModuleNotFoundError: No module named 'pathtools.patterns'` 

Attempted:
Multiple different install locations and drives
Ensured ample available drive space
Checked Visual C++ installed per instructions
Verified Python 3.10.10
Confirmed Windows long path enabled

### Screenshots

`Loading Python libraries...

Traceback (most recent call last):
  File "K:\Users\David\.venv\Lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\observers\__init__.py", line 90, in <module>
    from .read_directory_changes import WindowsApiObserver as Observer
  File "K:\Users\David\.venv\Lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\observers\read_directory_changes.py", line 26, in <module>
    from wandb_watchdog.events import (
  File "K:\Users\David\.venv\Lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\events.py", line 91, in <module>
    from pathtools.patterns import match_any_paths
ModuleNotFoundError: No module named 'pathtools.patterns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\Users\David\Downloads\InvokeAI-installer-v2.3.1.post1\InvokeAI-Installer\lib\main.py", line 50, in <module>
    inst.install(**args.__dict__)
  File "K:\Users\David\Downloads\InvokeAI-installer-v2.3.1.post1\InvokeAI-Installer\lib\installer.py", line 189, in install
    self.instance.configure()
  File "K:\Users\David\Downloads\InvokeAI-installer-v2.3.1.post1\InvokeAI-Installer\lib\installer.py", line 345, in configure
    from ldm.invoke.config import invokeai_configure
  File "K:\Users\David\.venv\Lib\site-packages\ldm\invoke\config\invokeai_configure.py", line 26, in <module>
    from diffusers import AutoencoderKL
  File "K:\Users\David\.venv\Lib\site-packages\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "K:\Users\David\.venv\Lib\site-packages\diffusers\configuration_utils.py", line 34, in <module>
    from .utils import DIFFUSERS_CACHE, HUGGINGFACE_CO_RESOLVE_ENDPOINT, DummyObject, deprecate, logging
  File "K:\Users\David\.venv\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "K:\Users\David\.venv\Lib\site-packages\diffusers\utils\accelerate_utils.py", line 24, in <module>
    import accelerate
  File "K:\Users\David\.venv\Lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "K:\Users\David\.venv\Lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "K:\Users\David\.venv\Lib\site-packages\accelerate\tracking.py", line 48, in <module>
    import wandb
  File "K:\Users\David\.venv\Lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "K:\Users\David\.venv\Lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "K:\Users\David\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 31, in <module>
    from .backend.backend import Backend
  File "K:\Users\David\.venv\Lib\site-packages\wandb\sdk\backend\backend.py", line 20, in <module>
    from ..internal.internal import wandb_internal
  File "K:\Users\David\.venv\Lib\site-packages\wandb\sdk\internal\internal.py", line 34, in <module>
    from . import context, handler, internal_util, sender, settings_static, writer
  File "K:\Users\David\.venv\Lib\site-packages\wandb\sdk\internal\sender.py", line 33, in <module>
    from wandb.filesync.dir_watcher import DirWatcher
  File "K:\Users\David\.venv\Lib\site-packages\wandb\filesync\dir_watcher.py", line 29, in <module>
    wd_polling = util.vendor_import("wandb_watchdog.observers.polling")
  File "K:\Users\David\.venv\Lib\site-packages\wandb\util.py", line 326, in vendor_import
    module = import_module(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "K:\Users\David\.venv\Lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\observers\__init__.py", line 92, in <module>
    from .polling import PollingObserver as Observer
  File "K:\Users\David\.venv\Lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\observers\polling.py", line 50, in <module>
    from wandb_watchdog.events import (
  File "K:\Users\David\.venv\Lib\site-packages\wandb\vendor\watchdog_0_9_0\wandb_watchdog\events.py", line 91, in <module>
    from pathtools.patterns import match_any_paths
ModuleNotFoundError: No module named 'pathtools.patterns'
Press any key to continue . . .
`

**Comment by lstein** [comment]
It may be that you've got a corrupted library in your python package manager (pip) cache. Before you run `install`, could you open up CMD and type the following: `pip cache purge` ? Then run install again.

@ebr does this seem like the mostly likely problem to you?

**Comment by dneesen** [comment]
Ran `pip cache purge` and attempted to run install again. Still getting the same result of `ModuleNotFoundError: No module named 'pathtools.patterns'` From what I can tell it seems like pathtools is installed but it is not recognizing it. Installation works fine until it tries to configure python libraries. Is it possible to install pathtools separately or uninstall and reinstall?

**Comment by ebr** [comment]
Some unusual paths seem to be present in the logs:

`File "K:\Users\David\Downloads\InvokeAI-installer-v2.3.1.post1\ ...` looks fine... but then we see `File "K:\Users\David.venv\Lib\site-packages...` once the install hands over to the configuration script.

`David.venv` does not look expected or intentional. @dneesen could you please confirm you are selecting a valid destination path at install time?

**Comment by dneesen** [comment]
@ebr I hadn't noticed that with the file structure. As far as I know it was always a valid destination path. However, after trying the install in various locations something could have certainly gotten messed up.

I ended up completely removing all previous install attempts directories and starting over, running the `pip cache purge`, and then attempted install. This solved the problem and it is working now. Thanks for your help everyone!
