### ISSUE TITLE
[bug]: Testing 2.3.1.post1, using mps, with PyTorch nightly dev20230226 yields RuntimeError

### ISSUE THREAD

**Issue by changeling** [invoke-ai/InvokeAI#2826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

16GB

### What happened?

Testing InvokeAI 2.3.1.post1 with PyTorch nightly dev20230226, using mps, yields `RuntimeError: Attempting to copy from device mps:0 to device meta, but cross-device copies are not allowed!`

### Additional context

InvokeAI 2.3.1.post1
MacOS Ventura 13.1 (22C65)
Python 3.10.4
torch-2.0.0.dev20230226
torchaudio-2.0.0.dev20230226
torchvision-0.15.0.dev20230226

```** model stable-diffusion-1.5 could not be loaded: Attempting to copy from device mps:0 to device meta, but cross-device copies are not allowed!
Traceback (most recent call last):
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/ldm/generate.py", line 889, in set_model
    model_data = cache.get_model(model_name)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/model_manager.py", line 106, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/model_manager.py", line 341, in _load_model
    model, width, height, model_hash = self._load_diffusers_model(mconfig)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/model_manager.py", line 514, in _load_diffusers_model
    pipeline = StableDiffusionGeneratorPipeline.from_pretrained(
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 870, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2362, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 776, in __init__
    self.text_model = CLIPTextTransformer(config)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 681, in __init__
    self.embeddings = CLIPTextEmbeddings(config)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 209, in __init__
    self.token_embedding = nn.Embedding(config.vocab_size, embed_dim)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 144, in __init__
    self.reset_parameters()
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 153, in reset_parameters
    init.normal_(self.weight)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/torch/nn/init.py", line 155, in normal_
    return _no_grad_normal_(tensor, mean, std)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/torch/nn/init.py", line 19, in _no_grad_normal_
    return tensor.normal_(mean, std)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/torch/_refs/__init__.py", line 437, in _fn
    return fn(a, *args, out=a, **kwargs)
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/torch/_prims_common/wrappers.py", line 248, in _fn
    _safe_copy_out(copy_from=result, copy_to=out, exact_dtype=exact_dtype)  # type: ignore[arg-type]
  File "/Users/.../invokeai/.venv/lib/python3.10/site-packages/torch/_prims_common/wrappers.py", line 168, in _safe_copy_out
    raise RuntimeError(msg)
RuntimeError: Attempting to copy from device mps:0 to device meta, but cross-device copies are not allowed!```

**Comment by gogurtenjoyer** [comment]
This is a pytorch error - if you'd like to use InvokeAI with the nightly builds of pytorch, try using one from the 15th or earlier before this change was made, or make sure an issue is filed with pytorch and await a fix.

**Comment by damian0815** [comment]
yeah i saw the same thing. is there an open issue on pytorch?

**Comment by changeling** [comment]
@damian0815 Just opened one.

**Comment by changeling** [comment]
@gogurtenjoyer  Could y'all revisit this, given the above comment?

**Comment by Adreitz** [comment]
I'd like to amend my comment. The latest PyTorch nightlies (at least up to March 9) did work with Invoke 2.2.5, but only with DDIM and maybe one other scheduler (I forget which). The majority of schedulers only produced noise. I didn't notice for a long time because I had only been using DDIM. I've rolled back to the default releases for now. Maybe there is some other dependency that needs updating in order to make the other schedulers work with nightlies, but I'm not knowledgeable enough to say offhand and I don't have the time to troubleshoot.

**Comment by changeling** [comment]
This bug is still present in InvokeAI 2.3.2 with PyTorch nightlies (dev20230327), but InvokeAI works well with PyTorch 2.0.0.

**Comment by changeling** [comment]
Tested with invoke ai 3.0.0+a0 and torch dev20230327. Problem persists. 3.0.0+a0 works fine with torch 2.0.0.
