### ISSUE TITLE
[regression]: missing dependency `pytorch-lightning` converting SD1.5 base to diffusers

### ISSUE THREAD

**Issue by damian0815** [invoke-ai/InvokeAI#2893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

Looks like there's a missing module dependency `pytorch-lightning`. just got this after building a new virtualenv on current main:
```
>> InvokeAI runtime directory is "/Users/damian/invokeai"
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> ALERT:
>> The location of your previously-installed diffusers models needs to move from
>> invokeai/models/diffusers to invokeai/models/hub due to a change introduced by
>> diffusers version 0.14. InvokeAI will now move all models from the "diffusers" directory
>> into "hub" and then remove the diffusers directory. This is a quick, safe, one-time
>> operation. However if you have customized either of these directories and need to
>> make adjustments, please press ctrl-C now to abort and relaunch InvokeAI when you are ready.
>> Otherwise press <enter> to continue.
continue> >? 
** /Users/damian/invokeai/models/diffusers/models--runwayml--stable-diffusion-v1-5 => /Users/damian/invokeai/models/hub/models--runwayml--stable-diffusion-v1-5
** Migration is done. Continuing...
>> Using device_type mps
>> xformers not installed
>> NSFW checker is disabled
>> Current VRAM usage:  0.00G
>> Loading stable-diffusion-1.5 from models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
>> Converting legacy checkpoint stable-diffusion-1.5 into a diffusers model...
>> vae-ft-mse-840000-ema-pruned VAE corresponds to known stabilityai/sd-vae-ft-mse diffusers version
  | Loading diffusers VAE from stabilityai/sd-vae-ft-mse
  | Using more accurate float32 precision
Downloading (…)_model.safetensors";:   0%|          | 0.00/335M [00:00<?, ?B/s]Error loading: /Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd_attach_to_process/attach_x86_64.dylib
Downloading (…)_model.safetensors";: 100%|██████████| 335M/335M [00:10<00:00, 32.3MB/s]
Downloading (…)lve/main/config.json: 100%|██████████| 547/547 [00:00<00:00, 162kB/s]
** model stable-diffusion-1.5 could not be loaded: No module named 'pytorch_lightning'
** trying to reload previous model
>> Loading stable-diffusion-1.5 from models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
>> Converting legacy checkpoint stable-diffusion-1.5 into a diffusers model...
>> vae-ft-mse-840000-ema-pruned VAE corresponds to known stabilityai/sd-vae-ft-mse diffusers version
  | Loading diffusers VAE from stabilityai/sd-vae-ft-mse
  | Using more accurate float32 precision
Traceback (most recent call last):
  File "/Users/damian/2.current/stablediffusion/stable-diffusion/invokeai/backend/generate.py", line 934, in set_model
    model_data = cache.get_model(model_name)
  File "/Users/damian/2.current/stablediffusion/stable-diffusion/invokeai/backend/model_management/model_manager.py", line 113, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "/Users/damian/2.current/stablediffusion/stable-diffusion/invokeai/backend/model_management/model_manager.py", line 343, in _load_model
    model, width, height, model_hash = self._load_ckpt_model(
  File "/Users/damian/2.current/stablediffusion/stable-diffusion/invokeai/backend/model_management/model_manager.py", line 453, in _load_ckpt_model
    pipeline = load_pipeline_from_original_stable_diffusion_ckpt(
  File "/Users/damian/2.current/stablediffusion/stable-diffusion/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 1080, in load_pipeline_from_original_stable_diffusion_ckpt
    else torch.load(checkpoint_path)
  File "/Users/damian/miniconda3/envs/invokeai/lib/python3.9/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/damian/miniconda3/envs/invokeai/lib/python3.9/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/Users/damian/miniconda3/envs/invokeai/lib/python3.9/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'pytorch_lightning'
** An error occurred while attempting to initialize the model: "No module named 'pytorch_lightning'"
** This can be caused by a missing or corrupted models file, and can sometimes be fixed by (re)installing the models.
Do you want to run invokeai-configure script to select and/or reinstall models? [y/N]: 
```

**Comment by keturn** [comment]
oh geez. yeah, I sure didn't consider legacy pickles in #2866; that the data files themselves might reference classes from those packages.

well that's a bit of a bummer. but in the end I don't think removing pytorch-lightning pruned _that_ much off the size of the total dependency tree.

**Comment by keturn** [comment]
huh, shouldn't any reference in a pickle file need to be explicitly allowed by picklescan?

In which case there should a reference to `pytorch_lightning` either in the picklescan code or in some configuration passed to it?

I'm not finding any such thing. Wanted to check there to see if there was anything else I might get in trouble for overzealously removing.
