### ISSUE TITLE
[bug]: Server error: invalid literal for int() with base 10: '\x00\x00\x00'  And  Server error: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Snobster** [invoke-ai/InvokeAI#2973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

amd

### VRAM

16GB

### What version did you experience this issue on?

2.3.2

### What happened?

It was working fine for a while, and then I don't know what happened, but the errors below started appearing:

Server error: invalid literal for int() with base 10: '\x00\x00\x00'
Server error: expected str, bytes or os.PathLike object, not NoneType

**Comment by psychedelicious** [comment]
You should have a longer error message in the terminal window when this occurs. Can you please copy and paste that longer error here?

**Comment by psychedelicious** [comment]
Thanks. I should have asked more clearly the first time, but there is more info in the terminal that we need. 

It starts with something like "image generation requested", followed by the settings used for this generation, some other stuff, and finally the error. Can you please paste in all of that? You'll need to scroll up a bit to get to it. Ty

**Comment by Snobster** [comment]
In the invoke ai console:

2023-03-17T22:39:03-0400: Image generation requested: {"prompt":"(extremely detailed CG unity 8k wallpaper), (masterpiece), (best quality), (ultra-detailed), (best illustration), (best shadow), (photorealistic), (japanese cute girl), real human skin, lens flare, shade, backlighting, (depth of field), (natural lighting), film grain, ((1 girl)), ultra-high res,(detailed eyes), brown eyes, pretty smile, cute, (solo focus), (blonde hair),((hime cut short hair with low tied back braided ponytail)), (grey wool trench coat), full body,(medium shot), blurred background, ((solo)), (glossy skin), cute, close mouth, wearing diamond necklace,(looking at viewer), (look to the front),(smile),(night),(close mouth),(no makeup) [canvas frame, cartoon, 3d, ((disfigured)), ((bad art)), ((deformed)),((extra limbs)),((close up)),((b&w)), wierd colors, blurry, (((duplicate))), ((morbid)), ((mutilated)), [out of frame], extra fingers, mutated hands, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), blurry, ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))), out of frame, ugly, extra limbs, (bad anatomy), gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), mutated hands, (fused fingers), (too many fingers), (((long neck))), Photoshop, video game, ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated, extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out of frame, blurry, bad art, ((bad anatomy)), 3d render, ((malformed eyes))]","iterations":1,"steps":25,"cfg_scale":10,"threshold":0,"perlin":0,"height":768,"width":512,"sampler_name":"k_dpm_2","seed":4080457498,"progress_images":false,"progress_latents":true,"save_intermediates":5,"generation_mode":"txt2img","init_mask":"","hires_fix":false,"seamless":false,"variation_amount":0}

2023-03-17T22:39:28-0400: Server error: invalid literal for int() with base 10: '\x00\x00\x00'

2023-03-17T22:39:28-0400: Server error: expected str, bytes or os.PathLike object, not NoneType


In the terminal:

>> Image Generation Parameters:

{'prompt': '(extremely detailed CG unity 8k wallpaper), (masterpiece), (best quality), (ultra-detailed), (best illustration), (best shadow), (photorealistic), (japanese cute girl), real human skin, lens flare, shade, backlighting, (depth of field), (natural lighting), film grain, ((1 girl)), ultra-high res,(detailed eyes), brown eyes, pretty smile, cute, (solo focus), (blonde hair),((hime cut short hair with low tied back braided ponytail)), (grey wool trench coat), full body,(medium shot), blurred background, ((solo)), (glossy skin), cute, close mouth, wearing diamond necklace,(looking at viewer), (look to the front),(smile),(night),(close mouth),(no makeup) [canvas frame, cartoon, 3d, ((disfigured)), ((bad art)), ((deformed)),((extra limbs)),((close up)),((b&w)), wierd colors, blurry, (((duplicate))), ((morbid)), ((mutilated)), [out of frame], extra fingers, mutated hands, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), blurry, ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))), out of frame, ugly, extra limbs, (bad anatomy), gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), mutated hands, (fused fingers), (too many fingers), (((long neck))), Photoshop, video game, ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated, extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out of frame, blurry, bad art, ((bad anatomy)), 3d render, ((malformed eyes))]', 'iterations': 1, 'steps': 25, 'cfg_scale': 10, 'threshold': 0, 'perlin': 0, 'height': 768, 'width': 512, 'sampler_name': 'k_dpm_2', 'seed': 4080457498, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'hires_fix': False, 'seamless': False, 'variation_amount': 0}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
Generating:   0%|                                                                                | 0/1 [00:00<?, ?it/s]>> Ksampler using karras noise schedule (steps < 30)
>> Sampling with k_dpm_2 starting at step 0 of 25 (25 new sampling steps)
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:21<00:00,  1.16it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:21<00:00,  1.34it/s]

Traceback (most recent call last):
  File "C:\Users\shobh\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1480, in save_result_image
    number_prefix = pngwriter.unique_prefix()
  File "C:\Users\shobh\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\ldm\invoke\pngwriter.py", line 33, in unique_prefix
    prefix=int(file.readline() or int(self._unused_prefix())-1)
ValueError: invalid literal for int() with base 10: '\x00\x00\x00'


Generating:   0%|                                                                                | 0/1 [00:22<?, ?it/s]
expected str, bytes or os.PathLike object, not NoneType


Traceback (most recent call last):
  File "C:\Users\shobh\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1293, in generate_images
    self.generate.prompt2image(
  File "C:\Users\shobh\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\ldm\generate.py", line 559, in prompt2image
    results = generator.generate(
  File "C:\Users\shobh\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\ldm\invoke\ckpt_generator\base.py", line 114, in generate
    image_callback(image, seed, first_seed=first_seed, attention_maps_image=attention_maps_image)
  File "C:\Users\shobh\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1241, in image_done
    image, os.path.basename(path), self.thumbnail_image_path
  File "C:\Users\shobh\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone\env\lib\ntpath.py", line 242, in basename
    return split(p)[1]
  File "C:\Users\shobh\AppData\Roaming\itch\apps\invokeai\invokeai_2_3_0_standalone\env\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by psychedelicious** [comment]
Thanks, something has gone awry as the application decides what to name the image. It does this by scanning the output  directory looking for the highest numbered image, then adding 1 to that number. This should be foolproof if the outputs directory is managed entirely by the application.

Did you paste any images into your output directory, rename anything in there, or otherwise touch it?

The most best way to fix this will be to look at the images in the outputs directory and figure out which one is causing the problem, then delete it or change its name to something without any numbers in it. Odds are, when you look at the file names, you'll see one that is obviously different from the rest.

You could also just move all images from the output directory somewhere else.

Please try again after those suggestions.
