### ISSUE TITLE
[bug]: txt2img got error: Compel.__init__() got an unexpected keyword argument 'truncate_long_prompts'

### ISSUE THREAD

**Issue by FreeBlues** [invoke-ai/InvokeAI#3048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

MacBookPro: intel CPU with an eGPU(RX 6600 8G)

### What version did you experience this issue on?

09dfde0b

### What happened?

After run `git pull` to  update invokeAI from `e0405031` to `09dfde0b`(the `e0405031` is ok),
Failed to generate an image, it return the error:

```
TypeError: Compel.__init__() got an unexpected keyword argument 'truncate_long_prompts'
```

### Screenshots

```
>> Image Generation Parameters:

{'prompt': 'a landscape and a cat [a cat]', 'iterations': 1, 'steps': 20, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'ddim', 'seed': 2175714035, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'hires_fix': False, 'seamless': False, 'variation_amount': 0}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
Compel.__init__() got an unexpected keyword argument 'truncate_long_prompts'


Traceback (most recent call last):
  File "/Users/ppt/Github/invokeAI/invokeai/backend/web/invoke_ai_web_server.py", line 1312, in generate_images
    self.generate.prompt2image(
  File "/Users/ppt/Github/invokeAI/invokeai/backend/generate.py", line 479, in prompt2image
    uc, c, extra_conditioning_info = get_uc_and_c_and_ec(
  File "/Users/ppt/Github/invokeAI/invokeai/backend/prompting/conditioning.py", line 37, in get_uc_and_c_and_ec
    compel = Compel(
TypeError: Compel.__init__() got an unexpected keyword argument 'truncate_long_prompts'
```

### Additional context

The version update log:

```
(base) ppt@pptdeMacBook-Pro invokeAI % git pull
remote: Enumerating objects: 4567, done.
remote: Counting objects: 100% (1907/1907), done.
remote: Compressing objects: 100% (272/272), done.
remote: Total 4567 (delta 1633), reused 1834 (delta 1588), pack-reused 2660
Receiving objects: 100% (4567/4567), 21.90 MiB | 188.00 KiB/s, done.
Resolving deltas: 100% (3018/3018), completed with 330 local objects.
From https://github.com/invoke-ai/InvokeAI
   e0405031..09dfde0b  main                                -> origin/main
   33411ec7..3d1164f9  JPPhoto-symmetry-enhancements       -> origin/JPPhoto-symmetry-enhancements
 * [new branch]        Model-Mgmt-API-Updates              -> origin/Model-Mgmt-API-Updates
 * [new branch]        bugfix/fix-merge-crash              -> origin/bugfix/fix-merge-crash
 * [new branch]        bugfix/move-localisation-files      -> origin/bugfix/move-localisation-files
 * [new branch]        dev/pytorch2                        -> origin/dev/pytorch2
 * [new branch]        feat/lora-training                  -> origin/feat/lora-training
 * [new branch]        feat/node-cli-autocompleter         -> origin/feat/node-cli-autocompleter
 * [new branch]        feat/unipc-scheduler                -> origin/feat/unipc-scheduler
 * [new branch]        feat/vae_tiling                     -> origin/feat/vae_tiling
   cc4e00d9..d313ae1c  gh-pages                            -> origin/gh-pages
 * [new branch]        kyle0654/cancel                     -> origin/kyle0654/cancel
 * [new branch]        kyle0654/model-api                  -> origin/kyle0654/model-api
 * [new branch]        kyle0654/node_latents               -> origin/kyle0654/node_latents
 * [new branch]        packaging/remove-binary-installer   -> origin/packaging/remove-binary-installer
 * [new branch]        refactor/move-models-and-generators -> origin/refactor/move-models-and-generators
 * [new branch]        release/v2.3.3-rc1                  -> origin/release/v2.3.3-rc1
 * [new branch]        unstale-issues                      -> origin/unstale-issues
   33f832e6..610a1483  v2.3                                -> origin/v2.3
 * [new tag]           v2.3.1.post2                        -> v2.3.1.post2
 * [new tag]           v2.3.2                              -> v2.3.2
 * [new tag]           v2.3.2.post1                        -> v2.3.2.post1
 * [new tag]           v2.3.3-rc1                          -> v2.3.3-rc1
Updating e0405031..09dfde0b
Fast-forward
```

The error log:

```
>> Image Generation Parameters:

{'prompt': 'a landscape and a cat [a cat]', 'iterations': 1, 'steps': 20, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'ddim', 'seed': 2175714035, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'hires_fix': False, 'seamless': False, 'variation_amount': 0}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
Compel.__init__() got an unexpected keyword argument 'truncate_long_prompts'


Traceback (most recent call last):
  File "/Users/ppt/Github/invokeAI/invokeai/backend/web/invoke_ai_web_server.py", line 1312, in generate_images
    self.generate.prompt2image(
  File "/Users/ppt/Github/invokeAI/invokeai/backend/generate.py", line 479, in prompt2image
    uc, c, extra_conditioning_info = get_uc_and_c_and_ec(
  File "/Users/ppt/Github/invokeAI/invokeai/backend/prompting/conditioning.py", line 37, in get_uc_and_c_and_ec
    compel = Compel(
TypeError: Compel.__init__() got an unexpected keyword argument 'truncate_long_prompts'
```

**Comment by damian0815** [comment]
@FreeBlues you'll need to update compel - after doing `git pull`, activate the InvokeAI python venv and run `pip install -e .` from the InvokeAI root dir

**Comment by FreeBlues** [comment]
> @FreeBlues you'll need to update Compel - after doing `git pull`, activate the InvokeAI python venv and run `pip install .` from the InvokeAI root dir

@damian0815  Thank you for the advice,  I update the Conda env and get another error, it looks like easy to deal with. 

The new error log:

```
Successfully built InvokeAI
Installing collected packages: InvokeAI
  Attempting uninstall: InvokeAI
    Found existing installation: InvokeAI 3.0.0+a0
    Uninstalling InvokeAI-3.0.0+a0:
      Successfully uninstalled InvokeAI-3.0.0+a0
Successfully installed InvokeAI-3.0.0+a0
(invokeai) ppt@pptdeMacBook-Pro invokeAI % python scripts/invoke.py --web --host 0.0.0.0
OMP: Error #15: Initializing libomp.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
zsh: abort      python scripts/invoke.py --web --host 0.0.0.0
(invokeai) ppt@pptdeMacBook-Pro invokeAI % 
```

**Comment by damian0815** [comment]
hmm, sorry, no idea about that. when that's happened to me in the past it's been due to a misconfigured environment. you could try rebuilding your invokeai .venv folder ..? if you're still using conda note it's no longer being actively supported.

**Comment by FreeBlues** [comment]
@damian0815 I think I got the reason,  both intel-openmp and llvm-openmp were installed, 
[here is a similar  issue](https://numba.discourse.group/t/prange-is-crashing-jupyter-lab-with-omp-error-15-initializing-libomp-dylib-but-found-libiomp5-dylib-already-initialized/577)

Do you mean the Conda will not be maintained?  It is a bad news.

**Comment by damian0815** [comment]
https://invoke-ai.github.io/InvokeAI/installation/020_INSTALL_MANUAL/:

```As of InvokeAI v2.3.0 installation using the conda package manager is no longer being supported. It will likely still work, but we are not testing this installation method.```
