### ISSUE TITLE
[bug]:  ERROR: Could not install packages due to an OSError

### ISSUE THREAD

**Issue by rokiLeeves** [invoke-ai/InvokeAI#3124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.3.3

### What happened?

when  use the  install.bat  with the administrator.

❗ Directory E:\InvokeAi already exists ❗
🛑 Are you sure you want to (re)install in this location? [y/n] (n): y

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pip in e:\invokeai\.venv\lib\site-packages (21.1.1)
Collecting pip
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/07/51/2c0959c5adf988c44d9e1e0d940f5b074516ecc87e96b1af25f59de9ba38/pip-23.0.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
ERROR: Could not install packages due to an OSError: [WinError 5] [Access is denied]: 'e:\\invokeai\\.venv\\scripts\\pip.exe'
Check the permissions.

Traceback (most recent call last):
  File "G:\download\InvokeAI-installer-v2.3.3\InvokeAI-Installer\lib\main.py", line 50, in <module>
    inst.install(**args.__dict__)
  File "G:\download\InvokeAI-installer-v2.3.3\InvokeAI-Installer\lib\installer.py", line 173, in install
    self.venv = self.app_venv()
  File "G:\download\InvokeAI-installer-v2.3.3\InvokeAI-Installer\lib\installer.py", line 148, in app_venv
    pip[ "install", "--upgrade", "pip"] & FG
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\base.py", line 252, in run
    return p.run()
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\processes.py", line 304, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\machines\base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | 'E:\InvokeAi\.venv\Scripts\pip.exe' install --upgrade pip

### Screenshots

when  use the  install.bat  with the administrator.

❗ Directory E:\InvokeAi already exists ❗
🛑 Are you sure you want to (re)install in this location? [y/n] (n): y

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pip in e:\invokeai\.venv\lib\site-packages (21.1.1)
Collecting pip
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/07/51/2c0959c5adf988c44d9e1e0d940f5b074516ecc87e96b1af25f59de9ba38/pip-23.0.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'e:\\invokeai\\.venv\\scripts\\pip.exe'
Check the permissions.

Traceback (most recent call last):
  File "G:\download\InvokeAI-installer-v2.3.3\InvokeAI-Installer\lib\main.py", line 50, in <module>
    inst.install(**args.__dict__)
  File "G:\download\InvokeAI-installer-v2.3.3\InvokeAI-Installer\lib\installer.py", line 173, in install
    self.venv = self.app_venv()
  File "G:\download\InvokeAI-installer-v2.3.3\InvokeAI-Installer\lib\installer.py", line 148, in app_venv
    pip[ "install", "--upgrade", "pip"] & FG
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\base.py", line 252, in run
    return p.run()
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\processes.py", line 304, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\commands\processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "C:\Users\45319\AppData\Local\Temp\invokeai-installer-tmpmxdok3dy\Lib\site-packages\plumbum\machines\base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | 'E:\InvokeAi\.venv\Scripts\pip.exe' install --upgrade pip

**Comment by ovladuk** [comment]
did you fix it?

**Comment by rokiLeeves** [comment]
> 
ha ha ....
actually,i get it,
but , It's been too long since then, i  have fotgot that how to fit it  .....
sorry ~

> did you fix it?

**Comment by aWilson41** [comment]
I got this once because I have visual studios python. Not likely your issue but just putting it out there. InvokeAI seems to do some wonky stuff. Running through visual studio developer command prompt fixes it.
