### ISSUE TITLE
[bug]: No image generated | NotImplementedError: No operator found for `memory_efficient_attention_forward` 

### ISSUE THREAD

**Issue by xasx** [invoke-ai/InvokeAI#3130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

2.3.3

### What happened?

When trying to generate an image, I get a grey image.
The console reveals the following error:

```
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(16, 4096, 1, 40) (torch.float32)
     key         : shape=(16, 4096, 1, 40) (torch.float32)
     value       : shape=(16, 4096, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    triton is not available
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 40

```

I selected CUDA when installing. GPU is Nvidia RTX A3000 12GB Laptop.

A bit of research led me to this issue https://github.com/facebookresearch/xformers/issues/517
That made me trying to update xformers, however, new versions require torch 2.0 which inherently breaks InvokeAI when applying the update.

Is there any chance to get this fixed?

**Comment by xasx** [comment]
I tried branch dev/pytorch2, but for some reason, all generation runs on the CPU and is very slow. 

I don't get what's wrong with my setup.

**Comment by blessedcoolant** [comment]
Did you try installing an older version of xformers that works with the torch version you have installed?

You can find them here: https://pypi.org/project/xformers/#history

I'd say something around the version `0.0.16` might do.

**Comment by lstein** [comment]
I'm disturbed that the installation gave you a nonworking version of xformers. After the initial install did you do an update of any sort that might have brought in a new xformers?

In any case, here's what I'd recommend you try to fix the issue.
1. Launch `invokeai.bat`
2. Choose "Developer's console" from the menu
3. At the console command line prompt issue the following command:
```
pip install "InvokeAI[xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117
```
4. Exit the console by typing control-Z and return
5. Relaunch InvokeAI

**Comment by xasx** [comment]
I get this message on startup

```
Please enter 1-10, Q: [2] 2
Starting the InvokeAI browser-based UI..
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 1.13.1+cu117 with CUDA 1107 (you have 2.0.0+cpu)
    Python  3.10.9 (you have 3.10.10)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

```

I probably am on a different branch. So I get to make a new installation.

**Comment by xasx** [comment]
So I chose a different path for installation and now it seems to work. Not sure why it didn't work previously.

I am now seeing 
```

>> Using device_type cuda
>> CUDA device 'NVIDIA RTX A3000 12GB Laptop GPU' (GPU 0)

```
which I didn't see before if I recall correctly.

**Comment by poojan-solanki** [comment]
I also have similar error

```
[2023-08-05 16:38:38,812]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\app\services\processor.py", line 86, in __process
    outputs = invocation.invoke(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 363, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 461, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 194, in __call__
    for result in self.generator_method(*args, **kwargs):
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 515, in generate_latents_from_embeddings
    step_output = self.step(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 651, in step
    noise_pred = self.invokeai_diffuser.do_diffusion_step(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusion\shared_invokeai_diffusion.py", line 204, in do_diffusion_step
    ) = self._apply_standard_conditioning(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusion\shared_invokeai_diffusion.py", line 290, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 695, in _unet_forward
    return self.unet(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 915, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 996, in forward
    hidden_states = attn(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\diffusers\models\transformer_2d.py", line 292, in forward
    hidden_states = block(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\diffusers\models\attention.py", line 155, in forward
    attn_output = self.attn1(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\diffusers\models\attention_processor.py", line 322, in forward
    return self.processor(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\diffusers\models\attention_processor.py", line 1034, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 306, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 94, in _dispatch_fw
    return _run_priority_list(
  File "C:\Users\bluts\Downloads\InvokeAI-installer-v3.0.1\InvokeAI-Installer\outputs\.venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 69, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(16, 4096, 1, 40) (torch.float32)
     key         : shape=(16, 4096, 1, 40) (torch.float32)
     value       : shape=(16, 4096, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    has custom scale
    unsupported embed per head: 40

[2023-08-05 16:38:38,823]::[InvokeAI]::ERROR --> Error while invoking:
No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(16, 4096, 1, 40) (torch.float32)
     key         : shape=(16, 4096, 1, 40) (torch.float32)
     value       : shape=(16, 4096, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    has custom scale
    unsupported embed per head: 40

```
I also ran 
`pip install "InvokeAI[xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117`
it says requirement already satisfied
