### ISSUE TITLE
[bug]: Web-UI cannot process image deletion well when run in docker

### ISSUE THREAD

**Issue by pryadchenko** [invoke-ai/InvokeAI#3189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

2.3.4

### What happened?

I'm using docker image. Web-ui works well, except of when I'm trying to delete image, the following error occurs in the log:
>> Delete requested "outputs/000001.1b8f7b54.2640834933.png"

```
Traceback (most recent call last):
  File "/usr/src/InvokeAI/lib/python3.9/site-packages/invokeai/backend/web/invoke_ai_web_server.py", line 877, in handle_delete_image
    send2trash(path)
  File "/usr/src/InvokeAI/lib/python3.9/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/usr/src/InvokeAI/lib/python3.9/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/data/outputs/000001.1b8f7b54.2640834933.png' -> b'/data/.Trash-1000/files/000001.1b8f7b54.2640834933.png'
```

and web interface hangs.

**Comment by pryadchenko** [comment]
Looks like docker does not expose <host>:9090/outputs/<image_name>.png. Only if image has been cached right after generation it is possible to see it, otherwise it receives 404.
