### ISSUE TITLE
[bug]: Uncaught exception when trying to Update InvokeAI 

### ISSUE THREAD

**Issue by pedantic79** [invoke-ai/InvokeAI#3228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

v2.3.4.post1

### What happened?

This started after updating to v2.3.4.post1

Ran `invoke.sh`, select option 9 `Update InvokeAI`

I get this uncaught exception:

```
Traceback (most recent call last):
  File "/Users/myuser/invokeai/.venv/lib/python3.10/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/myuser/invokeai/.venv/lib/python3.10/site-packages/psutil/_psosx.py", line 404, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myuser/invokeai/.venv/bin/invokeai-update", line 8, in <module>
    sys.exit(main())
  File "/Users/myuser/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/config/invokeai_update.py", line 77, in main
    if invokeai_is_running():
  File "/Users/myuser/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/config/invokeai_update.py", line 37, in invokeai_is_running
    cmdline = p.cmdline()
  File "/Users/myuser/invokeai/.venv/lib/python3.10/site-packages/psutil/__init__.py", line 681, in cmdline
    return self._proc.cmdline()
  File "/Users/myuser/invokeai/.venv/lib/python3.10/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=83567)
```

Looks like this was introduced in commit 31333a7

Commit 1873817 added code to ignore `psutil.AccessDenied`, but it looks like it should also ignore `psutil.NoSuchProcess` since a process might have ended while the check is being done.

**Comment by temperatio** [comment]
same here

**Comment by caunus** [comment]
same here since the last update.

**Comment by nelsonre** [comment]
As a workaround until they fix this issue, I commented out these lines from invokeai_update.py:
```
    # if invokeai_is_running():
    #     print(f':exclamation: [bold red]Please terminate all running instances of InvokeAI before updating.[/red bold]')
    #     return
```
With the lines commented out, I was able to upgrade invokeai to 2.3.5-rc2

**Comment by caunus** [comment]
Hi @nelsonre,
sorry took some days testing your workaround. Thanks seems to work, at least I updated successfully to 2.3.5. After that I got a new version that file  with the same bug.
But at least I was able to make an update. Thanks again.
