### ISSUE TITLE
[bug]: 2.3.5rc1 fails to load LoRAs with non-default root_dir

### ISSUE THREAD

**Issue by maxdumas** [invoke-ai/InvokeAI#3293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

2.3.5rc1

### What happened?

InvokeAI fails when attempting to load LoRAs in 2.3.5rc1 with a non-default root_dir value. Two different error variations occur, both included below:

```
>> Initialization file /mnt/efs/fs1/invokeai/invokeai.init found. Loading...
>> Started Invoke AI Web Server!
Point your browser at http://localhost:9090 or use the host's DNS name or IP address.
>> System config requested
>> Patchmatch initialized


Traceback (most recent call last):
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/invokeai/backend/invoke_ai_web_server.py", line 528, in get_lora_models
    loras = lora_mgr.list_compatible_loras()
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/ldm/modules/lora_manager.py", line 78, in list_compatible_loras
    return self.list_loras(model_length)
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/ldm/modules/lora_manager.py", line 99, in list_loras
    elif token_vector_length == KohyaLoraManager.vector_length_from_checkpoint_file(path):
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/ldm/modules/kohya_lora_manager.py", line 553, in vector_length_from_checkpoint_file
    with LoraVectorLengthCache(self.vector_length_cache_path) as cache:
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/ldm/modules/kohya_lora_manager.py", line 573, in __enter__
    self.lock.acquire(timeout=10)
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/filelock/_api.py", line 182, in acquire
    self._acquire()
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/filelock/_unix.py", line 36, in _acquire
    fd = os.open(self._lock_file, open_flags, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/invokeai/loras/.cachelock'


>> System config requested



  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/ldm/modules/lora_manager.py", line 78, in list_compatible_loras
    return self.list_loras(model_length)
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/ldm/modules/kohya_lora_manager.py", line 573, in __enter__
    self.lock.acquire(timeout=10)
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/filelock/_api.py", line 182, in acquire
    self._acquire()
  File "/opt/conda/envs/invokeai/lib/python3.10/site-packages/filelock/_unix.py", line 36, in _acquire
    fd = os.open(self._lock_file, open_flags, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/invokeai/loras/.cachelock'
```

As this error indicates, it appears `filelock` is expecting to be able to create a `.cachelock` file in the default InvokeAI directory (which does not exist for me), and is failing to respect the `--root_dir` parameter, which I specified as `/mnt/fs1/invokeai`

**Comment by maxdumas** [comment]
Discussion #3288 references the same issue.

**Comment by lstein** [comment]
Thanks for the bug report. Working on it now.

**Comment by Rhyxivar** [comment]
Sorry for the necro but I'm getting something similar even in 2.3.5rc2:

 File "E:\Invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 528, in get_lora_models
    loras = lora_mgr.list_compatible_loras()
  File "E:\Invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\ldm\modules\lora_manager.py", line 78, in list_compatible_loras
    return self.list_loras(model_length)
  File "E:\Invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\ldm\modules\lora_manager.py", line 99, in list_loras    elif token_vector_length == KohyaLoraManager.vector_length_from_checkpoint_file(path):
  File "E:\Invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\ldm\modules\kohya_lora_manager.py", line 555, in vector_length_from_checkpoint_file
    with LoraVectorLengthCache(self.vector_length_cache_path) as cache:
  File "E:\Invokeai\invokeai_2_3_0_standalone\env\lib\site-packages\ldm\modules\kohya_lora_manager.py", line 571, in __init__
    print(f'DEBUG: lock path = {Path(cache_path.parent, ".cachelock")}')
AttributeError: 'NoneType' object has no attribute 'parent'

**Comment by maxyvisser** [comment]
This appears to be fixed in 2.3.5rc3
