### ISSUE TITLE
[bug]: Can't load any LORA files -> Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by jellersby** [invoke-ai/InvokeAI#3359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

24GB

### What version did you experience this issue on?

2.3.5

### What happened?

Loading any model results in the red "Error" label in the UI. However, the model DOES load; it's just that no LORAs end up loading due to the following error in the console:
```
Traceback (most recent call last):
  File "/opt/ml/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/invoke_ai_web_server.py", line 528, in get_lora_models
    loras = lora_mgr.list_compatible_loras()
  File "/opt/ml/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/lora_manager.py", line 78, in list_compatible_loras
    return self.list_loras(model_length)
  File "/opt/ml/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/lora_manager.py", line 99, in list_loras
    elif token_vector_length == KohyaLoraManager.vector_length_from_checkpoint_file(path):
  File "/opt/ml/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/kohya_lora_manager.py", line 565, in vector_length_from_checkpoint_file
    checkpoint = load_file(
  File "/opt/ml/invokeai/.venv/lib/python3.10/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

For debugging purposes, I put just one LORA file at a time into the loras dir. I haven't been able to get any Civitai LORA files to load. Here are two examples:
https://civitai.com/models/55613/rwps1
https://civitai.com/models/21270/pixhell-15-lora

### Contact Details

jellersby@protonmail.com

**Comment by andupotorac** [comment]
Same issue happens on my end. Using Invoke 3.0.
