### ISSUE TITLE
[bug]: Unable to download main models

### ISSUE THREAD

**Issue by metal3d** [invoke-ai/InvokeAI#3374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.5.3

### What happened?

I completely reinstalled InvokeAI because update script shown me some errors while downloading the models.
I removed `~/invokeai` then installed as usual with the installer.

Then the page to select models appears and I selected:

![image](https://github.com/invoke-ai/InvokeAI/assets/100080/53b1ff6d-233c-4a7f-9b9f-ff7c84488aec)

This is what happens:

```
>> Loading diffusers model from runwayml/stable-diffusion-v1-5
   | Using faster float16 precision
   | Loading diffusers VAE from stabilityai/sd-vae-ft-mse
** An unexpected error occurred while downloading the model: 404 Client Error: Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/fp16 (Request ID: Root=1-645a5b47-74ce206a69691a1473bcc000)

Sorry, we can't find the page you are looking for.)
** An unexpected error occurred while downloading the model: 404 Client Error: Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5 (Request ID: Root=1-645a5b47-53ade606315c7d0b7ef60fba)

Sorry, we can't find the page you are looking for.)
** model stable-diffusion-1.5 could not be loaded: "runwayml/stable-diffusion-v1-5" could not be loaded
Traceback (most recent call last):
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/generate.py", line 959, in set_model
    model_data = cache.get_model(model_name)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 107, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 325, in _load_model
    model, width, height, model_hash = self._load_diffusers_model(mconfig)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 446, in _load_diffusers_model
    assert pipeline is not None, OSError(f'"{name_or_path}" could not be loaded')
AssertionError: "runwayml/stable-diffusion-v1-5" could not be loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/CLI.py", line 161, in main
    gen.load_model()
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/generate.py", line 927, in load_model
    return self.set_model(self.model_name)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/generate.py", line 966, in set_model
    model_data = cache.get_model(previous_model_name)  # load previous
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 107, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 325, in _load_model
    model, width, height, model_hash = self._load_diffusers_model(mconfig)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 446, in _load_diffusers_model
    assert pipeline is not None, OSError(f'"{name_or_path}" could not be loaded')
AssertionError: "runwayml/stable-diffusion-v1-5" could not be loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/generate.py", line 959, in set_model
    model_data = cache.get_model(model_name)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 107, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 325, in _load_model
    model, width, height, model_hash = self._load_diffusers_model(mconfig)
  File "/home/metal3d/invokeai/.venv/lib64/python3.10/site-packages/ldm/invoke/model_manager.py", line 446, in _load_diffusers_model
    assert pipeline is not None, OSError(f'"{name_or_path}" could not be loaded')
AssertionError: "runwayml/stable-diffusion-v1-5" could not be loaded

** trying to reload previous model
>> Loading diffusers model from runwayml/stable-diffusion-v1-5
   | Using faster float16 precision
   | Loading diffusers VAE from stabilityai/sd-vae-ft-mse
** An unexpected error occurred while downloading the model: 404 Client Error: Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/fp16 (Request ID: Root=1-645a5b48-676e3fb210a6f00634517b9a)

Sorry, we can't find the page you are looking for.)
** An unexpected error occurred while downloading the model: 404 Client Error: Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5 (Request ID: Root=1-645a5b48-1528a5717ce87e57741f26d4)

Sorry, we can't find the page you are looking for.)
** An error occurred while attempting to initialize the model: ""runwayml/stable-diffusion-v1-5" could not be loaded"
** This can be caused by a missing or corrupted models file, and can sometimes be fixed by (re)installing the models.
Do you want to run invokeai-configure script to select and/or reinstall models? [y/N]:
```

I tried to answer "y" and reinstall models, the error is repeating.

### Contact Details

metal3d@gmail.com

**Comment by metal3d** [comment]
That's the same for a lot of (unfortunately for me) major models that I usually use... I will try to install throught the interface with model URLs.

**Comment by metal3d** [comment]
It seems to be fixed. Hugginface, on discord, said that they had issues.
Sorry for the bad placed issue :)
