### ISSUE TITLE
[bug]: Inference pipeline breaks with app/cli_app.py

### ISSUE THREAD

**Issue by saikrishna2893** [invoke-ai/InvokeAI#3429]
### OS

Windows

### GPU

amd

### What version did you experience this issue on?

from the latest main branch

### What happened?

Have followed the steps for backend execution of pipeline as listed out on [Discussion ](https://github.com/invoke-ai/InvokeAI/discussions/3246) page.

- Tried running python scripts/invoke-new.py as suggested.
- Few package issues are observed, resolved them.
- Started facing error with basic commands like : txt2img --prompt "an old man reading newspaper" - below quoted error
t2l --prompt "an old man reading newspaper" | l2i - Warning --> Invalid command.
Facing error as in below snippet.
```
(test_Invoekai) C:\Users\user1\Invokeai\InvokeAI>python scripts\invoke-new.py
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> Patchmatch initialized
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> Initializing, be patient...
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> Initialization file C:\Users\mcw\invokeai\invokeai.init found. Loading...
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> InvokeAI, version 3.0.0+a0
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> InvokeAI runtime directory is "C:\Users\mcw\invokeai"
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> Model manager initialized
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> GFPGAN Initialized
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> CodeFormer Initialized
[16-05-2023 03:48:08]::[InvokeAI]::INFO --> Face restoration initialized
**invoke> txt2img --prompt "an old man reading newspaper"**
[16-05-2023 03:48:14]::[InvokeAI]::INFO --> Loading diffusers model from runwayml/stable-diffusion-v1-5
[16-05-2023 03:48:14]::[InvokeAI]::DEBUG --> Using more accurate float32 precision
[16-05-2023 03:48:14]::[InvokeAI]::DEBUG --> Loading diffusers VAE from stabilityai/sd-vae-ft-mse
[16-05-2023 03:48:14]::[InvokeAI]::DEBUG --> Using more accurate float32 precision
[16-05-2023 03:48:16]::[InvokeAI]::DEBUG --> Default image dimensions = 512 x 512
[16-05-2023 03:48:16]::[InvokeAI]::INFO --> Loading embeddings from C:\Users\mcw\Documents\InvokeAI_org\invokeai\embeddings
[16-05-2023 03:48:16]::[InvokeAI]::INFO --> Textual inversion triggers:
[16-05-2023 03:48:16]::[InvokeAI]::INFO --> Model loaded in 2.13s
Generating:   0%|                                                                                                                                | 0/1 [00:00<?, ?it/s]
[16-05-2023 03:48:17]::[InvokeAI]::ERROR --> Error in node fe27d5da-b317-43e1-851e-5ec112abcdb8 (source node 0): Traceback (most recent call last):
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\app\services\processor.py", line 70, in __process
    outputs = invocation.invoke(
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\app\invocations\generate.py", line 92, in invoke
    generate_output = next(outputs)
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\backend\generator\base.py", line 144, in generate
    results = generator.generate(prompt,
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\backend\generator\base.py", line 374, in generate
    image = make_image(x_T, seed)
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\backend\generator\txt2img.py", line 65, in make_image
    pipeline_output = pipeline.image_from_embeddings(
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 480, in image_from_embeddings
    result_latents, result_attention_map_saver = self.latents_from_embeddings(
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 523, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 207, in __call__
    callback(result)
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\app\invocations\generate.py", line 66, in dispatch_progress
    stable_diffusion_step_callback(
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\app\util\step_callback.py", line 40, in stable_diffusion_step_callback
    image = Generator.sample_to_lowres_estimated_image(sample)
  File "C:\Users\user1\Invokeai\InvokeAI\invokeai\backend\generator\base.py", line 514, in sample_to_lowres_estimated_image
    latent_image = samples[0].permute(1, 2, 0) @ v1_5_latent_rgb_factors
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

[16-05-2023 03:48:17]::[InvokeAI]::WARNING --> Session error: creating a new session
```

Testing as part of understanding the Nodestructure changes as suggested in [PR#3380](https://github.com/invoke-ai/InvokeAI/pull/3380#pullrequestreview-1421128861)

**Comment by hipsterusername** [comment]
The CLI is completely changing with Nodes, moving to a new graph/node based syntax. CLI is not quite ready yet - Stay tuned for more details.
