### ISSUE TITLE
[bug]: Lora not working (RuntimeError: output with shape [128, 320] doesn't match the broadcast shape [128, 320, 128, 320])

### ISSUE THREAD

**Issue by pivot69** [invoke-ai/InvokeAI#3436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64gb

### What version did you experience this issue on?

2.3.5

### What happened?

Loras placed in lora directory is recognised fine, but when I try to include it in a prompt it will only result in an error:

`   | Loading lora 21NEIGHBORS.safetensors with weight 0.75
   | Found lora 21NEIGHBORS at /Users/pivot/invokeai/loras/21NEIGHBORS.safetensors
** Could not generate image.
output with shape [128, 320] doesn't match the broadcast shape [128, 320, 128, 320]

Traceback (most recent call last):
  File "/Users/pivot/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/invoke_ai_web_server.py", line 1344, in generate_images
    self.generate.prompt2image(
  File "/Users/pivot/invokeai/.venv/lib/python3.10/site-packages/ldm/generate.py", line 525, in prompt2image
    uc, c, extra_conditioning_info = get_uc_and_c_and_ec(
  File "/Users/pivot/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/conditioning.py", line 79, in get_uc_and_c_and_ec
    with InvokeAIDiffuserComponent.custom_attention_context(model.unet,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/pivot/invokeai/.venv/lib/python3.10/site-packages/ldm/models/diffusion/shared_invokeai_diffusion.py", line 103, in custom_attention_context
    condition() # target model is stored in condition state for some reason
  File "/Users/pivot/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/lora_manager.py", line 43, in __call__
    self.kohya_manager.apply_lora_model(self.name,self.weight)
  File "/Users/pivot/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/kohya_lora_manager.py", line 508, in apply_lora_model
    lora = self.load_lora_module(name, path_file, mult)
  File "/Users/pivot/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/kohya_lora_manager.py", line 489, in load_lora_module
    lora.load_from_dict(checkpoint)
  File "/Users/pivot/invokeai/.venv/lib/python3.10/site-packages/ldm/modules/kohya_lora_manager.py", line 366, in load_from_dict
    layer_down.weight.copy_(value_down)
RuntimeError: output with shape [128, 320] doesn't match the broadcast shape [128, 320, 128, 320]

`

**Comment by pivot69** [comment]
Was this Closed/resolved because its fixed in 3.0.0?

**Comment by hipsterusername** [comment]
It’ll need to be retested in 3.0 but we anticipate many Lora issues will be fixed

**Comment by hipsterusername** [comment]
We have a new model directory and management system.

**Comment by pivot69** [comment]
Awesome! Looking forward to testing 3.0.0. Great work!

**Comment by Neosettler** [comment]
I understand 3.0 will fix this but is there an explanation/workaround why 2.1 LoRA (with 2.1 models) files spit out this error in 2.3.5?

**Comment by hipsterusername** [comment]
The shape [128, 320] didn’t match the broadcast shape [128, 320, 128, 320], indicating the 2.1 Lora’s weren’t being handled correctly.

**Comment by pivot69** [comment]
Great explanation! 😆
Congrats on closing in on 3.0 release!
