### ISSUE TITLE
[bug]: Debian 11 automated installation fails on PyTorch install

### ISSUE THREAD

**Issue by nekrasovdmitriy** [invoke-ai/InvokeAI#3440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16GB

### What version did you experience this issue on?

2.3.5.post1

### What happened?

Trying to install with automated installer, using Debian 11, Nvidia driver 525.116.04.

`(.venv) root@sd:/home/debian/invokeai# python --version
Python 3.10.9`

`(.venv) root@sd:/home/debian/invokeai# pip --version
pip 22.3.1 from /home/debian/invokeai/.venv/lib/python3.10/site-packages/pip (python 3.10)`

Installation failed every time after:

`Installing collected packages: mpmath, lit, cmake, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, triton, torch, torchvision`

It shows:

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/debian/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/debian/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/debian/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 494, in run
    installed = install_given_reqs(
  File "/home/debian/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/home/debian/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 792, in install
    install_wheel(
  File "/home/debian/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 729, in install_wheel
    _install_wheel(
  File "/home/debian/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 589, in _install_wheel
    file.save()
  File "/home/debian/invokeai/.venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "/usr/local/lib/python3.10/shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/local/lib/python3.10/zipfile.py", line 925, in read
    data = self._read1(n)
  File "/usr/local/lib/python3.10/zipfile.py", line 1001, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid block type

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: /home/debian/invokeai/.venv/bin/python3.10 -m pip install --upgrade pip
Traceback (most recent call last):
  File "/home/debian/InvokeAI-Installer/./lib/main.py", line 50, in <module>
    inst.install(**args.__dict__)
  File "/home/debian/InvokeAI-Installer/lib/installer.py", line 179, in install
    self.instance.install(
  File "/home/debian/InvokeAI-Installer/lib/installer.py", line 232, in install
    self.install_torch(extra_index_url, find_links)
  File "/home/debian/InvokeAI-Installer/lib/installer.py", line 250, in install_torch
    pip[
  File "/tmp/invokeai-installer-tmp4gxm9eop/lib/python3.10/site-packages/plumbum/commands/modifiers.py", line 145, in __rand__
    cmd(
  File "/tmp/invokeai-installer-tmp4gxm9eop/lib/python3.10/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "/tmp/invokeai-installer-tmp4gxm9eop/lib/python3.10/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
  File "/tmp/invokeai-installer-tmp4gxm9eop/lib/python3.10/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "/tmp/invokeai-installer-tmp4gxm9eop/lib/python3.10/site-packages/plumbum/commands/processes.py", line 304, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/tmp/invokeai-installer-tmp4gxm9eop/lib/python3.10/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/tmp/invokeai-installer-tmp4gxm9eop/lib/python3.10/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 2
Command line: | /home/debian/invokeai/.venv/bin/pip install --require-virtualenv 'torch~=2.0.0' 'torchvision>=0.14.1' --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu117
```

I tried Python 3.9, pip 23.1.2, manual install... all the same.

### Screenshots

<img width="1081" alt="Снимок экрана 2023-05-20 в 20 26 00" src="https://github.com/invoke-ai/InvokeAI/assets/18664106/7c8e422e-84cc-4e99-8a38-eb68e8c6ceca">
<img width="1410" alt="Снимок экрана 2023-05-20 в 20 33 10" src="https://github.com/invoke-ai/InvokeAI/assets/18664106/e9497193-455a-43ab-bbce-1fda5450cbe1">

### Contact Details

mail@dmitrynekrasov.ru

**Comment by ebr** [comment]
This is not a problem with Invoke. Looks like failure to decompress the archive, which indicates it might have been corrupted when downloading.

Try to purge the pip cache and reinstall. `python -m pip cache purge` .

**Comment by nekrasovdmitriy** [comment]
Thanks for reply, i will try it
