### ISSUE TITLE
[bug]: Error running invokeai-configure - no module named _curses - on Linux

### ISSUE THREAD

**Issue by jmkgreen** [invoke-ai/InvokeAI#3445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

main

### What happened?

I ran through the CLI installation which worked a treat until the following hit me:

```
(InvokeAI) [ec2-user@ip-172-31-27-250 invokeai]$ deactivate && source .venv/bin/activate
(InvokeAI) [ec2-user@ip-172-31-27-250 invokeai]$ invokeai-configure
Loading Python libraries...

Traceback (most recent call last):
  File "/home/ec2-user/invokeai/.venv/bin/invokeai-configure", line 5, in <module>
    from ldm.invoke.config.invokeai_configure import main
  File "/home/ec2-user/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/config/invokeai_configure.py", line 23, in <module>
    import npyscreen
  File "/home/ec2-user/invokeai/.venv/lib/python3.10/site-packages/npyscreen/__init__.py", line 5, in <module>
    from .wgwidget                  import TEST_SETTINGS, ExhaustedTestInput, add_test_input_from_iterable, add_test_input_ch
  File "/home/ec2-user/invokeai/.venv/lib/python3.10/site-packages/npyscreen/wgwidget.py", line 5, in <module>
    import curses
  File "/usr/local/lib/python3.10/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
(InvokeAI) [ec2-user@ip-172-31-27-250 invokeai]$ python
Python 3.10.10 (main, Mar 24 2023, 16:01:42) [GCC 7.3.1 20180712 (Red Hat 7.3.1-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

The OS is a fully up to date Amazon Linux 2. I have even tried with `libncurses-dev` but that did not help.

**Comment by jmkgreen** [comment]
Thanks @lstein - I downloaded Python 3.10.11 and after adding ncurses-devel through yum managed to configure and install. The configuration tool now launches.

Might be handy to detect this situation and warn instead of just crashing. I'm sure there are many such scenarios!
