### ISSUE TITLE
[bug]: Can't change model 

### ISSUE THREAD

**Issue by ShmuelRonen** [invoke-ai/InvokeAI#3472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

2.3.5 post 2

### What happened?

Got error when try to replace model

>> Model change requested: lofi_V21Inpaint
>> Current VRAM usage:  2.17G
>> Offloading lofi_V21 to CPU
>> Loading lofi_V21Inpaint from C:/vlad/automatic/models/Stable-diffusion/lofi_V21Inpaint.safetensors
>> Converting legacy checkpoint lofi_V21Inpaint into a diffusers model...
   | global_step key not found in model
** model lofi_V21Inpaint could not be loaded: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
Traceback (most recent call last):
  File "C:\Users\derec\invokeai\.venv\lib\site-packages\ldm\generate.py", line 964, in set_model
    model_data = cache.get_model(model_name)
  File "C:\Users\derec\invokeai\.venv\lib\site-packages\ldm\invoke\model_manager.py", line 105, in get_model
    requested_model, width, height, hash = self._load_model(model_name)
  File "C:\Users\derec\invokeai\.venv\lib\site-packages\ldm\invoke\model_manager.py", line 317, in _load_model
    model, width, height, model_hash = self._load_ckpt_model(
  File "C:\Users\derec\invokeai\.venv\lib\site-packages\ldm\invoke\model_manager.py", line 376, in _load_ckpt_model
    pipeline = load_pipeline_from_original_stable_diffusion_ckpt(
  File "C:\Users\derec\invokeai\.venv\lib\site-packages\ldm\invoke\ckpt_to_diffuser.py", line 1230, in load_pipeline_from_original_stable_diffusion_ckpt
    unet.load_state_dict(converted_unet_checkpoint)
  File "C:\Users\derec\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).

** trying to reload previous model
>> Retrieving model lofi_V21 from system RAM cache
>> Textual inversion triggers:
>> Setting Sampler to k_lms (LMSDiscreteScheduler)

**Comment by gogurtenjoyer** [comment]
This is an inpainting model - when you add it via the model manager, make sure you select the 'inpainting' type.
