### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by q444781603** [invoke-ai/InvokeAI#3557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.3.5.post2

### What happened?

(InvokeAI) PS I:\AIProject\invokeai> invokeai-ti --gui
logging_dirC:\Users\Vmprotect\invokeai\text-inversion-output\fenglai\logs
** An exception occurred during training. The exception was:
Accelerator.__init__() got an unexpected keyword argument 'logging_dir'
** DETAILS:
Traceback (most recent call last):
  File "I:\AIProject\invokeai\.venv\lib\site-packages\ldm\invoke\training\textual_inversion.py", line 425, in do_front_end
    do_textual_inversion_training(**args)
  File "I:\AIProject\invokeai\.venv\lib\site-packages\ldm\invoke\training\textual_inversion_training.py", line 582, in do_textual_inversion_training
    accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'logging_dir'

**Comment by q444781603** [comment]
use accelerate-0.18.0
