### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by PatheticProgrammingPerson** [invoke-ai/InvokeAI#3605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

2.3.5.post2

### What happened?

On a fresh installation of InvokeAI, attempting to generate gives the following error:  

```
** Could not generate image.
No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(16, 4096, 1, 40) (torch.float32)
     key         : shape=(16, 4096, 1, 40) (torch.float32)
     value       : shape=(16, 4096, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    has custom scale
    unsupported embed per head: 40


Traceback (most recent call last):
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1344, in generate_images
    self.generate.prompt2image(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\generate.py", line 570, in prompt2image
    results = generator.generate(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\invoke\generator\base.py", line 115, in generate
    image = make_image(x_T)
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\invoke\generator\txt2img.py", line 45, in make_image
    pipeline_output = pipeline.image_from_embeddings(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 431, in image_from_embeddings
    result_latents, result_attention_map_saver = self.latents_from_embeddings(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 457, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 180, in __call__
    for result in self.generator_method(*args, **kwargs):
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 494, in generate_latents_from_embeddings
    step_output = self.step(batched_t, latents, conditioning_data,
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 538, in step
    noise_pred = self.invokeai_diffuser.do_diffusion_step(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\models\diffusion\shared_invokeai_diffusion.py", line 218, in do_diffusion_step
    ) = self._apply_standard_conditioning(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\models\diffusion\shared_invokeai_diffusion.py", line 271, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 572, in _unet_forward
    return self.unet(latents, t, text_embeddings,
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 724, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 867, in forward
    hidden_states = attn(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\diffusers\models\transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\diffusers\models\attention.py", line 313, in forward
    attn_output = self.attn1(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\diffusers\models\attention_processor.py", line 267, in forward
    return self.processor(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\diffusers\models\attention_processor.py", line 696, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 306, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 94, in _dispatch_fw
    return _run_priority_list(
  File "C:\Users\[redacted]\Documents\AI\Stable Diffusion\InvokeAI\.venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 69, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(16, 4096, 1, 40) (torch.float32)
     key         : shape=(16, 4096, 1, 40) (torch.float32)
     value       : shape=(16, 4096, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    has custom scale
    unsupported embed per head: 40
```

### Additional context

I have previously got Invoke to work on this same machine (uninstalled for space some time ago)

Tested with both 1.5 and 2.1 models, same results. 

### Contact Details

8v1np04j@duck.com

**Comment by PatheticProgrammingPerson** [comment]
I installed via the automatic installer script

**Comment by PatheticProgrammingPerson** [comment]
I installed via the automatic installer script, from the latest release, which should have been  `3b2e02` at the time.
