### ISSUE TITLE
[bug]: I'm unable to complete installation

### ISSUE THREAD

**Issue by PollutionPotential** [invoke-ai/InvokeAI#3687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What version did you experience this issue on?

2.3.5 Post 2

### What happened?

ERROR: Exception:
Traceback (most recent call last):
  File "L:\Programs\InvokeAI\.venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "L:\Programs\InvokeAI\.venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Programs\InvokeAI\.venv\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "L:\Programs\InvokeAI\.venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "L:\Programs\InvokeAI\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\Programs\InvokeAI\.venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

Traceback:
  File "L:\InvokeAI-Installer\lib\main.py", line 50, in <module>
    inst.install(**args.__dict__)
  File "L:\InvokeAI-Installer\lib\installer.py", line 179, in install
    self.instance.install(
  File "L:\InvokeAI-Installer\lib\installer.py", line 235, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "L:\InvokeAI-Installer\lib\installer.py", line 313, in install_app
    pip[
  File "J:\Temp\invokeai-installer-tmp3u89aqrx\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "J:\Temp\invokeai-installer-tmp3u89aqrx\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Temp\invokeai-installer-tmp3u89aqrx\Lib\site-packages\plumbum\commands\base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "J:\Temp\invokeai-installer-tmp3u89aqrx\Lib\site-packages\plumbum\commands\base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Temp\invokeai-installer-tmp3u89aqrx\Lib\site-packages\plumbum\commands\processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Temp\invokeai-installer-tmp3u89aqrx\Lib\site-packages\plumbum\commands\processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "J:\Temp\invokeai-installer-tmp3u89aqrx\Lib\site-packages\plumbum\machines\base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 2
Command line: | 'L:\Programs\InvokeAI\.venv\Scripts\pip.exe' install --require-virtualenv --use-pep517 'L:\InvokeAI-Installer\lib\InvokeAI-2.3.5.post2-py3-none-any.whl[xformers]' --extra-index-url https://download.pytorch.org/whl/cu117

### Additional context

Main drive (NVME SSD) C: as 11.2GB of space
Temp redirected to a drive (3.5 inch HDD) with 72GB of space "J:\Temp"
Installer location was on an NVME SSD with 23GB "L:\InvokeAI-Installer"
Install location was also on an NVME SSD "L:\Programs\InvokeAI"

**Comment by PollutionPotential** [comment]
Fixed, user error. I had Python 3.11.4 installed, yet setup didn't catch it and began installing anyway.
Ran it with 3.10.11, it caught the version and told me to downgrade to 3.10.9.
Setup then completed.
