### ISSUE TITLE
[bug]: 3.0.0b4 - invokeai-migrate3 Mac / mps: "ERROR --> Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False"

### ISSUE THREAD

**Issue by panicsteve** [invoke-ai/InvokeAI#3719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

3.0.0b4

### What happened?

invokeai-migrate3 appears to be trying to perform cuda operations on Mac / mps platforms.  I'm seeing this logged many times as the script runs:

```
[2023-07-10 05:47:59,631]::[InvokeAI]::ERROR --> Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by panicsteve** [comment]
Just FYI, issue persists on 3.0.0rc1.  Appears to occur while attempting to migrate embeddings from my 2.3.5-post2 installation.  I have 9 embeddings in the previous installation, and only 1 gets migrated over to 3.0.0rc1.  The error described above occurs 8 times, which probably explains the missing 8 embeddings.

(BTW, 3.0.0 is phenomenal work! Congratulations and well done!)

**Comment by panicsteve** [comment]
Here is an example of one of the embeddings that fails to migrate:

[verybadimagenegative_v1.3.pt.zip](https://github.com/invoke-ai/InvokeAI/files/12101359/verybadimagenegative_v1.3.pt.zip)

**Comment by panicsteve** [comment]
Sorry, one last comment to add that if I simply copy the .pt files from the 2.x installation to models/sd-1/embedding in the 3.x installation and restart InvokeAI, they seem to work fine just as they always have.

**Comment by panicsteve** [comment]
I just realized this morning that all the embeddings that reported the error were .pt format and the one that worked was .safetensors.  So the issue would appear to be that, for .pt format embeddings specifically, the migration script is attempting to use CUDA on Mac/MPS platforms.

**Comment by novitae** [comment]
Same error, here is my full traceback:
```
[2023-07-30 16:21:08,022]::[InvokeAI]::INFO --> Installing https://civitai.com/api/download/models/20068 [1/1]
[2023-07-30 16:21:10,443]::[InvokeAI]::INFO --> /Users/n/invokeai/models/tmp4emgpntp/badhandv4.pt: Downloading...
/Users/n/invokeai/models/tmp4emgpntp/badhandv4.pt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19.4k/19.4k [00:00<00:00, 23.1MiB/s]
An exception has occurred: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU. Details:
Traceback (most recent call last):
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/frontend/install/model_install.py", line 796, in main
    select_and_download_models(opt)
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/frontend/install/model_install.py", line 722, in select_and_download_models
    process_and_execute(opt, installApp.install_selections)
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/frontend/install/model_install.py", line 652, in process_and_execute
    installer.install(selections)
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/install/model_install_backend.py", line 195, in install
    self.heuristic_import(path)
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/install/model_install_backend.py", line 244, in heuristic_import
    models_installed.update({str(model_path_id_or_url): self._install_url(model_path_id_or_url)})
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/install/model_install_backend.py", line 274, in _install_url
    info = ModelProbe().heuristic_probe(location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/model_management/model_probe.py", line 66, in heuristic_probe
    return cls.probe(model_path=model, prediction_type_helper=prediction_type_helper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/model_management/model_probe.py", line 101, in probe
    probe = probe_class(model_path, model, prediction_type_helper)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/model_management/model_probe.py", line 234, in __init__
    self.checkpoint = checkpoint or ModelProbe._scan_and_load_checkpoint(checkpoint_path)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/model_management/model_probe.py", line 197, in _scan_and_load_checkpoint
    return torch.load(model_path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/n/invokeai/.venv/lib/python3.11/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Press any key to continue...
```
