### ISSUE TITLE
[bug]: ERROR:    Application startup failed. Exiting. Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by metadreamx** [invoke-ai/InvokeAI#3758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

current

### What happened?

Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [2] 1
Starting the InvokeAI browser-based UI..
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
>> patchmatch.patch_match: INFO - Downloading patchmatch libraries from github release https://github.com/invoke-ai/PyPatchMatch/releases/download/0.1.1/libpatchmatch_windows_amd64.dll
100%|█████████████████████████████████████████████████████████████████████████████| 47.0k/47.0k [00:00<00:00, 2.65MB/s]
>> patchmatch.patch_match: INFO - Downloading patchmatch libraries from github release https://github.com/invoke-ai/PyPatchMatch/releases/download/0.1.1/opencv_world460.dll
100%|█████████████████████████████████████████████████████████████████████████████| 61.4M/61.4M [00:09<00:00, 6.72MB/s]
[2023-07-13 16:06:01,768]::[InvokeAI]::INFO --> Patchmatch initialized
INFO:     Started server process [4856]
INFO:     Waiting for application startup.
[2023-07-13 16:06:03,598]::[InvokeAI]::DEBUG --> InvokeAI version 3.0.0+b5
[2023-07-13 16:06:03,598]::[InvokeAI]::DEBUG --> Internet connectivity is True
[2023-07-13 16:06:03,790]::[InvokeAI]::DEBUG --> config file=C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\configs\models.yaml
[2023-07-13 16:06:03,790]::[InvokeAI]::DEBUG --> GPU device = cuda
[2023-07-13 16:06:03,790]::[InvokeAI]::DEBUG --> Maximum RAM cache size: 6.0 GiB
ERROR:    Traceback (most recent call last):
  File "C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api_app.py", line 77, in startup_event
    ApiDependencies.initialize(
  File "C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 123, in initialize
    model_manager=ModelManagerService(config,logger),
  File "C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 286, in __init__
    self.mgr = ModelManager(
  File "C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 332, in __init__
    model_name, base_model, model_type = self.parse_key(model_key)
  File "C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 378, in parse_key
    base_model_str, model_type_str, model_name = model_key.split('/', 2)
ValueError: not enough values to unpack (expected 3, got 1)

ERROR:    Application startup failed. Exiting.
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<FastAPIEventService.__dispatch_from_queue() running at C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api\events.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [2]

### Screenshots

![Screenshot 2023-07-13 161247](https://github.com/invoke-ai/InvokeAI/assets/93571019/7ef7ddc5-fa81-4ce7-a71f-c1403a26f6ad)

### Additional context

I installed everything 3 times fresh installs but keep running into this error.
ERROR:    Application startup failed. Exiting.
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<FastAPIEventService.__dispatch_from_queue() running at C:\Users\antho\AppData\Local\Temp\Temp1_InvokeAI-installer-v3.0.0+b5.zip\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api\events.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>

**Comment by mcmikemn** [comment]
I had been running InvokeAI fine since September, but I'm getting this error now.

**Comment by psychedelicious** [comment]
We have a totally new model manager in v4.0.0. This method of model loading is no longer used. The solution is to upgrade the app to the latest version.
