### ISSUE TITLE
[bug]: RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

### ISSUE THREAD

**Issue by tasslehawk** [invoke-ai/InvokeAI#3789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12gb

### What version did you experience this issue on?

3.0.0+b5

### What happened?

when invoking an image it starts but at the end I get the fallowing and no picture.

[2023-07-15 19:41:11,757]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\invoke3\.venv\lib\site-packages\invokeai\app\services\processor.py", line 70, in __process
    outputs = invocation.invoke(
  File "D:\invoke3\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\invoke3\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 327, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
  File "D:\invoke3\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 485, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "D:\invoke3\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 207, in __call__
    for result in self.generator_method(*args, **kwargs):
  File "D:\invoke3\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 541, in generate_latents_from_embeddings
    step_output = self.step(
  File "D:\invoke3\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\invoke3\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 686, in step
    step_output = self.scheduler.step(
  File "D:\invoke3\.venv\lib\site-packages\diffusers\schedulers\scheduling_dpmsolver_singlestep.py", line 670, in step
    step_index = step_index.item()
RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

### Additional context

It generated 2 images and then that happened

### Contact Details

tasslehawk@yahoo.com

**Comment by hipsterusername** [comment]
Can you share other settings - Any/all information on your setup, and what led to the error

**Comment by tasslehawk** [comment]
all setting where default with SD v1.5 was fresh install to 3.0.0 so was just testing a few prompts to start. I have an AMD Ryzen 7 7700X 8-Core Processor 4.50 GHz, 64GB ram, nvidia RTX 2060 12GB. have no issues in invoke 2.3.5

**Comment by drwootton** [comment]
I have this same problem on Fedora 36 Linux, both with the current, as of 7/21/23, pre-packaged v3 zip file and following the command line install steps for Linux.  I installed into a clean directory and downloaded only the deliberate model to start with. My prompt was 'Realistic photo of a cat', no negative prompt, generating only 1 image, 50 steps, cfg scale 7.5 and DPM++ 2S Karras, no control net or other extra processing.

**Comment by Paramortis** [comment]
Which scheduler were you using?  I found I had this same error, but only when using DPM++ 2S Karras.  As soon as I changed to a different scheduler, everything worked fine.

**Comment by drwootton** [comment]
I was using DPM++ 2S Karras. I tried 8 other schedulers with the exact same prompt and settings and they all worked properly.

**Comment by Tywele** [comment]
I can confirm I have the same error with the DPM++ 2S Karras scheduler.

**Comment by tasslehawk** [comment]
I confirm DPM++ 2S Karras causes the error on mine as well DPM++ 2M Karras works fine.

**Comment by hipsterusername** [comment]
@StAlKeR7779 - any thoughts on the 2S scheduler?

**Comment by codingcoder365** [comment]
same issue for this scheduler, running in the latest build of invoke ai

**Comment by alexisrolland** [comment]
@hipsterusername it seems this is an issue with `DPMSolverSinglestepScheduler` from `diffusers`. I have reported the bug here: https://github.com/huggingface/diffusers/issues/4631

**Comment by hipsterusername** [comment]
> @hipsterusername it seems this is an issue with `DPMSolverSinglestepScheduler` from `diffusers`. I have reported the bug here: [huggingface/diffusers#4631](https://github.com/huggingface/diffusers/issues/4631)

Thanks for the heads up @alexisrolland !

**Comment by Millu** [comment]
With diffusers 0.22 out, this has been fixed
