### ISSUE TITLE
[bug]: server error

### ISSUE THREAD

**Issue by idealcrash07** [invoke-ai/InvokeAI#3855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### What version did you experience this issue on?

3.0.0 Release Candidate

### What happened?

I launch an image generation and a message appears: "server error"

[2023-07-20 12:44:34,848]::[InvokeAI]::ERROR --> Traceback (most recent call last):

  File "E:\InvokeAI-3\.venv\lib\site-packages\invokeai\app\services\processor.py", line 70, in __process
    outputs = invocation.invoke(
  File "E:\InvokeAI-3\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\InvokeAI-3\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 142, in invoke
    c, options = compel.build_conditioning_tensor_for_prompt_object(
  File "E:\InvokeAI-3\.venv\lib\site-packages\compel\compel.py", line 208, in build_conditioning_tensor_for_prompt_object
    return self._get_conditioning_for_flattened_prompt(prompt), {}
  File "E:\InvokeAI-3\.venv\lib\site-packages\compel\compel.py", line 270, in _get_conditioning_for_flattened_prompt
    return self.conditioning_provider.get_embeddings_for_weighted_prompt_fragments(
  File "E:\InvokeAI-3\.venv\lib\site-packages\compel\embeddings_provider.py", line 118, in get_embeddings_for_weighted_prompt_fragments
    base_embedding = self.build_weighted_embedding_tensor(tokens, per_token_weights, mask, device=device)
  File "E:\InvokeAI-3\.venv\lib\site-packages\compel\embeddings_provider.py", line 348, in build_weighted_embedding_tensor
    empty_z = self._encode_token_ids_to_embeddings(empty_token_ids)
  File "E:\InvokeAI-3\.venv\lib\site-packages\compel\embeddings_provider.py", line 381, in _encode_token_ids_to_embeddings
    text_encoder_output = self.text_encoder(token_ids,
  File "E:\InvokeAI-3\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\InvokeAI-3\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 823, in forward
    return self.text_model(
  File "E:\InvokeAI-3\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\InvokeAI-3\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 741, in forward
    encoder_outputs = self.encoder(
  File "E:\InvokeAI-3\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\InvokeAI-3\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 655, in forward
    layer_outputs = encoder_layer(
  File "E:\InvokeAI-3\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\InvokeAI-3\.venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 384, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "E:\InvokeAI-3\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\InvokeAI-3\.venv\lib\site-packages\torch\nn\modules\normalization.py", line 190, in forward
    return F.layer_norm(
  File "E:\InvokeAI-3\.venv\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### Screenshots

![Capture d’écran 2023-07-20 125109](https://github.com/invoke-ai/InvokeAI/assets/128288951/eeda4eab-0bf5-4d31-bbab-564cfd3426e6)

**Comment by Millu** [comment]
Give this a try: https://github.com/invoke-ai/InvokeAI/issues/3434#issuecomment-1554877703
