### ISSUE TITLE
[bug]: soft lock on crash related to number being not a multiple of 8

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#3860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

rc1

### What happened?

```py
Exception in thread invoker_processor:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jsp/InvokeAI3/src/invokeai/app/services/processor.py", line 50, in __process
    self.__invoker.services.graph_execution_manager.get(
  File "/home/jsp/InvokeAI3/src/invokeai/app/services/sqlite.py", line 79, in get
    return self._parse_item(result[0])
  File "/home/jsp/InvokeAI3/src/invokeai/app/services/sqlite.py", line 52, in _parse_item
    return parse_raw_as(item_type, item)
  File "pydantic/tools.py", line 82, in pydantic.tools.parse_raw_as
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[GraphExecutionState]
__root__ -> execution_graph -> nodes -> 6c87d68f-031c-4bd5-bdb7-a6cfb84caadf -> NoiseInvocation -> height
  ensure this value is a multiple of 8 (type=value_error.number.not_multiple; multiple_of=8)
[2023-07-19 21:35:00,484]::[InvokeAI]::ERROR --> Image record not found
```

https://discord.com/channels/1020123559063990373/1131414478949470359

@JPPhoto

**Comment by brandonrising** [comment]
Odd, the discord link doesn't seem to be working for me and I can't find that stacktrace when searching for it

**Comment by psychedelicious** [comment]
Here's another issue with same root cause https://github.com/invoke-ai/InvokeAI/issues/3412

The root cause is failed validation during processing, not when the graph is created. I'll test some of these scenarios and see if your pr fixes it.
