### ISSUE TITLE
[bug]: conversion to diffusers doesn't work

### ISSUE THREAD

**Issue by MaddyAurora** [invoke-ai/InvokeAI#3891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.0

### What happened?

this whole repository is very unusable by the fact that you cant use checkpoints models to generate and you have to convert them, and converting fails
it seems like there should be some tool in core folder which is missing by default

OSError: Can't load the configuration of 'F:\InvokeAI-Installer\InvokeAI\models\core\convert\clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'F:\InvokeAI-Installer\InvokeAI\models\core\convert\clip-vit-large-patch14' is the correct path to a directory containing a config.json file

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/123410261/2284edb5-39e0-42f7-86e5-a8c55687bba9)

**Comment by drwootton** [comment]
I think I have the same problem where I am trying to convert photon_v1.safetensors on my Fedora 36 Linux system. I get an error with the following traceback. In my case it looks like something is prefixing 'https://huggingface.co to the local pathname for some file even though I am running with all files local and no intent to download anything from huggingface.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/fastapi_events/middleware.py", line 43, in __call__
    await self.app(scope, receive, send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/app/api/routers/models.py", line 271, in convert_model
    ApiDependencies.invoker.services.model_manager.convert_model(model_name,
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/app/services/model_manager_service.py", line 498, in convert_model
    return self.mgr.convert_model(model_name, base_model, model_type, convert_dest_directory)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/backend/model_management/model_manager.py", line 755, in convert_model
    model = self.get_model(model_name,
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/backend/model_management/model_manager.py", line 472, in get_model
    model_path = model_class.convert_if_required(
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/backend/model_management/models/stable_diffusion.py", line 120, in convert_if_required
    return _convert_ckpt_and_cache(
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/backend/model_management/models/stable_diffusion.py", line 293, in _convert_ckpt_and_cache
    convert_ckpt_to_diffusers(
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 1165, in convert_ckpt_to_diffusers
    pipe = load_pipeline_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 1125, in load_pipeline_from_original_stable_diffusion_ckpt
    text_model = convert_ldm_clip_checkpoint(checkpoint)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 835, in convert_ldm_clip_checkpoint
    text_model = CLIPTextModel.from_pretrained(CONVERT_MODEL_ROOT / 'clip-vit-large-patch14')
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/transformers/modeling_utils.py", line 2325, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 134, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/nvme/dave/AI/invokeai/.venv/lib64/python3.10/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /nvme/dave/AI/invokeai/models/core/convert/clip-vit-large-patch14 does not appear to have a file named config.json. Checkout 'https://huggingface.co//nvme/dave/AI/invokeai/models/core/convert/clip-vit-large-patch14/main' for available files.
INFO:     127.0.0.1:38778 - "GET /api/v1/models/?model_type=main HTTP/1.1" 200 OK
is:issue is:open is:issue is:open

**Comment by hipsterusername** [comment]
@lstein - Looking at the conversion logic, is there anything that might be confusing local linux path names with a huggingface repo_id?
