### ISSUE TITLE
[bug]: some schedulers don't work in unified canvas

### ISSUE THREAD

**Issue by eyalgi11** [invoke-ai/InvokeAI#3900]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10

### What version did you experience this issue on?

3.0

### What happened?

some schedulers don't work specifically in the unified canvas
error message:
[2023-07-22 17:35:10,865]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\app\services\processor.py", line 70, in __process
    outputs = invocation.invoke(
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\generate.py", line 239, in invoke
    generator_output = next(outputs)
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\generator\base.py", line 142, in generate
    results = generator.generate(
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\generator\base.py", line 330, in generate
    image = make_image(x_T, seed)
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\generator\inpaint.py", line 310, in make_image
    pipeline_output = pipeline.inpaint_from_embeddings(
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 885, in inpaint_from_embeddings
    result_latents, result_attention_maps = self.latents_from_embeddings(
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 483, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 207, in __call__
    for result in self.generator_method(*args, **kwargs):
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 538, in generate_latents_from_embeddings
    step_output = self.step(
  File "D:\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 693, in step
    step_output = guidance(step_output, timestep, conditioning_data)
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 118, in __call__
    {
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 120, in <dictcomp>
    self.apply_mask(v, self._t_for_field(k, t))
  File "D:\InvokeAI\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 144, in apply_mask
    mask_latents = self.scheduler.add_noise(self.mask_latents, self.noise, t)
  File "D:\InvokeAI\.venv\lib\site-packages\diffusers\schedulers\scheduling_k_dpm_2_ancestral_discrete.py", line 410, in add_noise
    step_indices = [self.index_for_timestep(t, schedule_timesteps) for t in timesteps]
  File "D:\InvokeAI\.venv\lib\site-packages\diffusers\schedulers\scheduling_k_dpm_2_ancestral_discrete.py", line 410, in <listcomp>
    step_indices = [self.index_for_timestep(t, schedule_timesteps) for t in timesteps]
  File "D:\InvokeAI\.venv\lib\site-packages\diffusers\schedulers\scheduling_k_dpm_2_ancestral_discrete.py", line 159, in index_for_timestep
    return indices[pos].item()
IndexError: index 2 is out of bounds for dimension 0 with size 2

the schedulers:
DPM++ SDE
DPM++ SDE Karras
Heun
Heun Karras
KDPM 2
KDPM 2 Ancestral

Update: it's only when i'm outpainting

**Comment by hipsterusername** [comment]
We ought to test this when we break out and fix the inpainting node to confirm it fixes @blessedcoolant @StAlKeR7779
