### ISSUE TITLE
[bug]:  Error when selecting option 5 to run model installer

### ISSUE THREAD

**Issue by toon-geek** [invoke-ai/InvokeAI#3908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

https://github.com/invoke-ai/InvokeAI/releases/tag/v3.0.0

### What happened?

Error when selecting option 5 to run model installer

### Screenshots

Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 5
Running invokeai-model-install...
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[2023-07-23 11:54:24,201]::[InvokeAI]::INFO --> Scanning H:\InvokeAI\InvokeAI\models for new models
[2023-07-23 11:54:24,284]::[InvokeAI]::INFO --> Scanned 5 files and directories, imported 0 models
[2023-07-23 11:54:24,320]::[InvokeAI]::INFO --> Scanning H:\InvokeAI\InvokeAI\models for new models
[2023-07-23 11:54:24,411]::[InvokeAI]::INFO --> Scanned 5 files and directories, imported 0 models
An exception has occurred: vline() returned ERR Details:
Traceback (most recent call last):
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 791, in main
    select_and_download_models(opt)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 707, in select_and_download_models
    installApp.run()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\apNPSApplicationManaged.py", line 148, in main
    self.onStart()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 555, in onStart
    self.main_form = self.addForm(
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\apNPSApplicationManaged.py", line 55, in addForm
    fm = FormClass( parentApp=self, *args, **keywords)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 77, in __init__
    super().__init__(parentApp=parentApp, name=name, *args, **keywords)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\fmFormMultiPage.py", line 16, in __init__
    super(FormMultiPage, self).__init__(*args, **keywords)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\fmForm.py", line 70, in __init__
    self.create()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 198, in create
    self._toggle_tables([self.current_tab])
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 355, in _toggle_tables
    self.display()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\fmForm.py", line 321, in display
    w.update(clear=clear)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\wgboxwidget.py", line 139, in update
    super(BoxTitle, self).update(clear=clear)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\wgboxwidget.py", line 24, in update
    self.parent.curses_pad.vline(self.rely, self.relx, curses.ACS_VLINE, self.height)
_curses.error: vline() returned ERR

Press any key to continue...

**Comment by hipsterusername** [comment]
Try resizing your terminal window to be full screen and do this step again.

**Comment by toon-geek** [comment]
resized and not resized produce different errors

Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 5
Running invokeai-model-install...
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[2023-07-23 13:10:35,446]::[InvokeAI]::INFO --> Scanning H:\InvokeAI\InvokeAI\models for new models
[2023-07-23 13:10:35,587]::[InvokeAI]::INFO --> Scanned 5 files and directories, imported 0 models
[2023-07-23 13:10:35,618]::[InvokeAI]::INFO --> Scanning H:\InvokeAI\InvokeAI\models for new models
[2023-07-23 13:10:35,712]::[InvokeAI]::INFO --> Scanned 5 files and directories, imported 0 models
An exception has occurred: vline() returned ERR Details:
Traceback (most recent call last):
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 791, in main
    select_and_download_models(opt)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 707, in select_and_download_models
    installApp.run()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\apNPSApplicationManaged.py", line 148, in main
    self.onStart()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 555, in onStart
    self.main_form = self.addForm(
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\apNPSApplicationManaged.py", line 55, in addForm
    fm = FormClass( parentApp=self, *args, **keywords)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 77, in __init__
    super().__init__(parentApp=parentApp, name=name, *args, **keywords)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\fmFormMultiPage.py", line 16, in __init__
    super(FormMultiPage, self).__init__(*args, **keywords)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\fmForm.py", line 70, in __init__
    self.create()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 198, in create
    self._toggle_tables([self.current_tab])
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\invokeai\frontend\install\model_install.py", line 355, in _toggle_tables
    self.display()
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\fmForm.py", line 321, in display
    w.update(clear=clear)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\wgboxwidget.py", line 139, in update
    super(BoxTitle, self).update(clear=clear)
  File "H:\InvokeAI\InvokeAI\.venv\lib\site-packages\npyscreen\wgboxwidget.py", line 24, in update
    self.parent.curses_pad.vline(self.rely, self.relx, curses.ACS_VLINE, self.height)
_curses.error: vline() returned ERR

Press any key to continue...
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 5
Running invokeai-model-install...
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[2023-07-23 13:11:06,349]::[InvokeAI]::INFO --> Scanning H:\InvokeAI\InvokeAI\models for new models
[2023-07-23 13:11:06,434]::[InvokeAI]::INFO --> Scanned 5 files and directories, imported 0 models
This window is too narrow for the user interface. Please make it wider.
This window is too short for the user interface. Please make it taller.
Press any key to continue..
