### ISSUE TITLE
[bug]: migration from 2.3.5 to fresh 3.0 install fails

### ISSUE THREAD

**Issue by xaroth8088** [invoke-ai/InvokeAI#3912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.0

### What happened?

After copying the model files from the old location, the following error is given:
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\invokeai-3\.venv\Scripts\invokeai-migrate3.exe\__main__.py", line 7, in <module>
  File "D:\invokeai-3\.venv\lib\site-packages\invokeai\backend\install\migrate_to_3.py", line 603, in main
    do_migrate(src_root,dest_root)
  File "D:\invokeai-3\.venv\lib\site-packages\invokeai\backend\install\migrate_to_3.py", line 556, in do_migrate
    (dest_directory / 'configs' / 'models.yaml').replace(src_directory / 'configs' / 'models.yaml.orig')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1247, in replace
    self._accessor.replace(self, target)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'D:\\invokeai-3\\configs\\models.yaml' -> 'S:\\invokeai\\configs\\models.yaml.orig'
```

It's important to note that `D:` is my _destination_ drive, and `S:` is my _source_ drive, so the error message makes it look like the error comes from trying to copy a file out of the destination path and into the source path.

### Additional context

It looks like the intent of the last three lines of `do_migrate()` is to do three renames within the destination directory:
* `/config/models.yaml` -> `/config/models.yaml.orig`
* `/config/models.yaml.3` -> `/config/models.yaml`
* `/models.3/` -> `/models/`

After manually doing these renames and starting the web interface, everything appears to work normally.

**Comment by Millu** [comment]
@lstein any thoughts on the cause of this?
