### ISSUE TITLE
[bug]: .safetensors Import fails from local file. Hugging Face Repro ID import works.

### ISSUE THREAD

**Issue by 5chlupp** [invoke-ai/InvokeAI#3921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64

### What version did you experience this issue on?

3.0.0

### What happened?

Hello,
I cannot import .safetensors models that are on my hard disk and that I use in Automatic1111. Download from Hugging Face with the Repro ID works.

> INFO:     127.0.0.1:50396 - "GET /api/v1/models/?model_type=main HTTP/1.1" 200 OK
[2023-07-23 21:06:23,735]::[InvokeAI]::INFO --> Successfully imported /Users/XXX/Pictures/AI-Kunst/Automatic1111/stable-diffusion-webui/models/Stable-diffusion/photon_v1.safetensors, got name='photon_v1' model_type=<ModelType.Main: 'main'> base_model=<BaseModelType.StableDiffusion1: 'sd-1'> config=CheckpointConfig(path='/Users/XXX/Pictures/AI-Kunst/Automatic1111/stable-diffusion-webui/models/Stable-diffusion/photon_v1.safetensors', description='sd-1 main model photon_v1', model_format=<StableDiffusion1ModelFormat.Checkpoint: 'checkpoint'>, error=None, vae=None, config='configs/stable-diffusion/v1-inference.yaml', variant='normal')
INFO:     127.0.0.1:50400 - "POST /api/v1/models/import HTTP/1.1" 201 Created
INFO:     127.0.0.1:50400 - "GET /api/v1/models/?model_type=main HTTP/1.1" 200 OK
INFO:     127.0.0.1:50401 - "GET /api/v1/images/?board_id=none&categories=general&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200 OK
INFO:     127.0.0.1:50402 - "GET /api/v1/images/?board_id=none&categories=control&categories=mask&categories=user&categories=other&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200 OK
INFO:     127.0.0.1:50404 - "POST /api/v1/sessions/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:50404 - "PUT /api/v1/sessions/0eab2c77-fec2-4610-a7bf-71e71e15883c/invoke?all=true HTTP/1.1" 202 Accepted
[2023-07-23 21:09:18,632]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/app/services/processor.py", line 70, in __process
    outputs = invocation.invoke(
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/app/invocations/compel.py", line 88, in invoke
    tokenizer_info = context.services.model_manager.get_model(
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/app/services/model_manager_service.py", line 360, in get_model
    model_info = self.mgr.get_model(
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/backend/model_management/model_manager.py", line 472, in get_model
    model_path = model_class.convert_if_required(
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/backend/model_management/models/stable_diffusion.py", line 120, in convert_if_required
    return _convert_ckpt_and_cache(
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/backend/model_management/models/stable_diffusion.py", line 293, in _convert_ckpt_and_cache
    convert_ckpt_to_diffusers(
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 1165, in convert_ckpt_to_diffusers
    pipe = load_pipeline_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 1125, in load_pipeline_from_original_stable_diffusion_ckpt
    text_model = convert_ldm_clip_checkpoint(checkpoint)
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 835, in convert_ldm_clip_checkpoint
    text_model = CLIPTextModel.from_pretrained(CONVERT_MODEL_ROOT / 'clip-vit-large-patch14')
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2325, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 134, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /.venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /models/core/convert/clip-vit-large-patch14 does not appear to have a file named config.json. Checkout 'https://huggingface.co//Users/XXX/Pictures/AI-Kunst/InvokeAI/InvokeAI300 /models/core/convert/clip-vit-large-patch14/main' for available files.

### Screenshots

<img width="1350" alt="Bildschirmfoto 2023-07-23 um 21 06 21" src="https://github.com/invoke-ai/InvokeAI/assets/58439006/831079d7-504e-4a87-b1a1-3c8151f2d1e6">

**Comment by easp** [comment]
You should add a Title to the bug report.
