### ISSUE TITLE
[bug]: Expected out tensor to have dtype float

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#4003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32GB

### What version did you experience this issue on?

3.0.0

### What happened?

Tried to generate image on fresh install.
Got the following error in console and no image.

```
[2023-07-26 15:06:11,145]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/services/processor.py", line 70, in __process
    outputs = invocation.invoke(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/invocations/latent.py", line 368, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 483, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 207, in __call__
    for result in self.generator_method(*args, **kwargs):
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 538, in generate_latents_from_embeddings
    step_output = self.step(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 672, in step
    noise_pred = self.invokeai_diffuser.do_diffusion_step(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 211, in do_diffusion_step
    ) = self._apply_standard_conditioning(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 283, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 722, in _unet_forward
    return self.unet(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 905, in forward
    sample, res_samples = downsample_block(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 993, in forward
    hidden_states = attn(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 291, in forward
    hidden_states = block(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 154, in forward
    attn_output = self.attn1(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 321, in forward
    return self.processor(
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/util/mps_fixes.py", line 134, in __call__
    self.get_attention_scores_chunked(attn, query_slice, key_slice, attn_mask_slice, hidden_states[start_idx:end_idx], value[start_idx:end_idx], chunk_tmp_tensor)
  File "/Users/username/custom/invokeai3/.venv/lib/python3.10/site-packages/invokeai/backend/util/mps_fixes.py", line 198, in get_attention_scores_chunked
    torch.baddbmm(
RuntimeError: Expected out tensor to have dtype float, but got c10::Half instead
```

**Comment by psychedelicious** [comment]
Hi @ioma8 , a fix for this issue is in v3.0.1post3. Can you please update and try again?
