### ISSUE TITLE
[bug]: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

### ISSUE THREAD

**Issue by coder543** [invoke-ai/InvokeAI#4017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

24GB

### What version did you experience this issue on?

3.0.1RC

### What happened?

I cannot generate images using SDXL. Instead, I receive this error:

```
[2023-07-26 17:56:25,881]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/Users/coder/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/services/processor.py", line 90, in __process
    outputs = invocation.invoke(
  File "/Users/coder/workspace/invokeai/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/coder/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/invocations/sdxl.py", line 340, in invoke
    noise_pred = unet(
  File "/Users/coder/workspace/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/coder/workspace/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 793, in forward
    timesteps = timesteps[None].to(sample.device)
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

[2023-07-26 17:56:25,883]::[InvokeAI]::ERROR --> Error while invoking:
Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

### Additional context

If I try to generate images with SD 2.1, it works fine.

This is the first time I've tried to install InvokeAI on this Mac, so it is a fresh install using the guided installer script.

**Comment by Millu** [comment]
How did you download SDXL?

**Comment by coder543** [comment]
@Millu The installation script offered it as an option. I just used the script to download the model for me.

**Comment by Millu** [comment]
Gotcha. I was able to reproduce this both via the installer & the Model Importer

@StAlKeR7779 does this relate to the MPS issue you were handling?

**Comment by jooray** [comment]
Same here.

Maybe a quantized model would work?

**Comment by ioma8** [comment]
Is this issue related to this issue of mine? Seems also like float format mismatch.
https://github.com/invoke-ai/InvokeAI/issues/4003

**Comment by sr1234** [comment]
Yep, running into this as well, but with the 3.0.1 RC1 version that *just* came out.

**Comment by GoldmanOz** [comment]
Having this issue also, complete fresh install of 3.0.1rc3 ???

**Comment by psychedelicious** [comment]
A fix for this issue is in v3.0.1post3. Can you please update and try again?

**Comment by liuchibing** [comment]
successfully using Euler A on my Intel CPU and AMD GPU Macbook Pro.

**Comment by jooray** [comment]
This issue is about MPS, which is used on Apple Sillicon (M1, M2 processors), so anyone using Intel Macs and AMD GPUs will never touch this issue.

Please comment only if you use MPS backend.

**Comment by jooray** [comment]
> A fix for this issue is in v3.0.1post3. Can you please update and try again?

Yes, works. We can close this now. Thank you.

**Comment by liuchibing** [comment]
> 

Intel Mac also has MPS

**Comment by jooray** [comment]
My bad then, sorry.
