### ISSUE TITLE
[bug]: No module named 'basicsr'

### ISSUE THREAD

**Issue by pippojedi** [invoke-ai/InvokeAI#4029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.1rc2

### What happened?

After installing at first launch I get this error
```
from basicsr.archs.rrdbnet_arch import RRDBNet
ModuleNotFoundError: No module named 'basicsr'
```
I have searched around, made a clean install of pyton 3.10.9, trashed all installation, did a clean installation again and still got same error.

thank you for your time.

**Comment by psychedelicious** [comment]
Please try these steps:
- run the launcher
- choose the developer console option
- run `pip install basicsr`
- close and run the app normally

This will try to manually install the missing `basicsr` dependency, which is used for upscaling. I'm expecting there to be some error at this point - please copy and paste the message into this issue.

**Comment by pippojedi** [comment]
Thank you for your time!

The output of 
> run pip install basicsr


```
(.venv) CUSTOMPATH\InvokeAI3>pip install basicsr
Requirement already satisfied: basicsr in CUSTOMPATH\invokeai3\.venv\lib\site-packages (1.4.2)
Requirement already satisfied: opencv-python in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (4.8.0.74)
Requirement already satisfied: addict in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (2.4.0)
Requirement already satisfied: numpy>=1.17 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (1.23.5)
Requirement already satisfied: future in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (0.18.3)
Requirement already satisfied: lmdb in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (1.4.1)
Requirement already satisfied: Pillow in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (10.0.0)
Requirement already satisfied: scikit-image in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (0.21.0)
Requirement already satisfied: scipy in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (1.11.1)
Requirement already satisfied: yapf in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (0.40.1)
Requirement already satisfied: torch>=1.7 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (2.0.1+cu117)
Requirement already satisfied: tb-nightly in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (2.14.0a20230727)
Requirement already satisfied: torchvision in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (0.15.2+cu117)
Requirement already satisfied: requests in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (2.28.2)
Requirement already satisfied: pyyaml in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (6.0.1)
Requirement already satisfied: tqdm in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from basicsr) (4.65.0)
Requirement already satisfied: jinja2 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from torch>=1.7->basicsr) (3.1.2)
Requirement already satisfied: typing-extensions in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from torch>=1.7->basicsr) (4.7.1)
Requirement already satisfied: filelock in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from torch>=1.7->basicsr) (3.12.2)
Requirement already satisfied: sympy in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from torch>=1.7->basicsr) (1.12)
Requirement already satisfied: networkx in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from torch>=1.7->basicsr) (3.1)
Requirement already satisfied: certifi>=2017.4.17 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from requests->basicsr) (2023.7.22)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from requests->basicsr) (1.26.16)
Requirement already satisfied: idna<4,>=2.5 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from requests->basicsr) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from requests->basicsr) (3.2.0)
Requirement already satisfied: packaging>=21 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from scikit-image->basicsr) (23.1)
Requirement already satisfied: lazy_loader>=0.2 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from scikit-image->basicsr) (0.3)
Requirement already satisfied: tifffile>=2022.8.12 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from scikit-image->basicsr) (2023.7.18)
Requirement already satisfied: imageio>=2.27 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from scikit-image->basicsr) (2.31.1)
Requirement already satisfied: PyWavelets>=1.1.1 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from scikit-image->basicsr) (1.4.1)
Requirement already satisfied: absl-py>=0.4 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (1.4.0)
Requirement already satisfied: protobuf>=3.19.6 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (3.20.3)
Requirement already satisfied: wheel>=0.26 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (0.41.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (2.3.6)
Requirement already satisfied: grpcio>=1.48.2 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (1.56.2)
Requirement already satisfied: setuptools>=41.0.0 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (65.5.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (2.22.0)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tb-nightly->basicsr) (3.4.4)
Requirement already satisfied: colorama in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from tqdm->basicsr) (0.4.6)
Requirement already satisfied: platformdirs>=3.5.1 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from yapf->basicsr) (3.9.1)
Requirement already satisfied: importlib-metadata>=6.6.0 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from yapf->basicsr) (6.8.0)
Requirement already satisfied: tomli>=2.0.1 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from yapf->basicsr) (2.0.1)
Requirement already satisfied: rsa<5,>=3.1.4 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr) (4.9)
Requirement already satisfied: six>=1.9.0 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr) (1.16.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr) (0.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr) (5.3.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tb-nightly->basicsr) (1.3.1)
Requirement already satisfied: zipp>=0.5 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from importlib-metadata>=6.6.0->yapf->basicsr) (3.16.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from werkzeug>=1.0.1->tb-nightly->basicsr) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from sympy->torch>=1.7->basicsr) (1.3.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tb-nightly->basicsr) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in CUSTOMPATH\invokeai3\.venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tb-nightly->basicsr) (3.2.2)
[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```
Then I closed the command prompt, restarted the bat file, picked the first option and ... nothing same error output as before, as follows:

```
Starting the InvokeAI browser-based UI..
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[2023-07-31 11:03:09,910]::[InvokeAI]::INFO --> Patchmatch initialized
Traceback (most recent call last):
File "E:\divertimento\varie\Python\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "E:\divertimento\varie\Python\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "CUSTOMPATH\InvokeAI3\.venv\Scripts\invokeai-web.exe\__main__.py", line 4, in <module>
File "CUSTOMPATH\InvokeAI3\.venv\lib\site-packages\invokeai\app\api_app.py", line 36, in <module>    from .api.dependencies import ApiDependencies
File "CUSTOMPATH\InvokeAI3\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 16, in <module>
from invokeai.app.services.images import ImageService, ImageServiceDependencies
File "CUSTOMPATH\InvokeAI3\.venv\lib\site-packages\invokeai\app\services\images.py", line 38, in <module>
from invokeai.app.util.metadata import get_metadata_graph_from_raw_session
File "CUSTOMPATH\InvokeAI3\.venv\lib\site-packages\invokeai\app\util\metadata.py", line 6, in <module>
from invokeai.app.services.graph import Edge
File "CUSTOMPATH\InvokeAI3\.venv\lib\site-packages\invokeai\app\services\graph.py", line 21, in <module>
from ..invocations import *
File "CUSTOMPATH\InvokeAI3\.venv\lib\site-packages\invokeai\app\invocations\upscale.py", line 7, in <module>
from basicsr.archs.rrdbnet_arch import RRDBNet  
ModuleNotFoundError: No module named 'basicsr
```

I swapped the actual path to my invoke installation with CUSTOMPATH.

I see there is a new release 3.0.1 , should I try upgrading and see or we try to fix this?

**Comment by psychedelicious** [comment]
Huh, that's weird. It shows `basicsr` is installed, I would have guessed, based on the error, that it was not installed. Ok.

How about this:
- run launcher
- developer console
- run the python interpreter (I think on windows you can just type `py`? maybe `python.exe`?)
- in the interpreter, run `import basicsr` - does that work?
- to exit, run `quit()`

Also, in dev console, we can try uninstalling `basicsr` before installing it, maybe the existing install is borko:
- `pip uninstall basicsr`
- `pip install basicsr`

Then try the app again.

It is indeed possible that upgrading will fix it, and that would be the next step.

**Comment by pippojedi** [comment]
Hi, thank you again for your time:
Nothing worked.
I unistalled and reinstalled basicsr and rerun, nothing.
I tried the import basicsr and got the same error message,
I update, from inside the console to latest pip, same error.

Something is messed up from previuos installations? To give more context, don't know if useful, I had a 2.3 Invoke AI installastion. I wiped out all of it, made a new folder for 3.0 install, did it, did not work, unistalled and reinstalled python 3.10.9 from scratch being sure to ADD TO PATH (stupid windows) but nothing worked. 
It may be that a previuos setting is somehow surviving and messing it up?
Shouldn't the new installation be "self contained" and resolve this kind of issues? I thought i did everything right but...

Should I proceed with erasing the current folder and start a new download of new release or should I try to upgrade from inside and see if it patches things?

thank you again.

**Comment by psychedelicious** [comment]
I'm not sure what is happening, sorry!

The installation is indeed self contained (inside a virtual environment), so precious installs shouldn't affect it.

Maybe something has gotten corrupted. I think yes, wiping the existing install fully and starting over is the next thing to try.

**Comment by smektalski** [comment]
hi, 

i have done similar steps to ["No module named 'npyscreen'" ](https://github.com/invoke-ai/InvokeAI/issues/3055)

1. I found **basicsr** folder on my computer from some another installation 
2. and copy/paste it to  "C:\Users\myname\invokeai\.venv\Lib\site-packages\"
 
Its worked for me.

**Comment by psychedelicious** [comment]
@smektalski Thanks for sharing a fix. 

I'm rather confused now - pip (the python package installer) should handle installing these packages into the right place. That's its whole job!

@lstein any ideas?

**Comment by sleeplesskyru** [comment]
> hi,
> 
> i have done similar steps to ["No module named 'npyscreen'" ](https://github.com/invoke-ai/InvokeAI/issues/3055)
> 
> 1. I found **basicsr** folder on my computer from some another installation
> 2. and copy/paste it to  "C:\Users\myname\invokeai.venv\Lib\site-packages"
> 
> Its worked for me.

This fixed my issue too! You can download the missing module from https://pypi.org/project/basicsr/ and inside there will be a folder called `basicsr`. Drag that into the site-package folder and everything should be fine :D I really hope this works for you cause this error has been a problem for a while now...
