### ISSUE TITLE
[bug]: pip package 3.0.1rc1 - found duplicate key sdxl-refiner/main/stable-diffusion-xl-refiner-1-0

### ISSUE THREAD

**Issue by kamtar** [invoke-ai/InvokeAI#4037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.0.1rc1

### What happened?

New RTX4090 instance on runpod, image: runpod/pytorch:2.0.1-py3.10-cuda11.8.0-devel

This is issue specific for pip package 3.0.1rc1, 3.0.0 works. 

Commands run beforehand:
```
/workspace/invokeai# python -m venv .venv --prompt InvokeAI
/workspace/invokeai# source .venv/bin/activate
/workspace/invokeai# pip install "InvokeAI[xformers]"==3.0.1rc1 --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu117

```

Then I try to run invokeai-configure and get this error:
```
[2023-07-27 19:39:47,409]::[InvokeAI]::INFO --> Initializing InvokeAI runtime directory
[2023-07-27 19:39:47,469]::[InvokeAI]::INFO --> Scanning /root/invokeai/models for new models
Traceback (most recent call last):
  File "/workspace/invokeai/.venv/bin/invokeai-configure", line 8, in <module>
    sys.exit(invokeai_configure())
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/install/invokeai_configure.py", line 784, in main
    models_to_download = default_user_selections(opt)
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/install/invokeai_configure.py", line 544, in default_user_selections
    installer = ModelInstall(config)
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/install/model_install_backend.py", line 102, in __init__
    self.mgr = model_manager or ModelManager(config.model_conf_path)
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/model_manager.py", line 340, in __init__
    self._read_models(config)
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/model_manager.py", line 363, in _read_models
    self.scan_models_directory()
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/model_manager.py", line 914, in scan_models_directory
    imported_models = self.autoimport()
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/model_manager.py", line 956, in autoimport
    installer = ModelInstall(config = self.app_config,
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/install/model_install_backend.py", line 103, in __init__
    self.datasets = OmegaConf.load(Dataset_path)
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 190, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/workspace/invokeai/.venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 144, in construct_mapping
    raise yaml.constructor.ConstructorError(
yaml.constructor.ConstructorError: while constructing a mapping
  in "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/configs/INITIAL_MODELS.yaml", line 2, column 1
found duplicate key sdxl-refiner/main/stable-diffusion-xl-refiner-1-0
  in "/workspace/invokeai/.venv/lib/python3.10/site-packages/invokeai/configs/INITIAL_MODELS.yaml", line 27, column 1
```

**Comment by kamtar** [comment]
If somebody with the same problem is looking for hot-fix its as easy as removing the extra stable-diffusion-xl-refiner-1-0 record from the INITIAL_MODELS.yaml file
