### ISSUE TITLE
[bug]: Adding new XL models gives errors: 

### ISSUE THREAD

**Issue by def1701** [invoke-ai/InvokeAI#4050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.1

### What happened?

There are 2 errors - 
1. Error while invoking: 'time_embed.0.weight', this one occurs after adding the XL model and running invoke on any prompt.  This error occurs on models that are smaller than 1 GB.   

2. Error while invoking: 'ModuleList' object has no attribute '1'
Also occurs after adding the model and invoking on any prompt.  This error occurs on larger models.  Most were 6gb+

I have successfully added 3 XL models and about 10+ have failed with one of these two errors.

3. Using today's release 3.0.1 Post 3 - tries 6 more models,,  anew error is showing in addition to #2194 Error while invoking:
'model.diffusion_model.input_blocks.0.0.bias'

### Additional context

Full error:
============================================================
#1 error
 =====================================================
[2023-07-28 08:46:59,688]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\app\services\processor.py", line 86, in __process
    outputs = invocation.invoke(
  File "E:\data\invoke3\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 352, in invoke
    c1, c1_pooled, ec1 = self.run_clip_compel(context, self.clip, self.prompt, False)
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 243, in run_clip_compel
    tokenizer_info = context.services.model_manager.get_model(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 364, in get_model
    model_info = self.mgr.get_model(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 484, in get_model
    model_path = model_class.convert_if_required(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\models\sdxl.py", line 118, in convert_if_required
    return _convert_ckpt_and_cache(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 282, in _convert_ckpt_and_cache
    convert_ckpt_to_diffusers(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\convert_ckpt_to_diffusers.py", line 1726, in convert_ckpt_to_diffusers
    pipe = download_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\convert_ckpt_to_diffusers.py", line 1397, in download_from_original_stable_diffusion_ckpt
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\convert_ckpt_to_diffusers.py", line 440, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'

[2023-07-28 08:46:59,688]::[InvokeAI]::ERROR --> Error while invoking:
'time_embed.0.weight'

===================================================
#2 error
================================================================
[2023-07-28 09:16:04,888]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\app\services\processor.py", line 86, in __process
    outputs = invocation.invoke(
  File "E:\data\invoke3\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 352, in invoke
    c1, c1_pooled, ec1 = self.run_clip_compel(context, self.clip, self.prompt, False)
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 243, in run_clip_compel
    tokenizer_info = context.services.model_manager.get_model(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 364, in get_model
    model_info = self.mgr.get_model(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 484, in get_model
    model_path = model_class.convert_if_required(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\models\sdxl.py", line 118, in convert_if_required
    return _convert_ckpt_and_cache(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 282, in _convert_ckpt_and_cache
    convert_ckpt_to_diffusers(
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\convert_ckpt_to_diffusers.py", line 1726, in convert_ckpt_to_diffusers
    pipe = download_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)
  File "E:\data\invoke3\.venv\lib\site-packages\invokeai\backend\model_management\convert_ckpt_to_diffusers.py", line 1407, in download_from_original_stable_diffusion_ckpt
    set_module_tensor_to_device(unet, param_name, "cpu", value=param)
  File "E:\data\invoke3\.venv\lib\site-packages\accelerate\utils\modeling.py", line 255, in set_module_tensor_to_device
    new_module = getattr(module, split)
  File "E:\data\invoke3\.venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute '1'

[2023-07-28 09:16:04,888]::[InvokeAI]::ERROR --> Error while invoking:
'ModuleList' object has no attribute '1'

### Contact Details

davidf@argus-holdings.com

**Comment by def1701** [comment]
Just confirmed Issues #2 and 3 above on the latest release 3.0.1 post3

**Comment by TheTharin** [comment]
Experiencing the same bug

**Comment by shawngkelly** [comment]
Same issues: 
[2023-09-06 20:29:10,898]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\services\processor.py", line 95, in __process
    outputs = invocation.invoke_internal(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 514, in invoke_internal
    return self.invoke(context)
  File "E:\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 287, in invoke
    c1, c1_pooled, ec1 = self.run_clip_compel(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 162, in run_clip_compel
    tokenizer_info = context.services.model_manager.get_model(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 373, in get_model
    model_info = self.mgr.get_model(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 485, in get_model
    model_path = model_class.convert_if_required(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\models\sdxl.py", line 120, in convert_if_required
    return _convert_ckpt_and_cache(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 286, in _convert_ckpt_and_cache
    convert_ckpt_to_diffusers(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\convert_ckpt_to_diffusers.py", line 1732, in convert_ckpt_to_diffusers
    pipe = download_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\convert_ckpt_to_diffusers.py", line 1410, in download_from_original_stable_diffusion_ckpt
    set_module_tensor_to_device(unet, param_name, "cpu", value=param)
  File "E:\invokeai\.venv\lib\site-packages\accelerate\utils\modeling.py", line 255, in set_module_tensor_to_device
    new_module = getattr(module, split)
  File "E:\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute '1'

[2023-09-06 20:29:10,913]::[InvokeAI]::ERROR --> Error while invoking:
'ModuleList' object has no attribute '1'

**Comment by gingerkrueger** [comment]
Having the same issue, has anyone had an update on this?

**Comment by sertsessiz** [comment]
Same :(

**Comment by Millu** [comment]
@gingerkrueger @sertsessiz can you share the models you are having issues with? 

Also what version of InvokeAI are you using?

**Comment by sertsessiz** [comment]
I have this problem on automatic1111 and I encounter this problem on SDXL models. There is no problem with SD1.5 models.

    On Monday, October 30, 2023 at 01:43:04 AM GMT+3, Millun Atluri ***@***.***> wrote:  
 
 


@gingerkrueger @sertsessiz can you share the models you are having issues with?

Also what version of InvokeAI are you using?

**Comment by invincibledinku** [comment]
Error occurred when executing KSampler:

'ModuleList' object has no attribute '1'

**Comment by ZRZ-DEL** [comment]
'ModuleList' object has no attribute '1' Has anyone solved this error? I really need this solution

**Comment by psychedelicious** [comment]
We have a new model manager in v4.0.0. If you still have this problem on v4.0.0, please open a new issue.

**Comment by freshlesh3** [comment]
I have this issue using Invokeai 4.2.3. It occurs when using any sdxl openpose model.

**Comment by psychedelicious** [comment]
@freshlesh3 Please create a new issue with details about the problem.
