### ISSUE TITLE
[bug]: Version 3.0.1 installation error message, how to deal with it?

### ISSUE THREAD

**Issue by onlinedear** [invoke-ai/InvokeAI#4074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12G

### What version did you experience this issue on?

3.0.1

### What happened?

`  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "E:\InvokeAI\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-90pav6ax\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-90pav6ax\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-90pav6ax\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-90pav6ax\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "E:\InvokeAI\InvokeAI-installer-v3.0.1\InvokeAI-Installer\lib\main.py", line 50, in <module>
    inst.install(**args.__dict__)
  File "E:\InvokeAI\InvokeAI-installer-v3.0.1\InvokeAI-Installer\lib\installer.py", line 180, in install
    self.instance.install(
  File "E:\InvokeAI\InvokeAI-installer-v3.0.1\InvokeAI-Installer\lib\installer.py", line 236, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "E:\InvokeAI\InvokeAI-installer-v3.0.1\InvokeAI-Installer\lib\installer.py", line 312, in install_app
    pip[
  File "C:\Users\Administrator\AppData\Local\Temp\invokeai-installer-tmpcu0f3ajz\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "C:\Users\Administrator\AppData\Local\Temp\invokeai-installer-tmpcu0f3ajz\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "C:\Users\Administrator\AppData\Local\Temp\invokeai-installer-tmpcu0f3ajz\Lib\site-packages\plumbum\commands\base.py", line 252, in run
    return p.run()
  File "C:\Users\Administrator\AppData\Local\Temp\invokeai-installer-tmpcu0f3ajz\Lib\site-packages\plumbum\commands\base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "C:\Users\Administrator\AppData\Local\Temp\invokeai-installer-tmpcu0f3ajz\Lib\site-packages\plumbum\commands\processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "C:\Users\Administrator\AppData\Local\Temp\invokeai-installer-tmpcu0f3ajz\Lib\site-packages\plumbum\commands\processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "C:\Users\Administrator\AppData\Local\Temp\invokeai-installer-tmpcu0f3ajz\Lib\site-packages\plumbum\machines\base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | 'E:\InvokeAI\.venv\Scripts\pip.exe' install --require-virtualenv --use-pep517 'E:\InvokeAI\InvokeAI-installer-v3.0.1\InvokeAI-Installer\lib\InvokeAI-3.0.1-py3-none-any.whl[xformers]' --extra-index-url https://download.pytorch.org/whl/cu117`

### Screenshots

![20230730172815](https://github.com/invoke-ai/InvokeAI/assets/10751712/e7ffa419-490b-46ef-90e0-5e7803e9dc0a)

### Contact Details

lvxiaoxin@gmail.com

**Comment by jr19861013** [comment]
Hi, I had the same problem, can I ask if you solved it?

**Comment by Millu** [comment]
This has been fixed as of 3.2.x
