### ISSUE TITLE
[bug]: ModuleNotFoundError: No module named 'safetensors._safetensors_rust'

### ISSUE THREAD

**Issue by BeeMeeN** [invoke-ai/InvokeAI#4092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.1

### What happened?

When trying to install following error(s) appear(s):

Traceback (most recent call last):
  File "C:\Users\BerndM\Desktop\InvokeAI 3 Installer\lib\main.py", line 51, in <module>
    inst.install(**args.__dict__)
  File "C:\Users\BerndM\Desktop\InvokeAI 3 Installer\lib\installer.py", line 191, in install
    self.instance.configure()
  File "C:\Users\BerndM\Desktop\InvokeAI 3 Installer\lib\installer.py", line 351, in configure
    from invokeai.frontend.install import invokeai_configure
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\invokeai\frontend\install\__init__.py", line 4, in <module>
    from .invokeai_configure import main as invokeai_configure
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\invokeai\frontend\install\invokeai_configure.py", line 4, in <module>
    from ...backend.install.invokeai_configure import main
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\invokeai\backend\__init__.py", line 4, in <module>
    from .generator import InvokeAIGeneratorBasicParams, InvokeAIGenerator, InvokeAIGeneratorOutput, Img2Img, Inpaint
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\invokeai\backend\generator\__init__.py", line 4, in <module>
    from .base import (
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\invokeai\backend\generator\base.py", line 9, in <module>
    import diffusers
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\diffusers\configuration_utils.py", line 34, in <module>
    from .utils import (
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\diffusers\utils\accelerate_utils.py", line 24, in <module>
    import accelerate
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\accelerate\utils\__init__.py", line 64, in <module>
    from .modeling import (
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\accelerate\utils\modeling.py", line 39, in <module>
    from safetensors import safe_open
  File "C:\Users\BerndM\invokeai-3\.venv\Lib\site-packages\safetensors\__init__.py", line 4, in <module>
    from ._safetensors_rust import SafetensorError, deserialize, safe_open, serialize, serialize_file  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'safetensors._safetensors_rust'

What can I do?

### Additional context

Always happens when trying to install.

### Contact Details

info@nieschalk.com

**Comment by Casuallynoted** [comment]
I'm also having this issue, not sure why

**Comment by danny-zhu** [comment]
Using safetensors==0.4.2 can solve the problem.

**Comment by gitouni** [comment]
For the same command, this issue did not happen in my terminal but happened in a tmux env. I really cannot figure out why.
```
Traceback (most recent call last):
  File "/home/ouni/miniconda3/envs/comfy/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/home/ouni/miniconda3/envs/comfy/lib/python3.12/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/home/ouni/miniconda3/envs/comfy/lib/python3.12/site-packages/accelerate/accelerator.py", line 36, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/ouni/miniconda3/envs/comfy/lib/python3.12/site-packages/accelerate/checkpointing.py", line 21, in <module>
    from safetensors.torch import load_model
  File "/home/work/.local/safetensors/__init__.py", line 2, in <module>
    from ._safetensors_rust import (  # noqa: F401
ModuleNotFoundError: No module named 'safetensors._safetensors_rust'
```
My environment:
|accelerate|safetensors|transformers|torch|python|
|---|---|---|---|---|
|1.2.1|0.4.5|4.47.0|2.5.1|3.12.8|
