### ISSUE TITLE
[bug]: ERROR: Could not find a version that satisfies the requirement diffusers[torch]~=0.19.0

### ISSUE THREAD

**Issue by Refone** [invoke-ai/InvokeAI#4106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

32GB

### What version did you experience this issue on?

3.0.1

### What happened?

I met a fatal error exception while running `install.bat` on my Win10. I have no idea what's going on, seems about an software version issue
```
Successfully installed MarkupSafe-2.1.3 certifi-2023.7.22 charset-normalizer-3.2.0 filelock-3.12.2 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.24.4 packaging-23.1 pillow-10.0.0 requests-2.28.2 sympy-1.12 torch-2.0.1+cu117 torchmetrics-0.11.4 torchvision-0.15.2+cu117 typing-extensions-4.7.1 urllib3-1.26.16
─────────────────────────────────────── Installing the InvokeAI Application 🎨 ────────────────────────────────────────
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple, https://download.pytorch.org/whl/cu117
Processing f:\invokeai\invokeai-installer\lib\invokeai-3.0.1.post3-py3-none-any.whl
Collecting accelerate~=0.21.0 (from InvokeAI==3.0.1.post3)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/70/f9/c381bcdd0c3829d723aa14eec8e75c6c377b4ca61ec68b8093d9f35fc7a7/accelerate-0.21.0-py3-none-any.whl (244 kB)
Collecting albumentations (from InvokeAI==3.0.1.post3)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/9b/f6/c486cedb4f75147232f32ec4c97026714cfef7c7e247a1f0427bc5489f66/albumentations-1.3.1-py3-none-any.whl (125 kB)
Collecting click (from InvokeAI==3.0.1.post3)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/1a/70/e63223f8116931d365993d4a6b7ef653a4d920b41d03de7c59499962821f/click-8.1.6-py3-none-any.whl (97 kB)
Collecting clip-anytorch (from InvokeAI==3.0.1.post3)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/10/70/b92c966262ee935e32ae6c5b124f886fa9a8c441830f1764be31682976a6/clip_anytorch-2.5.2-py3-none-any.whl (1.4 MB)
Collecting compel~=2.0.0 (from InvokeAI==3.0.1.post3)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/e8/1f/feae2433b15f708d195b21492f5be8576de07da78cf17a5ba4afb08a6f9c/compel-2.0.0-py3-none-any.whl (29 kB)
Collecting controlnet-aux>=0.0.6 (from InvokeAI==3.0.1.post3)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/48/89/a9c1d8fea2e1266eed9ea505215efa330de3385bee618326252c62edbccd/controlnet_aux-0.0.6-py3-none-any.whl (261 kB)
Collecting timm==0.6.13 (from InvokeAI==3.0.1.post3)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/f6/c6/806d9b2fa95f418ad700dd206a935d5e8d7355505589dd13a70eb3a45048/timm-0.6.13-py3-none-any.whl (549 kB)
Collecting datasets (from InvokeAI==3.0.1.post3)
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/74/a0/ec3868a14a0d0518e4559dd80b2f92259ddf58dbd39f27cf328ad294b22c/datasets-2.14.0-py3-none-any.whl (492 kB)
INFO: pip is looking at multiple versions of invokeai[xformers] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement diffusers[torch]~=0.19.0 (from invokeai[xformers]) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.18.2)
ERROR: No matching distribution found for diffusers[torch]~=0.19.0
Traceback (most recent call last):
  File "F:\invokeAI\InvokeAI-Installer\lib\main.py", line 51, in <module>
    inst.install(**args.__dict__)
  File "F:\invokeAI\InvokeAI-Installer\lib\installer.py", line 181, in install
    self.instance.install(
  File "F:\invokeAI\InvokeAI-Installer\lib\installer.py", line 237, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "F:\invokeAI\InvokeAI-Installer\lib\installer.py", line 316, in install_app
    pip[
  File "C:\Users\XXX\AppData\Local\Temp\invokeai-installer-tmpqj5fu176\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "C:\Users\XXX\AppData\Local\Temp\invokeai-installer-tmpqj5fu176\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "C:\Users\XXX\AppData\Local\Temp\invokeai-installer-tmpqj5fu176\Lib\site-packages\plumbum\commands\base.py", line 252, in run
    return p.run()
  File "C:\Users\XXX\AppData\Local\Temp\invokeai-installer-tmpqj5fu176\Lib\site-packages\plumbum\commands\base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "C:\Users\XXX\AppData\Local\Temp\invokeai-installer-tmpqj5fu176\Lib\site-packages\plumbum\commands\processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "C:\Users\XXX\AppData\Local\Temp\invokeai-installer-tmpqj5fu176\Lib\site-packages\plumbum\commands\processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "C:\Users\XXX\AppData\Local\Temp\invokeai-installer-tmpqj5fu176\Lib\site-packages\plumbum\machines\base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | 'F:\invokeAI\Invokeai\.venv\Scripts\pip.exe' install --require-virtualenv --use-pep517 'F:\invokeAI\InvokeAI-Installer\lib\InvokeAI-3.0.1.post3-py3-none-any.whl[xformers]' --extra-index-url https://download.pytorch.org/whl/cu117
请按任意键继续. . .
```

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/16611716/ddf571ec-34c8-4468-a371-feecaaaa2eb1)

### Contact Details

710196926@qq.com

**Comment by Millu** [comment]
This should be fixed in 3.3.0post3
