### ISSUE TITLE
[bug]: line 196, in _run_module_as_main     return _run_code(code, main_globals, None,

### ISSUE THREAD

**Issue by ksorah1** [invoke-ai/InvokeAI#4108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

amd

### VRAM

8

### What version did you experience this issue on?

impossible to know

### What happened?

Hello,

When I try to update or repair my install, I get this :

Traceback (most recent call last):
  File "C:\Users\JyCS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\JyCS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\JyCS\invokeai\.venv\Scripts\invokeai-configure.exe\__main__.py", line 4, in <module>
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\invokeai\frontend\install\__init__.py", line 4, in <module>
    from .invokeai_configure import main as invokeai_configure
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\invokeai\frontend\install\invokeai_configure.py", line 4, in <module>
    from ...backend.install.invokeai_configure import main
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\invokeai\backend\__init__.py", line 4, in <module>
    from .generator import InvokeAIGeneratorBasicParams, InvokeAIGenerator, InvokeAIGeneratorOutput, Img2Img, Inpaint
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\invokeai\backend\generator\__init__.py", line 4, in <module>
    from .base import (
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\invokeai\backend\generator\base.py", line 9, in <module>
    import diffusers
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\diffusers\configuration_utils.py", line 34, in <module>
    from .utils import (
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 24, in <module>
    import accelerate
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\accelerate\accelerator.py", line 41, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\accelerate\tracking.py", line 50, in <module>
    import wandb
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\wandb\sdk\__init__.py", line 5, in <module>
    from . import wandb_helper as helper  # noqa: F401
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\wandb\sdk\wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\wandb\sdk\lib\config_util.py", line 9, in <module>
    from wandb.util import load_yaml
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\wandb\util.py", line 55, in <module>
    import sentry_sdk  # type: ignore
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\sentry_sdk\__init__.py", line 1, in <module>
    from sentry_sdk.hub import Hub, init
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\sentry_sdk\hub.py", line 9, in <module>
    from sentry_sdk.scope import Scope
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\sentry_sdk\scope.py", line 7, in <module>
    from sentry_sdk.utils import logger, capture_internal_exceptions
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 959, in <module>
    HAS_REAL_CONTEXTVARS, ContextVar = _get_contextvars()
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 929, in _get_contextvars
    if not _is_contextvars_broken():
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\sentry_sdk\utils.py", line 890, in _is_contextvars_broken
    from eventlet.patcher import is_monkey_patched  # type: ignore
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\eventlet\support\greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\eventlet\support\greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\eventlet\patcher.py", line 132, in import_patched
    return inject(
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\eventlet\patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\dns\zone.py", line 85, in <module>
    class Zone(dns.transaction.TransactionManager):
  File "C:\Users\JyCS\invokeai\.venv\lib\site-packages\dns\zone.py", line 756, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'

**Comment by Millu** [comment]
Can you try updating to the latest version 3.3.0post3?

**Comment by Harvester62** [comment]
Not having received any feedback from the user, can we close this bug report?
