### ISSUE TITLE
[bug]: Unable to load other Inpaint Models ; "failed to load sd-1:main:unet model"

### ISSUE THREAD

**Issue by MaxMagnos** [invoke-ai/InvokeAI#4119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0.1 (hotfix 3)

### What happened?

The whole Application is working fine in general.
All CivitAI models i've downloaded so far have worked, EXCEPT the Inpainting variants.

Whenever i try to generate something using one, (like "Realistic Vision V5.1-Inpainting(VAE)" ) i get an error similar to this : 

> [2023-07-31 15:53:21,578]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\StableDiffusion\Tools\InvokeAI\.venv\lib\site-packages\invokeai\app\services\processor.py", line 86, in __process
    outputs = invocation.invoke(
  File "D:\StableDiffusion\Tools\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\generate.py", line 220, in invoke
    with self.load_model_old_way(context, scheduler) as model:
  File "C:\Users\Tim\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "D:\StableDiffusion\Tools\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\generate.py", line 174, in load_model_old_way
    unet_info = context.services.model_manager.get_model(
  File "D:\StableDiffusion\Tools\InvokeAI\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 364, in get_model
    model_info = self.mgr.get_model(
  File "D:\StableDiffusion\Tools\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 491, in get_model
    model_context = self.cache.get_model(
  File "D:\StableDiffusion\Tools\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 198, in get_model
    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)
  File "D:\StableDiffusion\Tools\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\models\base.py", line 286, in get_model
    raise Exception(f"Failed to load {self.base_model}:{self.model_type}:{child_type} model")
Exception: Failed to load sd-1:main:unet model
[2023-07-31 15:53:21,584]::[InvokeAI]::ERROR --> Error while invoking:
Failed to load sd-1:main:unet model

I've tried manually converting the model in the Model Manager, but that didn't fix the issue. The models still won't load.
Had this with 3 different Inpaint-Models so far.
The base SD1.5-Inpainting model works fine however.

**Comment by VictorZakharov** [comment]
Same issue.

**Comment by Millu** [comment]
This has been resolved as of 3.0.2
