### ISSUE TITLE
[bug]: ERROR WHILE INVOKING

### ISSUE THREAD

**Issue by egoegoegoegoego** [invoke-ai/InvokeAI#4157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12gb

### What version did you experience this issue on?

3.0.1post3

### What happened?

all my inpainting models does not work after updating to the lastest version. Always get the error invoking message. deleted everything and tried again with a fresh installation but the error still persists. 

### Screenshots

[2023-08-05 02:51:40,361]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\app\services\processor.py", line 86, in __process
    outputs = invocation.invoke(
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 334, in invoke
    unet_info = context.services.model_manager.get_model(
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 364, in get_model
    model_info = self.mgr.get_model(
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 491, in get_model
    model_context = self.cache.get_model(
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 200, in get_model
    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)
  File "C:\Users\TCS\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\models\base.py", line 286, in get_model
    raise Exception(f"Failed to load {self.base_model}:{self.model_type}:{child_type} model")
Exception: Failed to load sd-1:main:unet model

[2023-08-05 02:51:40,366]::[InvokeAI]::ERROR --> Error while invoking:
Failed to load sd-1:main:unet model

### Additional context

normal models work fine it's just the inpainting models that have issues, and the bounding box alignment is way off in that it won't stay inside the image on the corners and always get errors on it too. Should've listened to my grandpa's advice: "if it ain't broken don't fix it" but I had to since I wanted to be part of the kool kids club.

**Comment by marpstar** [comment]
This is a dupe of #4135

**Comment by egoegoegoegoego** [comment]
> This is a dupe of #4135

is there a fix to this?

**Comment by egoegoegoegoego** [comment]
never mind deleted the whole folder and never been happier. no issues now.
