### ISSUE TITLE
[bug]: VERSION 3.0 CANNOT GENERATE IMAGES ON UNIFIED CANVAS WHEN GIVEN A SEED NUMBER

### ISSUE THREAD

**Issue by aferlo78** [invoke-ai/InvokeAI#4179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

3.0

### What happened?

I WANT TO MODIFY AND EXTEND PARTS OF IMAGES ON UNIFIED CANVAS. I USED PREVIOUSLY GENERATED IMAGES AND NEED TO FIX ERRORS AND EXTEND THE IMAGE SIZE. I USED TO DO IT FINE WITH VERSION 2. I USE THE SAME PARAMETERS THAT THE IMAGE IS GENERATED WITH INCLUDING SEED NUMBER. I WANT TO GENERATE 5 TO 10 IMAGES AND SELECT THE BEST.

NOW WHEN I USE THE SEED NUMBER IS NOT ABLE TO GENERATE AN IMAGE. GETS STUCK.

I HAPPENS EVERY TIME THAT I WANT TO USE A FIX SEED.

### Screenshots

Exception in thread invoker_processor:
Traceback (most recent call last):
  File "C:\Users\aferl\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\aferl\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\aferl\invokeAI7\.venv\lib\site-packages\invokeai\app\services\processor.py", line 50, in __process
    self.__invoker.services.graph_execution_manager.get(
  File "C:\Users\aferl\invokeAI7\.venv\lib\site-packages\invokeai\app\services\sqlite.py", line 79, in get
    return self._parse_item(result[0])
  File "C:\Users\aferl\invokeAI7\.venv\lib\site-packages\invokeai\app\services\sqlite.py", line 52, in _parse_item
    return parse_raw_as(item_type, item)
  File "pydantic\tools.py", line 82, in pydantic.tools.parse_raw_as
  File "pydantic\tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[GraphExecutionState]
__root__ -> execution_graph -> nodes -> 51cca1bf-6f28-4e21-a4be-782973399642 -> InpaintInvocation -> seed
  ensure this value is less than or equal to 2147483647 (type=value_error.number.not_le; limit_value=2147483647)
INFO:     127.0.0.1:50000 - "GET /api/v1/images/c58f8638-2552-4dc4-82e9-c83be27a53ec.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:50000 - "GET /api/v1/images/c58f8638-2552-4dc4-82e9-c83be27a53ec.png/full HTTP/1.1" 200 OK
INFO:     127.0.0.1:50001 - "DELETE /api/v1/sessions/f59839a4-1e32-4629-8e66-501adf016a87/invoke HTTP/1.1" 202 Accepted
INFO:     127.0.0.1:50002 - "POST /api/v1/images/?image_category=general&is_intermediate=true HTTP/1.1" 201 Created
INFO:     127.0.0.1:50002 - "POST /api/v1/images/?image_category=mask&is_intermediate=true HTTP/1.1" 201 Created
INFO:     127.0.0.1:50002 - "POST /api/v1/sessions/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:50002 - "PUT /api/v1/sessions/3fc988b9-4157-455e-9c91-9f1cd379a17c/invoke?all=true HTTP/1.1" 202 Accepted
INFO:     127.0.0.1:50003 - "DELETE /api/v1/sessions/3fc988b9-4157-455e-9c91-9f1cd379a17c/invoke HTTP/1.1" 202 Accepted
INFO:     127.0.0.1:50004 - "GET / HTTP/1.1" 304 Not Modified
INFO:     connection closed
INFO:     127.0.0.1:50004 - "GET /socket.io/?EIO=4&transport=polling&t=OdBkKlX HTTP/1.1" 200 OK
INFO:     127.0.0.1:50004 - "GET /api/v1/images/e5d8e1e5-b1c9-4d33-9e73-e2e384d3dbce.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:50005 - "GET /api/v1/app/version HTTP/1.1" 200 OK
INFO:     127.0.0.1:50006 - "GET /api/v1/models/?model_type=embedding HTTP/1.1" 200 OK
INFO:     127.0.0.1:50007 - "GET /api/v1/boards/?all=true HTTP/1.1" 200 OK
INFO:     127.0.0.1:50008 - "GET /api/v1/models/?model_type=main HTTP/1.1" 200 OK
INFO:     127.0.0.1:50004 - "GET /api/v1/models/?model_type=controlnet HTTP/1.1" 200 OK
INFO:     127.0.0.1:50005 - "GET /api/v1/models/?model_type=lora HTTP/1.1" 200 OK
INFO:     127.0.0.1:50009 - "GET /api/v1/models/?model_type=vae HTTP/1.1" 200 OK
INFO:     127.0.0.1:50006 - "GET /api/v1/app/config HTTP/1.1" 200 OK
INFO:     127.0.0.1:50005 - "POST /socket.io/?EIO=4&transport=polling&t=OdBkKms&sid=aHg-OEz6n-o01V0mAAAE HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 50010) - "WebSocket /socket.io/?EIO=4&transport=websocket&sid=aHg-OEz6n-o01V0mAAAE" [accepted]
INFO:     connection open
INFO:     127.0.0.1:50009 - "GET /socket.io/?EIO=4&transport=polling&t=OdBkKmu&sid=aHg-OEz6n-o01V0mAAAE HTTP/1.1" 200 OK
INFO:     127.0.0.1:50009 - "GET /socket.io/?EIO=4&transport=polling&t=OdBkKoh&sid=aHg-OEz6n-o01V0mAAAE HTTP/1.1" 200 OK
INFO:     127.0.0.1:50009 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:50011 - "POST /api/v1/images/?image_category=general&is_intermediate=true HTTP/1.1" 201 Created
INFO:     127.0.0.1:50011 - "POST /api/v1/images/?image_category=mask&is_intermediate=true HTTP/1.1" 201 Created
INFO:     127.0.0.1:50011 - "POST /api/v1/sessions/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:50011 - "PUT /api/v1/sessions/0ee8ca99-3a1b-4f4a-99a9-7efe359ee96b/invoke?all=true HTTP/1.1" 202 Accepted

**Comment by Millu** [comment]
Are you using a seed greater than 2147483647?

**Comment by aferlo78** [comment]
Yes! It started with 219 . Can remember the whole number now.
Is 2147483647 an upper limit for the seed?

Thank you for your reply

**Comment by Millu** [comment]
I believe it is as the moment - give a lower number a try and go from there!

**Comment by aferlo78** [comment]
thank you for your help
