### ISSUE TITLE
[enhancement]: Suggest inpainting model when incorrect type used

### ISSUE THREAD

**Issue by dannyvfilms** [invoke-ai/InvokeAI#4219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

`Input type (c10::Half) and bias type (float) should be the same`

This error appears for me when using a regular model like `epicrealism_pureEvolutionV5.safetensors` on a mask layer of the unified canvas instead of  `epicrealism_pureEvolutionV5-inpainting.safetensors`, which resolves the issue. It seems reasonable to either restrict the model list or add more information to the error suggesting that a different model be used. 

### Aditional Content

```[2023-08-09 20:26:23,036]::[uvicorn.access]::INFO --> 127.0.0.1:53738 - "POST /api/v1/images/upload?image_category=general&is_intermediate=true HTTP/1.1" 201
[2023-08-09 20:26:23,061]::[uvicorn.access]::INFO --> 127.0.0.1:53738 - "POST /api/v1/images/upload?image_category=mask&is_intermediate=true HTTP/1.1" 201
[2023-08-09 20:26:23,075]::[uvicorn.access]::INFO --> 127.0.0.1:53738 - "POST /api/v1/sessions/ HTTP/1.1" 200
[2023-08-09 20:26:23,116]::[uvicorn.access]::INFO --> 127.0.0.1:53738 - "PUT /api/v1/sessions/3a023468-ed1f-4ca9-9727-4a7bf0d62233/invoke?all=true HTTP/1.1" 202
[2023-08-09 20:26:23,135]::[uvicorn.access]::INFO --> 127.0.0.1:53741 - "PATCH /api/v1/images/i/55b0007c-9f89-4382-86f7-6259a25e3b78.png HTTP/1.1" 200
[2023-08-09 20:26:23,141]::[uvicorn.access]::INFO --> 127.0.0.1:53742 - "PATCH /api/v1/images/i/e966b627-589d-425a-a723-7e9bda530abf.png HTTP/1.1" 200
Generating:   0%|                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_img2img.StableDiffusionImg2ImgPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Generating:   0%|                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]
[2023-08-09 20:26:28,043]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/invokeai/app/services/processor.py", line 90, in __process
    outputs = invocation.invoke(
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/invokeai/app/invocations/generate.py", line 236, in invoke
    generator_output = next(outputs)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/invokeai/backend/generator/base.py", line 144, in generate
    results = generator.generate(
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/invokeai/backend/generator/base.py", line 328, in generate
    image = make_image(x_T, seed)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/invokeai/backend/generator/inpaint.py", line 292, in make_image
    pipeline_output = pipeline.inpaint_from_embeddings(
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 826, in inpaint_from_embeddings
    init_image_latents = self.non_noised_latents_from_image(init_image, device=device, dtype=latents_dtype)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 886, in non_noised_latents_from_image
    init_latent_dist = self.vae.encode(init_image).latent_dist
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/diffusers/models/autoencoder_kl.py", line 242, in encode
    h = self.encoder(x)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/diffusers/models/vae.py", line 110, in forward
    sample = self.conv_in(sample)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Applications/InvokeAI/.venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same

[2023-08-09 20:26:28,047]::[InvokeAI]::ERROR --> Error while invoking:
Input type (c10::Half) and bias type (float) should be the same
[```

**Comment by hipsterusername** [comment]
@lstein @psychedelicious - I'm seeing this as well on main. Unclear what is causing the issue, but non-inpainting models should be working.

No issues on txt2img.

**Comment by hipsterusername** [comment]
@lstein - Issue seems to be caused by non-default VAE selection. 

https://discord.com/channels/1020123559063990373/1131987080466137219/1138919616157073468
