### ISSUE TITLE
[bug]: Image2Image SDXL fails with `Not a valid model: <INVOKEAI_MODELS_DIR>`

### ISSUE THREAD

**Issue by raldone01** [invoke-ai/InvokeAI#4228]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

d42b45116fafafc713f659866f8bf4da857d2de6

### What happened?

![image](https://github.com/invoke-ai/InvokeAI/assets/27293675/8d032c93-001b-4c2f-b8d4-cb31a8e565b9)

Image2Image works with sd-1 and sd-2.
Before pulling in the latest main sdxl was working too.

Now it fails with the following error:
```
[2023-08-10 12:29:24,700]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/opt/invokeai/invokeai/app/services/processor.py", line 90, in __process
    outputs = invocation.invoke(
  File "/opt/venv/invokeai/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/invokeai/invokeai/app/invocations/latent.py", line 690, in invoke
    vae_info = context.services.model_manager.get_model(
  File "/opt/invokeai/invokeai/app/services/model_manager_service.py", line 365, in get_model
    model_info = self.mgr.get_model(
  File "/opt/invokeai/invokeai/backend/model_management/model_manager.py", line 484, in get_model
    model_path = model_class.convert_if_required(
  File "/opt/invokeai/invokeai/backend/model_management/models/vae.py", line 105, in convert_if_required
    if cls.detect_format(model_path) == VaeModelFormat.Checkpoint:
  File "/opt/invokeai/invokeai/backend/model_management/models/vae.py", line 95, in detect_format
    raise InvalidModelException(f"Not a valid model: {path}")
invokeai.backend.model_management.models.base.InvalidModelException: Not a valid model: /my/models

[2023-08-10 12:29:24,716]::[InvokeAI]::ERROR --> Error while invoking:
Not a valid model: /my/models
```

![image](https://github.com/invoke-ai/InvokeAI/assets/27293675/883d7fb9-6c1a-492f-be49-a35024080d2f)

I can generate normal images with sdxl.
Only Image2Image fails.

Note: I had to manually add sdxl otherwise it would be recognized as sd-1 onnx runtime.

**Comment by hipsterusername** [comment]
This seems to be specifically failing with VAE - Can you download and manually configure the VAE location, to see if this resolves it?

**Comment by raldone01** [comment]
Today I had time to work on invoke again and I pulled in the latest master: `250d530260b50893285a1287ba211d9adda8d03b`
Without further changes the issue is gone.
