### ISSUE TITLE
[bug]: memory_efficient_attention_forward

### ISSUE THREAD

**Issue by poojan-solanki** [invoke-ai/InvokeAI#4230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4 GB

### What version did you experience this issue on?

3.0.1post3

### What happened?

I just installed invokeai. For the first when i entered prompt on invokeai-web i got this error

```
[2023-08-10 21:30:54,942]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\app\services\processor.py", line 86, in __process
    outputs = invocation.invoke(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 363, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 461, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 194, in __call__
    for result in self.generator_method(*args, **kwargs):
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 515, in generate_latents_from_embeddings
    step_output = self.step(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 651, in step
    noise_pred = self.invokeai_diffuser.do_diffusion_step(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusion\shared_invokeai_diffusion.py", line 204, in do_diffusion_step
    ) = self._apply_standard_conditioning(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusion\shared_invokeai_diffusion.py", line 290, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 695, in _unet_forward
    return self.unet(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 915, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 996, in forward
    hidden_states = attn(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\diffusers\models\transformer_2d.py", line 292, in forward
    hidden_states = block(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\diffusers\models\attention.py", line 155, in forward
    attn_output = self.attn1(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\diffusers\models\attention_processor.py", line 322, in forward
    return self.processor(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\diffusers\models\attention_processor.py", line 1034, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 306, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 94, in _dispatch_fw
    return _run_priority_list(
  File "C:\Users\bluts\invokeai\.venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 69, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(10, 4096, 1, 64) (torch.float32)
     key         : shape=(10, 4096, 1, 64) (torch.float32)
     value       : shape=(10, 4096, 1, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    has custom scale
    unsupported embed per head: 64

[2023-08-10 21:30:54,950]::[InvokeAI]::ERROR --> Error while invoking:
No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(10, 4096, 1, 64) (torch.float32)
     key         : shape=(10, 4096, 1, 64) (torch.float32)
     value       : shape=(10, 4096, 1, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    has custom scale
    unsupported embed per head: 64
```

output of `python -m xformers.info`

```
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xFormers 0.0.20
memory_efficient_attention.cutlassF:               available
memory_efficient_attention.cutlassB:               available
memory_efficient_attention.flshattF:               available
memory_efficient_attention.flshattB:               available
memory_efficient_attention.smallkF:                available
memory_efficient_attention.smallkB:                available
memory_efficient_attention.tritonflashattF:        unavailable
memory_efficient_attention.tritonflashattB:        unavailable
indexing.scaled_index_addF:                        available
indexing.scaled_index_addB:                        available
indexing.index_select:                             available
swiglu.dual_gemm_silu:                             available
swiglu.gemm_fused_operand_sum:                     available
swiglu.fused.p.cpp:                                available
is_triton_available:                               False
is_functorch_available:                            False
pytorch.version:                                   2.0.1+cu117
pytorch.cuda:                                      available
gpu.compute_capability:                            8.6
gpu.name:                                          NVIDIA GeForce RTX 3050 Laptop GPU
build.info:                                        available
build.cuda_version:                                1108
build.python_version:                              3.10.11
build.torch_version:                               2.0.1+cu118
build.env.TORCH_CUDA_ARCH_LIST:                    5.0+PTX 6.0 6.1 7.0 7.5 8.0 8.6
build.env.XFORMERS_BUILD_TYPE:                     Release
build.env.XFORMERS_ENABLE_DEBUG_ASSERTIONS:        None
build.env.NVCC_FLAGS:                              None
build.env.XFORMERS_PACKAGE_FROM:                   wheel-v0.0.20
build.nvcc_version:                                11.8.89
source.privacy:                                    open source
```

pytorch version
```
(InvokeAI) PS C:\Users\bluts\invokeai\.venv\Scripts> pip show torch
Name: torch
Version: 2.0.1+cu117
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\bluts\invokeai\.venv\lib\site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, basicsr, clip-anytorch, compel, controlnet-aux, facexlib, gfpgan, invisible-watermark, InvokeAI, pytorch-lightning, realesrgan, test-tube, timm, torchmetrics, torchsde, torchvision, xformers
```
pip command shows me deprecation warning
```
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
```

### Contact Details

blutspoojansolanki@gmail.com

**Comment by hipsterusername** [comment]
Your installation did not install with CUDA - specifically says "device=cpu (supported: {'cuda'})" 

Please reinstall and select the NVidia option to get CUDA

**Comment by poojan-solanki** [comment]
Actually i did select nvidia cuda option while installing invokeai

First I installed with installation script. Got same error

Deleted all the files of invokeai manually then build from source using this code which is for nvidia gpu
`pip install "InvokeAI[xformers]" --use-pep517 --extra-index-url https://download.pytorch.org/whl/cu118`

Still got same error.

**Comment by poojan-solanki** [comment]
Thank you for your support, but I did select  Nvidia gpu while installing. Also, I performed installation twice, first by installation script and then from source. In both the cases the issue remains the same. Hope you understand and please reopen my issue #4230.


________________________________
