### ISSUE TITLE
[bug]: invokeai-3.log path mixup during configuration in 

### ISSUE THREAD

**Issue by gsreeves** [invoke-ai/InvokeAI#4245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32GB

### What version did you experience this issue on?

3.0.2

### What happened?

When running internal upgrade, model management, or re-install from zip, scripts look to write to invokeai-3.log but form the path with BOTH the full path to installer folder AND the user-home-relative path to designated destination folder starting with ~ (tilde).
For example, during re-install from zip file:
An OS error was encountered during configuration and download: [Errno 2] No such file or directory: '/Users/USERNAME/Pictures/AI_Paintings/InvokeAI-Installer/~/Pictures/AI_Paintings/invokeai-3/invokeai-3.log'

**Comment by gsreeves** [comment]
Now attempting install to default folder that I never used before ~/invokeai

**Comment by gsreeves** [comment]
A hint is that the same error occurred during model install script:
`Download and install models
Traceback (most recent call last):
  File "/Users/shawn/Pictures/AI_Paintings/invokeai-3/.venv/bin/invokeai-model-install", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/shawn/Pictures/AI_Paintings/invokeai-3/.venv/lib/python3.11/site-packages/invokeai/frontend/install/model_install.py", line 774, in main
    logger = InvokeAILogger().getLogger(config=config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawn/Pictures/AI_Paintings/invokeai-3/.venv/lib/python3.11/site-packages/invokeai/backend/util/logging.py", line 364, in getLogger
    for ch in cls.getLoggers(config):
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawn/Pictures/AI_Paintings/invokeai-3/.venv/lib/python3.11/site-packages/invokeai/backend/util/logging.py", line 391, in getLoggers
    ch = cls._parse_file_args(args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawn/Pictures/AI_Paintings/invokeai-3/.venv/lib/python3.11/site-packages/invokeai/backend/util/logging.py", line 428, in _parse_file_args
    return logging.FileHandler(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shawn/Pictures/AI_Paintings/invokeai-3/~/Pictures/AI_Paintings/invokeai-3/invokeai-3.log'`

**Comment by gsreeves** [comment]
Install to default folder fixes issue. Beware installation environment with pyenv and homebrew python, or non-default install location, which might throw a curve to logging code.

**Comment by gsreeves** [comment]
Argh, it was a custom log path in my yaml that caused all this. CLOSING.
