### ISSUE TITLE
[bug]: Can't generate image - Server Error OS Error

### ISSUE THREAD

**Issue by shap-po** [invoke-ai/InvokeAI#4257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.2post1

### What happened?

The image generator is not working. The console is empty, but the web interface is showing a `Server Error OS Error`.
I tried reinstalling it manually and using the installer, but neither helped. Windows permissions checked, starting `invoke.bat` with admin perms. What am I missing?
There is a guy with the same problem on Discord: https://discord.com/channels/1020123559063990373/1140153482926628964

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/50052124/968a083b-1deb-455f-b5c5-aadf1fc9ec51)

**Comment by hipsterusername** [comment]
Can you press F12 in the browser, open the console, and see what error is displayed there?

**Comment by shap-po** [comment]
after a model load is complete:
[socketio]: Invocation error (t2l):
```json
{
  "data": {
    "graph_execution_state_id": "ea1d4616-c30b-4cf6-b0c4-bc4772638663",
    "node": {
      "id": "943cdb9a-c7e5-48d8-8c11-e0d03aa2f887",
      "is_intermediate": true,
      "type": "t2l",
      "positive_conditioning": {
        "conditioning_name": "ea1d4616-c30b-4cf6-b0c4-bc4772638663_c3420c7a-5f87-40d1-be8b-c00d005f2a15_conditioning"
      },
      "negative_conditioning": {
        "conditioning_name": "ea1d4616-c30b-4cf6-b0c4-bc4772638663_4966f502-6352-4262-832b-c59c4837ef46_conditioning"
      },
      "noise": {
        "latents_name": "ea1d4616-c30b-4cf6-b0c4-bc4772638663__5a384aa2-431f-4cb7-8ec0-da6db6322d16"
      },
      "steps": 50,
      "cfg_scale": 7.5,
      "scheduler": "euler",
      "unet": {
        "unet": {
          "model_name": "stable-diffusion-2-1",
          "base_model": "sd-2",
          "model_type": "main",
          "submodel": "unet"
        },
        "scheduler": {
          "model_name": "stable-diffusion-2-1",
          "base_model": "sd-2",
          "model_type": "main",
          "submodel": "scheduler"
        },
        "loras": []
      },
      "control": null
    },
    "source_node_id": "text_to_latents",
    "error_type": "OSError",
    "error": "Traceback (most recent call last):\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\invokeai\\app\\services\\processor.py\", line 90, in __process\n    outputs = invocation.invoke(\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\torch\\utils\\_contextlib.py\", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\latent.py\", line 358, in invoke\n    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\invokeai\\backend\\stable_diffusion\\diffusers_pipeline.py\", line 383, in latents_from_embeddings\n    result: PipelineIntermediateState = infer_latents_from_embeddings(\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\invokeai\\backend\\stable_diffusion\\diffusers_pipeline.py\", line 189, in __call__\n    for result in self.generator_method(*args, **kwargs):\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\invokeai\\backend\\stable_diffusion\\diffusers_pipeline.py\", line 435, in generate_latents_from_embeddings\n    for i, t in enumerate(self.progress_bar(timesteps)):\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\diffusers\\pipelines\\pipeline_utils.py\", line 1599, in progress_bar\n    return tqdm(iterable, **self._progress_bar_config)\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\tqdm\\asyncio.py\", line 24, in __init__\n    super(tqdm_asyncio, self).__init__(iterable, *args, **kwargs)\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\tqdm\\std.py\", line 1097, in __init__\n    self.sp = self.status_printer(self.fp)\n  File \"C:\\Workspace\\AI\\invokeai\\.venv\\lib\\site-packages\\tqdm\\std.py\", line 451, in status_printer\n    getattr(sys.stderr, 'flush', lambda: None)()\nOSError: [WinError 6] The handle is invalid\n",
    "timestamp": 1691935874
  }
}
```

**Comment by JSorngard** [comment]
I face the same error whenever I try to generate an image. It says "Server Error: OS Error" in a popup just like this.

**Comment by Nico-Src** [comment]
same for me here. Anybody found a fix or workaround?

**Comment by blueneogeo** [comment]
Same here. I tried the fixes in the FAQ section of the website, did not fix it.

**Comment by s31z** [comment]
I have the same issue on InvokeAI 3.1.1 / Windows 11 / CUDA / Python 3.9.
Reinstalled 2 times now and tried different models.

Always fails and shows the famous popup "Server Error / OS Error" after loading the model.
```
debug  [socketio]: Model load started: sd-1/main/stable-diffusion-v1-5/unet  
debug  [socketio]: Model load complete: sd-1/main/stable-diffusion-v1-5/unet  
debug  [socketio]: Model load started: sd-1/main/stable-diffusion-v1-5/scheduler  
debug  [socketio]: Model load complete: sd-1/main/stable-diffusion-v1-5/scheduler  
error  [socketio]: Invocation error (denoise_latents)
```

Detailed error output:
```python
Traceback (most recent call last):
  File "d:\invokeai\.venv\lib\site-packages\invokeai\app\services\processor.py", line 95, in __process
    outputs = invocation.invoke_internal(
  File "d:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 568, in invoke_internal
    return self.invoke(context)
  File "d:\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "d:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 527, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
  File "d:\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 397, in latents_from_embeddings
    latents, attention_map_saver = self.generate_latents_from_embeddings(
  File "d:\invokeai\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 452, in generate_latents_from_embeddings
    for i, t in enumerate(self.progress_bar(timesteps)):
  File "d:\invokeai\.venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1618, in progress_bar
    return tqdm(iterable, **self._progress_bar_config)
  File "d:\invokeai\.venv\lib\site-packages\tqdm\asyncio.py", line 24, in __init__
    super(tqdm_asyncio, self).__init__(iterable, *args, **kwargs)
  File "d:\invokeai\.venv\lib\site-packages\tqdm\std.py", line 1097, in __init__
    self.sp = self.status_printer(self.fp)
  File "d:\invokeai\.venv\lib\site-packages\tqdm\std.py", line 451, in status_printer
    getattr(sys.stderr, 'flush', lambda: None)()
OSError: [WinError 6] The handle is invalid
```

Can anyone point us into the right direction?

**Comment by hipsterusername** [comment]
Going to ping @lstein to see if he has any idea - this seems to be happening deep in the Python interactions on your OS.

cc: @Millu

**Comment by Nico-Src** [comment]
For me it worked after uninstalling 3.9 and installing 3.10.

**Comment by s31z** [comment]
Just tried that (upgraded to 3.11) and yes, now it works fine. 
Thank you for the suggestion!
