### ISSUE TITLE
[bug]: “CUDA out of memory” trying to use SD-XL model

### ISSUE THREAD

**Issue by palant** [invoke-ai/InvokeAI#4264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

3.0.2

### What happened?

In A1111 Web UI, I can use SD-XL and generate 1024x1024 images (GTX 1660 graphics card). Same sd_xl_base_1.0_0.9vae.safetensors file imported into InvokeAI immediately produces “CUDA out of memory” error however, even when I set image size to 512x512. Not sure what I can do to find out more about the cause of the issue here.

### Additional context

Traceback:

```
  File "invokeai/.venv/lib/python3.9/site-packages/invokeai/app/services/processor.py", line 90, in __process
    outputs = invocation.invoke(
  File "invokeai/.venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "invokeai/.venv/lib/python3.9/site-packages/invokeai/app/invocations/sdxl.py", line 309, in invoke
    with ModelPatcher.apply_lora_unet(unet_info.context.model, _lora_loader()), unet_info as unet:
  File "invokeai/.venv/lib/python3.9/site-packages/invokeai/backend/model_management/model_manager.py", line 283, in __enter__
    return self.context.__enter__()
  File "invokeai/.venv/lib/python3.9/site-packages/invokeai/backend/model_management/model_cache.py", line 243, in __enter__
    self.model.to(self.cache.execution_device)  # move into GPU
  File "invokeai/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "invokeai/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "invokeai/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "invokeai/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 7 more times]
  File "invokeai/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "invokeai/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 5.79 GiB total capacity; 4.36 GiB already allocated; 44.88 MiB free; 4.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by mrtkp9993** [comment]
I have same problem. I have RTX 3060 with 6GB VRAM.

**Comment by Millu** [comment]
Can you try setting your VAE precision to fp16?

**Comment by mrtkp9993** [comment]
> Can you try setting your VAE precision to fp16?

Yes, I tried. This is the error message:

```
[2023-08-23 15:42:36,454]::[InvokeAI]::INFO --> Loading model C:\Users\murat\Desktop\projects\art\InvokeAI\models\sdxl\main\stable-diffusion-xl-base-1-0, type sdxl:main:tokenizer
[2023-08-23 15:42:37,248]::[InvokeAI]::INFO --> Loading model C:\Users\murat\Desktop\projects\art\InvokeAI\models\sdxl\main\stable-diffusion-xl-base-1-0, type sdxl:main:text_encoder
[2023-08-23 15:42:43,272]::[InvokeAI]::INFO --> Loading model C:\Users\murat\Desktop\projects\art\InvokeAI\models\sdxl\main\stable-diffusion-xl-base-1-0, type sdxl:main:tokenizer_2
[2023-08-23 15:42:43,553]::[InvokeAI]::INFO --> Loading model C:\Users\murat\Desktop\projects\art\InvokeAI\models\sdxl\main\stable-diffusion-xl-base-1-0, type sdxl:main:text_encoder_2
[2023-08-23 15:43:04,738]::[InvokeAI]::INFO --> Loading model C:\Users\murat\Desktop\projects\art\InvokeAI\models\sdxl\main\stable-diffusion-xl-base-1-0, type sdxl:main:scheduler
[2023-08-23 15:43:04,999]::[InvokeAI]::INFO --> Loading model C:\Users\murat\Desktop\projects\art\InvokeAI\models\sdxl\main\stable-diffusion-xl-base-1-0, type sdxl:main:unet
[2023-08-23 15:43:11,050]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\invokeai\app\services\processor.py", line 90, in __process
    outputs = invocation.invoke(
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\sdxl.py", line 309, in invoke
    with ModelPatcher.apply_lora_unet(unet_info.context.model, _lora_loader()), unet_info as unet:
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 283, in __enter__
    return self.context.__enter__()
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 243, in __enter__
    self.model.to(self.cache.execution_device)  # move into GPU
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\murat\Desktop\projects\art\InvokeAI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.06 GiB already allocated; 0 bytes free; 5.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

[2023-08-23 15:43:11,058]::[InvokeAI]::ERROR --> Error while invoking:
CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.06 GiB already allocated; 0 bytes free; 5.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by palant** [comment]
> Can you try setting your VAE precision to fp16?

I already tried, along with a bunch of other tweaks. Nothing helped, still out of memory.

**Comment by omer-bar** [comment]
same here! And I'm with an 8 GB VRAM card(3070)...
The same modal works fine in comfyUI and in A1111 even with 1024x1024...
I'm setting the modal to 256x256 and it's out of memory so...

**Comment by freshlesh3** [comment]
Has anyone resolved this? I have two 12gb RTX 4070s and still get this error?

**Comment by Millu** [comment]
@freshlesh3 could you try setting your VRAM cache in your invokeai.yaml to 0.25?

**Comment by psychedelicious** [comment]
We've refactored much of the model loading in v4. Please update and if you still have this issue, we can investigate further.
