### ISSUE TITLE
[bug]: Error Running Web Interface

### ISSUE THREAD

**Issue by Metal-Toilet** [invoke-ai/InvokeAI#4286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What version did you experience this issue on?

3.0.2

### What happened?

First I ran ```sudo /home/myname/invokeai/invoke.sh``` to get the start dialog. After selecting one (run the web interface) I was met with the following error: 

```
Traceback (most recent call last):
  File "/home/henry/invokeai/.venv/bin/invokeai-web", line 5, in <module>
    from invokeai.app.api_app import invoke_api
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/api_app.py", line 22, in <module>
    from ..backend.util.logging import InvokeAILogger
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/__init__.py", line 4, in <module>
    from .generator import InvokeAIGeneratorBasicParams, InvokeAIGenerator, InvokeAIGeneratorOutput, Img2Img, Inpaint
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/generator/__init__.py", line 4, in <module>
    from .base import (
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/generator/base.py", line 9, in <module>
    import diffusers
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 24, in <module>
    import accelerate
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 13, in <module>
    from .dataclasses import (
  File "/home/henry/invokeai/.venv/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 29, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'
```

### Additional context

Any help is greatly appreciated!

### Contact Details

metaltoilet <--discord

**Comment by Millu** [comment]
Can you try option [7] to fix a broken install?

**Comment by Metal-Toilet** [comment]
Tried that a minute ago and it fixed it right up.
------- Original Message -------
