### ISSUE TITLE
[bug]: Exception in ASGI application when I try to merge models

### ISSUE THREAD

**Issue by WildPowerHammer** [invoke-ai/InvokeAI#4327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.2post1

### What happened?

I tried merging models and got error: 

[2023-08-19 16:16:31,193]::[uvicorn.error]::ERROR --> Exception in ASGI application

Traceback (most recent call last):
  File "E:\InvokeAI\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\InvokeAI\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "E:\InvokeAI\.venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "E:\InvokeAI\.venv\lib\site-packages\fastapi_events\middleware.py", line 43, in __call__
    await self.app(scope, receive, send)
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\InvokeAI\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\InvokeAI\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\InvokeAI\.venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\InvokeAI\.venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "E:\InvokeAI\.venv\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "E:\InvokeAI\.venv\lib\site-packages\invokeai\app\api\routers\models.py", line 368, in merge_models
    result = ApiDependencies.invoker.services.model_manager.merge_models(
  File "E:\InvokeAI\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 595, in merge_models
    result = merger.merge_diffusion_models_and_save(
  File "E:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_merge.py", line 125, in merge_diffusion_models_and_save
    merged_pipe.save_pretrained(dump_path, safe_serialization=True)
  File "E:\InvokeAI\.venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 643, in save_pretrained
    self.save_config(save_directory)
  File "E:\InvokeAI\.venv\lib\site-packages\diffusers\configuration_utils.py", line 156, in save_config
    self.to_json_file(output_config_file)
  File "E:\InvokeAI\.venv\lib\site-packages\diffusers\configuration_utils.py", line 566, in to_json_file
    writer.write(self.to_json_string())
  File "E:\InvokeAI\.venv\lib\site-packages\diffusers\configuration_utils.py", line 555, in to_json_string
    return json.dumps(config_dict, indent=2, sort_keys=True) + "\n"
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\MyUser\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable

The most important thing I've highlighted: ERROR --> Exception in ASGI application and TypeError: Object of type WindowsPath is not JSON serializable

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/136165053/bc9319f5-1f53-43d7-b7a3-b653790f6e44)

### Additional context

Maybe I'm just a bit stupid and these two models can't be merged, but according to the error, the problem is something else.
I can try merge something else to see if this will work, but then I need to know exactly which ones can be merged under normal conditions

**Comment by WildPowerHammer** [comment]
After upgrading to 3.1.0, merging works from the text interface, it still doesn't work in the web gui, but I'm pretty sure it's my browser and other local issues.
### You are the best, thanks a lot!

**Comment by WildPowerHammer** [comment]
P.S. - After a few browser changes and some experiments it works on the browsers as well, thanks again!
