### ISSUE TITLE
[bug]: No module named invokeai.app.assets

### ISSUE THREAD

**Issue by c-montgomery** [invoke-ai/InvokeAI#4329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.0.2post1

### What happened?

When using stable-diffusion-xl-base-1-0, image generation looks to complete in the cmd.exe and image preview but throws error. I expected an image of a cat or a dragon. 
                                                                                                                                                                                              
![cmd_error_invokeai](https://github.com/invoke-ai/InvokeAI/assets/67046360/1ddb1801-3d28-4870-a4bf-9a6f24f43448)
[2023-08-19 11:01:21,293]::[InvokeAI]::INFO --> Loading model Z:\invokeai\models\sdxl\main\stable-diffusion-xl-base-1-0, type sdxl:main:vae Z:\invokeai.venv\lib\site-packages\diffusers\image_processor.py:65: RuntimeWarning: invalid value encountered in cast images = (images * 255).round().astype("uint8") [2023-08-19 11:01:23,077]::[uvicorn.access]::INFO --> 127.0.0.1:53980 - "GET /api/v1/images/i/2dfe4edc-cf2c-46a0-8e13-5a46a2015a93.png HTTP/1.1" 200 [2023-08-19 11:01:23,095]::[InvokeAI]::INFO --> A potentially NSFW image has been detected. Image will be blurred. [2023-08-19 11:01:23,105]::[InvokeAI]::ERROR --> Traceback (most recent call last): File "Z:\invokeai.venv\lib\site-packages\invokeai\app\services\processor.py", line 90, in __process outputs = invocation.invoke( File "Z:\invokeai.venv\lib\site-packages\invokeai\app\invocations\image.py", line 592, in invoke caution = self._get_caution_img() File "Z:\invokeai.venv\lib\site-packages\invokeai\app\invocations\image.py", line 613, in _get_caution_img import invokeai.app.assets.images as image_assets ModuleNotFoundError: No module named 'invokeai.app.assets' [2023-08-19 11:01:23,134]::[InvokeAI]::ERROR --> Error while invoking: No module named 'invokeai.app.assets'

### Additional context

Only happens with xl-base-1-0 . It's always marked nsfw, no matter the prompt (in this example the prompt was "dragons" or "cats"). When preview are turned on, an image generates and changes, and then isnt output to the right panel as an error is displayed. Seems almost random as I've tried with various schedulers, VAE, precision on/off. I've also stopped all options after the general tab. No refiner/LoRa/dynamic_prompts/noise

### Contact Details

collinrmontgomery@proton.me

**Comment by Millu** [comment]
Could you trying running option [7] in the launcher script to see if that resolves the issue?

**Comment by c-montgomery** [comment]
I should have mentioned that I tried that to no avail.  Updating python appears to have fixed it. I can no longer reproduce it.

**Comment by regstuff** [comment]
> I should have mentioned that I tried that to no avail. Updating python appears to have fixed it. I can no longer reproduce it.

@c-montgomery might I ask which version of python worked? I have an issue where sdxl outputs only black images, and this error pops up in the backend: `RuntimeWarning: invalid value encountered in cast images = (images * 255).round().astype("uint8") `
I'm on python 3.10

**Comment by c-montgomery** [comment]
Something in the 3.11.x range. I think it was 3.11.1, but i'm not 100% sure. No access to that comp, so that's my best guess
