### ISSUE TITLE
[bug]:  Error while invoking: Failed to load sd-1:main:unet model

### ISSUE THREAD

**Issue by Zorgonaute84** [invoke-ai/InvokeAI#4348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10

### What version did you experience this issue on?

3.0.2Post1

### What happened?

All in painting models run error (except the SD1.5 inpainting).

In the WEB UI I have this error after "Invoke" :
![image](https://github.com/invoke-ai/InvokeAI/assets/13313177/b97ff8d1-4611-443d-a993-c07dfbad1cab)

and this message in the consol : 

====ERR LOAD====
None: Cannot load C:\InvokeAI\autoimport\sd-1\main\RealisticVision v51 Inpainting because conv_in.weight expected shape tensor(..., device='meta', size=(320, 4, 3, 3)), but got torch.Size([320, 9, 3, 3]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
[2023-08-23 22:54:42,148]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\InvokeAI\.venv\lib\site-packages\invokeai\app\services\processor.py", line 90, in __process
    outputs = invocation.invoke(
  File "C:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\generate.py", line 217, in invoke
    with self.load_model_old_way(context, scheduler) as model:
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\generate.py", line 171, in load_model_old_way
    unet_info = context.services.model_manager.get_model(
  File "C:\InvokeAI\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 365, in get_model
    model_info = self.mgr.get_model(
  File "C:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 491, in get_model
    model_context = self.cache.get_model(
  File "C:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 198, in get_model
    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)
  File "C:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\models\base.py", line 300, in get_model
    raise Exception(f"Failed to load {self.base_model}:{self.model_type}:{child_type} model")
Exception: Failed to load sd-1:main:unet model

[2023-08-23 22:54:42,154]::[InvokeAI]::ERROR --> Error while invoking:
Failed to load sd-1:main:unet model

I read that some parameters have to be set, but don't understand why and where...

PS : I didn't have this issue with InvokeAI 2

**Comment by Millu** [comment]
Could you try clearing your models/.cache and restarting Invoke?

**Comment by Zorgonaute84** [comment]
Thanks for your reply, delete the cache folder did'nt solve my issue (the folder was empty, be cause I already convert my models to diffusers with InvokeAI), But, I try to delete the converted model, redownload it, and convert it again... And it works !
I concluded that my models was converter between 3.0 and 3.02 :-)
Thanks
