### ISSUE TITLE
[bug]: Error when using Random seed in webui

### ISSUE THREAD

**Issue by angelo-melis** [invoke-ai/InvokeAI#4371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

3.0.2post1

### What happened?

When setting the Random seed and then press Invoke I get the error message 'Server Error. Internal server error' in the web interface. When setting a manual seed the problem goes away and invoke generates an image. This always worked before, but some commit back this started to occur. 

In the console window the following error is visible:

[2023-08-27 23:55:29,555]::[uvicorn.error]::ERROR --> Exception in ASGI application

Traceback (most recent call last):
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/fastapi_events/middleware.py", line 43, in __call__
    await self.app(scope, receive, send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/Volumes/Angelo-T7b/InvokeAI/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/Volumes/Angelo-T7b/InvokeAI/invokeai/app/api/routers/sessions.py", line 263, in invoke_session
    ApiDependencies.invoker.invoke(session, invoke_all=all)
  File "/Volumes/Angelo-T7b/InvokeAI/invokeai/app/services/invoker.py", line 25, in invoke
    invocation = graph_execution_state.next()
  File "/Volumes/Angelo-T7b/InvokeAI/invokeai/app/services/graph.py", line 772, in next
    prepared_id = self._prepare()
  File "/Volumes/Angelo-T7b/InvokeAI/invokeai/app/services/graph.py", line 960, in _prepare
    create_results = self._create_execution_node(next_node_id, iteration_mappings)  # type: ignore
  File "/Volumes/Angelo-T7b/InvokeAI/invokeai/app/services/graph.py", line 875, in _create_execution_node
    self.execution_graph.add_edge(new_edge)
  File "/Volumes/Angelo-T7b/InvokeAI/invokeai/app/services/graph.py", line 302, in add_edge
    self._validate_edge(edge)
  File "/Volumes/Angelo-T7b/InvokeAI/invokeai/app/services/graph.py", line 391, in _validate_edge
    raise InvalidEdgeError(
invokeai.app.services.graph.InvalidEdgeError: Fields are incompatible: cannot connect 074ea867-0bcd-4288-b068-3a5a36028927.a to 72c56a63-2bb5-4476-ac0d-69c89b330429.start

Hope someone knows whats going on here.

### Additional context

Only happens when I select a Random seed

**Comment by Millu** [comment]
Are you on 3.0.2post1 or are you pulling from main?
