### ISSUE TITLE
[bug]: SDXL embedding <negativeXL_D> throw error

### ISSUE THREAD

**Issue by frankyifei** [invoke-ai/InvokeAI#4401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.0.2post1

### What happened?

popular negative embedding for SDXL `<negativeXL_D>` does not work with counterfeitxl and sdxl-base1.0. another popular embedding `<unaestheticXLv31>` also throw same error message

`[2023-08-31 14:46:36,949]::[InvokeAI]::ERROR --> Error while invoking:
Cannot load embedding for <negativeXL_D>. It was trained on a model with token dimension 1280, but the current model has token dimension 768.`

**Comment by damian0815** [comment]
i think this is an issue with InvokeAI - can you post the bug report there? https://github.com/invoke-ai/InvokeAI

**Comment by frankyifei** [comment]
log is this
`[2023-08-31 20:30:07,741]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "F:\InvokeAI\.venv\lib\site-packages\invokeai\app\services\processor.py", line 95, in __process
    outputs = invocation.invoke_internal(
  File "F:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 514, in invoke_internal
    return self.invoke(context)
  File "F:\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 287, in invoke
    c1, c1_pooled, ec1 = self.run_clip_compel(
  File "F:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 217, in run_clip_compel
    with ModelPatcher.apply_lora(
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "F:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\lora.py", line 199, in apply_ti
    raise ValueError(
ValueError: Cannot load embedding for <unaestheticXLv31>. It was trained on a model with token dimension 1280, but the current model has token dimension 768.

[2023-08-31 20:30:07,759]::[InvokeAI]::ERROR --> Error while invoking:
Cannot load embedding for <unaestheticXLv31>. It was trained on a model with token dimension 1280, but the current model has token dimension 768.`

**Comment by damian0815** [comment]
oh whoops i thought this was a bug on compel, sorry

**Comment by frankyifei** [comment]
both embeddings work well with automatic1111 and comfyui
