### ISSUE TITLE
Error caught was: No module named 'triton'[bug]: 

### ISSUE THREAD

**Issue by def1701** [invoke-ai/InvokeAI#4403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.1.0

### What happened?

Latest version doesn't seem to install on Windows.  Tried upgrade and then zip file.  I realize it should skip this issue, but the install fails at that point and does not continue.

### Contact Details

davidf@argus-holdings.com

**Comment by vladimmi** [comment]
Same here, though actual error caught can be seen in this log:
```
(.venv) F:\InvokeAI3>invokeai-configure --root .
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\InvokeAI3\.venv\Scripts\invokeai-configure.exe\__main__.py", line 4, in <module>
  File "F:\InvokeAI3\.venv\lib\site-packages\invokeai\frontend\install\invokeai_configure.py", line 4, in <module>
    from ...backend.install.invokeai_configure import main as invokeai_configure
  File "F:\InvokeAI3\.venv\lib\site-packages\invokeai\backend\__init__.py", line 5, in <module>
    from .model_management import ModelManager, ModelCache, BaseModelType, ModelType, SubModelType, ModelInfo
  File "F:\InvokeAI3\.venv\lib\site-packages\invokeai\backend\model_management\__init__.py", line 4, in <module>
    from .model_manager import ModelManager, ModelInfo, AddModelResult, SchedulerPredictionType
  File "F:\InvokeAI3\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 249, in <module>
    from .model_cache import ModelCache, ModelLocker
  File "F:\InvokeAI3\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 31, in <module>
    from .models import BaseModelType, ModelType, SubModelType, ModelBase
  File "F:\InvokeAI3\.venv\lib\site-packages\invokeai\backend\model_management\models\__init__.py", line 21, in <module>
    from .vae import VaeModel
  File "F:\InvokeAI3\.venv\lib\site-packages\invokeai\backend\model_management\models\vae.py", line 8, in <module>
    from diffusers.utils import is_safetensors_available
ImportError: cannot import name 'is_safetensors_available' from 'diffusers.utils' (F:\InvokeAI3\.venv\lib\site-packages\diffusers\utils\__init__.py)
```

**Comment by psychedelicious** [comment]
These issues sound like issues with dependency resolution with the old installer. Please create a new issue if the problems persist with the latest release (v4.1.0).
