### ISSUE TITLE
[bug]: Error if VAE other than "Default" is used with XL

### ISSUE THREAD

**Issue by realmalikov** [invoke-ai/InvokeAI#4441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What version did you experience this issue on?

3.1.0

### What happened?

My VAE is shown to me in the dropdown under SDXL, but no image can be completed because I get the following error every time:
Error while invoking: Vae conversion not supported for model type: sdxl

### Additional context

The VAE is by the way the normal sdxl_vae.safetensors from Stability, which was copied into the intended folder.
Custom VAEs for 1.5 work fine.

**Comment by YKefasu** [comment]
up same issue

```
[2023-09-28 00:39:45,519]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\AI FOLDER\InvokeAI\.venv\lib\site-packages\invokeai\app\services\processor.py", line 95, in __process
    outputs = invocation.invoke_internal(
  File "C:\AI FOLDER\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 549, in invoke_internal
    return self.invoke(context)
  File "C:\AI FOLDER\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\AI FOLDER\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 794, in invoke
    vae_info = context.services.model_manager.get_model(
  File "C:\AI FOLDER\InvokeAI\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 373, in get_model
    model_info = self.mgr.get_model(
  File "C:\AI FOLDER\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 485, in get_model
    model_path = model_class.convert_if_required(
  File "C:\AI FOLDER\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\models\vae.py", line 105, in convert_if_required
    return _convert_vae_ckpt_and_cache(
  File "C:\AI FOLDER\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\models\vae.py", line 156, in _convert_vae_ckpt_and_cache
    raise Exception(f"Vae conversion not supported for model type: {base_model}")
Exception: Vae conversion not supported for model type: sdxl

[2023-09-28 00:39:45,536]::[InvokeAI]::ERROR --> Error while invoking:
Vae conversion not supported for model type: sdxl
```

**Comment by DexeconGithub** [comment]
same here

**Comment by psychedelicious** [comment]
The model manager has been rewritten and we have no issues with SDXL VAEs in recent memory. Please create a new issue if the problem persisted with the latest release (v4.1.0)
