### ISSUE TITLE
[bug]:  my Ivokeai is error. please help

### ISSUE THREAD

**Issue by thienbaogithub** [invoke-ai/InvokeAI#4453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

32

### What version did you experience this issue on?

3.1.0

### What happened?

Generate images with a browser-based interface
/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
objc[1850]: Class CaptureDelegate is implemented in both /Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so (0x2889665e0) and /opt/homebrew/Cellar/opencv/4.8.0_4/lib/libopencv_videoio.4.8.0.dylib (0x299bdc880). One of the two will be used. Which one is undefined.
objc[1850]: Class CVWindow is implemented in both /Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so (0x288966630) and /opt/homebrew/Cellar/opencv/4.8.0_4/lib/libopencv_highgui.4.8.0.dylib (0x299040b38). One of the two will be used. Which one is undefined.
objc[1850]: Class CVView is implemented in both /Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so (0x288966658) and /opt/homebrew/Cellar/opencv/4.8.0_4/lib/libopencv_highgui.4.8.0.dylib (0x299040b60). One of the two will be used. Which one is undefined.
objc[1850]: Class CVSlider is implemented in both /Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so (0x288966680) and /opt/homebrew/Cellar/opencv/4.8.0_4/lib/libopencv_highgui.4.8.0.dylib (0x299040b88). One of the two will be used. Which one is undefined.
[2023-09-04 23:09:03,908]::[InvokeAI]::INFO --> Patchmatch initialized
[2023-09-04 23:09:04,266]::[uvicorn.error]::INFO --> Started server process [1850]
[2023-09-04 23:09:04,266]::[uvicorn.error]::INFO --> Waiting for application startup.
[2023-09-04 23:09:04,266]::[InvokeAI]::INFO --> InvokeAI version 3.1.0
[2023-09-04 23:09:04,266]::[InvokeAI]::INFO --> Root directory = /Users/thienbao/Downloads/InvokeAI-Installer
[2023-09-04 23:09:04,268]::[InvokeAI]::INFO --> GPU device = mps 
[2023-09-04 23:09:04,284]::[InvokeAI]::INFO --> Scanning /Users/thienbao/Downloads/InvokeAI-Installer/models for new models
[2023-09-04 23:09:04,400]::[InvokeAI]::INFO --> Scanned 7 files and directories, imported 0 models
[2023-09-04 23:09:04,412]::[InvokeAI]::INFO --> Model manager service initialized
[2023-09-04 23:09:04,413]::[uvicorn.error]::INFO --> Application startup complete.
[2023-09-04 23:09:04,414]::[uvicorn.error]::INFO --> Uvicorn running on http://127.0.0.1:9090 (Press CTRL+C to quit)
[2023-09-04 23:09:34,628]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /socket.io/?EIO=4&transport=polling&t=OfWzDoX HTTP/1.1" 200
[2023-09-04 23:09:34,726]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /api/v1/app/version HTTP/1.1" 200
[2023-09-04 23:09:35,757]::[InvokeAI]::INFO --> NSFW checker initialized
[2023-09-04 23:09:35,757]::[uvicorn.access]::INFO --> 127.0.0.1:49859 - "GET /api/v1/app/config HTTP/1.1" 200
[2023-09-04 23:09:35,758]::[uvicorn.access]::INFO --> 127.0.0.1:49860 - "GET /api/v1/models/?model_type=embedding HTTP/1.1" 200
[2023-09-04 23:09:35,760]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /api/v1/models/?model_type=controlnet HTTP/1.1" 200
[2023-09-04 23:09:35,761]::[uvicorn.access]::INFO --> 127.0.0.1:49861 - "GET /api/v1/models/?base_models=sd-1&base_models=sd-2&base_models=sdxl&model_type=main HTTP/1.1" 200
[2023-09-04 23:09:35,761]::[uvicorn.access]::INFO --> 127.0.0.1:49859 - "GET /api/v1/images/i/1d03ee7a-d83c-4622-a72f-8425aa885018.png HTTP/1.1" 200
[2023-09-04 23:09:35,762]::[uvicorn.access]::INFO --> 127.0.0.1:49860 - "GET /api/v1/images/i/b5618bc8-a7b0-4977-adb2-250a3ea05e09.png HTTP/1.1" 200
[2023-09-04 23:09:35,766]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /api/v1/models/?model_type=lora HTTP/1.1" 200
[2023-09-04 23:09:35,767]::[uvicorn.access]::INFO --> 127.0.0.1:49862 - "GET /api/v1/models/?base_models=sd-1&base_models=sd-2&base_models=sdxl&model_type=onnx HTTP/1.1" 200
[2023-09-04 23:09:35,767]::[uvicorn.access]::INFO --> 127.0.0.1:49863 - "GET /api/v1/models/?model_type=vae HTTP/1.1" 200
[2023-09-04 23:09:35,768]::[uvicorn.error]::INFO --> ('127.0.0.1', 49864) - "WebSocket /socket.io/?EIO=4&transport=websocket&sid=wi_XQD7dWaNhMv-iAAAA" [accepted]
[2023-09-04 23:09:35,768]::[uvicorn.access]::INFO --> 127.0.0.1:49861 - "GET /api/v1/images/i/621e91d5-b111-4bcf-a751-1fb6655b5b20.png HTTP/1.1" 200
[2023-09-04 23:09:35,768]::[uvicorn.access]::INFO --> 127.0.0.1:49859 - "GET /api/v1/boards/?all=true HTTP/1.1" 200
[2023-09-04 23:09:35,768]::[uvicorn.access]::INFO --> 127.0.0.1:49860 - "GET /api/v1/images/?board_id=none&categories=general&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200
[2023-09-04 23:09:35,769]::[uvicorn.error]::INFO --> connection open
[2023-09-04 23:09:35,769]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /api/v1/images/?board_id=none&categories=control&categories=mask&categories=user&categories=other&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200
[2023-09-04 23:09:35,769]::[uvicorn.access]::INFO --> 127.0.0.1:49862 - "GET /api/v1/images/?board_id=none&categories=general&is_intermediate=false&limit=100&offset=0 HTTP/1.1" 200
[2023-09-04 23:09:35,770]::[uvicorn.access]::INFO --> 127.0.0.1:49863 - "POST /socket.io/?EIO=4&transport=polling&t=OfWzDqt&sid=wi_XQD7dWaNhMv-iAAAA HTTP/1.1" 200
[2023-09-04 23:09:35,770]::[uvicorn.access]::INFO --> 127.0.0.1:49861 - "GET /socket.io/?EIO=4&transport=polling&t=OfWzDqu&sid=wi_XQD7dWaNhMv-iAAAA HTTP/1.1" 200
[2023-09-04 23:09:35,841]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /socket.io/?EIO=4&transport=polling&t=OfWzE5W&sid=wi_XQD7dWaNhMv-iAAAA HTTP/1.1" 200
[2023-09-04 23:09:35,895]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /socket.io/?EIO=4&transport=polling&t=OfWzE6M&sid=wi_XQD7dWaNhMv-iAAAA HTTP/1.1" 200
[2023-09-04 23:09:36,294]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /openapi.json HTTP/1.1" 200
[2023-09-04 23:09:36,296]::[uvicorn.access]::INFO --> 127.0.0.1:49859 - "GET /api/v1/models/?base_models=sd-1&base_models=sd-2&base_models=sdxl&model_type=main HTTP/1.1" 200
[2023-09-04 23:09:36,300]::[uvicorn.access]::INFO --> 127.0.0.1:49860 - "GET /api/v1/models/?model_type=lora HTTP/1.1" 200
[2023-09-04 23:09:36,302]::[uvicorn.access]::INFO --> 127.0.0.1:49861 - "GET /api/v1/models/?model_type=controlnet HTTP/1.1" 200
[2023-09-04 23:09:36,302]::[uvicorn.access]::INFO --> 127.0.0.1:49862 - "GET /api/v1/models/?model_type=vae HTTP/1.1" 200
[2023-09-04 23:09:36,303]::[uvicorn.access]::INFO --> 127.0.0.1:49863 - "GET /api/v1/models/?model_type=embedding HTTP/1.1" 200
[2023-09-04 23:09:36,303]::[uvicorn.access]::INFO --> 127.0.0.1:49858 - "GET /api/v1/app/config HTTP/1.1" 200
[2023-09-04 23:09:36,303]::[uvicorn.access]::INFO --> 127.0.0.1:49859 - "GET /api/v1/app/version HTTP/1.1" 200
[2023-09-04 23:09:47,197]::[uvicorn.access]::INFO --> 127.0.0.1:49866 - "POST /api/v1/sessions/ HTTP/1.1" 200
[2023-09-04 23:09:47,277]::[uvicorn.access]::INFO --> 127.0.0.1:49866 - "PUT /api/v1/sessions/b36d7b53-e879-46d6-abc3-2cb094e10899/invoke?all=true HTTP/1.1" 202
[2023-09-04 23:09:47,291]::[InvokeAI]::INFO --> Loading model /Users/thienbao/Downloads/InvokeAI-Installer/models/sd-2/main/stable-diffusion-2-1, type sd-2:main:tokenizer
[2023-09-04 23:09:47,515]::[InvokeAI]::INFO --> Loading model /Users/thienbao/Downloads/InvokeAI-Installer/models/sd-2/main/stable-diffusion-2-1, type sd-2:main:text_encoder
Token indices sequence length is longer than the specified maximum sequence length for this model (113 > 77). Running this sequence through the model will result in indexing errors
[2023-09-04 23:09:50,522]::[InvokeAI]::INFO --> Loading model /Users/thienbao/Downloads/InvokeAI-Installer/models/sd-2/main/stable-diffusion-2-1, type sd-2:main:unet
[2023-09-04 23:09:56,775]::[InvokeAI]::INFO --> Loading model /Users/thienbao/Downloads/InvokeAI-Installer/models/sd-2/main/stable-diffusion-2-1, type sd-2:main:scheduler
[2023-09-04 23:09:56,970]::[InvokeAI]::INFO --> Loading model /Users/thienbao/Downloads/InvokeAI-Installer/models/sd-1/controlnet/canny, type sd-1:controlnet
[2023-09-04 23:10:00,203]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/invokeai/app/services/processor.py", line 95, in __process
    outputs = invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/invokeai/app/invocations/baseinvocation.py", line 514, in invoke_internal
    return self.invoke(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/invokeai/app/invocations/latent.py", line 522, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 405, in latents_from_embeddings
    latents, attention_map_saver = self.generate_latents_from_embeddings(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 432, in generate_latents_from_embeddings
    self._adjust_memory_efficient_attention(latents)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 295, in _adjust_memory_efficient_attention
    self.enable_xformers_memory_efficient_attention()
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1660, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1686, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1676, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 226, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 219, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 226, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 222, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 219, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/thienbao/Downloads/InvokeAI-Installer/.venv/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 193, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers

[2023-09-04 23:10:00,205]::[InvokeAI]::ERROR --> Error while invoking:
Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers

**Comment by gogurtenjoyer** [comment]
When you installed, did you choose xformers in the configuration? This is only for NVIDIA devices.

**Comment by thienbaogithub** [comment]
i try again, thanks

**Comment by thienbaogithub** [comment]
i tried, but ivokeai is errored. i don;t choose xformers, i choose auto.

Generate images with a browser-based interface
/Users/thienbao/invokeai/.venv/lib/python3.11/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
objc[2603]: Class CaptureDelegate is implemented in both /Users/thienbao/invokeai/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so (0x285cf65e0) and /opt/homebrew/Cellar/opencv/4.8.0_4/lib/libopencv_videoio.4.8.0.dylib (0x29078c880). One of the two will be used. Which one is undefined.
objc[2603]: Class CVWindow is implemented in both /Users/thienbao/invokeai/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so (0x285cf6630) and /opt/homebrew/Cellar/opencv/4.8.0_4/lib/libopencv_highgui.4.8.0.dylib (0x28fbecb38). One of the two will be used. Which one is undefined.
objc[2603]: Class CVView is implemented in both /Users/thienbao/invokeai/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so (0x285cf6658) and /opt/homebrew/Cellar/opencv/4.8.0_4/lib/libopencv_highgui.4.8.0.dylib (0x28fbecb60). One of the two will be used. Which one is undefined.
objc[2603]: Class CVSlider is implemented in both /Users/thienbao/invokeai/.venv/lib/python3.11/site-packages/cv2/cv2.abi3.so (0x285cf6680) and /opt/homebrew/Cellar/opencv/4.8.0_4/lib/libopencv_highgui.4.8.0.dylib (0x28fbecb88). One of the two will be used. Which one is undefined.
[2023-09-05 12:05:03,001]::[InvokeAI]::INFO --> Patchmatch initialized
[2023-09-05 12:05:03,355]::[uvicorn.error]::INFO --> Started server process [2603]
[2023-09-05 12:05:03,356]::[uvicorn.error]::INFO --> Waiting for application startup.
[2023-09-05 12:05:03,356]::[InvokeAI]::INFO --> InvokeAI version 3.1.0
[2023-09-05 12:05:03,356]::[InvokeAI]::INFO --> Root directory = /Users/thienbao/invokeai
[2023-09-05 12:05:03,358]::[InvokeAI]::INFO --> GPU device = mps 
[2023-09-05 12:05:03,360]::[InvokeAI]::INFO --> Scanning /Users/thienbao/invokeai/models for new models
[2023-09-05 12:05:03,450]::[InvokeAI]::INFO --> Scanned 7 files and directories, imported 0 models
[2023-09-05 12:05:03,451]::[InvokeAI]::INFO --> Model manager service initialized
[2023-09-05 12:05:03,453]::[uvicorn.error]::INFO --> Application startup complete.
[2023-09-05 12:05:03,453]::[uvicorn.error]::INFO --> Uvicorn running on http://127.0.0.1:9090 (Press CTRL+C to quit)

**Comment by thienbaogithub** [comment]
again error controlnet....!

Change InvokeAI startup options
[2023-09-05 14:58:17,114]::[InvokeAI]::INFO --> Initializing InvokeAI runtime directory
[2023-09-05 14:58:17,125]::[InvokeAI]::INFO --> Scanning /Users/thienbao/invokeai/models for new models
[2023-09-05 14:58:17,154]::[InvokeAI]::INFO --> Scanned 7 files and directories, imported 0 models
[2023-09-05 14:58:17,179]::[InvokeAI]::INFO --> Scanning /Users/thienbao/invokeai/models for new models
[2023-09-05 14:58:17,207]::[InvokeAI]::INFO --> Scanned 7 files and directories, imported 0 models
[2023-09-05 14:59:12,211]::[InvokeAI]::INFO --> Skipping support models at user's request
[2023-09-05 14:59:12,212]::[InvokeAI]::WARNING --> Skipping diffusion weights download per user request

** INVOKEAI INSTALLATION SUCCESSFUL **
If you installed manually from source or with 'pip install': activate the virtual environment
then run one of the following commands to start InvokeAI.

Web UI:
   invokeai-web

Command-line client:
   invokeai

If you installed using an installation script, run:
  /Users/thienbao/invokeai/invoke.sh

Add the '--help' argument to see all of the command-line switches available for use.

Press any key to continue...

<img width="449" alt="Screenshot 2023-09-05 at 15 01 57" src="https://github.com/invoke-ai/InvokeAI/assets/143694073/d080a086-4a38-4c6e-b3ac-4c9775a26f4c">

**Comment by singultus** [comment]
I'm very new to invokeAI (used to Auto1111 and Comfy), feel free to ignore me. However, are you trying to use canny controlnet with SDXL? The installer seems to install canny for SD-1 and not SDXL. I believe you have to manually add them from here https://models.invoke.ai/. In my opinion it is not very verbose about what kind of control net it downloads automatically. Copy the link from the site and feed it to the console installer (number 5, control net). Take care, I managed to install a depth model (zoe depth) from there, but with the canny model something is broken. I'll open a ticket about that...

**Comment by thienbaogithub** [comment]
HIC, ERROR MORE....

<img width="449" alt="Screenshot 2023-09-06 at 09 03 46" src="https://github.com/invoke-ai/InvokeAI/assets/143694073/2d244967-30e3-4401-89dd-77f89970a756">
<img width="788" alt="Screenshot 2023-09-06 at 09 09 39" src="https://github.com/invoke-ai/InvokeAI/assets/143694073/d4601b50-add8-4e4f-a0e9-90d7022ece05">
<img width="449" alt="Screenshot 2023-09-06 at 09 05 54" src="https://github.com/invoke-ai/InvokeAI/assets/143694073/af50e692-7ea1-49d5-ae8f-3368261a926e">

**Comment by Millu** [comment]
ControlNet requires an image to work - did you add an image to the ControlNet? Optionally, you can turn off the ControlNet

**Comment by thienbaogithub** [comment]
CONTROLNET IS ERROR ON MODEL XL, MODEL 1,5 Í NORMAL
<img width="456" alt="Screenshot 2023-09-06 at 11 05 56" src="https://github.com/invoke-ai/InvokeAI/assets/143694073/bf44c4a0-a531-4005-83b1-9daf09483636">

**Comment by Millu** [comment]
Have you downloaded the SDXL Canny model?

https://models.invoke.ai/diffusers/diffuserscontrolnet-canny-sdxl-1.0

**Comment by thienbaogithub** [comment]
> 

i have downloaded canny, but i downloaded by invokeai. thanks

**Comment by thienbaogithub** [comment]
i have loaded image but it 's not working
<img width="437" alt="Screenshot 2023-09-06 at 23 44 37" src="https://github.com/invoke-ai/InvokeAI/assets/143694073/a5a6954a-4e67-472d-8294-671289fcfef0">

**Comment by Millu** [comment]
It's because the Canny model you are using is the Canny model for SD1.5. You'll need to download Canny for SDXL from this link: https://models.invoke.ai/diffusers/controlnet-canny-sdxl-1.0 by pasting `diffusers/controlnet-canny-sdxl-1.0` into the "Add Model" field of the Model Manager
