### ISSUE TITLE
[bug] Unable to download LoRAs/ControlNets through model manager

### ISSUE THREAD

**Issue by kevadiyasmt** [invoke-ai/InvokeAI#4494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Is it possible that the "Model manager" in Web UI can become an all-rounder "Asset manager"? 
- instead of just dealing with the main models, it can deal with scanning/importing/downloading (from URL's or folders) the main models, control nets, LoRa's, embeddings, scripts, and extensions (for future). 
- All this directly from UI would make life and management a lot easier. 
- Also, I am aware that there is an "Assets" tab that deals with images but I think it could be renamed to something more suitable or maybe even move that assets tab inside of the above proposed "Asset manager" under a separate tab, that could be named as "image assets"?

**Comment by Millu** [comment]
I'm not sure I'm following - the model manager is able to download LoRA/embeddings/ControlNets. 

Maybe an issue with the naming

**Comment by kevadiyasmt** [comment]
Oh, but I tried downloading controlnet models from Hugging Face and Lora's from Civit AI and it did nothing on the UI side and gave the following errors on the console, so I assumed it didn't work for Lora, controlnet, etc.

**1. Error while downloading Lora:
Lora link: https://civitai.com/api/download/models/77173
Error:**

`[2023-09-09 06:43:51,918]::[uvicorn.error]::ERROR --> Exception in ASGI application

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/middleware.py", line 43, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/app/api/routers/models.py", line 159, in import_model
    installed_models = ApiDependencies.invoker.services.model_manager.heuristic_import(
  File "/usr/local/lib/python3.10/dist-packages/invokeai/app/services/model_manager_service.py", line 580, in heuristic_import
    return self.mgr.heuristic_import(items_to_import, prediction_type_helper)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/model_management/model_manager.py", line 1104, in heuristic_import
    installed = installer.heuristic_import(thing)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/install/model_install_backend.py", line 259, in heuristic_import
    models_installed.update({str(model_path_id_or_url): self._install_url(model_path_id_or_url)})
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/install/model_install_backend.py", line 286, in _install_url
    location = download_with_resume(url, Path(staging))
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/util/util.py", line 290, in download_with_resume
    file_name = re.search('filename="(.+)"', resp.headers.get("Content-Disposition")).group(1)
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object`


**2. Error while downloading controlnet from hugging face
Link: https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_depth.pth
Error:**

`[2023-09-09 06:46:29,727]::[InvokeAI]::INFO --> /content/InvokeAi/models/tmprkwazjap/control_sd15_depth.pth: Downloading...
/content/InvokeAi/models/tmprkwazjap/control_sd15_depth.pth: 100% 5.71G/5.71G [01:55<00:00, 49.5MiB/s]
[2023-09-09 06:48:36,622]::[uvicorn.access]::INFO --> 2405:201:1:8b74:ccec:7f0b:4ab:9300:0 - "POST /api/v1/models/import HTTP/1.1" 500
[2023-09-09 06:48:36,622]::[uvicorn.error]::ERROR --> Exception in ASGI application

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/middleware.py", line 43, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/app/api/routers/models.py", line 159, in import_model
    installed_models = ApiDependencies.invoker.services.model_manager.heuristic_import(
  File "/usr/local/lib/python3.10/dist-packages/invokeai/app/services/model_manager_service.py", line 580, in heuristic_import
    return self.mgr.heuristic_import(items_to_import, prediction_type_helper)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/model_management/model_manager.py", line 1104, in heuristic_import
    installed = installer.heuristic_import(thing)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/install/model_install_backend.py", line 259, in heuristic_import
    models_installed.update({str(model_path_id_or_url): self._install_url(model_path_id_or_url)})
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/install/model_install_backend.py", line 289, in _install_url
    info = ModelProbe().heuristic_probe(location)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/model_management/model_probe.py", line 70, in heuristic_probe
    return cls.probe(model_path=model, prediction_type_helper=prediction_type_helper)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/model_management/model_probe.py", line 106, in probe
    probe = probe_class(model_path, model, prediction_type_helper)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/model_management/model_probe.py", line 241, in __init__
    self.checkpoint = checkpoint or ModelProbe._scan_and_load_checkpoint(checkpoint_path)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/model_management/model_probe.py", line 206, in _scan_and_load_checkpoint
    return safetensors.torch.load_file(model_path)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge`


So if the model manager supports downloading of Lora/embeddings/controlnets then these might be bugs?

**Comment by Millu** [comment]
Try downloading this and see: https://huggingface.co/lllyasviel/control_v11p_sd15_canny/tree/main

You can do that by copying the hugging face repo: `lllyasviel/control_v11p_sd15_canny` and pasting it in the import field of the model manager

**Comment by kevadiyasmt** [comment]
I tried downloading using the link you mentioned above and I still got the same error as shown below. 
**but the hugging face repo id method worked.**

Error using the link:
`[2023-09-09 07:53:07,390]::[uvicorn.error]::ERROR --> Exception in ASGI application

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/middleware.py", line 43, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/app/api/routers/models.py", line 159, in import_model
    installed_models = ApiDependencies.invoker.services.model_manager.heuristic_import(
  File "/usr/local/lib/python3.10/dist-packages/invokeai/app/services/model_manager_service.py", line 580, in heuristic_import
    return self.mgr.heuristic_import(items_to_import, prediction_type_helper)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/model_management/model_manager.py", line 1104, in heuristic_import
    installed = installer.heuristic_import(thing)
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/install/model_install_backend.py", line 259, in heuristic_import
    models_installed.update({str(model_path_id_or_url): self._install_url(model_path_id_or_url)})
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/install/model_install_backend.py", line 286, in _install_url
    location = download_with_resume(url, Path(staging))
  File "/usr/local/lib/python3.10/dist-packages/invokeai/backend/util/util.py", line 290, in download_with_resume
    file_name = re.search('filename="(.+)"', resp.headers.get("Content-Disposition")).group(1)
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object`

**Comment by Millu** [comment]
Sorry that wasn't clear - what I meant by that pass the HF repo id to the model manager. Glad you got it sorted though!
