### ISSUE TITLE
[bug]: ModuleNotFoundError: No module named 'semver'

### ISSUE THREAD

**Issue by theRolento** [invoke-ai/InvokeAI#4504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.1

### What happened?

Just updated with git pull and now i get this error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PuPpEt\invokeai\.venv\Scripts\invokeai-web.exe\__main__.py", line 4, in <module>
  File "C:\Users\PuPpEt\invokeai\InvokeAI\invokeai\app\api_app.py", line 35, in <module>
    from .api.dependencies import ApiDependencies
  File "C:\Users\PuPpEt\invokeai\InvokeAI\invokeai\app\api\dependencies.py", line 15, in <module>
    from invokeai.app.services.images import ImageService, ImageServiceDependencies
  File "C:\Users\PuPpEt\invokeai\InvokeAI\invokeai\app\services\images.py", line 7, in <module>
    from invokeai.app.invocations.metadata import ImageMetadata
  File "C:\Users\PuPpEt\invokeai\InvokeAI\invokeai\app\invocations\metadata.py", line 5, in <module>
    from invokeai.app.invocations.baseinvocation import (
  File "C:\Users\PuPpEt\invokeai\InvokeAI\invokeai\app\invocations\baseinvocation.py", line 29, in <module>
    import semver
ModuleNotFoundError: No module named 'semver'
```

**Comment by theRolento** [comment]
Anyway, i've installed the package manually and now is working.

**Comment by hipsterusername** [comment]
If you git pull you need to run a pip install -e .  In order to get any new packages. Sounds like you sorted it though!
