### ISSUE TITLE
[bug]:  Error after update to 3.1.1 

### ISSUE THREAD

**Issue by mirek190** [invoke-ai/InvokeAI#4524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.1.1

### What happened?

Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
[2023-09-12 22:09:00,380]::[InvokeAI]::INFO --> Patchmatch initialized
E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[2023-09-12 22:09:02,893]::[uvicorn.error]::INFO --> Started server process [29044]
[2023-09-12 22:09:02,893]::[uvicorn.error]::INFO --> Waiting for application startup.
[2023-09-12 22:09:02,893]::[InvokeAI]::INFO --> InvokeAI version 3.1.1
[2023-09-12 22:09:02,894]::[InvokeAI]::INFO --> Root directory = E:\DIFFUSION\InvokeAI-Installer
[2023-09-12 22:09:02,896]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce RTX 3090
[2023-09-12 22:09:02,909]::[InvokeAI]::INFO --> Scanning E:\DIFFUSION\InvokeAI-Installer\models for new models
[2023-09-12 22:09:02,912]::[InvokeAI]::WARNING --> Model with key sd-1/main/juggernaut_aftermath added twice
[2023-09-12 22:09:02,913]::[uvicorn.error]::ERROR --> Traceback (most recent call last):
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api_app.py", line 76, in startup_event
    ApiDependencies.initialize(config=app_config, event_handler_id=event_handler_id, logger=logger)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 120, in initialize
    model_manager=ModelManagerService(config, logger),
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 340, in __init__
    self.mgr = ModelManager(
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 352, in __init__
    self._read_models(config)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 375, in _read_models
    self.scan_models_directory()
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 995, in scan_models_directory
    model_config: ModelConfigBase = model_class.probe_config(
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 54, in probe_config
    model_format = cls.detect_format(path)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 103, in detect_format
    raise ModelNotFoundException()
invokeai.backend.model_management.models.base.ModelNotFoundException

[2023-09-12 22:09:02,914]::[uvicorn.error]::ERROR --> Application startup failed. Exiting.
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<FastAPIEventService.__dispatch_from_queue() running at E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api\events.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>

**Comment by Millu** [comment]
Looks like this is breaking it: 

Model with key sd-1/main/juggernaut_aftermath added twice

Can you check you've only got 1 of that model in your models folder?

**Comment by mirek190** [comment]
I removed that model and updated again Invoke
Still broken ... Before update to 3.1.1 via script ( 9. Update InvokeAI  )  was working fine 


✔ Upgrade successful
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
[2023-09-13 23:39:02,778]::[InvokeAI]::INFO --> Patchmatch initialized
E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[2023-09-13 23:39:05,448]::[uvicorn.error]::INFO --> Started server process [6316]
[2023-09-13 23:39:05,448]::[uvicorn.error]::INFO --> Waiting for application startup.
[2023-09-13 23:39:05,448]::[InvokeAI]::INFO --> InvokeAI version 3.1.1
[2023-09-13 23:39:05,448]::[InvokeAI]::INFO --> Root directory = E:\DIFFUSION\InvokeAI-Installer
[2023-09-13 23:39:05,464]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce RTX 3090
[2023-09-13 23:39:05,480]::[InvokeAI]::INFO --> Scanning E:\DIFFUSION\InvokeAI-Installer\models for new models
[2023-09-13 23:39:05,502]::[uvicorn.error]::ERROR --> Traceback (most recent call last):
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api_app.py", line 76, in startup_event
    ApiDependencies.initialize(config=app_config, event_handler_id=event_handler_id, logger=logger)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 120, in initialize
    model_manager=ModelManagerService(config, logger),
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 340, in __init__
    self.mgr = ModelManager(
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 352, in __init__
    self._read_models(config)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 375, in _read_models
    self.scan_models_directory()
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 995, in scan_models_directory
    model_config: ModelConfigBase = model_class.probe_config(
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 54, in probe_config
    model_format = cls.detect_format(path)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 103, in detect_format
    raise ModelNotFoundException()
invokeai.backend.model_management.models.base.ModelNotFoundException

[2023-09-13 23:39:05,502]::[uvicorn.error]::ERROR --> Application startup failed. Exiting.
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<FastAPIEventService.__dispatch_from_queue() running at E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\app\api\events.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1]

**Comment by Millu** [comment]
Could you try running [7] to fix a broken install and then using [5] to re-download the model you're trying to use?

**Comment by mirek190** [comment]
Rerun no 7 ...
Still errors ...


Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 7
Running invokeai-configure...
[2023-09-15 23:14:42,260]::[InvokeAI]::INFO --> Initializing InvokeAI runtime directory
[2023-09-15 23:14:42,311]::[InvokeAI]::INFO --> Scanning E:\DIFFUSION\InvokeAI-Installer\models for new models
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\Scripts\invokeai-configure.exe\__main__.py", line 7, in <module>
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\install\invokeai_configure.py", line 922, in main
    models_to_download = default_user_selections(opt)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\install\invokeai_configure.py", line 673, in default_user_selections
    installer = ModelInstall(config)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\install\model_install_backend.py", line 108, in __init__
    self.mgr = model_manager or ModelManager(config.model_conf_path)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 352, in __init__
    self._read_models(config)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 375, in _read_models
    self.scan_models_directory()
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 995, in scan_models_directory
    model_config: ModelConfigBase = model_class.probe_config(
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 54, in probe_config
    model_format = cls.detect_format(path)
  File "E:\DIFFUSION\InvokeAI-Installer\.venv\lib\site-packages\invokeai\backend\model_management\models\stable_diffusion.py", line 103, in detect_format
    raise ModelNotFoundException()
invokeai.backend.model_management.models.base.ModelNotFoundException
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1]

**Comment by shap-po** [comment]
Have you resolved this issue?

**Comment by mirek190** [comment]
yes ..yesterday

Problem was connected to wrong version of  controlnet models for sdxl. When I removed then everything back to normal.

**Comment by mirek190** [comment]
Problem was connected to wrong version of controlnet models for sdxl. When I removed then everything back to normal.
