### ISSUE TITLE
[enhancement]: Support Kaggle

### ISSUE THREAD

**Issue by cfragkos** [invoke-ai/InvokeAI#4537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Create a guide in the docs and if needed make changed to invoke, to be able to run in Kaggle. Current problem is that kaggle does not have a terminal so it's impossible to run the installer. Maybe there is a way to configure it without the installer but it is not documented. A tutorial at least would be greatly appreciated.

**Comment by Millu** [comment]
If I understand properly, Kaggle uses Jupyter notebooks. Take a look at this user's Colab notebook: 

https://github.com/kevadiyasmt/notebooks/blob/main/Invokeai_web_interface.ipynb

**Comment by cfragkos** [comment]
I have tried it and I get this error on the final step. Also any other notebook I have found also doesn't work or is for Invoke v2
`
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/opt/conda/bin/invokeai-web", line 5, in <module>
    from invokeai.app.api_app import invoke_api
  File "/opt/conda/lib/python3.10/site-packages/invokeai/app/api_app.py", line 35, in <module>
    from .api.dependencies import ApiDependencies
  File "/opt/conda/lib/python3.10/site-packages/invokeai/app/api/dependencies.py", line 5, in <module>
    from invokeai.app.services.board_image_record_storage import SqliteBoardImageRecordStorage
  File "/opt/conda/lib/python3.10/site-packages/invokeai/app/services/board_image_record_storage.py", line 6, in <module>
    from invokeai.app.services.image_record_storage import OffsetPaginatedResults
  File "/opt/conda/lib/python3.10/site-packages/invokeai/app/services/image_record_storage.py", line 9, in <module>
    from pydantic.generics import GenericModel
  File "/opt/conda/lib/python3.10/site-packages/pydantic/generics.py", line 2, in <module>
    from ._migration import getattr_migration
  File "/opt/conda/lib/python3.10/site-packages/pydantic/_migration.py", line 6, in <module>
    from .version import version_short
ImportError: cannot import name 'version_short' from 'pydantic.version' (/opt/conda/lib/python3.10/site-packages/pydantic/version.cpython-310-x86_64-linux-gnu.so)`

**Comment by jjiikkkk** [comment]
this colab notebook is killed for many starting options
