### ISSUE TITLE
Reinstalling 2 times and it doesnt work for me.

### ISSUE THREAD

**Issue by Thorev** [invoke-ai/InvokeAI#4551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What version did you experience this issue on?

3.1.1

### What happened?

Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
Traceback (most recent call last):
  File "C:\Users\tesmo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tesmo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Ai\InvokeAI\.venv\Scripts\invokeai-web.exe\__main__.py", line 4, in <module>
    from invokeai.app.api_app import invoke_api
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\api_app.py", line 19, in <module>
    from ..backend.util.logging import InvokeAILogger
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\backend\__init__.py", line 4, in <module>
    from .model_management import ModelManager, ModelCache, BaseModelType, ModelType, SubModelType, ModelInfo  # noqa: F401
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\__init__.py", line 4, in <module>
    from .model_manager import ModelManager, ModelInfo, AddModelResult, SchedulerPredictionType  # noqa: F401
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 249, in <module>
    from .model_cache import ModelCache, ModelLocker
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 31, in <module>
    from .models import BaseModelType, ModelType, SubModelType, ModelBase
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\models\__init__.py", line 5, in <module>
    from .base import (  # noqa: F401
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_management\models\base.py", line 17, in <module>
    from diffusers import DiffusionPipeline, ConfigMixin
ModuleNotFoundError: No module named 'diffusers'

### Screenshots

![Снимок экрана 2023-09-15 145813](https://github.com/invoke-ai/InvokeAI/assets/77360994/8883c826-d325-4576-b2b9-c6f08d25f19b)

**Comment by Millu** [comment]
In your venv, try `pip install diffusers` to install the diffusers package

**Comment by Thorev** [comment]
> In your venv, try `pip install diffusers` to install the diffusers package

Oh thanks! For some reason this information is not in the instructions.

**Comment by Thorev** [comment]
No, it didn't work. Now I understand why this is not in the instructions)

**Comment by psychedelicious** [comment]
The installer has been redone to prevent issues like this (certain packages not being installed). Please create a new issue if the problem persisted with the latest release (v4.1.0)
