### ISSUE TITLE
[bug]: RangeError: Invalid array length

### ISSUE THREAD

**Issue by ddm21** [invoke-ai/InvokeAI#4567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What version did you experience this issue on?

3.1.1

### What happened?

I was trying to take an Image to Unified Canvas and ran into this error

```
{
  "name": "RangeError",
  "message": "Invalid array length",
  "stack": "RangeError: Invalid array length\n    at PN (http://127.0.0.1:9090/assets/App-d1567775.js:1:6825)\n    at http://127.0.0.1:9090/assets/App-d1567775.js:1:7023\n    at http://127.0.0.1:9090/assets/App-d1567775.js:89:12214\n    at _f (http://127.0.0.1:9090/assets/App-d1567775.js:70:20938)\n    at pC (http://127.0.0.1:9090/assets/App-d1567775.js:70:27593)\n    at fC (http://127.0.0.1:9090/assets/App-d1567775.js:70:27449)\n    at K8 (http://127.0.0.1:9090/assets/App-d1567775.js:70:26990)\n    at Z8 (http://127.0.0.1:9090/assets/App-d1567775.js:70:38492)\n    at pi (http://127.0.0.1:9090/assets/App-d1567775.js:70:37859)\n    at xC (http://127.0.0.1:9090/assets/App-d1567775.js:70:34499)"
}
```

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/98445934/e2b171fc-d9ca-4d75-8fef-41f3bb4abc88)

**Comment by Millu** [comment]
Thanks for flagging - this should be fixed in the upcoming release! #4515
