### ISSUE TITLE
[bug]:  Node mask_combine not found in graph 

### ISSUE THREAD

**Issue by pivot69** [invoke-ai/InvokeAI#4586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64gb

### What version did you experience this issue on?

3.1.1

### What happened?

i get an error when trying to inpaint a mask through the unified canvas with either stable-diffusion-xl-1.0-inpainting-0.1 or stable-diffusion-xl-base-1-0 together with the sdxl refiner model (stable-diffusion-xl-refiner-1-0)

```
raise NodeNotFoundError(f"Node {node_path} not found in graph")
invokeai.app.services.graph.NodeNotFoundError: Node mask_combine not found in graph 

```

i have recently replaced the original sdxl-vae-fix (the one i can install using the model installer through the startup-script) with madebyollin/sdxl-vae-fp16-fix and it might be related since i noticed the issues quickly after this (but i cannot be 100% certain)

if i activate "scale before processing" it is able to complete without issues (even without any actual scaling)

### Additional context

heres the full error log:
```
[2023-09-18 23:47:57,277]::[uvicorn.error]::ERROR --> Exception in ASGI application

Traceback (most recent call last):
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/fastapi_events/middleware.py", line 43, in __call__
    await self.app(scope, receive, send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/api/routers/sessions.py", line 263, in invoke_session
    ApiDependencies.invoker.invoke(session, invoke_all=all)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/services/invoker.py", line 25, in invoke
    invocation = graph_execution_state.next()
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/services/graph.py", line 766, in next
    prepared_id = self._prepare()
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/services/graph.py", line 898, in _prepare
    next_node_id = next(
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/services/graph.py", line 906, in <genexpr>
    isinstance(self.graph.get_node(n), IterateInvocation)  # `n` is an iterate node...
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/services/graph.py", line 431, in get_node
    graph, node_id = self._get_graph_and_node(node_path)
  File "/Users/pivot/invokeai3/.venv/lib/python3.10/site-packages/invokeai/app/services/graph.py", line 259, in _get_graph_and_node
    raise NodeNotFoundError(f"Node {node_path} not found in graph")
invokeai.app.services.graph.NodeNotFoundError: Node mask_combine not found in graph
```

**Comment by hipsterusername** [comment]
@psychedelicious @Millu - I think the graphs for Non-Scale before processing on Canvas have some regressions that might need to be resolved.
