### ISSUE TITLE
[bug]: Can't INVOKE, InvokeAI UNUSABLE = Invoker.create_execution_state() got an unexpected keyword argument 'queue_id'

### ISSUE THREAD

**Issue by theRolento** [invoke-ai/InvokeAI#4651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

b152fbf

### What happened?

I've just did a `git pull` and i can't invoke anymore.
Whenever i invoke i get this error now:
`Invoker.create_execution_state() got an unexpected keyword argument 'queue_id'`

This is the log:

```
[2023-09-22 11:29:21,186]::[uvicorn.access]::INFO --> 127.0.0.1:50921 - "GET /api/v1/images/?board_id=none&categories=general&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200
[2023-09-22 11:29:34,289]::[uvicorn.access]::INFO --> 127.0.0.1:50924 - "POST /api/v1/sessions/ HTTP/1.1" 500
[2023-09-22 11:29:34,289]::[uvicorn.error]::ERROR --> Exception in ASGI application

Traceback (most recent call last):
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\fastapi_events\middleware.py", line 43, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\invokeai\.venv\Lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\invokeai\InvokeAI\invokeai\app\api\routers\sessions.py", line 33, in create_session
    session = ApiDependencies.invoker.create_execution_state(queue_id=queue_id, graph=graph)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Invoker.create_execution_state() got an unexpected keyword argument 'queue_id'
```

**Comment by theRolento** [comment]
Updated with `git pull` to c485cf5 and still getting the error

**Comment by theRolento** [comment]
Updated to e3de996 and still not working.

InvokeAI is literally unusable, if anyone know a workaround i'll appreciate.

**Comment by tkoenig89** [comment]
exact same issue here. I'm on `e3de996` as well. Cant generate anything, regardless of what settings i try to change.

Windows 11, 8GB RTX 2060 super

**Comment by psychedelicious** [comment]
Hi, it looks like you haven't rebuilt the UI.

If you use `main`, you'll need to do that if there are any changes to the UI that are sync'd with changes to the backend.

When we release updates, we do the build for the release. Between releases, `main` typically does not have a current UI build.

You can see the instructions here for setting up a development environment and then doing a production build: https://github.com/invoke-ai/InvokeAI/blob/main/docs/contributing/contribution_guides/contributingToFrontend.md

That should get your UI updated.

If you don't want to do that, you should revert to a previous commit.

**Comment by theRolento** [comment]
The problem was found and now fixed!

**Comment by ultradyran** [comment]
I

> Hi, it looks like you haven't rebuilt the UI.
> 
> If you use `main`, you'll need to do that if there are any changes to the UI that are sync'd with changes to the backend.
> 
> When we release updates, we do the build for the release. Between releases, `main` typically does not have a current UI build.
> 
> You can see the instructions here for setting up a development environment and then doing a production build: https://github.com/invoke-ai/InvokeAI/blob/main/docs/contributing/contribution_guides/contributingToFrontend.md
> 
> That should get your UI updated.
> 
> If you don't want to do that, you should revert to a previous commit.

forgive me i am relatively new to coding if i misunderstood the solution there  @psychedelicious 

I just ran an update to InvokeAI and got the same error

on PC, I go to invokeai\.venv\Lib\site-packages\invokeai\frontend\web, run in windows powershell did a '`yarn install`' as per the document says, i got "`success Already up-to-date.`" and assumed that's it.

but still i ran back to the same error when re-run the `invoke.bat`, did i miss anything?:
 `File "C:\Users\Adrian\invokeai\.venv\lib\site-packages\invokeai\app\api\routers\sessions.py", line 33, in create_session
    session = ApiDependencies.invoker.create_execution_state(queue_id=queue_id, graph=graph)
TypeError: Invoker.create_execution_state() got an unexpected keyword argument 'queue_id'`

**Comment by psychedelicious** [comment]
This is expected. You can periodically clean up images using the clear intermediates button in settings.
