### ISSUE TITLE
[bug]: can't use inpainting brand new install MBP M2+

### ISSUE THREAD

**Issue by Autantpourmoi** [invoke-ai/InvokeAI#4673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64

### What version did you experience this issue on?

3.1.1

### What happened?

![ScreenShot 2023-09-24 à 14 44 53](https://github.com/invoke-ai/InvokeAI/assets/57645178/cf69064e-6591-476c-942e-fec3c1c6ecce)
when i try to expand image or doing inpaint always end with this error message 

### Screenshots

[2023-09-24 14:34:40,460]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/app/services/processor.py", line 95, in __process
    outputs = invocation.invoke_internal(
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/app/invocations/baseinvocation.py", line 568, in invoke_internal
    return self.invoke(context)
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/app/invocations/latent.py", line 527, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 397, in latents_from_embeddings
    latents, attention_map_saver = self.generate_latents_from_embeddings(
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 454, in generate_latents_from_embeddings
    step_output = self.step(
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 563, in step
    step_output = guidance(step_output, timestep, conditioning_data)
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 97, in __call__
    {
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 98, in <dictcomp>
    k: (self.apply_mask(v, self._t_for_field(k, t)) if are_like_tensors(prev_sample, v) else v)
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 121, in apply_mask
    masked_input = torch.lerp(mask_latents.to(dtype=latents.dtype), latents, mask.to(dtype=latents.dtype))
  File "/Users/lucvaligny/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/util/mps_fixes.py", line 54, in new_torch_lerp
    result = _torch_lerp(input, end, weight, out=out_fp32)
NotImplementedError: The operator 'aten::lerp.Tensor_out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

[2023-09-24 14:34:40,463]::[InvokeAI]::ERROR --> Error while invoking:
The operator 'aten::lerp.Tensor_out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

### Contact Details

luc.valigny@gmail.com

**Comment by Millu** [comment]
Start invoke, and then in the developer console (option [8]) run this: 

`export PYTORCH_ENABLE_MPS_FALLBACK=1`

**Comment by Autantpourmoi** [comment]
thanks for answering , but where do i find this developer console ?

**Comment by parnas** [comment]
@Autantpourmoi Upvote this, please: https://github.com/pytorch/pytorch/issues/77764#issuecomment-1739071491

**Comment by Autantpourmoi** [comment]
no invoke.sh  but it work with 'export PYTORCH_ENABLE_MPS_FALLBACK=1' after activate venv
