### ISSUE TITLE
[bug]: Error during installation on Mac Silicon

### ISSUE THREAD

**Issue by mikecastrodemaria** [invoke-ai/InvokeAI#4736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### What version did you experience this issue on?

InvokeAI 3.1.1 

### What happened?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/install/invokeai_configure.py", line 201, in download_with_progress_bar
    request.urlretrieve(model_url, model_dest, ProgressBar(os.path.basename(model_dest)))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>

### Contact Details

mcd@supersonique.net

**Comment by Millu** [comment]
Does this installer finish after this error is shown?

**Comment by Millu** [comment]
To fix this error, run this in your terminal: 

`/Applications/Python\ 3.11/Install\ Certificates.command`

For anyone reading this, change "3.11" to your python version (should be 3.10 or 3.11 as InvokeAI 3.4)
