### ISSUE TITLE
[bug]: TypeError: new_LoRACompatibleConv_forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by KarlVanSnail** [invoke-ai/InvokeAI#4757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.1.1

### What happened?

[2023-10-02 12:45:01,020]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\services\processor.py", line 95, in __process
    outputs = invocation.invoke_internal(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 568, in invoke_internal
    return self.invoke(context)
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\invocations\latent.py", line 527, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 397, in latents_from_embeddings
    latents, attention_map_saver = self.generate_latents_from_embeddings(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 454, in generate_latents_from_embeddings
    step_output = self.step(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 529, in step
    uc_noise_pred, c_noise_pred = self.invokeai_diffuser.do_unet_step(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusion\shared_invokeai_diffusion.py", line 308, in do_unet_step
    ) = self._apply_standard_conditioning(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusion\shared_invokeai_diffusion.py", line 407, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 592, in _unet_forward
    return self.unet(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 958, in forward
    sample, res_samples = downsample_block(
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1085, in forward
    hidden_states = resnet(hidden_states, temb, scale=lora_scale)
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\diffusers\models\resnet.py", line 637, in forward
    hidden_states = self.conv1(hidden_states, scale)
  File "D:\StabilityAI\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: new_LoRACompatibleConv_forward() takes 2 positional arguments but 3 were given

[2023-10-02 12:45:01,027]::[InvokeAI]::ERROR --> Error while invoking:
new_LoRACompatibleConv_forward() takes 2 positional arguments but 3 were given

**Comment by KarlVanSnail** [comment]
I only want to generate an Image and i get this error. I dont load a Lora btw.

**Comment by psychedelicious** [comment]
Please first update the app - we've just released 3.2.

If the issue still occurs, please take screenshot of the settings used. Also, did you have seamless enabled?
