### ISSUE TITLE
Lora pixel-art-xl-v1.1.safetensors seems not to work[bug]: 

### ISSUE THREAD

**Issue by Serasul1984** [invoke-ai/InvokeAI#4769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

16GB

### What version did you experience this issue on?

3.2.0

### What happened?

when selecting the lora in the model manager and than select it in the lora tab on the left side, everything is fine but when you hit generate in combination of the the vanilla SDXL model it spits out an error in the CMD window.

### Additional context

[2023-10-03 08:59:13,556]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\app\services\processor.py", line 106, in __process
    outputs = invocation.invoke_internal(
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 609, in invoke_internal
    output = self.invoke(context)
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 289, in invoke    c1, c1_pooled, ec1 = self.run_clip_compel(
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 217, in run_clip_compel
    with (
  File "C:\Users\Seradest\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\backend\model_management\lora.py", line 126, in apply_lora
    for lora, lora_weight in loras:
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 189, in _lora_loader
    lora_info = context.services.model_manager.get_model(**lora.dict(exclude={"weight"}), context=context)
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\app\services\model_manager_service.py", line 374, in get_model
    model_info = self.mgr.get_model(
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 487, in get_model
    model_path = model_class.convert_if_required(
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\backend\model_management\models\lora.py", line 88, in convert_if_required
    if cls.detect_format(model_path) == LoRAModelFormat.Diffusers:
  File "E:\AI\InvokeAI-Installer\invoke\.venv\lib\site-packages\invokeai\backend\model_management\models\lora.py", line 78, in detect_format
    raise InvalidModelException(f"Not a valid model: {path}")
invokeai.backend.model_management.models.base.InvalidModelException: Not a valid model: E:\AI\InvokeAI-Installer\invoke\models\sdxl\lora\pixel-art-xl-v1.1

[2023-10-03 08:59:13,787]::[InvokeAI]::ERROR --> Error while invoking:
Not a valid model: E:\AI\InvokeAI-Installer\invoke\models\sdxl\lora\pixel-art-xl-v1.1

**Comment by Millu** [comment]
How did you install the LoRA?

**Comment by Serasul1984** [comment]
> How did you install the LoRA?

i added the lora to the sdxl folder for loras and than selected it in the the model manager
![rthrhrhrhtr](https://github.com/invoke-ai/InvokeAI/assets/106548837/d5956a8b-6435-4dab-a092-d1a2fe4fb6b3)

**Comment by Serasul1984** [comment]
So i assume its an unique bug (again) and i cant solve this myself (again)

**Comment by keturn** [comment]
I just ran in to the same traceback with the [Essenz v1.0](https://civitai.com/models/198378/essenz-high-quality-heavily-post-processed-photography-style-lora-for-sdxl-10) LoRA, running git 7fcb8959fbee93d1ce455ff53fae10040ca6d873

**Comment by keturn** [comment]
For my problem with `Essenz`, I eventually discovered that it was because it had lost its `.safetensors` file extension, and was maybe trying to load it as some other file type instead? After renaming the file to end with `.safetensors` it loads fine.

**Comment by Millu** [comment]
Closed by #5522
