### ISSUE TITLE
can't install new version 3.2.0 ( Mac osx 13.5.2 MBP M2 max)[bug]: 

### ISSUE THREAD

**Issue by Autantpourmoi** [invoke-ai/InvokeAI#4781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

64

### What version did you experience this issue on?

3.2.0

### What happened?

tried to install automatically and thru Git Hub repo alway ending with this message 👍 File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/var/folders/3q/9hp16x655c7c9qr8r3nbrt6h0000gn/T/invokeai-installer-tmpa8409dbu/bin/python3.11', '-m', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.

### Screenshots

![ScreenShot 2023-10-03 à 19 16 29](https://github.com/invoke-ai/InvokeAI/assets/57645178/6da08714-9a17-4954-9072-de4320e0af13)

**Comment by Millu** [comment]
Some Mac users have had problems with brew's python installation - would recommend installing python from python.org and trying to install

**Comment by sammcj** [comment]
I've hit this problem as well.

Shouldn't InvokeAI be using it's own python version/venv to keep it isolated?

```
.....
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.31.6 requires pillow<10.1.0,>=8.3.2, but you have pillow 10.1.0 which is incompatible.
invokeai 3.3.0 requires torch~=2.0.1, but you have torch 2.1.0 which is incompatible.
invokeai 3.3.0 requires torchvision~=0.15.2, but you have torchvision 0.16.0 which is incompatible.
Successfully installed MarkupSafe-2.1.3 certifi-2023.7.22 charset-normalizer-3.3.2 filelock-3.13.1 fsspec-2023.10.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 numpy-1.24.4 packaging-23.2 pillow-10.1.0 requests-2.28.2 sympy-1.12 torch-2.1.0 torchmetrics-0.11.4 torchvision-0.16.0 typing-extensions-4.8.0 urllib3-1.26.18
─────────────────────────────────────────────────────── Installing the InvokeAI Application 🎨 ────────────────────────────────────────────────────────
Unable to find a wheel or perform a source install. Giving up.
ERROR: Directory '/Users/samm/git/InvokeAI/installer[onnx]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Traceback (most recent call last):
  File "/Users/samm/git/InvokeAI/installer/./lib/main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 173, in install
    self.instance.install(
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 229, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 308, in install_app
    pip[
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp62hqyu_g/lib/python3.11/site-packages/plumbum/commands/modifiers.py", line 145, in __rand__
    cmd(
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp62hqyu_g/lib/python3.11/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp62hqyu_g/lib/python3.11/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp62hqyu_g/lib/python3.11/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp62hqyu_g/lib/python3.11/site-packages/plumbum/commands/processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp62hqyu_g/lib/python3.11/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp62hqyu_g/lib/python3.11/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /Users/samm/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 '/Users/samm/git/InvokeAI/installer[onnx]'
```

**Comment by mbrostami** [comment]
Running `python ./lib/main.py` instead of `./install.sh` worked for me.
