### ISSUE TITLE
[bug]: Unable to install 3.2, Getting requirements to build wheel error

### ISSUE THREAD

**Issue by darks0u1s** [invoke-ai/InvokeAI#4825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

3.2

### What happened?

Hi everyone,

I've tried several times to get Invoke to install but running into the same error everytime. No issues on my end (running python 3.10.6, no issues with other SD frontends like A1111)

I get the following error everytime a few minutes after the install begins, I pick option 1 for cuda (I have a 4090):

```
`Collecting basicsr>=1.3.3.11
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c7/c9/9dda955cc560db80bd7433210a3a8e5fc4676fcd88e64527dc3271feb7d1/basicsr-1.4.1.tar.gz (171 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "E:\AI\Invoke\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "E:\AI\Invoke\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "E:\AI\Invoke\.venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\sriramatrix\AppData\Local\Temp\pip-build-env-a721ks37\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\sriramatrix\AppData\Local\Temp\pip-build-env-a721ks37\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\sriramatrix\AppData\Local\Temp\pip-build-env-a721ks37\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\sriramatrix\AppData\Local\Temp\pip-build-env-a721ks37\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.2.1 -> 23.2.1
[notice] To update, run: E:\AI\Invoke\.venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "E:\AI\InvokeAI-Installer\lib\main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "E:\AI\InvokeAI-Installer\lib\installer.py", line 181, in install
    self.instance.install(
  File "E:\AI\InvokeAI-Installer\lib\installer.py", line 237, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "E:\AI\InvokeAI-Installer\lib\installer.py", line 316, in install_app
    pip[
  File "C:\Users\sriramatrix\AppData\Local\Temp\invokeai-installer-tmpmcdgof9k\Lib\site-packages\plumbum\commands\modifiers.py", line 145, in __rand__
    cmd(
  File "C:\Users\sriramatrix\AppData\Local\Temp\invokeai-installer-tmpmcdgof9k\Lib\site-packages\plumbum\commands\base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "C:\Users\sriramatrix\AppData\Local\Temp\invokeai-installer-tmpmcdgof9k\Lib\site-packages\plumbum\commands\base.py", line 252, in run
    return p.run()
  File "C:\Users\sriramatrix\AppData\Local\Temp\invokeai-installer-tmpmcdgof9k\Lib\site-packages\plumbum\commands\base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "C:\Users\sriramatrix\AppData\Local\Temp\invokeai-installer-tmpmcdgof9k\Lib\site-packages\plumbum\commands\processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "C:\Users\sriramatrix\AppData\Local\Temp\invokeai-installer-tmpmcdgof9k\Lib\site-packages\plumbum\commands\processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "C:\Users\sriramatrix\AppData\Local\Temp\invokeai-installer-tmpmcdgof9k\Lib\site-packages\plumbum\machines\base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | 'E:\AI\Invoke\.venv\Scripts\pip.exe' install --require-virtualenv --use-pep517 'E:\AI\InvokeAI-Installer\lib\InvokeAI-3.2.0rc3-py3-none-any.whl[xformers,onnx-cuda]' --extra-index-url https://download.pytorch.org/whl/cu118
Press any key to continue . . .`
![installerror](https://github.com/invoke-ai/InvokeAI/assets/35632843/be8390b5-4fed-4ac2-b4b1-6dd472b8f44e)

```
Any help would be great, really excited about trying the newest features. Thanks!

### Screenshots

![273430251-be8390b5-4fed-4ac2-b4b1-6dd472b8f44e](https://github.com/invoke-ai/InvokeAI/assets/35632843/540e78c3-7f0e-464d-9ffa-810eb19aa55c)

**Comment by DouHao92** [comment]
Hi man, I face the same issue as you do, could you tell me what's the solution of this?

**Comment by Drun555** [comment]
Same here

**Comment by cyanineeee** [comment]
same here... is there any solution now?

**Comment by Millu** [comment]
@cyanineeee can you open the developer console from your invoke.sh / invoke.bat file and run: `pip show torch`?
