### ISSUE TITLE
[bug]: step_index = step_index.item() 

### ISSUE THREAD

**Issue by Jammers33** [invoke-ai/InvokeAI#4924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.1.0

### What happened?

step_index = step_index.item() <000seems to be the issue as I keep getting this 
[2023-10-17 03:44:35,831]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\invokeai\app\services\processor.py", line 106, in __process
    outputs = invocation.invoke_internal(
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 610, in invoke_internal
    output = self.invoke(context)
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 703, in invoke
    result_latents, result_attention_map_saver = pipeline.latents_from_embeddings(
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 387, in latents_from_embeddings
    latents, attention_map_saver = self.generate_latents_from_embeddings(
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 460, in generate_latents_from_embeddings
    step_output = self.step(
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\invokeai\backend\stable_diffusion\diffusers_pipeline.py", line 611, in step
    step_output = self.scheduler.step(noise_pred, timestep, latents, **conditioning_data.scheduler_args)
  File "D:\_Invoke_AI\InvokeAI-main\InvokeAI-main\.venv\lib\site-packages\diffusers\schedulers\scheduling_dpmsolver_singlestep.py", line 669, in step
    step_index = step_index.item()
RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

[2023-10-17 03:44:35,842]::[InvokeAI]::ERROR --> Error while invoking:
a Tensor with 2 elements cannot be converted to Scalar

I went ahead a took a dep dive into the script scheduling_dpmsolver_singlestep.py", line 669, and even tried  to add my own if isinstance(timestep, torch.Tensor):
    timestep = timestep.to(self.timesteps.device)
step_index = (self.timesteps == timestep).nonzero()
if len(step_index) == 0:
    step_index = len(self.timesteps) - 1
else:
    if step_index.numel() != 1:
        print(f"Expected step_index to have 1 element, but got {step_index.numel()} elements. Values: {step_index}")
        # Here you can add additional logic to handle the multi-element tensor situation.
    else:
        step_index = step_index.item()
        
prev_timestep = 0 if step_index == len(self.timesteps) - 1 else self.timesteps[step_index + 1] and several variations of debugging., to offset the error, closed the terminal and reran invokeai --web still getting the same error, so I went ahead and set the scheduling_dpmsolver_singlestep.py back to origins, and here I am. 

### Contact Details

jamesa333t@gmail.com

**Comment by Millu** [comment]
This is an issue with the DPM++2S Karras scheduler - lower your step count to ~40 steps and it should be resolved.
