### ISSUE TITLE
[bug]: PydanticImportError: BaseSettings has been moved to the pydantic-settings package

### ISSUE THREAD

**Issue by drdancm** [invoke-ai/InvokeAI#4948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12Gb

### What version did you experience this issue on?

xx.xx.xx

### What happened?

When Invoke starts it does not give version. Nor can I find it anywhere. I've running Invoke inside Stability Matrix.
First version I had ran fine, but subsequent updates ( I lose count, but at least 5 Update notices) which I ran crash. Here is what latest update gave me:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\api_app.py", line 1, in <module>
    from .services.config import InvokeAIAppConfig
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\services\config\__init__.py", line 5, in <module>
    from .config_base import PagingArgumentParser  # noqa F401
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\services\config\config_base.py", line 21, in <module>
    from pydantic import BaseSettings
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\pydantic\__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\pydantic\_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.4/u/import-error

Process finished with exit code 1

### Screenshots

see above

### Additional context

Inside Stability Matrix. Haven't searched for existing issue because I'm not sure how to describe the problem.

### Contact Details

drdancm@computersandfood.com

**Comment by Millu** [comment]
We've seen this a couple times with users using InvokeAI with Stability Matrix - you'll need to downgrade your version of pydantic
