### ISSUE TITLE
[bug]: Problems with IP adapter

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.4.0rc1

### What happened?

Can't add IP adapter. But I downloaded it earlier, and I earlier in 3.2.0 I could add and enable IP adapter

<img width="436" alt="ip" src="https://github.com/invoke-ai/InvokeAI/assets/54937209/5652a0e4-6905-47e7-bd15-562cdaa7bbe4">

After adding IP adapter again from Repo - now I get this error, and IP-adapter not work
```
[2023-10-21 04:41:17,165]::[InvokeAI]::INFO --> Loading model D:\InvokeAI_3\models\any\clip_vision\ip_adapter_sd_image_encoder, type any:clip_vision
[2023-10-21 04:41:17,762]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\services\invocation_processor\invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 659, in invoke_internal
    output = self.invoke(context)
  File "D:\InvokeAI_3\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 744, in invoke
    ip_adapter_data = self.prep_ip_adapter_data(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 488, in prep_ip_adapter_data
    image_encoder_model_info = context.services.model_manager.get_model(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\services\model_manager\model_manager_default.py", line 112, in get_model
    model_info = self.mgr.get_model(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 496, in get_model
    model_context = self.cache.get_model(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 228, in get_model
    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\backend\model_management\models\clip_vision.py", line 63, in get_model
    model = CLIPVisionModelWithProjection.from_pretrained(self.model_path, torch_dtype=torch_dtype)
  File "D:\InvokeAI_3\.venv\lib\site-packages\transformers\modeling_utils.py", line 2629, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\InvokeAI_3\.venv\lib\site-packages\transformers\modeling_utils.py", line 447, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

[2023-10-21 04:41:17,768]::[InvokeAI]::ERROR --> Error while invoking:
Error while deserializing header: MetadataIncompleteBuffer

```

**Comment by vrubzov1957** [comment]
Update: IDK why, but previously added ip-adapters (from InvokeAI repo, on version 3.2 or 3.3) not found by version 3.4rc1. Downloaded from repo again - now I can enable IP adapters, but IDK why previous ip-models was lost

**Comment by Millu** [comment]
Glad you got it fixed!
