### ISSUE TITLE
[bug]: Register argument

### ISSUE THREAD

**Issue by catiktiks** [invoke-ai/InvokeAI#4971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8Gb

### What version did you experience this issue on?

3.3.0

### What happened?

Hello,

I am some kind of noob, sry :)

I installed invokeai a couple of years ago with no major problems.

I wanted to reinstall it today and i had problem with pip version at the beggining. I solved it and succeed to install invokai.

But when i want to launch the browser interface, i have this message : TypeError: Invalid first argument to `register()`: <staticmethod object at 0x000001BA1261A940>. Use either `@register(some_class)` or plain `@register` on an annotated function.

thx in advance :)

### Screenshots

Starting the InvokeAI browser-based UI..
[2023-10-21 15:07:11,394]::[InvokeAI]::INFO --> Patchmatch initialized
Traceback (most recent call last):
  File "C:\Users\catik\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\catik\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\invoke\.venv\Scripts\invokeai-web.exe\__main__.py", line 4, in <module>
    from invokeai.app.api_app import invoke_api
  File "C:\invoke\.venv\lib\site-packages\invokeai\app\api_app.py", line 33, in <module>
    from .api.dependencies import ApiDependencies
  File "C:\invoke\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 12, in <module>
    from invokeai.app.services.images import ImageService, ImageServiceDependencies
  File "C:\invoke\.venv\lib\site-packages\invokeai\app\services\images.py", line 32, in <module>
    from invokeai.app.util.metadata import get_metadata_graph_from_raw_session
  File "C:\invoke\.venv\lib\site-packages\invokeai\app\util\metadata.py", line 6, in <module>
    from invokeai.app.services.graph import Edge
  File "C:\invoke\.venv\lib\site-packages\invokeai\app\services\graph.py", line 14, in <module>
    from ..invocations import *  # noqa: F401 F403
  File "C:\invoke\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 920, in <module>
    class ImageToLatentsInvocation(BaseInvocation):
  File "C:\invoke\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 1006, in ImageToLatentsInvocation
    def _(vae: AutoencoderTiny, image_tensor: torch.FloatTensor) -> torch.FloatTensor:
  File "C:\Users\catik\AppData\Local\Programs\Python\Python39\lib\functools.py", line 909, in register
    return self.dispatcher.register(cls, func=method)
  File "C:\Users\catik\AppData\Local\Programs\Python\Python39\lib\functools.py", line 851, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`: <staticmethod object at 0x000001BA1261A940>. Use either `@register(some_class)` or plain `@register` on an annotated function.

**Comment by pryadchenko** [comment]
The same issue on MacOS

**Comment by catiktiks** [comment]
solved with the 3.4 pre release and python 3.11

**Comment by catiktiks** [comment]
solved with higher version apparentrly

**Comment by pryadchenko** [comment]
I've used exactly the latest one: https://github.com/invoke-ai/InvokeAI/releases/tag/v3.3.0post3
