### ISSUE TITLE
[bug]: TypeError: SqliteItemStorage.__init__() missing 1 required positional argument: 'lock'

### ISSUE THREAD

**Issue by jennifer-five** [invoke-ai/InvokeAI#5003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

3.3.0

### What happened?
patchmatch.patch_match: ERROR - patchmatch failed to load or compile (Command 'make clean && make' returned non-zero exit status 2.).
>> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
[2023-10-29 20:11:04,672]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)
[2023-10-29 20:11:04,816]::[InvokeAI]::INFO --> InvokeAI version 3.3.0post3
[2023-10-29 20:11:04,834]::[InvokeAI]::INFO --> GPU device = mps 
[2023-10-29 20:11:04,836]::[InvokeAI]::INFO --> Scanning /Users/jennifer/invokeai/models for new models
[2023-10-29 20:11:04,969]::[InvokeAI]::INFO --> Scanned 9 files and directories, imported 0 models
[2023-10-29 20:11:04,971]::[InvokeAI]::INFO --> Model manager service initialized
[2023-10-29 20:11:04,973]::[InvokeAI]::INFO --> InvokeAI database location is "/Users/invokeai/databases/invokeai.db"
Traceback (most recent call last):
  File "/Users/invokeai/.venv/bin/invokeai", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jennifer/invokeai/.venv/lib/python3.11/site-packages/invokeai/frontend/legacy_launch_invokeai.py", line 18, in main
    invoke_cli()
  File "/Users/jennifer/invokeai/.venv/lib/python3.11/site-packages/invokeai/app/cli_app.py", line 257, in invoke_cli
    graph_execution_manager = SqliteItemStorage[GraphExecutionState](conn=db_conn, table_name="graph_executions")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 1268, in __call__
    result = self.__origin__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SqliteItemStorage.__init__() missing 1 required positional argument: 'lock'

**Comment by Millu** [comment]
Did you encounter this error when trying to use the CLI?

**Comment by jennifer-five** [comment]
> Did you encounter this error when trying to use the CLI?

yes

**Comment by Millu** [comment]
The CLI has been deprecated and will not work as expected - it has since been removed from the launcher options.
