### ISSUE TITLE
[bug]: IP Adapter not work: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#5021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.4.0rc2

### What happened?

IP adapter not works. Give me "MetadataIncompleteBuffer" error.

```
[2023-11-01 13:08:02,709]::[InvokeAI]::INFO --> Loading model D:\InvokeAI_3\models\any\clip_vision\ip_adapter_sd_image_encoder, type any:clip_vision
[2023-11-01 13:08:03,273]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\services\invocation_processor\invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 659, in invoke_internal
    output = self.invoke(context)
  File "D:\InvokeAI_3\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 744, in invoke
    ip_adapter_data = self.prep_ip_adapter_data(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 488, in prep_ip_adapter_data
    image_encoder_model_info = context.services.model_manager.get_model(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\app\services\model_manager\model_manager_default.py", line 112, in get_model
    model_info = self.mgr.get_model(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 496, in get_model
    model_context = self.cache.get_model(
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 228, in get_model
    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)
  File "D:\InvokeAI_3\.venv\lib\site-packages\invokeai\backend\model_management\models\clip_vision.py", line 63, in get_model
    model = CLIPVisionModelWithProjection.from_pretrained(self.model_path, torch_dtype=torch_dtype)
  File "D:\InvokeAI_3\.venv\lib\site-packages\transformers\modeling_utils.py", line 2629, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\InvokeAI_3\.venv\lib\site-packages\transformers\modeling_utils.py", line 447, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

[2023-11-01 13:08:03,278]::[InvokeAI]::ERROR --> Error while invoking:
Error while deserializing header: MetadataIncompleteBuffer
```

I tried different diffusers models (SD 1.5) - all same.

IP-adapter on SDXL I cant try - because not enough VRAM for it

### Screenshots

<img width="442" alt="err" src="https://github.com/invoke-ai/InvokeAI/assets/54937209/021fbad1-d5be-4784-9920-1aa725d39ba7">

### Additional context

If it matters - I use frontend and backend on different computers (back on workstation, front on laptop)

**Comment by Millu** [comment]
Try deleting & redownloading the IP Adapter. Seems like something is wrong with the model you have installed

**Comment by vrubzov1957** [comment]
> Try deleting & redownloading the IP Adapter. Seems like something is wrong with the model you have installed

I already tried it - still the same

**Comment by Millu** [comment]
@vrubzov1957 where did you download the IP adapter from?

**Comment by vrubzov1957** [comment]
@Millu from InvokeAI repo.

Like this
* From page https://models.invoke.ai/InvokeAI/ip_adapter_plus_sd15
* I found _InvokeAI/ip_adapter_plus_sd15_
* Insert it to _model manager_ in InvokeAI on my PC.

I downoaded all resources from **models.invoke.ai** where was word "IP"

**Comment by vrubzov1957** [comment]
On 3.4.0post1 - works good.

@Millu  Can be closed
