### ISSUE TITLE
[bug]: ModuleList has no attribute 10_mlp_fc1 when using LoRA + CLIP Skip

### ISSUE THREAD

**Issue by lklklk248** [invoke-ai/InvokeAI#5077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8g

### What version did you experience this issue on?

3.4.0.rc3-rc4

### What happened?

**When I use Lora, the following error is reported, but I don't know why there is only detail_ Slider_ The v4 model runs normally, and I imported the LORA model from a shared folder. I have reinstalled v4 and the entire directory of configuration files, but the issue still persists. Help me**

[2023-11-11 23:03:19,758]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\services\invocation_processor\invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 596, in invoke_internal
    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\invocations\compel.py", line 110, in invoke
    with (
  File "D:\miniconda\envs\ai\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\backend\model_management\lora.py", line 76, in apply_lora_text_encoder
    with cls.apply_lora(text_encoder, loras, "lora_te_"):
  File "D:\miniconda\envs\ai\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\backend\model_management\lora.py", line 123, in apply_lora
    module_key, module = cls._resolve_lora_key(model, layer_key, prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\backend\model_management\lora.py", line 54, in _resolve_lora_key
    module = module.get_submodule(submodule_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 686, in get_submodule
    raise AttributeError(mod._get_name() + " has no "
AttributeError: ModuleList has no attribute `10_mlp_fc1`

[2023-11-11 23:03:19,765]::[InvokeAI]::ERROR --> Error while invoking:
ModuleList has no attribute `10_mlp_fc1`

### Screenshots

<img width="1081" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/53925023/3d772fd5-15c0-4268-80f1-95432e995d91">

**Comment by Millu** [comment]
Could you share a link to the LoRA? Do other LoRAs cause the same error?

**Comment by lklklk248** [comment]
> Could you share a link to the LoRA? Do other LoRAs cause the same error?
I don't know if it's because I used the first LORA after reinstalling, and all subsequent LORAs have the same problem. Here is the Lora link
https://civitai.com/models/153562/detail-slider-lora

**Comment by lklklk248** [comment]
**### When my clip is 0, the error is as follows**

[2023-11-13 10:37:53,122]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\services\invocation_processor\invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 596, in invoke_internal    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\invocations\compel.py", line 133, in invoke
    c, options = compel.build_conditioning_tensor_for_conjunction(conjunction)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\compel\compel.py", line 186, in build_conditioning_tensor_for_conjunction    this_conditioning, this_options = self.build_conditioning_tensor_for_prompt_object(p)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\compel\compel.py", line 218, in build_conditioning_tensor_for_prompt_object
    return self._get_conditioning_for_flattened_prompt(prompt), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\compel\compel.py", line 282, in _get_conditioning_for_flattened_prompt
    return self.conditioning_provider.get_embeddings_for_weighted_prompt_fragments(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\compel\embeddings_provider.py", line 120, in get_embeddings_for_weighted_prompt_fragments
    base_embedding = self.build_weighted_embedding_tensor(tokens, per_token_weights, mask, device=device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\compel\embeddings_provider.py", line 357, in build_weighted_embedding_tensor
    empty_z = self._encode_token_ids_to_embeddings(empty_token_ids)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\compel\embeddings_provider.py", line 390, in _encode_token_ids_to_embeddings
    text_encoder_output = self.text_encoder(token_ids,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 800, in forward
    return self.text_model(
           ^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 705, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 632, in forward
    layer_outputs = encoder_layer(
                    ^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 371, in forward
    hidden_states = self.layer_norm1(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\normalization.py", line 196, in forward
    return F.layer_norm(
           ^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\functional.py", line 2543, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

[2023-11-13 10:37:53,130]::[InvokeAI]::ERROR --> Error while invoking:
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)


**When the clip is 1, the error is as follows, and when the clip is 2-11, it is the error displayed for this bug**

<img width="849" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/53925023/b408a39c-9a6a-442f-a3c9-13886c6867dc">


**Error reported when clip is 12**
[2023-11-13 10:40:51,663]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\services\invocation_processor\invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 596, in invoke_internal
    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\app\invocations\compel.py", line 110, in invoke
    with (
  File "D:\miniconda\envs\ai\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\backend\model_management\lora.py", line 76, in apply_lora_text_encoder
    with cls.apply_lora(text_encoder, loras, "lora_te_"):
  File "D:\miniconda\envs\ai\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\backend\model_management\lora.py", line 123, in apply_lora
    module_key, module = cls._resolve_lora_key(model, layer_key, prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\invokeai\backend\model_management\lora.py", line 54, in _resolve_lora_key
    module = module.get_submodule(submodule_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda\envs\ai\Lib\site-packages\torch\nn\modules\module.py", line 686, in get_submodule
    raise AttributeError(mod._get_name() + " has no "
AttributeError: ModuleList has no attribute `0_mlp_fc1`

[2023-11-13 10:40:51,671]::[InvokeAI]::ERROR --> Error while invoking:
ModuleList has no attribute `0_mlp_fc1`

**Comment by psychedelicious** [comment]
The error when clip skip is 0 is not the full error. We can't see where the error is coming from. Please copy and paste the full error. 

The other errors are now resolved
