### ISSUE TITLE
[bug]: ERROR: Directory invokeAI/installer[onnx] is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by sammcj** [invoke-ai/InvokeAI#5097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

96GB

### What version did you experience this issue on?

3.3.0-post3

### What happened?

When trying to install InvokeAI on macOS the install / reinstall process fails with "Neither 'setup.py' nor 'pyproject.toml' found."

- macOS 14.1.1
- Python 3.11.6 from pyenv
	- Also tested with Python 3.12.0
	- Shouldn't InvokeAI be using it's own bundled / isolated python version 

```
~ which python
/Users/samm/.pyenv/shims/python
~ python --version
Python 3.11.6
```

### Additional context

Clean install:

```
─────────────────────────────────────────────────────── Installing the InvokeAI Application 🎨 ────────────────────────────────────────────────────────
Unable to find a wheel or perform a source install. Giving up.
ERROR: Directory '/Users/samm/git/InvokeAI/installer[onnx]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Traceback (most recent call last):
  File "/Users/samm/git/InvokeAI/installer/./lib/main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 173, in install
    self.instance.install(
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 229, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 308, in install_app
    pip[
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpmcjc5bbv/lib/python3.11/site-packages/plumbum/commands/modifiers.py", line 145, in __rand__
    cmd(
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpmcjc5bbv/lib/python3.11/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpmcjc5bbv/lib/python3.11/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpmcjc5bbv/lib/python3.11/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpmcjc5bbv/lib/python3.11/site-packages/plumbum/commands/processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpmcjc5bbv/lib/python3.11/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpmcjc5bbv/lib/python3.11/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /Users/samm/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 '/Users/samm/git/InvokeAI/installer[onnx]'
```

**Comment by Millu** [comment]
I'm not sure why onnx is trying to be installed since you're on macOS - did you what did you select for the configuration?

**Comment by sammcj** [comment]
This occurs when selecting either the default or CPU provider.

**Comment by sammcj** [comment]
<img width="1672" alt="image" src="https://github.com/invoke-ai/InvokeAI/assets/862951/99818f78-b25a-4559-82dc-0b3571685b2d">

```
~/git/InvokeAI/installer/install.sh.in                                                                         <region:ap-southeast-2>
Initializing the installer. This may take a minute - please wait...
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
╔═════════════════════════════════════════════════════════ Welcome to the InvokeAI Installer ═════════════════════════════════════════════════════════╗
║                                                                                                                                                     ║
║  macOS Users!                                                                                                                                       ║
║                                                                                                                                                     ║
║  Please be sure you have the Xcode command-line tools installed before continuing.                                                                  ║
║  If not, cancel with Control-C and follow the Xcode install instructions at https://www.freecodecamp.org/news/install-xcode-command-line-tools/.    ║
║                                                                                                                                                     ║
║      Some of the installation steps take a long time to run. Please be patient. If the script appears to hang for more than 10 minutes, please      ║
║                                                         interrupt with Control-C and retry.                                                         ║
║                                                                                                                                                     ║
╚═══════════════════════════════════════════════════════════════════ Darwin-arm64 ════════════════════════════════════════════════════════════════════╝

InvokeAI will be installed in /Users/samm/invokeai
Use this location? [y/n] (y): y

Your platform Darwin-arm64 only supports the "cpu" driver. Proceeding with that.
──────────────────────────────────────────────────────────────── Installing PyTorch 🔥 ────────────────────────────────────────────────────────────────
Collecting numpy~=1.24.0
  Using cached numpy-1.24.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting urllib3~=1.26.0
  Using cached urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
Collecting requests~=2.28.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting torch~=2.1.0
  Using cached torch-2.1.0-cp311-none-macosx_11_0_arm64.whl.metadata (24 kB)
Collecting torchmetrics==0.11.4
  Using cached torchmetrics-0.11.4-py3-none-any.whl (519 kB)
Collecting torchvision>=0.14.1
  Using cached torchvision-0.16.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.6 kB)
Collecting packaging (from torchmetrics==0.11.4)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting charset-normalizer<4,>=2 (from requests~=2.28.0)
  Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests~=2.28.0)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17 (from requests~=2.28.0)
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting filelock (from torch~=2.1.0)
  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting typing-extensions (from torch~=2.1.0)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch~=2.1.0)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx (from torch~=2.1.0)
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting jinja2 (from torch~=2.1.0)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting fsspec (from torch~=2.1.0)
  Using cached fsspec-2023.10.0-py3-none-any.whl.metadata (6.8 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision>=0.14.1)
  Using cached Pillow-10.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch~=2.1.0)
  Using cached MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.0 kB)
Collecting mpmath>=0.19 (from sympy->torch~=2.1.0)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached numpy-1.24.4-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
Using cached urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
Using cached torch-2.1.0-cp311-none-macosx_11_0_arm64.whl (59.6 MB)
Using cached torchvision-0.16.0-cp311-cp311-macosx_11_0_arm64.whl (1.6 MB)
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl (118 kB)
Using cached Pillow-10.1.0-cp311-cp311-macosx_11_0_arm64.whl (3.3 MB)
Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Using cached fsspec-2023.10.0-py3-none-any.whl (166 kB)
Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl (17 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, packaging, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torchmetrics
Successfully installed MarkupSafe-2.1.3 certifi-2023.7.22 charset-normalizer-3.3.2 filelock-3.13.1 fsspec-2023.10.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 numpy-1.24.4 packaging-23.2 pillow-10.1.0 requests-2.28.2 sympy-1.12 torch-2.1.0 torchmetrics-0.11.4 torchvision-0.16.0 typing-extensions-4.8.0 urllib3-1.26.18
─────────────────────────────────────────────────────── Installing the InvokeAI Application 🎨 ────────────────────────────────────────────────────────
Unable to find a wheel or perform a source install. Giving up.
ERROR: Directory '/Users/samm/git/InvokeAI/installer[onnx]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Traceback (most recent call last):
  File "/Users/samm/git/InvokeAI/installer/./lib/main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 173, in install
    self.instance.install(
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 229, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 308, in install_app
    pip[
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp4tnp02a7/lib/python3.11/site-packages/plumbum/commands/modifiers.py", line 145, in __rand__
    cmd(
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp4tnp02a7/lib/python3.11/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp4tnp02a7/lib/python3.11/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp4tnp02a7/lib/python3.11/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp4tnp02a7/lib/python3.11/site-packages/plumbum/commands/processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp4tnp02a7/lib/python3.11/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp4tnp02a7/lib/python3.11/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /Users/samm/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 '/Users/samm/git/InvokeAI/installer[onnx]'
```

**Comment by sammcj** [comment]
Tried with Python 3.10, 3.11, 3.12.

Here's the output of 3.10:

```

──────────────────────────────────────────────────────────────── Installing PyTorch 🔥 ────────────────────────────────────────────────────────────────
Collecting numpy~=1.24.0
  Downloading numpy-1.24.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting urllib3~=1.26.0
  Using cached urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
Collecting requests~=2.28.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting torch~=2.1.0
  Downloading torch-2.1.0-cp310-none-macosx_11_0_arm64.whl.metadata (24 kB)
Collecting torchmetrics==0.11.4
  Using cached torchmetrics-0.11.4-py3-none-any.whl (519 kB)
Collecting torchvision>=0.14.1
  Downloading torchvision-0.16.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (6.6 kB)
Collecting packaging (from torchmetrics==0.11.4)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting charset-normalizer<4,>=2 (from requests~=2.28.0)
  Using cached charset_normalizer-3.3.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests~=2.28.0)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17 (from requests~=2.28.0)
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting filelock (from torch~=2.1.0)
  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting typing-extensions (from torch~=2.1.0)
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch~=2.1.0)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx (from torch~=2.1.0)
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting jinja2 (from torch~=2.1.0)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting fsspec (from torch~=2.1.0)
  Using cached fsspec-2023.10.0-py3-none-any.whl.metadata (6.8 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision>=0.14.1)
  Downloading Pillow-10.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch~=2.1.0)
  Downloading MarkupSafe-2.1.3-cp310-cp310-macosx_10_9_universal2.whl.metadata (3.0 kB)
Collecting mpmath>=0.19 (from sympy->torch~=2.1.0)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Downloading numpy-1.24.4-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 103.7 MB/s eta 0:00:00
Using cached urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
Downloading torch-2.1.0-cp310-none-macosx_11_0_arm64.whl (59.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 97.4 MB/s eta 0:00:00
Downloading torchvision-0.16.0-cp310-cp310-macosx_11_0_arm64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 87.1 MB/s eta 0:00:00
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using cached charset_normalizer-3.3.2-cp310-cp310-macosx_11_0_arm64.whl (120 kB)
Downloading Pillow-10.1.0-cp310-cp310-macosx_11_0_arm64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 93.9 MB/s eta 0:00:00
Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Using cached fsspec-2023.10.0-py3-none-any.whl (166 kB)
Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Downloading MarkupSafe-2.1.3-cp310-cp310-macosx_10_9_universal2.whl (17 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, packaging, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torchmetrics
Successfully installed MarkupSafe-2.1.3 certifi-2023.7.22 charset-normalizer-3.3.2 filelock-3.13.1 fsspec-2023.10.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 numpy-1.24.4 packaging-23.2 pillow-10.1.0 requests-2.28.2 sympy-1.12 torch-2.1.0 torchmetrics-0.11.4 torchvision-0.16.0 typing-extensions-4.8.0 urllib3-1.26.18
─────────────────────────────────────────────────────── Installing the InvokeAI Application 🎨 ────────────────────────────────────────────────────────
Unable to find a wheel or perform a source install. Giving up.
ERROR: Directory '/Users/samm/git/InvokeAI/installer' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Traceback (most recent call last):
  File "/Users/samm/git/InvokeAI/installer/./lib/main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 173, in install
    self.instance.install(
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 229, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 308, in install_app
    pip[
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpkryz93mk/lib/python3.10/site-packages/plumbum/commands/modifiers.py", line 145, in __rand__
    cmd(
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpkryz93mk/lib/python3.10/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpkryz93mk/lib/python3.10/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpkryz93mk/lib/python3.10/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpkryz93mk/lib/python3.10/site-packages/plumbum/commands/processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpkryz93mk/lib/python3.10/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmpkryz93mk/lib/python3.10/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /Users/samm/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 /Users/samm/git/InvokeAI/installer
```

**Comment by sammcj** [comment]
Confirmed it's something wrong with the automatic installer.

I did a manual installation which worked perfectly.

**Comment by sammcj** [comment]
FYI - The automatic installer is still broken in v3.5.0rc1


```
~/git/invokeAI@main ./installer/install.sh.in                                                                    
...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 2.14.6 requires fsspec[http]<=2023.10.0,>=2023.1.0, but you have fsspec 2023.12.2 which is incompatible.
imageio 2.32.0 requires pillow<10.1.0,>=8.3.2, but you have pillow 10.1.0 which is incompatible.
Successfully installed MarkupSafe-2.1.3 certifi-2023.11.17 charset-normalizer-3.3.2 filelock-3.13.1 fsspec-2023.12.2 idna-3.6 jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 numpy-1.24.4 packaging-23.2 pillow-10.1.0 requests-2.28.2 sympy-1.12 torch-2.1.1 torchmetrics-0.11.4 torchvision-0.16.1 typing-extensions-4.9.0 urllib3-1.26.18
─────────────────────────────────────────────────────── Installing the InvokeAI Application 🎨 ────────────────────────────────────────────────────────
Unable to find a wheel or perform a source install. Giving up.
ERROR: Directory '/Users/samm/git/InvokeAI/installer[onnx]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Traceback (most recent call last):
  File "/Users/samm/git/InvokeAI/installer/./lib/main.py", line 52, in <module>
    inst.install(**args.__dict__)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 173, in install
    self.instance.install(
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 229, in install
    self.install_app(extra_index_url, optional_modules, find_links)
  File "/Users/samm/git/InvokeAI/installer/lib/installer.py", line 308, in install_app
    pip[
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp1kbt4j_c/lib/python3.11/site-packages/plumbum/commands/modifiers.py", line 145, in __rand__
    cmd(
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp1kbt4j_c/lib/python3.11/site-packages/plumbum/commands/base.py", line 113, in __call__
    return self.run(args, **kwargs)[1]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp1kbt4j_c/lib/python3.11/site-packages/plumbum/commands/base.py", line 252, in run
    return p.run()
           ^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp1kbt4j_c/lib/python3.11/site-packages/plumbum/commands/base.py", line 215, in runner
    return run_proc(p, retcode, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp1kbt4j_c/lib/python3.11/site-packages/plumbum/commands/processes.py", line 299, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp1kbt4j_c/lib/python3.11/site-packages/plumbum/commands/processes.py", line 17, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/private/var/folders/b2/wnpx7gg566l7dq63x0h27r9r0000gn/T/invokeai-installer-tmp1kbt4j_c/lib/python3.11/site-packages/plumbum/machines/base.py", line 27, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /Users/samm/invokeai/.venv/bin/pip install --require-virtualenv --use-pep517 '/Users/samm/git/InvokeAI/installer[onnx]'
```

**Comment by psychedelicious** [comment]
We redid the installer to be much simpler for v4 and it works for me on macOS. I'm pretty sure you have been up and running for a while since this issue, but please let me know if it is still a problem.

**Comment by sammcj** [comment]
Ah yes indeed! Thanks it's all sorted.
