### ISSUE TITLE
[bug]: „Error while invoking: unpickling stack underflow“ when using custom model

### ISSUE THREAD

**Issue by tibor** [invoke-ai/InvokeAI#5300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

8GB

### What version did you experience this issue on?

3.4.0post2

### What happened?

I try to import a custom model as a .cpkt. However, when I try to quick add it, I get the following error in terminal:
```
[2023-12-15 20:09:59,787]::[uvicorn.access]::INFO --> 127.0.0.1:57004 - "POST /api/v1/models/import HTTP/1.1" 500
[2023-12-15 20:09:59,787]::[uvicorn.error]::ERROR --> Exception in ASGI application
```

When advance add the model and I start to generate an image, the application throws an error:

```
Traceback (most recent call last):
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/app/services/invocation_processor/invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/app/invocations/baseinvocation.py", line 591, in invoke_internal
    output = self.invoke(context)
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/app/invocations/compel.py", line 69, in invoke
    tokenizer_info = context.services.model_manager.get_model(
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/app/services/model_manager/model_manager_default.py", line 112, in get_model
    model_info = self.mgr.get_model(
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/model_manager.py", line 490, in get_model
    model_path = model_class.convert_if_required(
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/models/stable_diffusion.py", line 127, in convert_if_required
    return _convert_ckpt_and_cache(
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/models/stable_diffusion.py", line 289, in _convert_ckpt_and_cache
    convert_ckpt_to_diffusers(
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 1728, in convert_ckpt_to_diffusers
    pipe = download_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/invokeai/backend/model_management/convert_ckpt_to_diffusers.py", line 1229, in download_from_original_stable_diffusion_ckpt
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Applications/InvokeAI/.venv/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
```

**Comment by Millu** [comment]
Is there a .safetensors version of the model you can try to import instead?

**Comment by psychedelicious** [comment]
The model manager has been rewritten in v4. Please create a new issue if the problem persists on the latest release.
