### ISSUE TITLE
[bug]: bug for last ver 3.5.0rc1

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#5304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

15

### What version did you experience this issue on?

3.5.0rc1

### What happened?

When I use it, it gives an error. The previous version was good. I don't know if it has been tested

2023-12-16 15:32:38.191749: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-16 15:32:38.191810: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-16 15:32:38.193166: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-16 15:32:39.303112: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
[2023-12-16 15:32:44,566]::[InvokeAI]::INFO --> Patchmatch initialized
[2023-12-16 15:32:49,570]::[uvicorn.error]::INFO --> Started server process [18730]
[2023-12-16 15:32:49,573]::[uvicorn.error]::INFO --> Waiting for application startup.
[2023-12-16 15:32:49,574]::[InvokeAI]::INFO --> InvokeAI version 3.5.0rc1
[2023-12-16 15:32:49,574]::[InvokeAI]::INFO --> Root directory = /content/db
[2023-12-16 15:32:49,574]::[InvokeAI]::INFO --> Initializing database at /content/db/databases/invokeai.db
[2023-12-16 15:32:49,605]::[InvokeAI]::INFO --> GPU device = cuda Tesla T4
[2023-12-16 15:32:49,610]::[InvokeAI]::INFO --> Scanning /content/db/models for new models
[2023-12-16 15:32:50,269]::[InvokeAI]::INFO --> Scanned 9 files and directories, imported 0 models
[2023-12-16 15:32:50,270]::[InvokeAI]::INFO --> Model manager service initialized
[2023-12-16 15:32:50,296]::[ModelInstallService]::INFO --> Checking for models that have been moved or deleted from disk
[2023-12-16 15:32:50,303]::[ModelInstallService]::INFO --> Scanning /content/db/models for new and orphaned models
[2023-12-16 15:32:50,322]::[ModelInstallService]::INFO --> 0 new models registered; 0 unregistered
[2023-12-16 15:32:50,327]::[ModelInstallService]::INFO --> Scanning autoimport directory for new models
[2023-12-16 15:32:50,329]::[ModelInstallService]::INFO --> 0 new models registered
[2023-12-16 15:32:50,329]::[ModelInstallService]::INFO --> Model installer (re)initialized
[2023-12-16 15:32:50,391]::[uvicorn.error]::INFO --> Application startup complete.
[2023-12-16 15:32:50,391]::[uvicorn.error]::INFO --> Uvicorn running on http://127.0.0.1:9090/ (Press CTRL+C to quit)
 
 and other this 
 2023-12-16 15:32:03.985060: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-16 15:32:03.985115: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-16 15:32:03.986590: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-16 15:32:05.113112: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
[2023-12-16 15:32:11,123]::[InvokeAI]::INFO --> Patchmatch initialized

An exception has occurred: /content/invokeai/configs/models.yaml not found
== STARTUP ABORTED ==
** One or more necessary files is missing from your InvokeAI root directory **
** Please rerun the configuration script to fix this problem. **
** From the launcher, selection option [7]. **
** From the command line, activate the virtual environment and run "invokeai-configure --yes --skip-sd-weights" **
** (To skip this check completely, add "--ignore_missing_core_models" to your CLI args. Not installing these core models will prevent the loading of some or all .safetensors and .ckpt files. However, you can always come back and install these core models in the future.)
Press any key to continue...Traceback (most recent call last):
  File "/content/InvokeAI/invokeai/backend/install/check_root.py", line 11, in check_invokeai_root
    assert config.model_conf_path.exists(), f"{config.model_conf_path} not found"
AssertionError: /content/invokeai/configs/models.yaml not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/invokeai-web", line 8, in <module>
    sys.exit(invoke_api())
  File "/content/InvokeAI/invokeai/app/api_app.py", line 250, in invoke_api
    check_invokeai_root(app_config)  # note, may exit with an exception if root not set up
  File "/content/InvokeAI/invokeai/backend/install/check_root.py", line 40, in check_invokeai_root
    input("Press any key to continue...")
EOFError: EOF when reading a line

AFTER I OPENED GIVE ME THIS

{"detail":"Not Found"}

**Comment by hipsterusername** [comment]
The last  (detail not found) will be fixed in an RC today

RE: The below - Did you rerun configuration, per instructions
> 
> == STARTUP ABORTED ==
> ** One or more necessary files is missing from your InvokeAI root directory **
> ** Please rerun the configuration script to fix this problem. **
> ** From the launcher, selection option [7]. **

**Comment by wolfkingal2000** [comment]
yes i run configuration but not any effect

**Comment by wolfkingal2000** [comment]
> yes i run configuration but not any effect



> The last (detail not found) will be fixed in an RC today
> 
> RE: The below - Did you rerun configuration, per instructions
> 
> > == STARTUP ABORTED ==
> > ** One or more necessary files is missing from your InvokeAI root directory **
> > ** Please rerun the configuration script to fix this problem. **
> > ** From the launcher, selection option [7]. **

yes i run configuration but not any effect

**Comment by wolfkingal2000** [comment]
> The last (detail not found) will be fixed in an RC today
> 
> RE: The below - Did you rerun configuration, per instructions
> 
> > == STARTUP ABORTED ==
> > ** One or more necessary files is missing from your InvokeAI root directory **
> > ** Please rerun the configuration script to fix this problem. **
> > ** From the launcher, selection option [7]. **

3.5.0rc2 ver {"detail":"Not Found"} don't fixed

**Comment by rhurta** [comment]
Hi, I have the same issue after update to 3.5.0rc2.
I execute the option to rerun config after upgrade and database maintenance without success.
In the rc1 I didn't have this problem
