### ISSUE TITLE
[bug]:  3.5.0rc3 Automatic installer: No module named varint

### ISSUE THREAD

**Issue by Lesani** [invoke-ai/InvokeAI#5346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24

### What version did you experience this issue on?

 3.5.0rc3

### What happened?

`Desired action:
1. Generate images with the browser-based interface
2. Run textual inversion training
3. Merge models (diffusers type only)
4. Download and install models
5. Change InvokeAI startup options
6. Re-run the configure script to fix a broken install or to complete a major upgrade
7. Open the developer console
8. Update InvokeAI
9. Run the InvokeAI image database maintenance script
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
[2023-12-24 14:32:23,102]::[InvokeAI]::INFO --> Patchmatch initialized
C:\Users\Lesani\invokeai\.venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Lesani\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Lesani\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lesani\invokeai\.venv\Scripts\invokeai-web.exe\__main__.py", line 4, in <module>
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\app\api_app.py", line 43, in <module>
    from .api.dependencies import ApiDependencies
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 26, in <module>
    from ..services.model_install import ModelInstallService
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\app\services\model_install\__init__.py", line 3, in <module>
    from .model_install_base import (
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\app\services\model_install\model_install_base.py", line 15, in <module>
    from invokeai.app.services.model_records import ModelRecordServiceBase
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\app\services\model_records\__init__.py", line 2, in <module>
    from .model_records_base import (  # noqa F401
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\app\services\model_records\model_records_base.py", line 10, in <module>
    from invokeai.backend.model_manager.config import AnyModelConfig, BaseModelType, ModelFormat, ModelType
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\__init__.py", line 14, in <module>
    from .probe import ModelProbe
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\probe.py", line 25, in <module>
    from .hash import FastModelHash
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\hash.py", line 16, in <module>
    from imohash import hashfile
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\imohash\__init__.py", line 1, in <module>
    from .imohash import hashfile, hashfileobject
  File "C:\Users\Lesani\invokeai\.venv\lib\site-packages\imohash\imohash.py", line 10, in <module>
    import varint
ModuleNotFoundError: No module named 'varint'
Desired action:
1. Generate images with the browser-based interface
2. Run textual inversion training
3. Merge models (diffusers type only)
4. Download and install models
5. Change InvokeAI startup options
6. Re-run the configure script to fix a broken install or to complete a major upgrade
7. Open the developer console
8. Update InvokeAI
9. Run the InvokeAI image database maintenance script
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 7
Developer Console
Python command is:
C:\Users\Lesani\invokeai\.venv\Scripts\python.exe
C:\Users\Lesani\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\Lesani\AppData\Local\Programs\Python\Python311\python.exe
C:\Users\Lesani\AppData\Local\Microsoft\WindowsApps\python.exe
Python version is:
Python 3.10.6
*************************
You are now in the system shell, with the local InvokeAI Python virtual environment activated,
so that you can troubleshoot this InvokeAI installation as necessary.
*************************
*** Type `exit` to quit this shell and deactivate the Python virtual environment ***
(.venv) C:\Users\Lesani\invokeai>pip install varint
Requirement already satisfied: varint in c:\users\lesani\invokeai\.venv\lib\site-packages (1.0.2)

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(.venv) C:\Users\Lesani\invokeai>`

### Additional context

After updating my prvious install using the launcher option 8 "update invokeAI" messed up torch (not updating with cuda torch, but rather CPU torch, which led to invoke not being able to launch anymore), I did a fresh invoke isntall using the automatic installer, overwriting my prvious isntallation folder.

**Comment by Lesani** [comment]
What fixed the issue for me was, in the developer console:

1. pip uninstall varint
2. pip install --no-cache-dir varint

**Comment by Millu** [comment]
Going to close this with the workaround identified. Will re-open if the issue occurs for others as well
