### ISSUE TITLE
ImportError: cannot import name 'PagingArgumentParser' from 'invokeai.app.services.config' (/Users/m1/invokeai/.venv/lib/python3.11/site-packages/invokeai/app/services/config/__init__.py)[bug]: 

### ISSUE THREAD

**Issue by fdshjkfhdsjkfhdjskhfjkds** [invoke-ai/InvokeAI#5395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

 3.5.1

### What happened?

Textual inversion training
Traceback (most recent call last):
  File "/Users/m1/invokeai/.venv/bin/invokeai-ti", line 5, in <module>
    from invokeai.frontend.training import invokeai_textual_inversion
  File "/Users/m1/invokeai/.venv/lib/python3.11/site-packages/invokeai/frontend/training/__init__.py", line 4, in <module>
    from .textual_inversion import main as invokeai_textual_inversion  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/invokeai/.venv/lib/python3.11/site-packages/invokeai/frontend/training/textual_inversion.py", line 26, in <module>
    from ...backend.training import do_textual_inversion_training, parse_args
  File "/Users/m1/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/training/__init__.py", line 4, in <module>
    from .textual_inversion_training import do_textual_inversion_training, parse_args  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/invokeai/.venv/lib/python3.11/site-packages/invokeai/backend/training/textual_inversion_training.py", line 43, in <module>
    from invokeai.app.services.config import InvokeAIAppConfig, PagingArgumentParser
ImportError: cannot import name 'PagingArgumentParser' from 'invokeai.app.services.config' (/Users/m1/invokeai/.venv/lib/python3.11/site-packages/invokeai/app/services/config/__init__.py)
(base) m1@m1s-MacBook-Air ~ % 

### Additional context

generator works good but issue with training. i download today and run the update command to no avail

**Comment by Millu** [comment]
There's a known issue with training that is being addressed in the [invoke-training](https://github.com/invoke-ai/invoke-training) repo

**Comment by lstein** [comment]
There is a pending PR that will fix this issue.
