### ISSUE TITLE
[bug]: nvokeai-model-install.py  don't work to add civitai file give error

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#5577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

15

### What version did you experience this issue on?

v3.6.2

### What happened?

When I try to download and install a model with a script, it gives this error
2024-01-25 17:47:47.679798: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-25 17:47:47.679859: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-25 17:47:47.681463: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-25 17:47:48.909850: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-01-25 17:47:51,482]::[InvokeAI]::INFO --> Scanning /content/db/models for new models
[2024-01-25 17:47:51,560]::[InvokeAI]::INFO --> Scanned 9 files and directories, imported 0 models
[2024-01-25 17:47:51,621]::[InvokeAI]::INFO --> Installing https://civitai.com/api/download/models/120702 [1/1]
An exception has occurred: expected string or bytes-like object Details:
Traceback (most recent call last):
  File "/content/InvokeAI/invokeai/frontend/install/model_install.py", line 817, in main
    select_and_download_models(opt)
  File "/content/InvokeAI/invokeai/frontend/install/model_install.py", line 715, in select_and_download_models
    installer.install(selections)
  File "/content/InvokeAI/invokeai/backend/install/model_install_backend.py", line 217, in install
    self.heuristic_import(path)
  File "/content/InvokeAI/invokeai/backend/install/model_install_backend.py", line 277, in heuristic_import
    models_installed.update({str(model_path_id_or_url): self._install_url(model_path_id_or_url)})
  File "/content/InvokeAI/invokeai/backend/install/model_install_backend.py", line 329, in _install_url
    location = download_with_resume(url, Path(staging))
  File "/content/InvokeAI/invokeai/backend/util/util.py", line 294, in download_with_resume
    file_name = re.search('filename="(.+)"', resp.headers.get("Content-Disposition")).group(1)
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

Press any key to continue...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/InvokeAI/scripts/invokeai-model-install.py", line 5, in <module>
    main()
  File "/content/InvokeAI/invokeai/frontend/install/model_install.py", line 840, in main
    input("Press any key to continue...")
KeyboardInterrupt

**Comment by hipsterusername** [comment]
I believe this might be a new restriction civit has put on downloads.

**Comment by psychedelicious** [comment]
This script no longer exists. Please refer to https://invoke-ai.github.io/InvokeAI/installation/050_INSTALLING_MODELS for help with installing models.
