### ISSUE TITLE
Starting the InvokeAI browser-based UI. ModuleNotFoundError: No module named 'varint'

### ISSUE THREAD

**Issue by DaytonaBlep** [invoke-ai/InvokeAI#5640]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060

### GPU VRAM

12

### Version number

3.6.2

### Browser

Google Chrome 121.0.6167.87

### What happened

I installed the latest version of InvokeAI today and after the installation was successfully completed, I see this error every time I try to launch the web interface

```
Desired action:
1. Generate images with the browser-based interface
2. Run textual inversion training
3. Merge models (diffusers type only)
4. Download and install models
5. Change InvokeAI startup options
6. Re-run the configure script to fix a broken install or to complete a major upgrade
7. Open the developer console
8. Update InvokeAI
9. Run the InvokeAI image database maintenance script
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\AIStuff\InvokeAI\.venv\Scripts\invokeai-web.exe\__main__.py", line 4, in <module>
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\app\api_app.py", line 43, in <module>
    from .api.dependencies import ApiDependencies
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\app\api\dependencies.py", line 5, in <module>
    from invokeai.app.services.shared.sqlite.sqlite_util import init_db
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\app\services\shared\sqlite\sqlite_util.py", line 8, in <module>
    from invokeai.app.services.shared.sqlite_migrator.migrations.migration_3 import build_migration_3
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\app\services\shared\sqlite_migrator\migrations\migration_3.py", line 7, in <module>
    from .util.migrate_yaml_config_1 import MigrateModelYamlToDb1
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\app\services\shared\sqlite_migrator\migrations\util\migrate_yaml_config_1.py", line 15, in <module>
    from invokeai.app.services.model_records import (
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\app\services\model_records\__init__.py", line 2, in <module>
    from .model_records_base import (  # noqa F401
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\app\services\model_records\model_records_base.py", line 14, in <module>
    from invokeai.backend.model_manager.config import AnyModelConfig, BaseModelType, ModelFormat, ModelType
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\backend\model_manager\__init__.py", line 15, in <module>
    from .probe import ModelProbe
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\backend\model_manager\probe.py", line 25, in <module>
    from .hash import FastModelHash
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\invokeai\backend\model_manager\hash.py", line 16, in <module>
    from imohash import hashfile
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\imohash\__init__.py", line 1, in <module>
    from .imohash import hashfile, hashfileobject
  File "F:\AIStuff\InvokeAI\.venv\Lib\site-packages\imohash\imohash.py", line 10, in <module>
    import varint
ModuleNotFoundError: No module named 'varint'
Desired action:
1. Generate images with the browser-based interface
2. Run textual inversion training
3. Merge models (diffusers type only)
4. Download and install models
5. Change InvokeAI startup options
6. Re-run the configure script to fix a broken install or to complete a major upgrade
7. Open the developer console
8. Update InvokeAI
9. Run the InvokeAI image database maintenance script
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1]
```

### What you expected to happen

I expected to be able to start browser-based interface

### Additional context

I've already installed and reinstalled the varint module, and even used a workaround from one of the old bug reports from here, it doesn't help me

**Comment by psychedelicious** [comment]
Hmm, that's unexpected. I wonder if you've installed `varint` correctly.

Please try this:
- Run the launcher
- Select the option to open developer console
- Run `pip show imohash` - it should show installed. If it doesn't, run `pip install imohash`.
- Run `pip show varint` - it should show installed. If it doesn't, run `pip install varint`.
- Copy the terminal output, so if this doesn't work, you can paste it into this issue.
- Exit the developer console, re-launch the app.

**Comment by DaytonaBlep** [comment]
For some reason varint.py was being installed in the directory where my python is located, I seem to have fixed this by copying the file manually and placing it in the invoke directory where it should have been
