### ISSUE TITLE
[bug]: SDXL models break on `.swap()`

### ISSUE THREAD

**Issue by clsn** [invoke-ai/InvokeAI#5662]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060

### GPU VRAM

12GB

### Version number

3.6.2

### Browser

Firefox 120.0.1

### Python dependencies

accelerate

0.26.1

compel

2.0.2

cuda

12.1

diffusers

0.25.1

numpy

1.26.3

opencv

4.9.0.80

onnx

1.15.0

pillow

10.1.0

python

3.11.6

torch

2.1.2+cu121

torchvision

0.16.2

transformers

4.37.0

xformers

Not Installed

### What happened

Prompt `a cat.swap(dog) playing with a ball in the forest`, works fine with SD1.5-based models (at least ones I've tried), and is given as an example in the Invoke docs.  But trying it out with a SDXL-based model (in this case, juggernaut, but also others I've tried) causes the image generation to crash in the middle, when the swap-over would happen (so basically at the `t_start` value, if one is supplied.)  Error message:
```
 20%|████████████████████████████████                                                                                                                                | 10/50 [00:08<00:35,  1.11it/s]
[2024-02-05 22:22:06,155]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/app/services/invocation_processor/invocation_processor_default.py", line 104, in __process
    outputs = invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/app/invocations/baseinvocation.py", line 669, in invoke_internal
    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/app/invocations/latent.py", line 773, in invoke
    ) = pipeline.latents_from_embeddings(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 381, in latents_from_embeddings
    latents, attention_map_saver = self.generate_latents_from_embeddings(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 454, in generate_latents_from_embeddings
    step_output = self.step(
                  ^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 587, in step
    uc_noise_pred, c_noise_pred = self.invokeai_diffuser.do_unet_step(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 246, in do_unet_step
    ) = self._apply_cross_attention_controlled_conditioning(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 557, in _apply_cross_attention_controlled_conditioning
    conditioned_next_x = self.model_forward_callback(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 664, in _unet_forward
    return self.unet(
           ^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/diffusers/models/unet_2d_condition.py", line 1112, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/diffusers/models/unet_2d_blocks.py", line 1160, in forward
    hidden_states = attn(
                    ^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/diffusers/models/transformer_2d.py", line 392, in forward
    hidden_states = block(
                    ^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/diffusers/models/attention.py", line 366, in forward
    attn_output = self.attn2(
                  ^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/diffusers/models/attention_processor.py", line 527, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusion/cross_attention_control.py", line 609, in __call__
    modified_text_key = attn.to_k(modified_text_embeddings)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/diffusers/models/lora.py", line 430, in forward
    out = super().forward(hidden_states)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXX/invokeai/.venv/lib64/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (77x768 and 2048x640)

[2024-02-05 22:22:06,160]::[InvokeAI]::ERROR --> Error while invoking:
mat1 and mat2 shapes cannot be multiplied (77x768 and 2048x640)
[2024-02-05 22:22:06,161]::[InvokeAI]::WARNING --> Attempted to log statistics for unknown graph 51b12750-dc32-4ea3-ac53-bf50e5268b61: '51b12750-dc32-4ea3-ac53-bf50e5268b61'.
```

### What you expected to happen

I expected prompt2prompt to be supported for XL models too.

### How to reproduce the problem

Prompt `a cat.swap(dog) playing with a ball in the forest` with juggernaut.

**Comment by Millu** [comment]
I believe this a bug with compel - the library Invoke uses to handle prompting

**Comment by Harvester62** [comment]
This syntax will be removed with this PR: https://github.com/invoke-ai/InvokeAI/pull/5925

Perhaps this bug report will be no longer relevant and could be closed.
