### ISSUE TITLE
[bug]: Issues with Invoke 3.7.0 install

### ISSUE THREAD

**Issue by RamonGuthrie** [invoke-ai/InvokeAI#5734]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

4080

### GPU VRAM

16

### Version number

3.7.0

### Browser

Chrome

### Python dependencies

I can't get this far to check

### What happened

Not booting up this is the error

Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Stable_Diffusion\InvokeAI\.venv\Scripts\invokeai-web.exe\__main__.py", line 4, in <module>
  File "D:\Stable_Diffusion\InvokeAI\.venv\Lib\site-packages\invokeai\app\api_app.py", line 43, in <module>
    from .api.dependencies import ApiDependencies
  File "D:\Stable_Diffusion\InvokeAI\.venv\Lib\site-packages\invokeai\app\api\dependencies.py", line 12, in <module>
    from ..services.board_images.board_images_default import BoardImagesService
  File "D:\Stable_Diffusion\InvokeAI\.venv\Lib\site-packages\invokeai\app\services\board_images\board_images_default.py", line 3, in <module>
    from invokeai.app.services.invoker import Invoker
  File "D:\Stable_Diffusion\InvokeAI\.venv\Lib\site-packages\invokeai\app\services\invoker.py", line 9, in <module>
    from .shared.graph import Graph, GraphExecutionState
  File "D:\Stable_Diffusion\InvokeAI\.venv\Lib\site-packages\invokeai\app\services\shared\graph.py", line 12, in <module>
    from invokeai.app.invocations import *  # noqa: F401 F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable_Diffusion\InvokeAI\.venv\Lib\site-packages\invokeai\app\invocations\controlnet_image_processors.py", line 9, in <module>
    from controlnet_aux import (
ModuleNotFoundError: No module named 'controlnet_aux'

### What you expected to happen

It to work

**Comment by Millu** [comment]
The easiest fix is to run the updater, and when asked about force reinstallation of all dependencies, enter "y"

**Comment by hipsterusername** [comment]
Going to resolve this issue until an underlying issue is identified.
