### ISSUE TITLE
[bug]: AMD HIP out of memory when generating more than one image at 1280x720

### ISSUE THREAD

**Issue by APoorDev** [invoke-ai/InvokeAI#5761]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

AMD (ROCm)

### GPU model

Radeon RX 7800 XT

### GPU VRAM

16GB

### Version number

3.7.0

### Browser

Firefox 123

### Python dependencies

{
  "accelerate": "0.27.2",
  "compel": "2.0.2",
  "cuda": null,
  "diffusers": "0.26.3",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.2.0",
  "python": "3.10.12",
  "torch": "2.1.2+rocm5.6",
  "torchvision": "0.16.2+rocm5.6",
  "transformers": "4.37.2",
  "xformers": null
}

### What happened

Set the height to 720 and the width to 1280 on the SD1.5 model and enabled the high resolution fix.  Generating the image the first time works with no issues. Any Image generation afterwards causes the following error.
```
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 6.18 GiB. GPU 0 has a total capacty of 15.98 GiB of which 808.00 MiB is free. Of the allocated memory 8.40 GiB is allocated by PyTorch, and 6.25 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
```
Looking at nvtop after the crash the VRAM sits at 15.9GB of usage with no generation in progress.

### What you expected to happen

The second image generation should not fail.

### How to reproduce the problem

Generate two images with the 1280x720 resolution and High Resolution Fix enabled.

### Additional context

```
[2024-02-20 21:59:54,553]::[InvokeAI]::INFO --> Loading model /home/user/invokeai/models/sd-1/main/stable-diffusion-v1-5, type sd-1:main:tokenizer
[2024-02-20 21:59:54,608]::[InvokeAI]::INFO --> Loading model /home/user/invokeai/models/sd-1/main/stable-diffusion-v1-5, type sd-1:main:text_encoder
[2024-02-20 21:59:55,232]::[InvokeAI]::INFO --> Loading model /home/user/invokeai/models/sd-1/main/stable-diffusion-v1-5, type sd-1:main:unet
[2024-02-20 21:59:56,460]::[InvokeAI]::INFO --> Loading model /home/user/invokeai/models/sd-1/main/stable-diffusion-v1-5, type sd-1:main:scheduler
100%|████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 10.21it/s]
[2024-02-20 22:00:01,487]::[InvokeAI]::INFO --> Loading model /home/user/invokeai/models/sd-1/main/stable-diffusion-v1-5, type sd-1:main:vae
Upscaling: 100%|███████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.97it/s]
100%|████████████████████████████████████████████████████████████████| 38/38 [00:25<00:00,  1.50it/s]
[2024-02-20 22:00:30,430]::[InvokeAI]::INFO --> Graph stats: 6962bbcb-cf5e-4a13-8daf-6beb3db605bf
                          Node   Calls   Seconds  VRAM Used
             main_model_loader       1    0.001s     0.000G
                     clip_skip       1    0.000s     0.000G
                        compel       2    0.676s     0.238G
                         noise       2    0.005s     2.008G
               denoise_latents       2   31.635s    14.577G
                           l2i       3    1.692s     5.666G
                        esrgan       1    1.502s     3.686G
                    img_resize       1    0.151s     2.144G
                           i2l       1    0.168s     3.116G
                 core_metadata       1    0.000s     2.144G
              linear_ui_output       1    0.042s     2.144G
TOTAL GRAPH EXECUTION TIME:  35.871s
TOTAL GRAPH WALL TIME:  35.880s
RAM used by InvokeAI process: 2.75G (+0.577G)
RAM used to load models: 1.99G
VRAM in use: 2.144G
RAM cache statistics:
   Model cache hits: 7
   Model cache misses: 5
   Models cached: 5
   Models cleared from cache: 0
   Cache high water mark: 1.99/30.00G

[2024-02-20 22:00:30,562]::[uvicorn.access]::INFO --> 127.0.0.1:54390 - "GET /api/v1/images/i/b4c2124b-61f4-4705-8d25-e9b6884f4657.png HTTP/1.1" 200
  0%|                                                                         | 0/50 [00:00<?, ?it/s][2024-02-20 22:00:30,602]::[uvicorn.access]::INFO --> 127.0.0.1:54390 - "GET /api/v1/images/i/b4c2124b-61f4-4705-8d25-e9b6884f4657.png/full HTTP/1.1" 200
[2024-02-20 22:00:30,771]::[uvicorn.access]::INFO --> 127.0.0.1:54390 - "GET /api/v1/images/i/b4c2124b-61f4-4705-8d25-e9b6884f4657.png/thumbnail HTTP/1.1" 200
  4%|██▌                                                              | 2/50 [00:00<00:04, 10.68it/s][2024-02-20 22:00:30,958]::[uvicorn.access]::INFO --> 127.0.0.1:54390 - "GET /api/v1/images/i/b4c2124b-61f4-4705-8d25-e9b6884f4657.png/metadata HTTP/1.1" 200
100%|████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 10.26it/s]
Upscaling: 100%|███████████████████████████████████████████████████████| 2/2 [00:00<00:00,  4.20it/s]
  0%|                                                                         | 0/38 [00:00<?, ?it/s]
[2024-02-20 22:00:38,105]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/services/invocation_processor/invocation_processor_default.py", line 134, in __process
    outputs = invocation.invoke_internal(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/invocations/baseinvocation.py", line 669, in invoke_internal
    output = self.invoke(context)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/invocations/latent.py", line 773, in invoke
    ) = pipeline.latents_from_embeddings(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 381, in latents_from_embeddings
    latents, attention_map_saver = self.generate_latents_from_embeddings(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 454, in generate_latents_from_embeddings
    step_output = self.step(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 587, in step
    uc_noise_pred, c_noise_pred = self.invokeai_diffuser.do_unet_step(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 267, in do_unet_step
    ) = self._apply_standard_conditioning(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 380, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 664, in _unet_forward
    return self.unet(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1186, in forward
    sample = upsample_block(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 2423, in forward
    hidden_states = attn(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py", line 391, in forward
    hidden_states = block(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 335, in forward
    attn_output = self.attn1(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 512, in forward
    return self.processor(
  File "/home/user/invokeai/.venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 1244, in __call__
    hidden_states = F.scaled_dot_product_attention(
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 6.18 GiB. GPU 0 has a total capacty of 15.98 GiB of which 808.00 MiB is free. Of the allocated memory 8.40 GiB is allocated by PyTorch, and 6.25 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF

[2024-02-20 22:00:38,105]::[InvokeAI]::ERROR --> Error while invoking:
HIP out of memory. Tried to allocate 6.18 GiB. GPU 0 has a total capacty of 15.98 GiB of which 808.00 MiB is free. Of the allocated memory 8.40 GiB is allocated by PyTorch, and 6.25 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
[2024-02-20 22:00:38,106]::[InvokeAI]::INFO --> Graph stats: 503e2756-03f4-4a1d-b965-217095919a57
                          Node   Calls   Seconds  VRAM Used
             main_model_loader       1    0.001s     2.144G
                     clip_skip       1    0.000s     2.144G
                        compel       2    0.000s     2.144G
                         noise       2    0.001s     2.144G
               denoise_latents       2    5.406s    14.528G
                           l2i       1    0.255s     3.145G
                        esrgan       1    1.531s     3.685G
                    img_resize       1    0.170s     2.144G
                           i2l       1    0.156s     3.117G
TOTAL GRAPH EXECUTION TIME:   7.522s
TOTAL GRAPH WALL TIME:   7.528s
RAM used by InvokeAI process: 2.76G (+0.017G)
RAM used to load models: 1.76G
VRAM in use: 2.009G
RAM cache statistics:
   Model cache hits: 6
   Model cache misses: 0
   Models cached: 5
   Models cleared from cache: 0
   Cache high water mark: 1.99/30.00G
```

Thanks for any help!

**Comment by hipsterusername** [comment]
This is an actual Out of Memory issue. I'd suggest looking at your usage of the Cache settings, as you may have too high a cache set.

**Comment by APoorDev** [comment]
I was using 4GB for the VRAM cache and 30GB for RAM cache for the results above. 

I just tested it with lowered cache settings (1GB VRAM, 10GB RAM) and it seems to crash immediately on the first image generation.
```
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 6.18 GiB. GPU 0 has a total capacty of 15.98 GiB of which 1.17 GiB is free. Of the allocated memory 8.16 GiB is allocated by PyTorch, and 6.10 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
```
Failing at the same point but now on the first generation.
```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 10.25it/s]
[2024-02-21 16:49:19,250]::[InvokeAI]::INFO --> Loading model /home/user/invokeai/models/sd-1/main/stable-diffusion-v1-5, type sd-1:main:vae
Upscaling: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.06it/s]
  0%|                                                                                                                                                                    | 0/38 [00:00<?, ?it/s]
  ```
  I also tried it with various other variations (1GB VRAM 4GB RAM, 0.25GB VRAM 10GB RAM, 0VRAM 8GB RAM) and got the same results.
  
  With 8GB VRAM and 40GB RAM I get the same results as my original comment. First image generation works fine but any ran after fail. 
  
  Apologies if these are not the correct cache settings you were talking about.

**Comment by Arthur-Stuhl** [comment]
I have an RX 7900 XTX and while it did take a few more attempts then just generating only 2 images (Because of my larger VRAM size) I did manage to replicate this same issue. But like @APoorDev said changing the cache size in the TUI did not help.

**Comment by hipsterusername** [comment]
Ok - Fascinating. The cache is doing…. Nothing, maybe?

Frankly, this is way more VRAM usage than you would normally see for an SD1.5 generation. It makes me wonder whether there are some ROCm quirks around memory management and clearing that aren’t being handled by torch.

Will cc @lstein here to see if he has any troubleshooting ideas to get more info from the system to triage
