### ISSUE TITLE
[bug]: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by m1-x3m** [invoke-ai/InvokeAI#5773]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4060

### GPU VRAM

8GB

### Version number

2.3.5

### Browser

Brave 1.62.165

### What happened

when invokeai.bat launched, I wanted to change the Generation Device from CPU to GPu. but when I launch it again  it shows the following error: 
Starting the InvokeAI browser-based UI..
[2024-02-21 22:57:15,411]::[InvokeAI]::INFO --> Patchmatch initialized
Traceback (most recent call last):
  File "C:\Users\m1-x3\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\m1-x3\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\m1-x3\invokeai\.venv\Scripts\invokeai-web.exe\__main__.py", line 4, in <module>
    from invokeai.app.api_app import invoke_api
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\invokeai\app\api_app.py", line 43, in <module>
    from .api.dependencies import ApiDependencies
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 12, in <module>
    from ..services.board_images.board_images_default import BoardImagesService
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\invokeai\app\services\board_images\board_images_default.py", line 3, in <module>
    from invokeai.app.services.invoker import Invoker
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\invokeai\app\services\invoker.py", line 9, in <module>
    from .shared.graph import Graph, GraphExecutionState
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\invokeai\app\services\shared\graph.py", line 12, in <module>
    from invokeai.app.invocations import *  # noqa: F401 F403
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 78, in <module>
    DEFAULT_PRECISION = choose_precision(choose_torch_device())
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\invokeai\backend\util\devices.py", line 35, in choose_precision
    device_name = torch.cuda.get_device_name(device)
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\torch\cuda\__init__.py", line 419, in get_device_name
    return get_device_properties(device).name
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\torch\cuda\__init__.py", line 449, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "C:\Users\m1-x3\invokeai\.venv\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

### What you expected to happen

I expected to launch web GUI with CUDA

**Comment by psychedelicious** [comment]
Hi, you'll need to download the installer and run it again, selecting GPU.

Note: You mentioned you are on v2.3.5. This is a very old version of the app.

**Comment by m1-x3m** [comment]
> Hi, you'll need to download the installer and run it again, selecting GPU.
> 
> Note: You mentioned you are on v2.3.5. This is a very old version of the app.

Thank you very much! It worked
As for the version: my bad, it’s 3.7
