### ISSUE TITLE
[bug]: Failed to load sdxl:main:unet model

### ISSUE THREAD

**Issue by TwistedGlass2** [invoke-ai/InvokeAI#5851]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

geforce rtx 3070

### GPU VRAM

8 gb

### Version number

3.7.0

### Browser

chrome

### Python dependencies

[2024-03-01 11:32:30,278]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\ADMIN\invokeai\.venv\lib\site-packages\invokeai\app\services\invocation_processor\invocation_processor_default.py", line 134, in __process
    outputs = invocation.invoke_internal(
  File "C:\Users\ADMIN\invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 669, in invoke_internal
    output = self.invoke(context)
  File "C:\Users\ADMIN\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ADMIN\invokeai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 716, in invoke
    unet_info = context.services.model_manager.get_model(
  File "C:\Users\ADMIN\invokeai\.venv\lib\site-packages\invokeai\app\services\model_manager\model_manager_default.py", line 112, in get_model
    model_info = self.mgr.get_model(
  File "C:\Users\ADMIN\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 497, in get_model
    model_context = self.cache.get_model(
  File "C:\Users\ADMIN\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 241, in get_model
    model = model_info.get_model(child_type=submodel, torch_dtype=self.precision)
  File "C:\Users\ADMIN\invokeai\.venv\lib\site-packages\invokeai\backend\model_management\models\base.py", line 308, in get_model
    raise Exception(f"Failed to load {self.base_model}:{self.model_type}:{child_type} model")
Exception: Failed to load sdxl:main:unet model

[2024-03-01 11:32:30,279]::[InvokeAI]::ERROR --> Error while invoking:
Failed to load sdxl:main:unet model

### What happened

Downloaded it with some issues with python and after retrying a couple steps web browser invoke started running, but had a server exception because of Failed to load sdxl:main:unet model. Not sure what this means or how to fix it to be completely honest. I've tried the built-in configure script where it says triton is missing every time, not sure if that has something to do with it.

### What you expected to happen

boooom picture

### How to reproduce the problem

Download using 3.7.0 file from github and install with python 3.10. Run the invoke.bat and have the web browser say server exception.

### Discord username

obamnaaaaa

**Comment by ebr** [comment]
Did you add any models? Does the model show up in your models dropdown?
