### ISSUE TITLE
[bug]: run or ckpt model to diffusers format give this error vr 4.0rc1

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#5934]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU VRAM

15

### Version number

4.0rc1

### Browser

Opera GX Browser

### What happened

run or ckpt model to diffusers format give this error

### What you expected to happen

2024-03-12 12:53:33,944]::[ModelLoadService]::INFO --> Converting /content/db/models/sd-1/main/meinamix_v11-inpainting.safetensors to diffusers format
[2024-03-12 12:53:35,768]::[InvokeAI]::ERROR --> Error while invoking session af38c865-7806-447f-8c49-fe0de2748f03, invocation efa0546f-1a63-45a4-a76f-0f66f7a5e4fb (compel):
Incorrect path_or_model_id: '/root/invokeai/models/core/convert/clip-vit-large-patch14'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
[2024-03-12 12:53:35,769]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/root/invokeai/models/core/convert/clip-vit-large-patch14'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/InvokeAI/invokeai/app/services/session_processor/session_processor_default.py", line 160, in _process
    outputs = self._invocation.invoke_internal(
  File "/content/InvokeAI/invokeai/app/invocations/baseinvocation.py", line 281, in invoke_internal
    output = self.invoke(context)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/InvokeAI/invokeai/app/invocations/compel.py", line 57, in invoke
    tokenizer_info = context.models.load(self.clip.tokenizer)
  File "/content/InvokeAI/invokeai/app/services/shared/invocation_context.py", line 339, in load
    return self._services.model_manager.load.load_model(model, _submodel_type, self._data)
  File "/content/InvokeAI/invokeai/app/services/model_load/model_load_default.py", line 79, in load_model
    ).load_model(model_config, submodel_type)
  File "/content/InvokeAI/invokeai/backend/model_manager/load/load_default.py", line 62, in load_model
    model_path = self._convert_if_needed(model_config, model_path, submodel_type)
  File "/content/InvokeAI/invokeai/backend/model_manager/load/load_default.py", line 82, in _convert_if_needed
    return self._convert_model(config, model_path, cache_path)
  File "/content/InvokeAI/invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py", line 80, in _convert_model
    convert_ckpt_to_diffusers(
  File "/content/InvokeAI/invokeai/backend/model_manager/convert_ckpt_to_diffusers.py", line 1720, in convert_ckpt_to_diffusers
    pipe = download_from_original_stable_diffusion_ckpt(checkpoint_path, **kwargs)
  File "/content/InvokeAI/invokeai/backend/model_manager/convert_ckpt_to_diffusers.py", line 1534, in download_from_original_stable_diffusion_ckpt
    text_model = convert_ldm_clip_checkpoint(
  File "/content/InvokeAI/invokeai/backend/model_manager/convert_ckpt_to_diffusers.py", line 788, in convert_ldm_clip_checkpoint
    config = CLIPTextConfig.from_pretrained(CONVERT_MODEL_ROOT / "clip-vit-large-patch14")
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/configuration_clip.py", line 142, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 633, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 688, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/root/invokeai/models/core/convert/clip-vit-large-patch14'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

[2024-03-12 12:53:35,974]::[InvokeAI]::INFO --> Graph stats: af38c865-7806-447f-8c49-fe0de2748f03
                          Node   Calls   Seconds  VRAM Used
             main_model_loader       1    0.002s     0.000G
                     clip_skip       1    0.000s     0.000G
                        compel       1    1.825s     0.000G
TOTAL GRAPH EXECUTION TIME:   1.828s
TOTAL GRAPH WALL TIME:   1.838s
RAM used by InvokeAI process: 8.02G (+3.773G)
RAM used to load models: 0.00G
RAM cache statistics:
   Model cache hits: 0
   Model cache misses: 0
   Models cached: 0
   Models cleared from cache: 0
   Cache high water mark: 0.00/0.00G

**Comment by lstein** [comment]
What is the full path to your models directory? I need to know whether the path is wrong or the file is missing…

**Comment by wolfkingal2000** [comment]
> What is the full path to your models directory? I need to know whether the path is wrong or the file is missing…

%cd /content/InvokeAI/
!python /content/InvokeAI/scripts/invokeai-model-install.py --root_dir /content/db --yes --add  this use full

**Comment by lstein** [comment]
Are you using Google Collab? Can you tell me what the root directory is? Is it `/content/db`, or `/root/invokeai/` ? This is the directory that contains `invokeai.yaml`.

Not sure what you are trying to do here:
```
python /content/InvokeAI/scripts/invokeai-model-install.py --root_dir /content/db --yes --add this use full
```

**Comment by wolfkingal2000** [comment]
> Are you using Google Collab? Can you tell me what the root directory is? Is it `/content/db`, or `/root/invokeai/` ? This is the directory that contains `invokeai.yaml`.
> 
> Not sure what you are trying to do here:
> ```
> python /content/InvokeAI/scripts/invokeai-model-install.py --root_dir /content/db --yes --add this use full
> ```
> 
> What you put after `--add` is the URL, path or repo_id of a model you want to install. "this use full" isn't either of these.


Yes i use colab and  `invokeai.yaml` in `/content/db` directory
