### ISSUE TITLE
[bug]: I updated to 4.0 but everything is broken

### ISSUE THREAD

**Issue by ninjasaid2k** [invoke-ai/InvokeAI#6108]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4070

### GPU VRAM

8GB

### Version number

4.0

### Browser

Windows Edge

### Python dependencies

  did not happen during image generation.

### What happened

I updated to 4.0 update. I chose to not update dependencies because it said it was not necessary.

### What you expected to happen

I expected for the 1-10 commands to be working normally.

### How to reproduce the problem

Update to 4.0

### Additional context

```

C:\Users\****\invokeai>u/echo off
'u' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\****\invokeai>PUSHD "C:\Users\****\invokeai\"

C:\Users\****\invokeai>setlocal

C:\Users\****\invokeai>call .venv\Scripts\activate.bat
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
[2024-04-02 14:09:24,802]::[InvokeAI]::INFO --> Loading node pack invoke_bria_rmbg
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\****\invokeai\.venv\Scripts\invokeai-web.exe\__main__.py", line 7, in <module>
  File "C:\Users\****\invokeai\.venv\Lib\site-packages\invokeai\app\run_app.py", line 10, in run_app
    from invokeai.app.api_app import invoke_api
  File "C:\Users\****\invokeai\.venv\Lib\site-packages\invokeai\app\api_app.py", line 28, in <module>
    from invokeai.app.invocations.model import ModelIdentifierField
  File "C:\Users\****\invokeai\.venv\Lib\site-packages\invokeai\app\invocations\__init__.py", line 24, in <module>
    spec.loader.exec_module(module)
  File "C:\Users\****\invokeai\nodes\__init__.py", line 46, in <module>
    spec.loader.exec_module(module)
  File "C:\Users\****\invokeai\nodes\invoke_bria_rmbg\__init__.py", line 1, in <module>
    from .node import *
  File "C:\Users\****\invokeai\nodes\invoke_bria_rmbg\node\__init__.py", line 1, in <module>
    from invokeai.app.invocations.baseinvocation import (
ImportError: cannot import name 'InputField' from 'invokeai.app.invocations.baseinvocation' (C:\Users\****\invokeai\.venv\Lib\site-packages\invokeai\app\invocations\baseinvocation.py)
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 2
Starting the InvokeAI command-line..
C:\Users\****\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\****\\invokeai\\.venv\\Scripts\\invokeai.exe': [Errno 2] No such file or directory
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 3
Starting textual inversion training..
C:\Users\****\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\****\\invokeai\\.venv\\Scripts\\invokeai-ti.exe': [Errno 2] No such file or directory
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 4
Starting model merging script..
C:\Users\****\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\****\\invokeai\\.venv\\Scripts\\invokeai-merge.exe': [Errno 2] No such file or directory
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 5
Running invokeai-model-install...
C:\Users\****\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\****\\invokeai\\.venv\\Scripts\\invokeai-model-install.exe': [Errno 2] No such file or directory
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 6
Running invokeai-configure...
C:\Users\****\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\****\\invokeai\\.venv\\Scripts\\invokeai-configure.exe': [Errno 2] No such file or directory
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 7
Running invokeai-configure...
C:\Users\****\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\****\\invokeai\\.venv\\Scripts\\invokeai-configure.exe': [Errno 2] No such file or directory
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 8
Developer Console
Python command is:
C:\Users\****\invokeai\.venv\Scripts\python.exe
C:\Users\****\AppData\Local\Programs\Python\Python311\python.exe
C:\Users\****\AppData\Local\Microsoft\WindowsApps\python.exe
Python version is:
Python 3.11.7
*************************
You are now in the system shell, with the local InvokeAI Python virtual environment activated,
so that you can troubleshoot this InvokeAI installation as necessary.
*************************
*** Type \exit` to quit this shell and deactivate the Python virtual environment ***`
(.venv) C:\Users\****\invokeai>\exit
'\exit' is not recognized as an internal or external command,
operable program or batch file.

(.venv) C:\Users\****\invokeai>\exit
'\exit' is not recognized as an internal or external command,
operable program or batch file.

(.venv) C:\Users\****\invokeai>exit
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 9
Running invokeai-update...
C:\Users\****\invokeai\.venv\Scripts\python.exe: No module named invokeai.frontend.install.invokeai_update
Desired action:
1. Generate images with the browser-based interface
2. Explore InvokeAI nodes using a command-line interface
3. Run textual inversion training
4. Merge models (diffusers type only)
5. Download and install models
6. Change InvokeAI startup options
7. Re-run the configure script to fix a broken install or to complete a major upgrade
8. Open the developer console
9. Update InvokeAI
10. Command-line help
Q - Quit
Please enter 1-10, Q: [1] 10
Displaying command line help...
C:\Users\****\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\Users\\****\\invokeai\\.venv\\Scripts\\invokeai.exe': [Errno 2] No such file or directory
Press any key to continue . . .
```

### Discord username

s2k

**Comment by psychedelicious** [comment]
Please download the installer from https://github.com/invoke-ai/InvokeAI/releases/tag/v4.0.1 and use that to update.

**Comment by ninjasaid2k** [comment]
> Please download the installer from https://github.com/invoke-ai/InvokeAI/releases/tag/v4.0.1 and use that to update.

is there a way to update it without starting everything from scratch?

**Comment by psychedelicious** [comment]
@ninjasaid2k The installer only reinstalls the application. Your user data is untouched.

**Comment by angeloshredder** [comment]
same error:
[2024-04-03 00:15:45,759]::[InvokeAI]::INFO --> Patchmatch initialized
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\invokeai\.venv\Scripts\invokeai-web.exe\__main__.py", line 7, in <module>
    sys.exit(run_app())
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\run_app.py", line 10, in run_app
    from invokeai.app.api_app import invoke_api
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\api_app.py", line 34, in <module>
    from .api.dependencies import ApiDependencies
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 20, in <module>
    from ..services.download import DownloadQueueService
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\download\__init__.py", line 4, in <module>
    from .download_default import DownloadQueueService, TqdmProgress
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\download\download_default.py", line 18, in <module>
    from invokeai.app.services.events.events_base import EventServiceBase
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\events\__init__.py", line 1, in <module>
    from .events_base import EventServiceBase  # noqa F401
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\events\events_base.py", line 7, in <module>
    from invokeai.app.services.session_queue.session_queue_common import (
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\session_queue\session_queue_common.py", line 10, in <module>
    from invokeai.app.services.shared.graph import Graph, GraphExecutionState, NodeNotFoundError
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\shared\graph.py", line 18, in <module>
    from invokeai.app.invocations import *  # noqa: F401 F403
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 51, in <module>
    from invokeai.app.invocations.t2i_adapter import T2IAdapterField
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\invocations\t2i_adapter.py", line 11, in <module>
    from invokeai.app.invocations.controlnet_image_processors import CONTROLNET_RESIZE_VALUES
ModuleNotFoundError: No module named 'invokeai.app.invocations.controlnet_image_processors'
Desired action:
1. Generate images with the browser-based interface
2. Open the developer console
3. Run the InvokeAI image database maintenance script
4. Command-line help
Q - Quit

**Comment by angeloshredder** [comment]
Starting the InvokeAI browser-based UI..
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\invokeai\.venv\Scripts\invokeai-web.exe\__main__.py", line 7, in <module>
    sys.exit(run_app())
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\run_app.py", line 10, in run_app
    from invokeai.app.api_app import invoke_api
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\api_app.py", line 34, in <module>
    from .api.dependencies import ApiDependencies
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 20, in <module>
    from ..services.download import DownloadQueueService
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\download\__init__.py", line 4, in <module>
    from .download_default import DownloadQueueService, TqdmProgress
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\download\download_default.py", line 18, in <module>
    from invokeai.app.services.events.events_base import EventServiceBase
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\events\__init__.py", line 1, in <module>
    from .events_base import EventServiceBase  # noqa F401
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\events\events_base.py", line 7, in <module>
    from invokeai.app.services.session_queue.session_queue_common import (
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\session_queue\session_queue_common.py", line 10, in <module>
    from invokeai.app.services.shared.graph import Graph, GraphExecutionState, NodeNotFoundError
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\services\shared\graph.py", line 18, in <module>
    from invokeai.app.invocations import *  # noqa: F401 F403
  File "C:\Users\USER\invokeai\.venv\lib\site-packages\invokeai\app\invocations\controlnet_image_processors.py", line 9, in <module>
    from controlnet_aux import (
ModuleNotFoundError: No module named 'controlnet_aux'
Desired action:
1. Generate images with the browser-based interface
2. Open the developer console
3. Run the InvokeAI image database maintenance script
4. Command-line help
Q - Quit

**Comment by angeloshredder** [comment]
when i launched the script for the first time, it doesn't reconize all my costum nodes, i backed-up them them deleted all folders in costom nodes , after that i restarted again, but now it seems that it has problem with app\invocations\

**Comment by psychedelicious** [comment]
@angeloshredder Please create a separate issue for your problem.

**Comment by angeloshredder** [comment]
> @angeloshredder Please create a separate issue for your problem if the solution suggested above does not fix it.

thanks, ok done
