### ISSUE TITLE
[bug]: Upgrading to Invoke 4.0.1 Doesn't work

### ISSUE THREAD

**Issue by fcoreveles** [invoke-ai/InvokeAI#6129]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

Geforce RTX 3060

### Version number

4.0.1

### Browser

Google Chrome

### What happened

When I try to start Invoke AI with Invoke.bat appears this:
Starting the InvokeAI browser-based UI..
[2024-04-03 14:05:46,835]::[InvokeAI]::INFO --> Patchmatch initialized
[2024-04-03 14:05:47,945]::[InvokeAI]::INFO --> Using torch device: NVIDIA GeForce RTX 3060
[2024-04-03 14:05:50,339]::[InvokeAI]::INFO --> cuDNN version: 8801
[2024-04-03 14:05:50,355]::[uvicorn.error]::INFO --> Started server process [15600]
[2024-04-03 14:05:50,355]::[uvicorn.error]::INFO --> Waiting for application startup.
[2024-04-03 14:05:50,355]::[InvokeAI]::INFO --> InvokeAI version 4.0.1
[2024-04-03 14:05:50,355]::[InvokeAI]::INFO --> Root directory = D:\Invoke
[2024-04-03 14:05:50,370]::[InvokeAI]::INFO --> Initializing database at D:\Invoke\databases\invokeai.db
[2024-04-03 14:05:50,401]::[uvicorn.error]::ERROR --> Traceback (most recent call last):
  File "D:\Invoke\.venv\lib\site-packages\starlette\routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\GRISSLY\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\Invoke\.venv\lib\site-packages\invokeai\app\api_app.py", line 73, in lifespan
    ApiDependencies.initialize(config=app_config, event_handler_id=event_handler_id, logger=logger)
  File "D:\Invoke\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 137, in initialize
    ApiDependencies.invoker = Invoker(services)
  File "D:\Invoke\.venv\lib\site-packages\invokeai\app\services\invoker.py", line 14, in __init__
    self._start()
  File "D:\Invoke\.venv\lib\site-packages\invokeai\app\services\invoker.py", line 31, in _start
    self.__start_service(getattr(self.services, service))
  File "D:\Invoke\.venv\lib\site-packages\invokeai\app\services\invoker.py", line 20, in __start_service
    start_op(self)
  File "D:\Invoke\.venv\lib\site-packages\invokeai\app\services\model_manager\model_manager_default.py", line 56, in start
    service.start(invoker)
  File "D:\Invoke\.venv\lib\site-packages\invokeai\app\services\model_install\model_install_default.py", line 129, in start
    self._migrate_yaml()
  File "D:\Invoke\.venv\lib\site-packages\invokeai\app\services\model_install\model_install_default.py", line 326, in _migrate_yaml
    legacy_models_yaml = yaml.safe_load(legacy_models_yaml_path.read_text())
  File "C:\Users\GRISSLY\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Users\GRISSLY\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 14835: character maps to <undefined>

[2024-04-03 14:05:50,401]::[uvicorn.error]::ERROR --> Application startup failed. Exiting.
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<FastAPIEventService.__dispatch_from_queue() running at D:\Invoke\.venv\lib\site-packages\invokeai\app\api\events.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>> 

### What you expected to happen

That the Invoke interface begins

### How to reproduce the problem

Start the app and pick option 1

### Additional context

I updated the Invoke to most recent version

**Comment by shmuelie** [comment]
I'm still running into this on 4.2.3

**Comment by psychedelicious** [comment]
@shmuelie please create a new issue detailing your specific problem.
