### ISSUE TITLE
I've been trying to install this for six months. Never succeeded. Will it ever work?

### ISSUE THREAD

**Issue by Thorev** [invoke-ai/InvokeAI#6222]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

rtx3070

### GPU VRAM

8Gb

### Version number

all of them

### Browser

Firefox 124.0.2

### What happened

Starting the InvokeAI browser-based UI..
Traceback (most recent call last):
  File "C:\Users\tesmo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tesmo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Ai\InvokeAI\.venv\Scripts\invokeai-web.exe\__main__.py", line 7, in <module>
    sys.exit(run_app())
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\run_app.py", line 10, in run_app
    from invokeai.app.api_app import invoke_api
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\api_app.py", line 34, in <module>
    from .api.dependencies import ApiDependencies
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\api\dependencies.py", line 20, in <module>
    from ..services.download import DownloadQueueService
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\services\download\__init__.py", line 4, in <module>
    from .download_default import DownloadQueueService, TqdmProgress
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\services\download\download_default.py", line 18, in <module>
    from invokeai.app.services.events.events_base import EventServiceBase
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\services\events\__init__.py", line 1, in <module>
    from .events_base import EventServiceBase  # noqa F401
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\services\events\events_base.py", line 7, in <module>
    from invokeai.app.services.session_queue.session_queue_common import (
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\services\session_queue\session_queue_common.py", line 10, in <module>
    from invokeai.app.services.shared.graph import Graph, GraphExecutionState, NodeNotFoundError
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\services\shared\graph.py", line 18, in <module>
    from invokeai.app.invocations import *  # noqa: F401 F403
  File "D:\Ai\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\controlnet_image_processors.py", line 9, in <module>
    from controlnet_aux import (
ModuleNotFoundError: No module named 'controlnet_aux'

### What you expected to happen

I expected it to work

### How to reproduce the problem

Install and run

**Comment by mirh** [comment]
Can you try with python 3.11 and/or with a different internet connection?

**Comment by hipsterusername** [comment]
This error specifically means you have an issue in your pip cache - use `pip install controlnet_aux --force-reinstall --no-cache-dir` in the "developer console". Then reinstall the application using the installer.

**Comment by ebr** [comment]
What is the `InvokeAI.venv` directory? Did you create that yourself?

Delete it completely and install using the official installer.

**Comment by jungleBadger** [comment]
I have a very similar system (RTX 3070), and in my first install, I couldn't get PyTorch to recognize it.

After I tried Python 3.11, I was able to run it and use my GPU.

Please give it a try. Let me know if you still need help then. Once I get home, I can share the exact commands I used to install and run everything.

**Comment by gogurtenjoyer** [comment]
Another simple solution is to completely clear your pip cache (for some reason, controlnet_aux seems to always be the problem these days, but clearing the whole cache doesn't require you to be in any particular venv):

`pip cache purge`

Afterwards, install InvokeAI from a freshly-unzipped installer.

**Comment by Thorev** [comment]
Ok, I tried reinstalling Python, Visual Basic, InvokeAI, rebooted. Did not help. Then I did it all again and it worked!  Thank you all! )
