### ISSUE TITLE
[bug]: 'fromisoformat: argument must be str'

### ISSUE THREAD

**Issue by JHubi1** [invoke-ai/InvokeAI#6286]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3060Ti

### GPU VRAM

8GB

### Version number

v4.2.0a3

### Browser

Chrome 124.0.6367.63

### Python dependencies

{
  "accelerate": "0.29.2",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.3.0",
  "python": "3.11.7",
  "torch": "2.2.2+cu121",
  "torchvision": "0.17.2",
  "transformers": "4.39.3",
  "xformers": null
}

### What happened

I tried to generate an image with SDXL. It kinda worked, the first stage was done, and I could see the image generating in that blurred view, but at the moment the refiner model was supposed to do its job, this error showed in console:

<details>
  <summary>Logs XL</summary>

```
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:29<00:00,  1.72it/s]
[2024-04-29 14:28:05,819]::[InvokeAI]::ERROR --> Problem saving image record and file: fromisoformat: argument must be str
[2024-04-29 14:28:05,877]::[InvokeAI]::ERROR --> Error while invoking session eff91e87-1862-48ec-9aaf-6b009347138a, invocation 1ec9c73e-7a85-410b-94e2-9ced37def828 (l2i):
fromisoformat: argument must be str
[2024-04-29 14:28:05,877]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 185, in _process
    outputs = self._invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 289, in invoke_internal
    return self.invoke(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\invocations\latent.py", line 1087, in invoke
    image_dto = context.images.save(image=image)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 194, in save
    return self._services.images.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\images\images_default.py", line 92, in create
    raise e
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\images\images_default.py", line 60, in create
    self.__invoker.services.image_records.save(
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\image_records\image_records_sqlite.py", line 378, in save
    created_at = datetime.fromisoformat(self._cursor.fetchone()[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str

[2024-04-29 14:28:05,878]::[InvokeAI]::INFO --> Graph stats: eff91e87-1862-48ec-9aaf-6b009347138a
                          Node   Calls   Seconds  VRAM Used
             sdxl_model_loader       1    0.001s     0.000G
            sdxl_compel_prompt       2    6.029s     1.310G
                       collect       2    0.000s     0.008G
                         noise       1    0.009s     0.008G
               denoise_latents       1   46.350s     5.210G
                 core_metadata       1    0.001s     0.009G
                           l2i       1    4.241s     4.055G
TOTAL GRAPH EXECUTION TIME:  56.630s
TOTAL GRAPH WALL TIME:  56.634s
RAM used by InvokeAI process: 8.52G (+7.843G)
RAM used to load models: 7.98G
VRAM in use: 0.009G
RAM cache statistics:
   Model cache hits: 11
   Model cache misses: 7
   Models cached: 7
   Models cleared from cache: 0
   Cache high water mark: 6.46/7.50G

```
</details>

-----

Then I tried generating a v1.5 image. Again, this worked. The image was generated in the background (in that blurry view), but when it was supposed to be finished, this error was shown:

<details>
  <summary>Logs v1.5</summary>

```
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:05<00:00,  9.62it/s]
[2024-04-29 14:36:13,991]::[InvokeAI]::ERROR --> Problem saving image record and file: fromisoformat: argument must be str
[2024-04-29 14:36:13,992]::[InvokeAI]::ERROR --> Error while invoking session dc63f541-151a-459a-b62c-aa8142fcd8db, invocation c172485e-229b-4982-acff-23e720249b00 (l2i):
fromisoformat: argument must be str
[2024-04-29 14:36:13,992]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 185, in _process
    outputs = self._invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 289, in invoke_internal
    return self.invoke(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\invocations\latent.py", line 1087, in invoke
    image_dto = context.images.save(image=image)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 194, in save
    return self._services.images.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\images\images_default.py", line 92, in create
    raise e
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\images\images_default.py", line 60, in create
    self.__invoker.services.image_records.save(
  File "E:\InvokeAI\App\.venv\Lib\site-packages\invokeai\app\services\image_records\image_records_sqlite.py", line 378, in save
    created_at = datetime.fromisoformat(self._cursor.fetchone()[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str

[2024-04-29 14:36:13,993]::[InvokeAI]::INFO --> Graph stats: dc63f541-151a-459a-b62c-aa8142fcd8db
                          Node   Calls   Seconds  VRAM Used
             main_model_loader       1    0.000s     0.009G
                     clip_skip       1    0.000s     0.009G
                        compel       2    0.000s     0.009G
                       collect       2    0.000s     0.009G
                         noise       1    0.004s     0.009G
               denoise_latents       1    5.843s     1.788G
                 core_metadata       1    0.001s     0.009G
                           l2i       1    0.353s     1.241G
TOTAL GRAPH EXECUTION TIME:   6.202s
TOTAL GRAPH WALL TIME:   6.206s
RAM used by InvokeAI process: 2.36G (+0.006G)
RAM used to load models: 1.76G
VRAM in use: 0.009G
RAM cache statistics:
   Model cache hits: 3
   Model cache misses: 0
   Models cached: 9
   Models cleared from cache: 0
   Cache high water mark: 6.92/7.50G

```
</details>

### What you expected to happen

I expected an image to be generated

### Additional context

I recently had a few update problems, I maybe installed a wrong dependency, but I'm not sure.

I'd be very thankful if someone could tell me what to do, thank you

**Comment by psychedelicious** [comment]
> I recently had a few update problems

- Can you please elaborate on what problems you had?
- How did you update (specific steps and actions please)?
- Does the error persist after restarting the application?

**Comment by JHubi1** [comment]
The issue persists after a restart, yes.
I then had the not found issues described in v3.6.3 or so, and I did not want to reinstall the application, because I didn't want to lose all my photos. I used the developer terminal to reinstall invoke via pip (with the correct version). Then I did another update to the recent version, right after the first one. I manually had to merge the old database with the newly generated one, because the updater had issues with that.
I believe it's best if I just reinstall and copy the database, output, models and config folder. Thank you

**Comment by psychedelicious** [comment]
Ok, the problem is almost certainly bc you edited the db. 

We have a robust, well-tested db migration system in place. In fact, we've had zero bug reports related to db migrations or integrity except when users edit the db themselves. You can safely run the latest installer over the older install and the app will migrate data if needed. 

However, now that you have made manual changes to the db, I'm not as confident that the migration system will work as it should. 

You mention the "updating having issues with the database". The updater doesn't touch the database. The application itself runs db migrations on first launch. Maybe there was some other problem with the updater.

Moving forward, hopefully you have a backup of the db and the invoke-managed directories from before you edited things. Copy that to a new install location. Download and run the latest installer from the releases, selecting this new install location with the copies. That should get things up and running.

**Comment by psychedelicious** [comment]
Ok, glad you have a backup to work from. If you upload your db backup (before the update), I can examine it to try and understand the issue.

**Comment by JHubi1** [comment]
I really don't want to waste your time. I'm glad to still have my images, not in the UI, but at least as files, that's probably enough. And I have already like kinda set up my new environment.
Again I want to thank you, I had very bad experiences in other repos with people, thanks for hearing me out

**Comment by psychedelicious** [comment]
No worries, happy to help 👍
