### ISSUE TITLE
[bug]: Installation error UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-78: character maps to <undefined>

### ISSUE THREAD

**Issue by rook2pawn** [invoke-ai/InvokeAI#6338]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

3060

### GPU VRAM

12gb

### Version number

4.2.0

### Browser

opera

### Python dependencies

During installation (install.bat) 

```
See https://invoke-ai.github.io/InvokeAI/installation/INSTALL_AUTOMATED/ for more details.

FOR THE BEST USER EXPERIENCE WE SUGGEST MAXIMIZING THIS WINDOW NOW.
Press any key to continue . . .

***** Checking and Updating Python *****
Initializing the installer. This may take a minute - please wait...
Traceback (most recent call last):
  File "E:\InvokeAI-Installer\lib\main.py", line 53, in <module>
    inst.install(**args.__dict__)
  File "E:\InvokeAI-Installer\lib\installer.py", line 143, in install
    messages.welcome(self.available_releases)
  File "E:\InvokeAI-Installer\lib\messages.py", line 54, in welcome
    console.rule()
  File "C:\Users\<name>\AppData\Local\Temp\invokeai-installer-tmpjw1k7r16\Lib\site-packages\rich\console.py", line 1580, in rule
    self.print(rule)
  File "C:\Users\<name>\AppData\Local\Temp\invokeai-installer-tmpjw1k7r16\Lib\site-packages\rich\console.py", line 1673, in print
    with self:
  File "C:\Users\<name>\AppData\Local\Temp\invokeai-installer-tmpjw1k7r16\Lib\site-packages\rich\console.py", line 865, in __exit__
    self._exit_buffer()
  File "C:\Users\<name>\AppData\Local\Temp\invokeai-installer-tmpjw1k7r16\Lib\site-packages\rich\console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "C:\Users\<name>\AppData\Local\Temp\invokeai-installer-tmpjw1k7r16\Lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\<name>\AppData\Local\Temp\invokeai-installer-tmpjw1k7r16\Lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\<name>\AppData\Local\Temp\invokeai-installer-tmpjw1k7r16\Lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\<name>\AppData\Local\Temp\invokeai-installer-tmpjw1k7r16\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\<name>\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-78: character maps to <undefined>
Press any key to continue . . .
```

I'm running Python 3.10.11

### What happened

Installation errored out. Expected installation program to work

### What you expected to happen

Expected install to work

### How to reproduce the problem

install.bat

**Comment by rook2pawn** [comment]
The solution was to not use MINGW terminal (the one that comes with Git for windows) but just use the regular vanilla terminal in windows. There was some issue with drawing a line in unicode on mingw term.
