### ISSUE TITLE
[bug]: Intsall.sh unter Ubuntu 24.04

### ISSUE THREAD

**Issue by jennner** [invoke-ai/InvokeAI#6443]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA GeForce RTX 4070/PCIe/SSE2

### GPU VRAM

12

### Version number

4.2.23

### Browser

chrome, firefox

### What happened

After updating from kubuntu 23.10 to 24.04, install.sh aborts with this message. This happens under Python 3.10, 3.11, 3.12.:
./install.sh 
Initializing the installer. This may take a minute - please wait...
Traceback (most recent call last):
  File "/home/jens/Downloads/InvokeAI-Installer/./lib/main.py", line 50, in <module>
    inst = Installer()
           ^^^^^^^^^^^
  File "/home/jens/Downloads/InvokeAI-Installer/lib/installer.py", line 49, in __init__
    self.bootstrap()
  File "/home/jens/Downloads/InvokeAI-Installer/lib/installer.py", line 81, in bootstrap
    venv_dir = self.mktemp_venv()
               ^^^^^^^^^^^^^^^^^^
  File "/home/jens/Downloads/InvokeAI-Installer/lib/installer.py", line 68, in mktemp_venv
    venv.create(venv_dir.name, with_pip=True)
  File "/usr/lib/python3.11/venv/__init__.py", line 468, in create
    builder.create(env_dir)
  File "/usr/lib/python3.11/venv/__init__.py", line 76, in create
    self._setup_pip(context)
  File "/usr/lib/python3.11/venv/__init__.py", line 358, in _setup_pip
    self._call_new_python(context, '-m', 'ensurepip', '--upgrade',
  File "/usr/lib/python3.11/venv/__init__.py", line 354, in _call_new_python
    subprocess.check_output(args, **kwargs)
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/invokeai-installer-tmpclp6vekd/bin/python3.11', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

### What you expected to happen

Start the installation (this wasn't a problem under Kubuntu 23.10).
The installation carried out under 23.10 (Invoke AI v4.2.2post1 also runs without any problems under Kubuntu 24.04 (both Python 3.10, 3.11, 3.12).
I think the problem is in front of the computer :-(.

**Comment by psychedelicious** [comment]
The installer didn't change between v4.2.2 and v4.2.3 (hasn't changed in a while actually). I suspect you are missing some python related things. I'd suggest using [pyenv](https://github.com/pyenv/pyenv) as a simple way to get a reliable python install.

Also, the installer will refuse to install if it is run with python 3.12. You must have something funky going on if it works with 3.12 - like, it's not actually using the python you think it is using.

**Comment by jennner** [comment]
Good morning, 
maybe misleading (sorry - google translation):
invoke.sh also works after updating to ubuntu 24.04 (with python 3.12)
install.sh doesn't work, the mentioned message on Python 3.10,  3.11,  3.12
Thanks for the reply

**Comment by jennner** [comment]
Hello, 
I'm a little further along now. I have now installed Python 3.11.9 with pyenv and it is running :-). 
insall.sh starts. Abort after GPU selection:

Installing the InvokeAI Application 🎨 
ERROR: Ignored the following versions that require a different python version: 2.2.4.5 Requires-Python <3.11,>=3.9; 2.2.4.6 Requires-Python <3.11,>=3.9; 2.2.4.7 Requires-Python <3.11,>=3.9; 2.2.5 Requires-Python <3.11,>=3.9; 2.3.0 Requires-Python <3.11,>=3.9; 2.3.0a0 Requires-Python <3.11,>=3.9; 2.3.0a1 Requires-Python <3.11,>=3.9; 2.3.0a2 Requires-Python <3.11,>=3.9; 2.3.0a3 Requires-Python <3.11,>=3.9; 2.3.0rc3 Requires-Python <3.11,>=3.9; 2.3.0rc4 Requires-Python <3.11,>=3.9; 2.3.0rc5 Requires-Python <3.11,>=3.9; 2.3.0rc6 Requires-Python <3.11,>=3.9; 2.3.0rc7 Requires-Python <3.11,>=3.9; 2.3.1 Requires-Python <3.11,>=3.9; 2.3.1.post1 Requires-Python <3.11,>=3.9; 2.3.1.post2 Requires-Python <3.11,>=3.9; 2.3.1rc4 Requires-Python <3.11,>=3.9; 2.3.2 Requires-Python <3.11,>=3.9; 2.3.2.post1 Requires-Python <3.11,>=3.9; 2.3.3 Requires-Python <3.11,>=3.9; 2.3.3rc1 Requires-Python <3.11,>=3.9; 2.3.4 Requires-Python <3.11,>=3.9; 2.3.4.post1 Requires-Python <3.11,>=3.9; 2.3.4a0 Requires-Python <3.11,>=3.9; 2.3.4rc1 Requires-Python <3.11,>=3.9; 2.3.5 Requires-Python <3.11,>=3.9; 2.3.5.post1 Requires-Python <3.11,>=3.9; 2.3.5.post2 Requires-Python <3.11,>=3.9; 2.3.5rc1 Requires-Python <3.11,>=3.9; 3.0.0 Requires-Python <3.11,>=3.9; 3.0.1 Requires-Python <3.12,>=3.9; 3.0.1.post1 Requires-Python <3.12,>=3.9; 3.0.1.post2 Requires-Python <3.12,>=3.9; 3.0.1.post3 Requires-Python <3.12,>=3.9; 3.0.1rc1 Requires-Python <3.11,>=3.9; 3.0.1rc2 Requires-Python <3.12,>=3.9; 3.0.2 Requires-Python <3.12,>=3.9; 3.0.2.post1 Requires-Python <3.12,>=3.9; 3.0.2a1 Requires-Python <3.12,>=3.9; 3.0.2rc1 Requires-Python <3.12,>=3.9; 3.1.0 Requires-Python <3.12,>=3.9; 3.1.1 Requires-Python <3.12,>=3.9; 3.1.1rc1 Requires-Python <3.12,>=3.9; 3.2.0 Requires-Python <3.12,>=3.9; 3.3.0 Requires-Python <3.12,>=3.9; 3.3.0.post1 Requires-Python <3.12,>=3.9; 3.3.0.post2 Requires-Python <3.12,>=3.9; 3.3.0.post3 Requires-Python <3.12,>=3.9; 3.4.0 Requires-Python <3.12,>=3.10; 3.4.0.post1 Requires-Python <3.12,>=3.10; 3.4.0.post2 Requires-Python <3.12,>=3.10; 3.4.0rc2 Requires-Python <3.12,>=3.10; 3.4.0rc3 Requires-Python <3.12,>=3.10; 3.4.0rc4 Requires-Python <3.12,>=3.10; 3.5.0 Requires-Python <3.12,>=3.10; 3.5.0rc1 Requires-Python <3.12,>=3.10; 3.5.0rc2 Requires-Python <3.12,>=3.10; 3.5.0rc3 Requires-Python <3.12,>=3.10; 3.5.1 Requires-Python <3.12,>=3.10; 3.6.0 Requires-Python <3.12,>=3.10; 3.6.0rc1 Requires-Python <3.12,>=3.10; 3.6.0rc2 Requires-Python <3.12,>=3.10; 3.6.0rc3 Requires-Python <3.12,>=3.10; 3.6.0rc4 Requires-Python <3.12,>=3.10; 3.6.0rc5 Requires-Python <3.12,>=3.10; 3.6.0rc6 Requires-Python <3.12,>=3.10; 3.6.1 Requires-Python <3.12,>=3.10; 3.6.2 Requires-Python <3.12,>=3.10; 3.6.3 Requires-Python <3.12,>=3.10; 3.6.3rc1 Requires-Python <3.12,>=3.10; 3.7.0 Requires-Python <3.12,>=3.10; 4.0.0 Requires-Python <3.12,>=3.10; 4.0.0rc1 Requires-Python <3.12,>=3.10; 4.0.0rc2 Requires-Python <3.12,>=3.10; 4.0.0rc4 Requires-Python <3.12,>=3.10; 4.0.0rc5 Requires-Python <3.12,>=3.10; 4.0.0rc6 Requires-Python <3.12,>=3.10; 4.0.1 Requires-Python <3.12,>=3.10; 4.0.2 Requires-Python <3.12,>=3.10; 4.0.3 Requires-Python <3.12,>=3.10; 4.0.4 Requires-Python <3.12,>=3.10; 4.1.0 Requires-Python <3.12,>=3.10; 4.2.0 Requires-Python <3.12,>=3.10; 4.2.0a1 Requires-Python <3.12,>=3.10; 4.2.0a2 Requires-Python <3.12,>=3.10; 4.2.0a3 Requires-Python <3.12,>=3.10; 4.2.0a4 Requires-Python <3.12,>=3.10; 4.2.0b1 Requires-Python <3.12,>=3.10; 4.2.0b2 Requires-Python <3.12,>=3.10; 4.2.1 Requires-Python <3.12,>=3.10; 4.2.2 Requires-Python <3.12,>=3.10; 4.2.2.post1 Requires-Python <3.12,>=3.10; 4.2.3 Requires-Python <3.12,>=3.10
ERROR: Could not find a version that satisfies the requirement invokeai[onnx-cuda,xformers] (from versions: none)
ERROR: No matching distribution found for invokeai[onnx-cuda,xformers]
Error: Unexpected exit code: 1
Command line: | /home/jens/invokeai/.venv/bin/pip install --require-virtualenv --force-reinstall --use-pep517 'invokeai[xformers,onnx-cuda]'
Could not install InvokeAI. Please try downloading the latest version of the installer and install again.

Cuda (Ubuntu-Version) (sudo apt-get install nvidia-cuda-dev  nvidia-cuda-toolkit)
 and xformers (pip install xformers) are installed.

Just discovered: reinstalling to a different directory works - update doesn't work

my Kubuntu is a standard update from 23.10 to 24.04 - invoke -> /home/username/invokeai

Thanks for the reply

**Comment by psychedelicious** [comment]
There is no update functionality. You must use the installer and specify the same install directory as the initial install to update the application packages. 

The error message indicates that python 3.11 is still not being used. You'll need to ensure that your `PATH` is set correctly so that `python3` points to it.

**Comment by jennner** [comment]
Hello,
 I did the update as you wrote. I know that there is no special update. It always worked under Kubuntu 23.10 (since invokeai 3.x). 
I installed python 3.11.9 with pyenv. python -version reports 3.11.9. 
If I install in the existing directory /home/username/invokeai, the error message mentioned appears (last post from me). Installing in a different directory works. 
This probably won't work with the wrong Python version either.

Best regards and thanks

sorry -translation is google

**Comment by psychedelicious** [comment]
Ok, next step - delete the virtual environment created by the installer and try again, ensuring that `python3` points to the 3.11 python binary.

**Comment by jennner** [comment]
Good evening,
worked now. I installed invokeai in a new directory and copied the database, models and images. Now invokeai is running again. 
Thank you for the great support.

**Comment by psychedelicious** [comment]
Good to hear, you're welcome. FWIW, that's accomplished the same thing as deleting the virtual environment as suggested in a previous reply.
