### ISSUE TITLE
[bug]: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by TeKett** [invoke-ai/InvokeAI#6455]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4070 Ti

### GPU VRAM

12GB

### Version number

4.2.3

### Browser

Chrome

### Python dependencies

{
  "accelerate": "0.29.2",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.3.0",
  "python": "3.10.9",
  "torch": "2.2.2+cu121",
  "torchvision": "0.17.2+cu121",
  "transformers": "4.39.3",
  "xformers": "0.0.25.post1"
}

### What happened

I downloaded and installed for the first time. I wanted to try and use my diffusers trained checkpoint now that Kohya supports training diffusers. Kohya can both train and generate samples. I wanted to try out InvokeAI, i cant load the checkpoint with A1111 since it does not support diffusers. I loaded the model, picked a very simple test prompt "1girl", and hit invoke, and program errored with `OverflowError: cannot fit 'int' into an index-sized integer`.

### What you expected to happen

That it generates an image without issue.

### How to reproduce the problem

1. load my diffusers checkpoint
2. hit invoke
--> error

### Additional context

Loading a safetensors model that i got from civitai works fine. There should not be an issue with my model since it both trains and samples just fine in Kohya.

My full error message
```
[2024-05-29 12:59:33,544]::[InvokeAI]::ERROR --> Error while invoking session c3c5bf7b-a661-45b2-9aa9-56636eed1485, invocation 54a35b4a-7ad1-4410-ba3f-6757563bea2a (compel):
cannot fit 'int' into an index-sized integer
[2024-05-29 12:59:33,544]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Train\InvokeAI\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 185, in _process
    outputs = self._invocation.invoke_internal(
  File "C:\Train\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 281, in invoke_internal
    output = self.invoke(context)
  File "C:\Train\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Train\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 111, in invoke
    c, _options = compel.build_conditioning_tensor_for_conjunction(conjunction)
  File "C:\Train\InvokeAI\.venv\lib\site-packages\compel\compel.py", line 186, in build_conditioning_tensor_for_conjunction
    this_conditioning, this_options = self.build_conditioning_tensor_for_prompt_object(p)
  File "C:\Train\InvokeAI\.venv\lib\site-packages\compel\compel.py", line 218, in build_conditioning_tensor_for_prompt_object
    return self._get_conditioning_for_flattened_prompt(prompt), {}
  File "C:\Train\InvokeAI\.venv\lib\site-packages\compel\compel.py", line 282, in _get_conditioning_for_flattened_prompt
    return self.conditioning_provider.get_embeddings_for_weighted_prompt_fragments(
  File "C:\Train\InvokeAI\.venv\lib\site-packages\compel\embeddings_provider.py", line 119, in get_embeddings_for_weighted_prompt_fragments
    tokens, per_token_weights, mask = self.get_token_ids_and_expand_weights(fragments, weights, device=device)
  File "C:\Train\InvokeAI\.venv\lib\site-packages\compel\embeddings_provider.py", line 280, in get_token_ids_and_expand_weights
    return self._chunk_and_pad_token_ids(all_token_ids, all_token_weights, device=device)
  File "C:\Train\InvokeAI\.venv\lib\site-packages\compel\embeddings_provider.py", line 307, in _chunk_and_pad_token_ids
    chunk_token_ids += [self.tokenizer.pad_token_id] * pad_length
OverflowError: cannot fit 'int' into an index-sized integer
```

**Comment by TeKett** [comment]
So i decided to dig a bit into the code to see what could cause it. This might be an issue i should probably send over to 'compel', since its a bug in their code. 
```
            pad_length = self.max_token_count - len(chunk_token_ids)
            chunk_token_ids += [self.tokenizer.pad_token_id] * pad_length
```
`self.max_token_count` is 1000000000000000019884624838656, and `chunk_token_ids` is 4, im guessing `bos + 1 + girl + eos`.

`self.max_token_count` should be 77, since its comparing it to a tensor of size 77, so i tried to force the max to be 77 rather then asking what the max is, and it solved the issue.
