### ISSUE TITLE
[bug]: Invoke drops queue items >1

### ISSUE THREAD

**Issue by aolko** [invoke-ai/InvokeAI#6456]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA GeForce GTX 1060

### GPU VRAM

6GB

### Version number

4.2.3

### Browser

Chrome 124.0.6367.218

### What happened

subj
```
Traceback (most recent call last):
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\invokeai\app\services\session_processor\session_processor_default.py", line 185, in _process
    outputs = self._invocation.invoke_internal(
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\invokeai\app\invocations\baseinvocation.py", line 281, in invoke_internal
    output = self.invoke(context)
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\invokeai\app\invocations\compel.py", line 117, in invoke
    conditioning_name = context.conditioning.save(conditioning_data)
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\invokeai\app\services\shared\invocation_context.py", line 307, in save
    name = self._services.conditioning.save(obj=conditioning_data)
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\invokeai\app\services\object_serializer\object_serializer_forward_cache.py", line 47, in save
    name = self._underlying_storage.save(obj)
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\invokeai\app\services\object_serializer\object_serializer_disk.py", line 55, in save
    torch.save(obj, file_path)  # pyright: ignore [reportUnknownMemberType]
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\venv\lib\site-packages\torch\serialization.py", line 628, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\venv\lib\site-packages\torch\serialization.py", line 502, in _open_zipfile_writer
    return container(name_or_buffer)
  File "D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\venv\lib\site-packages\torch\serialization.py", line 473, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory D:\Programs\StabilityMatrix\Data\Packages\InvokeAI\invokeai-root\outputs\conditioning\tmp_bx7h85t does not exist.
```

### What you expected to happen

Normal queue processing

### How to reproduce the problem

queue >1 images

**Comment by psychedelicious** [comment]
Can you reproduce this issue when installing invoke using the official installer? https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.3

**Comment by aolko** [comment]
> Can you reproduce this issue when installing invoke using the official installer? https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.3

No
![](https://i.ibb.co/nLns9bG/browser-QL7-ZKYo-Iw8.png)

**Comment by psychedelicious** [comment]
We can't offer support for stability matrix. You'll need to take this up with that project. 

If a stability matrix dev has technical questions we are happy to answer and try to help of course.

**Comment by aolko** [comment]
> We can't offer support for stability matrix. You'll need to take this up with that project.
> 
> If a stability matrix dev has technical questions we are happy to answer and try to help of course.

yeah right, amazing job with autoload system right here
