### ISSUE TITLE
[bug]: Stable diffusion 3 install Unauthorized error, but I have setup huggingface token and accepted sd3 licience

### ISSUE THREAD

**Issue by than0107** [invoke-ai/InvokeAI#6513]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### Version number

4.2.4

### Browser

Edge

### What happened

1. set up huggingface token as suggested in FAQ

python -c "import huggingface_hub; huggingface_hub.login()"
Token can be pasted using 'Right-Click'.
Enter your token (input will not be visible):
Add token as git credential? (Y/n)y
Token is valid (permission: write).
Your token has been saved in your configured git credential helpers (manager).
Your token has been saved to C:\Users\kent\.cache\huggingface\token
Login successful

2. tried to install sd3 (tried all the versions of sd3 in the repo) from huggingface and got this error message

[2024-06-14 19:01:39,516]::[DownloadQueueService]::ERROR --> https://huggingface.co/stabilityai/stable-diffusion-3-medium/resolve/main/sd3_medium_incl_clips_t5xxlfp16.safetensors: ['Traceback (most recent call last):\n', '  File "F:\\stable_diffusion_all\\invoke_ai_401\\.venv\\lib\\site-packages\\invokeai\\app\\services\\download\\download_default.py", line 229, in _download_next_item\n    self._do_download(job)\n', '  File "F:\\stable_diffusion_all\\invoke_ai_401\\.venv\\lib\\site-packages\\invokeai\\app\\services\\download\\download_default.py", line 255, in _do_download\n    raise HTTPError(resp.reason)\n', 'requests.exceptions.HTTPError: Unauthorized\n']
[2024-06-14 19:01:39,517]::[ModelInstallService]::ERROR --> Cancelling https://huggingface.co/stabilityai/stable-diffusion-3-medium/resolve/main/sd3_medium_incl_clips_t5xxlfp16.safetensors due to an error while downloading https://huggingface.co/stabilityai/stable-diffusion-3-medium/resolve/main/sd3_medium_incl_clips_t5xxlfp16.safetensors: Unauthorized
[2024-06-14 19:01:39,517]::[ModelInstallService]::ERROR --> Model install error: https://huggingface.co/stabilityai/stable-diffusion-3-medium/resolve/main/sd3_medium_incl_clips_t5xxlfp16.safetensors

3. tried to install from local path and got this error message

[2024-06-14 19:03:24,424]::[ModelInstallService]::ERROR --> Model install error: F:/stable_diffusion_all/ComfyUI/ComfyUI/models/checkpoints/sd3_medium_incl_clips_t5xxlfp16.safetensors
InvalidModelConfigException: Cannot determine base type

### What you expected to happen

can install sd3

**Comment by ausbitbank** [comment]
SD3 is not supported yet (and it may not ever be supported officially)
See these for more info

![image](https://github.com/invoke-ai/InvokeAI/assets/1692203/62bb9bb1-1884-43a0-a134-3412065deefd)

https://www.youtube.com/watch?v=r8oA42saTNI

**Comment by than0107** [comment]
Oh, they could have chosen: 1) sticking to former practice of SD1.x, SD2.x and SDXL; 2) offering one-off purchase; 3) offering less restrictive and more transparent license; 4) obtuse angle. Never thought 4 is the actual choice.  
Good work Invokeai team and hope you the best.
