### ISSUE TITLE
[bug]: default_style_presets.json is missing, InvokeAI can't start.

### ISSUE THREAD

**Issue by YesThisIsMe007** [invoke-ai/InvokeAI#6751]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3070 LHR

### Version number

v4.2.8rc1

### Browser

Edge Chromium 127.0.2651.105 64-bit

### What happened

I ran invokeai.bat and that selected option 1.
After that, this error:

```
[2024-08-16 13:43:03,147]::[uvicorn.error]::ERROR --> Traceback (most recent call last):
  File "C:\Users\tomaz\invokeai\.venv\Lib\site-packages\starlette\routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\tomaz\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomaz\invokeai\.venv\Lib\site-packages\invokeai\app\api_app.py", line 65, in lifespan
    ApiDependencies.initialize(config=app_config, event_handler_id=event_handler_id, loop=loop, logger=logger)
  File "C:\Users\tomaz\invokeai\.venv\Lib\site-packages\invokeai\app\api\dependencies.py", line 152, in initialize
    ApiDependencies.invoker = Invoker(services)
                              ^^^^^^^^^^^^^^^^^
  File "C:\Users\tomaz\invokeai\.venv\Lib\site-packages\invokeai\app\services\invoker.py", line 14, in __init__
    self._start()
  File "C:\Users\tomaz\invokeai\.venv\Lib\site-packages\invokeai\app\services\invoker.py", line 31, in _start
    self.__start_service(getattr(self.services, service))
  File "C:\Users\tomaz\invokeai\.venv\Lib\site-packages\invokeai\app\services\invoker.py", line 20, in __start_service
    start_op(self)
  File "C:\Users\tomaz\invokeai\.venv\Lib\site-packages\invokeai\app\services\style_preset_records\style_preset_records_sqlite.py", line 26, in start
    self._sync_default_style_presets()
  File "C:\Users\tomaz\invokeai\.venv\Lib\site-packages\invokeai\app\services\style_preset_records\style_preset_records_sqlite.py", line 211, in _sync_default_style_presets
    with self._lock, open(Path(__file__).parent / Path("default_style_presets.json"), "r") as file:
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\tomaz\\invokeai\\.venv\\Lib\\site-packages\\invokeai\\app\\services\\style_preset_records\\default_style_presets.json'

[2024-08-16 13:43:03,148]::[uvicorn.error]::ERROR --> Application startup failed. Exiting.
```

Error is present in v4.2.8rc1.

### What you expected to happen

I exptected InvokeAI to run normally.

### How to reproduce the problem

Run invokeai.bat.

**Comment by psychedelicious** [comment]
This is fixed in v4.2.8rc2: https://github.com/invoke-ai/InvokeAI/releases/tag/v4.2.8rc2
