### ISSUE TITLE
[bug]: Error Installing Invoke AI 4.2.9 No module named 'Controlnet_aux'

### ISSUE THREAD

**Issue by DAWiguna** [invoke-ai/InvokeAI#6907]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3080

### GPU VRAM

10GB

### Version number

4.2.9

### Browser

Chrome Versi 129.0.6668.58 (Build Resmi) (64 bit)

### What happened

I installed upgrade Invoke AI and the installation is successful.
Afterward, I run invoke and it generates this:
(base) C:\Users\donny\invokeai>invoke
Desired action:
1. Generate images with the browser-based interface
2. Open the developer console
3. Command-line help
Q - Quit

To update, download and run the installer from https://github.com/invoke-ai/InvokeAI/releases/latest

Please enter 1-4, Q: [1]
Starting the InvokeAI browser-based UI..
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\donny\invokeai\.venv\Scripts\invokeai-web.exe\__main__.py", line 7, in <module>
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\run_app.py", line 10, in run_app
    from invokeai.app.api_app import invoke_api
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\api_app.py", line 23, in <module>
    from invokeai.app.api.dependencies import ApiDependencies
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\api\dependencies.py", line 14, in <module>
    from invokeai.app.services.download.download_default import DownloadQueueService
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\services\download\__init__.py", line 10, in <module>
    from invokeai.app.services.download.download_default import DownloadQueueService, TqdmProgress
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\services\download\download_default.py", line 31, in <module>
    from invokeai.app.services.events.events_base import EventServiceBase
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\services\events\__init__.py", line 1, in <module>
    from .events_base import EventServiceBase  # noqa F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\services\events\events_base.py", line 6, in <module>
    from invokeai.app.services.events.events_common import (
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\services\events\events_common.py", line 9, in <module>
    from invokeai.app.services.session_queue.session_queue_common import (
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\services\session_queue\session_queue_common.py", line 19, in <module>
    from invokeai.app.services.shared.graph import Graph, GraphExecutionState, NodeNotFoundError
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\services\shared\graph.py", line 20, in <module>
    from invokeai.app.invocations import *  # noqa: F401 F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\donny\invokeai\.venv\Lib\site-packages\invokeai\app\invocations\controlnet_image_processors.py", line 10, in <module>
    from controlnet_aux import (
ModuleNotFoundError: No module named 'controlnet_aux'

### What you expected to happen

I expect to open Invoke AI in the browser

### How to reproduce the problem

In Anaconda Prompt, after installation, run invoke.bat

**Comment by DAWiguna** [comment]
Solution: simply remove pip cache of controlnet_aux
