### ISSUE TITLE
[bug]: Flux Schnell or any model:  Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by phazei** [invoke-ai/InvokeAI#7009]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3090

### GPU VRAM

24gb

### Version number

5.0.2

### Browser

Chrome 

### What happened

When I generate an image, regardless of the model I select, I get the same error about MetadataIncompleteBuffer

### What you expected to happen

A image to generate

### How to reproduce the problem

Install schnell model.  After it finishes download, backup the download for the main schnell model since it took forever.  Then reinstall Invoke.  Now install schnell model, and cancel the main item and let the rest of the items it gets finish downloading.  Then manually install the schnell that was downloaded before locally.  Then generate a model.

### Additional context

Stack Trace:
```
Error
Traceback (most recent call last):
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\flux_text_encoder.py", line 50, in invoke
    t5_embeddings = self._t5_encode(context)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\flux_text_encoder.py", line 61, in _t5_encode
    t5_text_encoder_info = context.models.load(self.t5_encoder.text_encoder)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 370, in load
    return self._services.model_manager.load.load_model(model, _submodel_type)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\app\services\model_load\model_load_default.py", line 70, in load_model
    ).load_model(model_config, submodel_type)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 56, in load_model
    locker = self._load_and_cache(model_config, submodel_type)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 77, in _load_and_cache
    loaded_model = self._load_model(config, submodel_type)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_loaders\flux.py", line 122, in _load_model
    state_dict = load_file(state_dict_path)
  File "D:\AITools\InvokeAI\.venv\lib\site-packages\safetensors\torch.py", line 311, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```

Extra data:
```
{
    "item_id": 22, 
    "status": "failed", 
    "priority": 0, 
    "batch_id": "019af6f1-18c1-45e2-82a8-d55607f9fd0e", 
    "origin": "canvas", 
    "destination": "canvas", 
    "session_id": "3eb87176-5699-4e1c-80f6-89e660e0921b", 
    "error_type": "SafetensorError", 
    "error_message": "Error while deserializing header: MetadataIncompleteBuffer", 
    "error_traceback": "Traceback (most recent call last):\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\app\\services\\session_processor\\session_processor_default.py\", line 129, in run_node\n    output = invocation.invoke_internal(context=context, services=self._services)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\baseinvocation.py\", line 290, in invoke_internal\n    output = self.invoke(context)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\torch\\utils\\_contextlib.py\", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\flux_text_encoder.py\", line 50, in invoke\n    t5_embeddings = self._t5_encode(context)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\app\\invocations\\flux_text_encoder.py\", line 61, in _t5_encode\n    t5_text_encoder_info = context.models.load(self.t5_encoder.text_encoder)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\app\\services\\shared\\invocation_context.py\", line 370, in load\n    return self._services.model_manager.load.load_model(model, _submodel_type)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\app\\services\\model_load\\model_load_default.py\", line 70, in load_model\n    ).load_model(model_config, submodel_type)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\backend\\model_manager\\load\\load_default.py\", line 56, in load_model\n    locker = self._load_and_cache(model_config, submodel_type)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\backend\\model_manager\\load\\load_default.py\", line 77, in _load_and_cache\n    loaded_model = self._load_model(config, submodel_type)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\invokeai\\backend\\model_manager\\load\\model_loaders\\flux.py\", line 122, in _load_model\n    state_dict = load_file(state_dict_path)\n  File \"D:\\AITools\\InvokeAI\\.venv\\lib\\site-packages\\safetensors\\torch.py\", line 311, in load_file\n    with safe_open(filename, framework=\"pt\", device=device) as f:\nsafetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer\n", 
    "created_at": "2024-10-02 07:10:56.134", 
    "updated_at": "2024-10-02 07:10:56.364", 
    "started_at": "2024-10-02 07:10:56.145", 
    "completed_at": "2024-10-02 07:10:56.355", 
    "queue_id": "default", 
    "field_values": [
        {"node_path": "flux_denoise:wpzFXqSICQ"     , "field_name": "seed"           , "value": 2191252018         }, 
        {"node_path": "core_metadata:zm73lKUxF7"    , "field_name": "seed"           , "value": 2191252018         }, 
        {"node_path": "flux_text_encoder:I2VxdzUm6J", "field_name": "prompt"         , "value": "sunset on a beach"}, 
        {"node_path": "core_metadata:zm73lKUxF7"    , "field_name": "positive_prompt", "value": "sunset on a beach"}  
    ], 
    "session": {
        "id": "3eb87176-5699-4e1c-80f6-89e660e0921b", 
        "graph": {
            "id": "flux_graph:gOHWn37cLT", 
            "nodes": {
                "flux_model_loader:6JRZ3PNp3g": {
                    "id": "flux_model_loader:6JRZ3PNp3g", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "model": {
                        "key" : "3a550cb9-5f89-4a20-a5a6-03667dab3816"                                   , 
                        "hash": "blake3:43127e572fa58c78cec72ca599f6a2d53504fcbd178330f1d8c9dd7e81194b4a", 
                        "name": "FLUX Schnell (Quantized)"                                               , 
                        "base": "flux"                                                                   , 
                        "type": "main"                                                                     
                    }, 
                    "t5_encoder_model": {
                        "key" : "1c2a54ad-5425-4278-8284-9a9ee3bb47a6"                                   , 
                        "hash": "blake3:6a71250a0c94da80466ebf90884f3477f347607b8ef0207096baf4f7d7a6f57c", 
                        "name": "t5_bnb_int8_quantized_encoder"                                          , 
                        "base": "any"                                                                    , 
                        "type": "t5_encoder"                                                               
                    }, 
                    "clip_embed_model": {
                        "key" : "e958867f-8d7e-4631-8df6-3b877f985968"                                   , 
                        "hash": "blake3:17c19f0ef941c3b7609a9c94a659ca5364de0be364a91d4179f0e39ba17c3b70", 
                        "name": "clip-vit-large-patch14"                                                 , 
                        "base": "any"                                                                    , 
                        "type": "clip_embed"                                                               
                    }, 
                    "vae_model": {
                        "key" : "ae6e661e-531b-47d7-8c69-73d1c1cbe6d2"                                   , 
                        "hash": "blake3:ce21cb76364aa6e2421311cf4a4b5eb052a76c4f1cd207b50703d8978198a068", 
                        "name": "FLUX.1-schnell_ae"                                                      , 
                        "base": "flux"                                                                   , 
                        "type": "vae"                                                                      
                    }, 
                    "type": "flux_model_loader"
                }, 
                "flux_text_encoder:I2VxdzUm6J": {
                    "id": "flux_text_encoder:I2VxdzUm6J", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "prompt": "sunset on a beach", 
                    "type": "flux_text_encoder"
                }, 
                "flux_denoise:wpzFXqSICQ": {
                    "id": "flux_denoise:wpzFXqSICQ", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "denoising_start": 0, 
                    "denoising_end": 1, 
                    "width": 1024, 
                    "height": 1024, 
                    "num_steps": 7, 
                    "guidance": 2, 
                    "seed": 2191252018, 
                    "type": "flux_denoise"
                }, 
                "flux_vae_decode:oRGhLXZuor": {
                    "id": "flux_vae_decode:oRGhLXZuor", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "type": "flux_vae_decode"
                }, 
                "core_metadata:zm73lKUxF7": {
                    "id": "core_metadata:zm73lKUxF7", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "generation_mode": "flux_txt2img", 
                    "positive_prompt": "sunset on a beach", 
                    "width": 768, 
                    "height": 768, 
                    "seed": 2191252018, 
                    "steps": 7, 
                    "model": {
                        "key" : "3a550cb9-5f89-4a20-a5a6-03667dab3816"                                   , 
                        "hash": "blake3:43127e572fa58c78cec72ca599f6a2d53504fcbd178330f1d8c9dd7e81194b4a", 
                        "name": "FLUX Schnell (Quantized)"                                               , 
                        "base": "flux"                                                                   , 
                        "type": "main"                                                                     
                    }, 
                    "vae": {
                        "key" : "ae6e661e-531b-47d7-8c69-73d1c1cbe6d2"                                   , 
                        "hash": "blake3:ce21cb76364aa6e2421311cf4a4b5eb052a76c4f1cd207b50703d8978198a068", 
                        "name": "FLUX.1-schnell_ae"                                                      , 
                        "base": "flux"                                                                   , 
                        "type": "vae"                                                                      
                    }, 
                    "type": "core_metadata", 
                    "guidance": 2, 
                    "t5_encoder": {
                        "key" : "1c2a54ad-5425-4278-8284-9a9ee3bb47a6"                                   , 
                        "hash": "blake3:6a71250a0c94da80466ebf90884f3477f347607b8ef0207096baf4f7d7a6f57c", 
                        "name": "t5_bnb_int8_quantized_encoder"                                          , 
                        "base": "any"                                                                    , 
                        "type": "t5_encoder"                                                               
                    }, 
                    "clip_embed_model": {
                        "key" : "e958867f-8d7e-4631-8df6-3b877f985968"                                   , 
                        "hash": "blake3:17c19f0ef941c3b7609a9c94a659ca5364de0be364a91d4179f0e39ba17c3b70", 
                        "name": "clip-vit-large-patch14"                                                 , 
                        "base": "any"                                                                    , 
                        "type": "clip_embed"                                                               
                    }
                }, 
                "canvas_output:Amdt61laYz": {
                    "id": "canvas_output:Amdt61laYz", 
                    "is_intermediate": true, 
                    "use_cache": false, 
                    "width": 768, 
                    "height": 768, 
                    "resample_mode": "bicubic", 
                    "type": "img_resize"
                }
            }, 
            "edges": [
                {
                    "source"     : {"node_id": "flux_model_loader:6JRZ3PNp3g", "field": "transformer"}, 
                    "destination": {"node_id": "flux_denoise:wpzFXqSICQ"     , "field": "transformer"}  
                }, 
                {
                    "source"     : {"node_id": "flux_model_loader:6JRZ3PNp3g", "field": "vae"}, 
                    "destination": {"node_id": "flux_vae_decode:oRGhLXZuor"  , "field": "vae"}  
                }, 
                {
                    "source"     : {"node_id": "flux_model_loader:6JRZ3PNp3g", "field": "clip"}, 
                    "destination": {"node_id": "flux_text_encoder:I2VxdzUm6J", "field": "clip"}  
                }, 
                {
                    "source"     : {"node_id": "flux_model_loader:6JRZ3PNp3g", "field": "t5_encoder"}, 
                    "destination": {"node_id": "flux_text_encoder:I2VxdzUm6J", "field": "t5_encoder"}  
                }, 
                {
                    "source"     : {"node_id": "flux_model_loader:6JRZ3PNp3g", "field": "max_seq_len"   }, 
                    "destination": {"node_id": "flux_text_encoder:I2VxdzUm6J", "field": "t5_max_seq_len"}  
                }, 
                {
                    "source"     : {"node_id": "flux_text_encoder:I2VxdzUm6J", "field": "conditioning"              }, 
                    "destination": {"node_id": "flux_denoise:wpzFXqSICQ"     , "field": "positive_text_conditioning"}  
                }, 
                {
                    "source"     : {"node_id": "flux_denoise:wpzFXqSICQ"   , "field": "latents"}, 
                    "destination": {"node_id": "flux_vae_decode:oRGhLXZuor", "field": "latents"}  
                }, 
                {
                    "source"     : {"node_id": "flux_vae_decode:oRGhLXZuor", "field": "image"}, 
                    "destination": {"node_id": "canvas_output:Amdt61laYz"  , "field": "image"}  
                }, 
                {
                    "source"     : {"node_id": "core_metadata:zm73lKUxF7", "field": "metadata"}, 
                    "destination": {"node_id": "canvas_output:Amdt61laYz", "field": "metadata"}  
                }
            ]
        }, 
        "execution_graph": {
            "id": "4b131494-7367-4760-8f2c-30bf988c5f4b", 
            "nodes": {
                "f0382ae3-d760-4879-b5cf-ba85aaff9382": {
                    "id": "f0382ae3-d760-4879-b5cf-ba85aaff9382", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "model": {
                        "key" : "3a550cb9-5f89-4a20-a5a6-03667dab3816"                                   , 
                        "hash": "blake3:43127e572fa58c78cec72ca599f6a2d53504fcbd178330f1d8c9dd7e81194b4a", 
                        "name": "FLUX Schnell (Quantized)"                                               , 
                        "base": "flux"                                                                   , 
                        "type": "main"                                                                     
                    }, 
                    "t5_encoder_model": {
                        "key" : "1c2a54ad-5425-4278-8284-9a9ee3bb47a6"                                   , 
                        "hash": "blake3:6a71250a0c94da80466ebf90884f3477f347607b8ef0207096baf4f7d7a6f57c", 
                        "name": "t5_bnb_int8_quantized_encoder"                                          , 
                        "base": "any"                                                                    , 
                        "type": "t5_encoder"                                                               
                    }, 
                    "clip_embed_model": {
                        "key" : "e958867f-8d7e-4631-8df6-3b877f985968"                                   , 
                        "hash": "blake3:17c19f0ef941c3b7609a9c94a659ca5364de0be364a91d4179f0e39ba17c3b70", 
                        "name": "clip-vit-large-patch14"                                                 , 
                        "base": "any"                                                                    , 
                        "type": "clip_embed"                                                               
                    }, 
                    "vae_model": {
                        "key" : "ae6e661e-531b-47d7-8c69-73d1c1cbe6d2"                                   , 
                        "hash": "blake3:ce21cb76364aa6e2421311cf4a4b5eb052a76c4f1cd207b50703d8978198a068", 
                        "name": "FLUX.1-schnell_ae"                                                      , 
                        "base": "flux"                                                                   , 
                        "type": "vae"                                                                      
                    }, 
                    "type": "flux_model_loader"
                }, 
                "003c5dc8-874b-4baf-8c40-7ee0cded1491": {
                    "id": "003c5dc8-874b-4baf-8c40-7ee0cded1491", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "generation_mode": "flux_txt2img", 
                    "positive_prompt": "sunset on a beach", 
                    "width": 768, 
                    "height": 768, 
                    "seed": 2191252018, 
                    "steps": 7, 
                    "model": {
                        "key" : "3a550cb9-5f89-4a20-a5a6-03667dab3816"                                   , 
                        "hash": "blake3:43127e572fa58c78cec72ca599f6a2d53504fcbd178330f1d8c9dd7e81194b4a", 
                        "name": "FLUX Schnell (Quantized)"                                               , 
                        "base": "flux"                                                                   , 
                        "type": "main"                                                                     
                    }, 
                    "vae": {
                        "key" : "ae6e661e-531b-47d7-8c69-73d1c1cbe6d2"                                   , 
                        "hash": "blake3:ce21cb76364aa6e2421311cf4a4b5eb052a76c4f1cd207b50703d8978198a068", 
                        "name": "FLUX.1-schnell_ae"                                                      , 
                        "base": "flux"                                                                   , 
                        "type": "vae"                                                                      
                    }, 
                    "type": "core_metadata", 
                    "guidance": 2, 
                    "t5_encoder": {
                        "key" : "1c2a54ad-5425-4278-8284-9a9ee3bb47a6"                                   , 
                        "hash": "blake3:6a71250a0c94da80466ebf90884f3477f347607b8ef0207096baf4f7d7a6f57c", 
                        "name": "t5_bnb_int8_quantized_encoder"                                          , 
                        "base": "any"                                                                    , 
                        "type": "t5_encoder"                                                               
                    }, 
                    "clip_embed_model": {
                        "key" : "e958867f-8d7e-4631-8df6-3b877f985968"                                   , 
                        "hash": "blake3:17c19f0ef941c3b7609a9c94a659ca5364de0be364a91d4179f0e39ba17c3b70", 
                        "name": "clip-vit-large-patch14"                                                 , 
                        "base": "any"                                                                    , 
                        "type": "clip_embed"                                                               
                    }
                }, 
                "da5532d4-7edb-4bfa-a0e1-0f0791568a57": {
                    "id": "da5532d4-7edb-4bfa-a0e1-0f0791568a57", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "clip": {
                        "tokenizer": {
                            "key"          : "e958867f-8d7e-4631-8df6-3b877f985968"                                   , 
                            "hash"         : "blake3:17c19f0ef941c3b7609a9c94a659ca5364de0be364a91d4179f0e39ba17c3b70", 
                            "name"         : "clip-vit-large-patch14"                                                 , 
                            "base"         : "any"                                                                    , 
                            "type"         : "clip_embed"                                                             , 
                            "submodel_type": "tokenizer"                                                                
                        }, 
                        "text_encoder": {
                            "key"          : "e958867f-8d7e-4631-8df6-3b877f985968"                                   , 
                            "hash"         : "blake3:17c19f0ef941c3b7609a9c94a659ca5364de0be364a91d4179f0e39ba17c3b70", 
                            "name"         : "clip-vit-large-patch14"                                                 , 
                            "base"         : "any"                                                                    , 
                            "type"         : "clip_embed"                                                             , 
                            "submodel_type": "text_encoder"                                                             
                        }, 
                        "skipped_layers": 0, 
                        "loras": []
                    }, 
                    "t5_encoder": {
                        "tokenizer": {
                            "key"          : "1c2a54ad-5425-4278-8284-9a9ee3bb47a6"                                   , 
                            "hash"         : "blake3:6a71250a0c94da80466ebf90884f3477f347607b8ef0207096baf4f7d7a6f57c", 
                            "name"         : "t5_bnb_int8_quantized_encoder"                                          , 
                            "base"         : "any"                                                                    , 
                            "type"         : "t5_encoder"                                                             , 
                            "submodel_type": "tokenizer_2"                                                              
                        }, 
                        "text_encoder": {
                            "key"          : "1c2a54ad-5425-4278-8284-9a9ee3bb47a6"                                   , 
                            "hash"         : "blake3:6a71250a0c94da80466ebf90884f3477f347607b8ef0207096baf4f7d7a6f57c", 
                            "name"         : "t5_bnb_int8_quantized_encoder"                                          , 
                            "base"         : "any"                                                                    , 
                            "type"         : "t5_encoder"                                                             , 
                            "submodel_type": "text_encoder_2"                                                           
                        }
                    }, 
                    "t5_max_seq_len": 256, 
                    "prompt": "sunset on a beach", 
                    "type": "flux_text_encoder"
                }, 
                "045d52c7-8490-4c4f-b42b-328e63be275f": {
                    "id": "045d52c7-8490-4c4f-b42b-328e63be275f", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "denoising_start": 0, 
                    "denoising_end": 1, 
                    "width": 1024, 
                    "height": 1024, 
                    "num_steps": 7, 
                    "guidance": 2, 
                    "seed": 2191252018, 
                    "type": "flux_denoise"
                }, 
                "7984defd-bc0a-4529-9a49-00559e994cb7": {
                    "id": "7984defd-bc0a-4529-9a49-00559e994cb7", 
                    "is_intermediate": true, 
                    "use_cache": true, 
                    "type": "flux_vae_decode"
                }, 
                "4eb91a2d-828a-4f3f-8f8d-a62e499f2918": {
                    "id": "4eb91a2d-828a-4f3f-8f8d-a62e499f2918", 
                    "is_intermediate": true, 
                    "use_cache": false, 
                    "width": 768, 
                    "height": 768, 
                    "resample_mode": "bicubic", 
                    "type": "img_resize"
                }
            }, 
            "edges": [
                {
                    "source"     : {"node_id": "f0382ae3-d760-4879-b5cf-ba85aaff9382", "field": "clip"}, 
                    "destination": {"node_id": "da5532d4-7edb-4bfa-a0e1-0f0791568a57", "field": "clip"}  
                }, 
                {
                    "source"     : {"node_id": "f0382ae3-d760-4879-b5cf-ba85aaff9382", "field": "t5_encoder"}, 
                    "destination": {"node_id": "da5532d4-7edb-4bfa-a0e1-0f0791568a57", "field": "t5_encoder"}  
                }, 
                {
                    "source"     : {"node_id": "f0382ae3-d760-4879-b5cf-ba85aaff9382", "field": "max_seq_len"   }, 
                    "destination": {"node_id": "da5532d4-7edb-4bfa-a0e1-0f0791568a57", "field": "t5_max_seq_len"}  
                }, 
                {
                    "source"     : {"node_id": "f0382ae3-d760-4879-b5cf-ba85aaff9382", "field": "transformer"}, 
                    "destination": {"node_id": "045d52c7-8490-4c4f-b42b-328e63be275f", "field": "transformer"}  
                }, 
                {
                    "source": {"node_id": "da5532d4-7edb-4bfa-a0e1-0f0791568a57", "field": "conditioning"}, 
                    "destination": {
                        "node_id": "045d52c7-8490-4c4f-b42b-328e63be275f", 
                        "field"  : "positive_text_conditioning"            
                    }
                }, 
                {
                    "source"     : {"node_id": "f0382ae3-d760-4879-b5cf-ba85aaff9382", "field": "vae"}, 
                    "destination": {"node_id": "7984defd-bc0a-4529-9a49-00559e994cb7", "field": "vae"}  
                }, 
                {
                    "source"     : {"node_id": "045d52c7-8490-4c4f-b42b-328e63be275f", "field": "latents"}, 
                    "destination": {"node_id": "7984defd-bc0a-4529-9a49-00559e994cb7", "field": "latents"}  
                }, 
                {
                    "source"     : {"node_id": "7984defd-bc0a-4529-9a49-00559e994cb7", "field": "image"}, 
                    "destination": {"node_id": "4eb91a2d-828a-4f3f-8f8d-a62e499f2918", "field": "image"}  
                }, 
                {
                    "source"     : {"node_id": "003c5dc8-874b-4baf-8c40-7ee0cded1491", "field": "metadata"}, 
                    "destination": {"node_id": "4eb91a2d-828a-4f3f-8f8d-a62e499f2918", "field": "metadata"}  
                }
            ]
        }, 
        "executed": ["f0382ae3-d760-4879-b5cf-ba85aaff9382", "flux_model_loader:6JRZ3PNp3g"], 
        "executed_history": ["flux_model_loader:6JRZ3PNp3g"], 
        "results": {
            "f0382ae3-d760-4879-b5cf-ba85aaff9382": {
                "transformer": {
                    "transformer": {
                        "key"          : "3a550cb9-5f89-4a20-a5a6-03667dab3816"                                   , 
                        "hash"         : "blake3:43127e572fa58c78cec72ca599f6a2d53504fcbd178330f1d8c9dd7e81194b4a", 
                        "name"         : "FLUX Schnell (Quantized)"                                               , 
                        "base"         : "flux"                                                                   , 
                        "type"         : "main"                                                                   , 
                        "submodel_type": "transformer"                                                              
                    }, 
                    "loras": []
                }, 
                "clip": {
                    "tokenizer": {
                        "key"          : "e958867f-8d7e-4631-8df6-3b877f985968"                                   , 
                        "hash"         : "blake3:17c19f0ef941c3b7609a9c94a659ca5364de0be364a91d4179f0e39ba17c3b70", 
                        "name"         : "clip-vit-large-patch14"                                                 , 
                        "base"         : "any"                                                                    , 
                        "type"         : "clip_embed"                                                             , 
                        "submodel_type": "tokenizer"                                                                
                    }, 
                    "text_encoder": {
                        "key"          : "e958867f-8d7e-4631-8df6-3b877f985968"                                   , 
                        "hash"         : "blake3:17c19f0ef941c3b7609a9c94a659ca5364de0be364a91d4179f0e39ba17c3b70", 
                        "name"         : "clip-vit-large-patch14"                                                 , 
                        "base"         : "any"                                                                    , 
                        "type"         : "clip_embed"                                                             , 
                        "submodel_type": "text_encoder"                                                             
                    }, 
                    "skipped_layers": 0, 
                    "loras": []
                }, 
                "t5_encoder": {
                    "tokenizer": {
                        "key"          : "1c2a54ad-5425-4278-8284-9a9ee3bb47a6"                                   , 
                        "hash"         : "blake3:6a71250a0c94da80466ebf90884f3477f347607b8ef0207096baf4f7d7a6f57c", 
                        "name"         : "t5_bnb_int8_quantized_encoder"                                          , 
                        "base"         : "any"                                                                    , 
                        "type"         : "t5_encoder"                                                             , 
                        "submodel_type": "tokenizer_2"                                                              
                    }, 
                    "text_encoder": {
                        "key"          : "1c2a54ad-5425-4278-8284-9a9ee3bb47a6"                                   , 
                        "hash"         : "blake3:6a71250a0c94da80466ebf90884f3477f347607b8ef0207096baf4f7d7a6f57c", 
                        "name"         : "t5_bnb_int8_quantized_encoder"                                          , 
                        "base"         : "any"                                                                    , 
                        "type"         : "t5_encoder"                                                             , 
                        "submodel_type": "text_encoder_2"                                                           
                    }
                }, 
                "vae": {
                    "vae": {
                        "key"          : "ae6e661e-531b-47d7-8c69-73d1c1cbe6d2"                                   , 
                        "hash"         : "blake3:ce21cb76364aa6e2421311cf4a4b5eb052a76c4f1cd207b50703d8978198a068", 
                        "name"         : "FLUX.1-schnell_ae"                                                      , 
                        "base"         : "flux"                                                                   , 
                        "type"         : "vae"                                                                    , 
                        "submodel_type": "vae"                                                                      
                    }, 
                    "seamless_axes": []
                }, 
                "max_seq_len": 256, 
                "type": "flux_model_loader_output"
            }
        }, 
        "errors": {
            "da5532d4-7edb-4bfa-a0e1-0f0791568a57": "SafetensorError: Error while deserializing header: MetadataIncompleteBuffer"
        }, 
        "prepared_source_mapping": {
            "f0382ae3-d760-4879-b5cf-ba85aaff9382": "flux_model_loader:6JRZ3PNp3g", 
            "003c5dc8-874b-4baf-8c40-7ee0cded1491": "core_metadata:zm73lKUxF7"    , 
            "da5532d4-7edb-4bfa-a0e1-0f0791568a57": "flux_text_encoder:I2VxdzUm6J", 
            "045d52c7-8490-4c4f-b42b-328e63be275f": "flux_denoise:wpzFXqSICQ"     , 
            "7984defd-bc0a-4529-9a49-00559e994cb7": "flux_vae_decode:oRGhLXZuor"  , 
            "4eb91a2d-828a-4f3f-8f8d-a62e499f2918": "canvas_output:Amdt61laYz"      
        }, 
        "source_prepared_mapping": {
            "flux_model_loader:6JRZ3PNp3g": ["f0382ae3-d760-4879-b5cf-ba85aaff9382"], 
            "core_metadata:zm73lKUxF7"    : ["003c5dc8-874b-4baf-8c40-7ee0cded1491"], 
            "flux_text_encoder:I2VxdzUm6J": ["da5532d4-7edb-4bfa-a0e1-0f0791568a57"], 
            "flux_denoise:wpzFXqSICQ"     : ["045d52c7-8490-4c4f-b42b-328e63be275f"], 
            "flux_vae_decode:oRGhLXZuor"  : ["7984defd-bc0a-4529-9a49-00559e994cb7"], 
            "canvas_output:Amdt61laYz"    : ["4eb91a2d-828a-4f3f-8f8d-a62e499f2918"]  
        }
    }
}
```

**Comment by phazei** [comment]
I redownloaded T5, clip, and VAE, and then it worked.  Must have failed a download somewhere.
