### ISSUE TITLE
[bug]: TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by Zren111** [invoke-ai/InvokeAI#7085]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

4060Ti

### GPU VRAM

16GB

### Version number

5.1.1

### Browser

chrome  129.0.6668.90

### Python dependencies

3.10.7

### What happened

When I Click Invoke, The log show this error

[2024-10-10 00:52:08,414]::[InvokeAI]::ERROR --> Error while invoking session 377fd706-2baf-4fea-9e3f-c1f88f3d2195, invocation 8b31bced-10b4-4ce5-8e83-0f5c628f2a52 (sdxl_compel_prompt): getattr(): attribute name must be string
[2024-10-10 00:52:08,414]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "F:\invokeai\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
  File "F:\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 267, in invoke
    c1, c1_pooled = self.run_clip_compel(context, self.clip, self.prompt, False, "lora_te1_", zero_on_empty=True)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\compel.py", line 140, in run_clip_compel
    tokenizer_info = context.models.load(clip_field.tokenizer)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 370, in load
    return self._services.model_manager.load.load_model(model, _submodel_type)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\app\services\model_load\model_load_default.py", line 70, in load_model
    ).load_model(model_config, submodel_type)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 56, in load_model
    locker = self._load_and_cache(model_config, submodel_type)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 77, in _load_and_cache
    loaded_model = self._load_model(config, submodel_type)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_loaders\stable_diffusion.py", line 73, in _load_model
    load_class = self.get_hf_load_class(model_path, submodel_type)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_loaders\generic_diffusers.py", line 60, in get_hf_load_class
    result = self._hf_definition_to_type(module=module, class_name=class_name)
  File "F:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_loaders\generic_diffusers.py", line 90, in _hf_definition_to_type
    result: ModelMixin = getattr(res_type, class_name)
TypeError: getattr(): attribute name must be string

### What you expected to happen

I expect no error

**Comment by psychedelicious** [comment]
Which model did you use? Please link to it

**Comment by Zren111** [comment]
> Which model did you use? Please link to it
I use SDXL Refiner as Model and here is my total config
![20241010-195455](https://github.com/user-attachments/assets/7e648bf2-f1fd-4037-a336-387f948558fb)

I also import model useable in version 3.2.0 before, and I can not use those model in version 5.1.1 too.

**Comment by psychedelicious** [comment]
The SDXL refiner is not a "main" model. I'm not sure how you ended up with it categorized as a main model. You'll need to delete this version of the refiner and use a different SDXL model for the main model. 

If you want to use the SDXL refiner, reinstall it from the starter models tab and you'll see it in the refiner section.
