### ISSUE TITLE
[bug]: image preview not working 

### ISSUE THREAD

**Issue by ShashwatDubey99** [invoke-ai/InvokeAI#7115]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

T4

### GPU VRAM

12

### Version number

5.1.1

### Browser

Chrome

### Python dependencies

maybe its related to fastapi 

### What happened

the image are generated but the preview of things like model downloading and image generation aren't updated /shown till reload  , it worked when i tried last time about 20 days ago 

### What you expected to happen

the realtime previews of model downloading and image generating 

### How to reproduce the problem

just download invoke-ai in colab through python 

### Additional context

sk exception was never retrieved
future: <Task finished name='Task-15062' coro=<_dispatch_as_task.<locals>.task() done, defined at /usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py:51> exception=AttributeError("'QueueItemStatusChangedEvent' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/dispatcher.py", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/handlers/local.py", line 195, in handle
    with create_span_for_handle_fn(
  File "/usr/local/lib/python3.10/dist-packages/fastapi_events/otel/utils.py", line 43, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagate/__init__.py", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/composite.py", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/trace/propagation/tracecontext.py", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/propagators/textmap.py", line 87, in get
    val = carrier.get(key, None)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'QueueItemStatusChangedEvent' object has no attribute 'get'

**Comment by ShashwatDubey99** [comment]
the link of the notebook if guys want :https://colab.research.google.com/drive/18oUOemaISJFJQAXgaT13B5PKMyEWL7Tq?usp=sharing

**Comment by psychedelicious** [comment]
We do not support Google Colab, as it's against the Colab terms of service to run an application like Invoke.
