### ISSUE TITLE
Codeformer face restoration fails - Placeholder storage has not been allocated on MPS device

### ISSUE THREAD

**Issue by AndyQ** [invoke-ai/InvokeAI#713]
**Describe your environment**
- GPU: mps
- VRAM: [if known]
- CPU arch: arm
- OS: macOS
- Python: Anaconda
- Branch: development

**Describe the bug**
Using Codeformer face restoration fails with the following error:
>> Error running RealESRGAN or GFPGAN. Your image was not upscaled.
Placeholder storage has not been allocated on MPS device!

This is on an M1 Mac, freshly updated environment.

**To Reproduce**
Use the following prompt:
superman portrait  -G 1.0 -ft codeformer

**Additional context**
Not sure if useful but a stack trace of the error:
```Traceback (most recent call last):
  File "/Users/andy/dev/mac/StableDiffusion/stable-diffusion/ldm/generate.py", line 548, in upscale_and_reconstruct
    image = CodeFormerRestoration().process(image=image, strength=strength, device=self.device, seed=seed, fidelity=codeformer_fidelity)
  File "/Users/andy/dev/mac/StableDiffusion/stable-diffusion/ldm/restoration/codeformer/codeformer.py", line 40, in process
    face_helper.get_face_landmarks_5(resize=640, eye_dist_threshold=5)
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 139, in get_face_landmarks_5
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 205, in detect_faces
    loc, conf, landmarks, priors = self.__detect_faces(image)
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 156, in __detect_faces
    loc, conf, landmarks = self(inputs)
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 121, in forward
    out = self.body(inputs)
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/torchvision/models/_utils.py", line 69, in forward
    x = module(x)
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/torch/nn/functional.py", line 2438, in batch_norm
    return torch.batch_norm(
RuntimeError: Placeholder storage has not been allocated on MPS device!
```

**Comment by lstein** [comment]
Tagging the MPS experts here: @magnusviri @mh-dm

**Comment by Any-Winter-4079** [comment]
I had that same error for Textual Inversion. My solution was to upgrade to `pytorch-lightning 1.7.5`.
If it doesn't work, let me know and I'll investigate.

**Comment by AndyQ** [comment]
I did try upgrading pytorch-lightning to 1.7.5 (it also upgraded a couple of other components too) but it broke some other things (on Mac), so I had to downgrade again.

**Comment by Any-Winter-4079** [comment]
What did it break?

**Comment by AndyQ** [comment]
Installing pytorch-lightning  1.7.5, downgrades protobuf from 3.20.1 to 3.19.5, and upgrades tensorboard from 2.9.0 to 2.10.0

When I run dream.py. I then get:

```
(ldm) ➜  stable-diffusion git:(development) ✗ python scripts/dream.py --full_precision
* Initializing, be patient...

Traceback (most recent call last):
  File "/Users/andy/dev/mac/StableDiffusion/stable-diffusion/scripts/dream.py", line 355, in <module>
    main()
  File "/Users/andy/dev/mac/StableDiffusion/stable-diffusion/scripts/dream.py", line 38, in main
    from ldm.generate import Generate
  File "/Users/andy/dev/mac/StableDiffusion/stable-diffusion/ldm/generate.py", line 24, in <module>
    from pytorch_lightning import seed_everything, logging
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/loggers/__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/tensorboard/compat/proto/event_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/andy/.asdf/installs/python/anaconda3-2022.05/envs/ldm/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6google8protobuf2io17CodedOutputStreamC1EPNS1_20ZeroCopyOutputStreamEb'
```

**Comment by Any-Winter-4079** [comment]
Yep, I am using
` tensorboard               2.10.0                   pypi_0    pypi` after upgrading `pytorch-lightning`
I'll have to check. One difference I see is Python version (3.9 for me)

**Comment by jdries3** [comment]
If you downgrade protobuf to 3.19.4 it will fix the symbol not found in flat namespace issue.

See https://github.com/protocolbuffers/protobuf/issues/10571

**Comment by AndyQ** [comment]
OK, so downgrading protobuf to 3.19.4 indeed did fix the symbol not found in flat namespace issue, however, when running again (with the upgrade to pytorch-lightning), I get the original error:
RuntimeError: Placeholder storage has not been allocated on MPS device!

**Comment by Vargol** [comment]
Thats a PyTorch error

from aten/src/ATen/native/mps/OperationUtils.mm  line 242

```
Placeholder::Placeholder(MPSGraphTensor* mpsGraphTensor, const Tensor& src, MPSShape *mpsShape) : _tensor(src)
{
  TORCH_CHECK(src.is_mps(), "Placeholder storage has not been allocated on MPS device!");
  // extract the pointer to MTLBuffer from the Tensor's storage
  id<MTLBuffer> srcBuf = getMTLBufferStorage(src);
```

**Comment by Vargol** [comment]
Quickly hacking the codeformer to use the CPU makes thing work okay.

                                if self.codeformer is not None:
                                    image = self.codeformer.process(image=image, strength=strength, device="cpu", seed=seed, fidelity=codeformer_fidelity)
                                else:
                                    print('>> CodeFormer not found. Face restoration is disabled.')
                            else:

The error seems to be coming from facexlib, looking to see if I can hack that to cpu only and leave codeformer

Obvs a proper fix is needed as I assume it works on CUDA.

**Comment by Vargol** [comment]
Okay, so the issue does seem to come from face lib, unfortunately once codeformer is running on MPS I get bad results

![image](https://user-images.githubusercontent.com/62868/192045772-e06672b3-ca40-4484-954d-00534bfe9046.png)

I'm ran a pure cpu test using the code changes below to run CodeFormer and thus Facexlib on the CPU.

```
                             if facetool == 'codeformer':
                                 if self.codeformer is not None:
-                                    image = self.codeformer.process(image=image, strength=strength, device=self.device, seed=seed, fidelity=codeformer_fidelity)
+                                    cf_device = 'cpu' if str(self.device) == 'mps' else self.device
+                                    print('device ' + str(cf_device)) 
+                                    image = self.codeformer.process(image=image, strength=strength, device=cf_device, seed=seed, fidelity=codeformer_fidelity)
                                 else:
                                     print('>> CodeFormer not found. Face restoration is disabled.')

```

And that seems to work, I get this  three faces from the same seed

![image](https://user-images.githubusercontent.com/62868/192064746-e96a08b5-1f92-41b6-ab50-55cb873081f7.png)

Real ERSGAN, CodeFormers and No Face Restoration respectively


For anyone wondering I hacked around 
https://github.com/invoke-ai/InvokeAI/issues/768
to run CodeFormers. Not code suitable for a fix though.

**Comment by Vargol** [comment]
Raised PR https://github.com/invoke-ai/InvokeAI/pull/779/commits to work around this issue

**Comment by Any-Winter-4079** [comment]
Okay, finally finished the Sampler tips and updated to the latest dev branch as well.

Testing this, the first thing I'm observing is:
`a photorealistic portrait of a nice cute girl -ft codeformer` works but I assume doesn't use codeformer
`a photorealistic portrait of a nice cute girl -ft codeformer -U 2` works but I assume doesn't use codeformer
`a photorealistic portrait of a nice cute girl -ft codeformer -G 0.8` fails trying to use codeformer

So the first thing I'll say is the help message looks a bit confusing to me.
```
Post-processing:
  -ft FACETOOL, --facetool FACETOOL
                        Select the face restoration AI to use: gfpgan, codeformer
  -G GFPGAN_STRENGTH, --gfpgan_strength GFPGAN_STRENGTH
                        The strength at which to apply the face restoration to the result.
  -cf CODEFORMER_FIDELITY, --codeformer_fidelity CODEFORMER_FIDELITY
                        Used along with CodeFormer. Takes values between 0 and 1. 0 produces high quality but low accuracy. 1 produces high accuracy but low quality.
  -U UPSCALE [UPSCALE ...], --upscale UPSCALE [UPSCALE ...]
                        Scale factor (2, 4) for upscaling final output followed by upscaling strength (0-1.0). If strength not specified, defaults to 0.75
```

`-G GFPGAN_STRENGTH` makes me think -G only needs to be passed for gfpgan in
` Select the face restoration AI to use: gfpgan, codeformer`
but it looks like it needs to be passed for codeformer as well

**Comment by Any-Winter-4079** [comment]
By the way, a second thing to improve is in the output:
`a photorealistic portrait of a nice cute girl -ft codeformer -G 0.6` produces:
`"a photorealistic portrait of a nice cute girl" -s 50 -S 429279781 -W 512 -H 512 -C 7.5 -A k_lms -G 0.6`
which doesn't show `-ft codeformer`
so you wouldn't get the same image running the same command.

**Comment by Any-Winter-4079** [comment]
About @Vargol's fix to run on CPU, for the time being it works and it's not a time consuming process, so the benefit of running on `mps` isn't going to be very big.
