### ISSUE TITLE
Server Error KeyError: 'middle_block_out.0.weight'

### ISSUE THREAD

**Issue by lunatico67** [invoke-ai/InvokeAI#7132]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4090

### Version number

5.11

### Browser

Microsoft Edge 

### What happened

When i apply controlnet appears this error:
Server Error
KeyError: 'middle_block_out.0.weight'

### What you expected to happen

That works well

**Comment by psychedelicious** [comment]
This typically means you've got a mismatch of controlnet model and base/main model. For example, using a SDXL controlnet for SD1.5. Please double-check that.

If that isn't the cause, please share the specific models you are using (main model and controlnet model).

**Comment by lunatico67** [comment]
> This typically means you've got a mismatch of controlnet model and base/main model. For example, using a SDXL controlnet for SD1.5. Please double-check that.
> 
> If that isn't the cause, please share the specific models you are using (main model and controlnet model).

Hi
Thanks for the help Psychedelicious.
Error:
[2024-10-17 00:17:39,931]::[InvokeAI]::ERROR --> Error while invoking session cb36cbf8-c12b-4d51-9661-448ab2cfdfe0, invocation 20cf05a8-233f-48ef-bd1d-ead572891a94 (denoise_latents): 'middle_block_out.0.weight'
[2024-10-17 00:17:39,931]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 790, in invoke
    return self._old_invoke(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 1022, in _old_invoke
    controlnet_data = self.prep_control_data(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 437, in prep_control_data
    control_model = exit_stack.enter_context(context.models.load(control_info.control_model))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 370, in load
    return self._services.model_manager.load.load_model(model, _submodel_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\app\services\model_load\model_load_default.py", line 70, in load_model
    ).load_model(model_config, submodel_type)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 56, in load_model
    locker = self._load_and_cache(model_config, submodel_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 77, in _load_and_cache
    loaded_model = self._load_model(config, submodel_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\invokeai\backend\model_manager\load\model_loaders\controlnet.py", line 31, in _load_model
    return ControlNetModel.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\diffusers\loaders\controlnet.py", line 124, in from_single_file
    component = create_diffusers_controlnet_model_from_ldm(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\diffusers\loaders\single_file_utils.py", line 973, in create_diffusers_controlnet_model_from_ldm
    diffusers_format_controlnet_checkpoint = convert_controlnet_checkpoint(checkpoint, diffusers_config)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luna\invokeai\.venv\Lib\site-packages\diffusers\loaders\single_file_utils.py", line 937, in convert_controlnet_checkpoint
    new_checkpoint["controlnet_mid_block.weight"] = controlnet_state_dict.pop("middle_block_out.0.weight")
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'middle_block_out.0.weight'





![Invoke__Error](https://github.com/user-attachments/assets/880cd9d3-2c8e-470b-8673-e857f528b557)

**Comment by cdmusic2019** [comment]
Search for and download models from the model manager, 'starter models ', so they don't load incorrectly. @lunatico67

**Comment by lunatico67** [comment]
> Search for and download models from the model manager, 'starter models ', so they don't load incorrectly. @lunatico67

Thanks for the information cdmusic2019.
All the models: checkpoints, loras, controlnet, vae.... I have installed them through Scan Folder choosing their source folders located in ComfyUI. Invoke ai loads checkpoints fine but for some unknown reason controlnet does not. I will follow your advice, I will install all the models from Starter Models and report back.

**Comment by cdmusic2019** [comment]
Yes, I started to install 'xinsir-contronet' by scanning the local folder and got the same error as you, then I downloaded it from the model manager and it worked fine. @lunatico67

**Comment by lunatico67** [comment]
@cdmusic2019  @psychedelicious 

Thanks for your help cgmusic2019 and psychedelicious, you have solved it. 
Psychedelicious thank you so much for creating and sharing such a beautiful artistic treasure.

As cgmusic2019 i installed the controlnet models through scan folder but they were not working. Through Starter Models are installed with the default names and their corresponding .json and they work perfectly!

Several questions arise on this subject:

1} - I have not been able to install any model through Huggingface, how can I do it?
I have tried copying and pasting the page address in Model Card, in Files and versions and copying and pasting the clone repository from both and when I click Install Repo nothing happens.

2} - I have installed several main models through civitai and they work but there are many loras that can not be installed; I put a few but there are many more:

https://civitai.com/models/200255?modelVersionId=953008

https://civitai.com/models/124347/xlmoreart-full-xlreal-enhancer?modelVersionId=152309

https://civitai.com/models/229213/extremely-detailed-no-trigger-slidersntcaixyz?modelVersionId=383563

https://civitai.com/models/251417/midjourney-mimic?modelVersionId=678485

https://civitai.com/models/200251/feet-xl-sd-15-flux1-dev?modelVersionId=471781

https://civitai.com/models/411088/detailed-perfection-style-xl-f1d-sd15-hands-feet-face-body-all-in-one?modelVersionId=458257

3} - In Starter Models you can install sdxl-vae-fp16-fix. I have several main fp32 models, can someone pass the link to sdxl-vae-fp32-fix?

4} - Are the playground, Stable cascade, kolors and AuraFlow models compatible with Invoke?

5} - There are several Sdxl inpainting models that cannot be installed in invoke, is it because they are incompatible?

https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1/tree/main

https://civitai.com/models/620368/realvisxl-inpainting

https://civitai.com/models/620440/lustify-sdxl-nsfw-inpainting

https://civitai.com/models/441879/haveallsdxl-inpaint
