### ISSUE TITLE
[bug]: v5.2.0 fails to start with Import Error [...] libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12

### ISSUE THREAD

**Issue by DivineOmega** [invoke-ai/InvokeAI#7141]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA GeForce RTX 3060

### GPU VRAM

12GB

### Version number

5.2.0

### Browser

Brave Version 1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit)

### What happened

When selecting item [1] Generate images with a browser-based interface in v5.2.0 (and its release candidates), I receive the following error in the terminal and Invoke does not start.

```
Generate images with a browser-based interface
Traceback (most recent call last):
  File "/media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/bin/invokeai-web", line 8, in <module>
    sys.exit(run_app())
             ^^^^^^^^^
  File "/media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/lib/python3.11/site-packages/invokeai/app/run_app.py", line 10, in run_app
    from invokeai.app.api_app import invoke_api
  File "/media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/lib/python3.11/site-packages/invokeai/app/api_app.py", line 8, in <module>
    import torch
  File "/media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/lib/python3.11/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/lib/python3.11/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

### What you expected to happen

I expect Invoke to start as with previous versions.

### How to reproduce the problem

Start the app with `./invoke.sh` and choose [1] Generate images with a browser-based interface.

### Additional context

Running using Python 3.11.10 in a conda environment.

**Comment by DivineOmega** [comment]
`nvidia-smi` output:

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.107.02             Driver Version: 550.107.02     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:01:00.0  On |                  N/A |
|  0%   49C    P5             21W /  170W |     956MiB /  12288MiB |     28%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by psychedelicious** [comment]
Please try in a venv with pip to rule out conda shenanigans.

**Comment by DivineOmega** [comment]
I'm running Ubuntu 24.04.1 LTS which comes with Python 3.12. 

The InvokeAI installer does not run with this Python version, so I was using conda to easily run it under Python 3.11, which has worked in previous versions without issue.

I don't think I can use a venv with an different Python version without multiple Python versions being installed at the system level?

**Comment by DivineOmega** [comment]
I've managed to get this working by using the v5.1.1 installer to install v5.2.0.

This suggests the v5.2.0 installer is missing something, perhaps? Could it be related to the new nvidia installation options?

**Comment by psychedelicious** [comment]
Yeah, probably same root cause as this issue: https://github.com/invoke-ai/InvokeAI/issues/7142

Will get that fixed ASAP

**Comment by DivineOmega** [comment]
Unfortunately the v5.3.0rc1 install causes the same issue.

However, I can install v5.3.0rc1 using the v5.1.1 installer, and the install is not present.

**Comment by psychedelicious** [comment]
I still suspect conda. The installer doesn't do anything fancy. It just pip installs the package with a specific index url. 

You could use https://github.com/pyenv/pyenv to install python 3.11 alongside 3.12. It's very easy to use. Set the python version to 3.11 before the invoke install, then set it back to 3.12 after. Invoke will "remember" the python version used for the install and continue to use it, so long as you don't uninstall 3.11.

**Comment by DivineOmega** [comment]
I've deactivated and removed my conda environment for invoke, and then performed the following steps.

```bash
pyenv install 3.11
pyenv global 3.11.10
./install.sh
# Go through installer selecting 5.3.0rc1, fresh install directory, and option 1 on GPU selection
# cd to relevant directory
./invoke.sh
# Select option 1 (generate images)
```

Unfortunately I still get the same error:

```
Generate images with a browser-based interface
Traceback (most recent call last):
  File "/media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/bin/invokeai-web", line 8, in <module>
    sys.exit(run_app())
             ^^^^^^^^^
  File "/media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/lib/python3.11/site-packages/invokeai/app/run_app.py", line 10, in run_app
    from invokeai.app.api_app import invoke_api
  File "/media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/lib/python3.11/site-packages/invokeai/app/api_app.py", line 8, in <module>
    import torch
  File "/media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/lib/python3.11/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /media/jordan/d4534942-ac20-40e9-ab99-6c02baeea3a2/invokeai/.venv/lib/python3.11/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

**Comment by DivineOmega** [comment]
Bizarrely, I've had to run the following before starting Invoke:

```
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libnvJitLink.so.12
```

I'm not sure why my LD library path did not reference this part of the NVIDIA driver / CUDA automatically, and I'm not sure why it is only affecting InvokeAI, and specifically only InvokeAI installs done with the InvokeAI installer v5.2.0 or above.

---

So this appears to be at least partially my setup, but I'm not sure what the root cause is, nor why is only affects InvokeAI and specific version of it when installed via specific installer versions.

**Comment by DivineOmega** [comment]
Also worth noting this is running fine under conda again now, so it seems it was not related to the python environment at all.

**Comment by psychedelicious** [comment]
Fun! And good to know `conda` wasn't related. Sorry for sending you down the garden path there.

In v5.2.0 we did make some changes to the installer so that `torch` installs from the correct PyPI indices: https://github.com/invoke-ai/InvokeAI/pull/7065/files

Since you've narrowed down the issue to the installer, I suppose it's related to that change.
