### ISSUE TITLE
[bug]: Crash when using t2i adapter

### ISSUE THREAD

**Issue by CubeTheThird** [invoke-ai/InvokeAI#7144]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

AMD (ROCm)

### GPU model

RX 6700XT

### GPU VRAM

12GB

### Version number

5.1.0

### Browser

Firefox 131.0.3 

### What happened

Crash when using a t2i adapter

### What you expected to happen

Generation to complete

### How to reproduce the problem

- Add the base image from [Community Challenge 21](https://discord.com/channels/1020123559063990373/1295767378621104185) as a control layer.
- Set the control type to t2i adapter
- Adjust the image scale according to the recommendation, to make its dimensions factors of 32
- Press Invoke

### Additional context

Crash log as follows:
```
[2024-10-15 16:20:15,989]::[InvokeAI]::ERROR --> Error while invoking session b936e609-987b-4028-9df0-fb3a63dbecef, invocation 88b8c854-e8da-4a0c-b4f5-c9c8661ef3cf (denoise_latents): The size of tensor a (77) must match the size of tensor b (76) at non-singleton dimension 3
[2024-10-15 16:20:15,989]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "./lib/python3.10/site-packages/invokeai/app/services/session_processor/session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "./lib/python3.10/site-packages/invokeai/app/invocations/baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
  File "./lib/python3.10/site-packages/invokeai/app/invocations/denoise_latents.py", line 790, in invoke
    return self._old_invoke(context)
  File "./lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "./lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "./lib/python3.10/site-packages/invokeai/app/invocations/denoise_latents.py", line 1050, in _old_invoke
    result_latents = pipeline.latents_from_embeddings(
  File "./lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 379, in latents_from_embeddings
    step_output = self.step(
  File "./lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "./lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 514, in step
    uc_noise_pred, c_noise_pred = self.invokeai_diffuser.do_unet_step(
  File "./lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 199, in do_unet_step
    ) = self._apply_standard_conditioning(
  File "./lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 343, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
  File "./lib/python3.10/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 577, in _unet_forward
    return self.unet(
  File "./lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "./lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "./lib/python3.10/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1228, in forward
    sample += down_intrablock_additional_residuals.pop(0)
RuntimeError: The size of tensor a (77) must match the size of tensor b (76) at non-singleton dimension 3
```

### Discord username

cubethethird

**Comment by SherLock707** [comment]
@CubeTheThird Are you atleast able to do regular image generation with 6700xt?

**Comment by CubeTheThird** [comment]
At present I am unable to reproduce this issue, so I will leave it closed for the time being.
