### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by z0rge** [invoke-ai/InvokeAI#7155]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX4090 i9

### GPU VRAM

64GB

### Version number

5.2.0

### Browser

Opera one 114.0.5282.102, Pinokio 2.15.1(with xformers)

### Python dependencies

{
  "accelerate": "0.30.1",
  "compel": "2.0.2",
  "cuda": "12.4",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.16.1",
  "pillow": "11.0.0",
  "python": "3.10.6",
  "torch": "2.4.1+cu124",
  "torchvision": "0.19.1+cu124",
  "transformers": "4.41.1",
  "xformers": null
}

### What happened

Flux Union Controlnet doesn't work and give that in console
 [2024-10-21 18:32:27,967]::[InvokeAI]::ERROR --> Error while invoking session 0e026243-71a7-43be-9278-277eaed20c77, invocation 22120cc4-761a-4785-a870-06903a6fcc90 (flux_denoise): Error while deserializing header: MetadataIncompleteBuffer
[2024-10-21 18:32:27,967]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\app\invocations\flux_denoise.py", line 105, in invoke
    latents = self._run_diffusion(context)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\app\invocations\flux_denoise.py", line 210, in _run_diffusion
    controlnet_extensions = self._prep_controlnet_extensions(
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\app\invocations\flux_denoise.py", line 338, in _prep_controlnet_extensions
    controlnet_models = [context.models.load(controlnet.control_model) for controlnet in controlnets]
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\app\invocations\flux_denoise.py", line 338, in <listcomp>
    controlnet_models = [context.models.load(controlnet.control_model) for controlnet in controlnets]
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 370, in load
    return self._services.model_manager.load.load_model(model, _submodel_type)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\app\services\model_load\model_load_default.py", line 70, in load_model
    ).load_model(model_config, submodel_type)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 56, in load_model
    locker = self._load_and_cache(model_config, submodel_type)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 77, in _load_and_cache
    loaded_model = self._load_model(config, submodel_type)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_loaders\flux.py", line 327, in _load_model
    sd = load_file(model_path)
  File "D:\_AI\Invokeai\.venv\lib\site-packages\safetensors\torch.py", line 311, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer 

### What you expected to happen

I expected that Flux controlnet will work)

### How to reproduce the problem

choose Flux Dev(Quanisated) add raster image and Flux Union Controlnet

**Comment by psychedelicious** [comment]
This error typically means the model didn't download fully. Try disabling it and re-downloading it.
