### ISSUE TITLE
[bug]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by sansu12138** [invoke-ai/InvokeAI#7216]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Apple Silicon (MPS)

### GPU model

Apple M2

### GPU VRAM

16GB

### Version number

5.3.0

### Browser

Google Chrome130.0.6723.70

### Python dependencies

```
{
  "name": "NotFoundError",
  "message": "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.",
  "stack": "NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.\n    at HX (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:26115)\n    at jl (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:25802)\n    at HX (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:26551)\n    at ls (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:27408)\n    at WX (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:27868)\n    at ls (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:27558)\n    at WX (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:27671)\n    at ls (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:27558)\n    at WX (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:27671)\n    at ls (http://127.0.0.1:9090/assets/index-BQPuxPiy.js:41:27558)",
  "code": 8
}
```

### What happened

I clicked on invoke and got this error

### What you expected to happen

I wish I didn't have this error message

**Comment by psychedelicious** [comment]
- Is this your first install or an update? If it was an update, do you remember what version you had previously?
- Does clicking the Reset button on the error screen fix it?
