### ISSUE TITLE
[bug]: Can't use select object tool

### ISSUE THREAD

**Issue by alex-des-santos** [invoke-ai/InvokeAI#7243]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4070

### GPU VRAM

12

### Version number

5.3

### Browser

Microsft Edge

### Python dependencies

{
  "accelerate": "0.30.1",
  "compel": "2.0.2",
  "cuda": "12.4",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.16.1",
  "pillow": "11.0.0",
  "python": "3.10.6",
  "torch": "2.4.1+cu124",
  "torchvision": "0.19.1+cu124",
  "transformers": "4.41.1",
  "xformers": null
}

### What happened

When I mark an object in an image, I receive an error in the browser and in the console.

### What you expected to happen

Detect and select object.

### How to reproduce the problem

start app
select a image
raster layer
select object
mark object

### Discord username

alexxsalles

**Comment by alex-des-santos** [comment]
I just figured out. 

Just clone the repo git clone https://huggingface.co/facebook/sam-vit-huge to the folder InvokeAi\models\.download_cache\facebook_sam-vit-huge
```
[2024-10-31 18:23:52,088]::[InvokeAI]::ERROR --> Error while invoking session 18d29b3a-b71e-4011-98d1-62743e3c2e60, invocation be43fb97-3e54-44b2-b4da-aee2a867816f (segment_anything): Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory J:\SD_Interfaces\InvokeAi_Desktop\models\.download_cache\facebook_sam-vit-huge\sam-vit-huge.
[2024-10-31 18:23:52,088]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\invokeai\app\invocations\segment_anything.py", line 98, in invoke
    masks = self._segment(context=context, image=image_pil)
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\invokeai\app\invocations\segment_anything.py", line 132, in _segment
    context.models.load_remote_model(
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 517, in load_remote_model
    return self._services.model_manager.load.load_model_from_path(model_path=model_path, loader=loader)
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\invokeai\app\services\model_load\model_load_default.py", line 111, in load_model_from_path
    raw_model = loader(model_path)
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\invokeai\app\invocations\segment_anything.py", line 110, in _load_sam_model
    sam_model = AutoModelForMaskGeneration.from_pretrained(
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "J:\SD_Interfaces\InvokeAi_Desktop\.venv\lib\site-packages\transformers\modeling_utils.py", line 3305, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory J:\SD_Interfaces\InvokeAi_Desktop\models\.download_cache\facebook_sam-vit-huge\sam-vit-huge.

[2024-10-31 18:23:52,108]::[InvokeAI]::INFO --> Graph stats: 18d29b3a-b71e-4011-98d1-62743e3c2e60
                          Node   Calls   Seconds  VRAM Used
              segment_anything       1    0.012s     0.000G
TOTAL GRAPH EXECUTION TIME:   0.012s
TOTAL GRAPH WALL TIME:   0.012s
RAM used by InvokeAI process: 1.37G (+0.004G)
RAM used to load models: 0.00G
RAM cache statistics:
   Model cache hits: 0
   Model cache misses: 1
   Models cached: 0
   Models cleared from cache: 0
   Cache high water mark: 0.00/0.00G

[2024-10-31 18:23:52,116]::[uvicorn.access]::INFO --> 127.0.0.1:58347 - "GET /assets/images/invoke-alert-favicon.svg HTTP/1.1" 200
[2024-10-31 18:23:52,147]::[uvicorn.access]::INFO --> 127.0.0.1:58347 - "PUT /api/v1/queue/default/cancel_by_batch_ids HTTP/1.1" 200
[2024-10-31 18:23:52,163]::[uvicorn.access]::INFO --> 127.0.0.1:58346 - "GET /api/v1/queue/default/current HTTP/1.1" 200
[2024-10-31 18:23:52,166]::[uvicorn.access]::INFO --> 127.0.0.1:58347 - "GET /assets/images/invoke-favicon.svg HTTP/1.1" 200
[2024-10-31 18:23:52,182]::[uvicorn.access]::INFO --> 127.0.0.1:58347 - "GET /api/v1/queue/default/status HTTP/1.1" 200
[2024-10-31 18:23:52,184]::[uvicorn.access]::INFO --> 127.0.0.1:58346 - "GET /api/v1/queue/default/counts_by_destination?destination=canvas HTTP/1.1" 200
```

**Comment by psychedelicious** [comment]
Thanks. Looks like the model didn't download correctly initially. If anybody else runs into this, you can delete `models/.download_cache/facebook_sam-vit-huge` and when you next start the select object process, it will download the model in the background.
