### ISSUE TITLE
development branch - web ui - TypeError: image_done() got an unexpected keyword argument 'first_seed'

### ISSUE THREAD

**Issue by jspraul** [invoke-ai/InvokeAI#751]
**Describe your environment**
- GPU: cuda
- VRAM: 4gb
- CPU arch: x86
- OS: Windows
- Python: miniconda
- Branch: development
- Commit: f1d4862b132a3c604db9632862192f24fe01b3bd Wed Sep 21 17:09:29 2022 -0400

**Describe the bug**
Web UI - TypeError: image_done() got an unexpected keyword argument 'first_seed'

**To Reproduce**
1. `python scripts/dream.py --web --no_restore`
2. http://127.0.0.1:9090/
3. Enter prompt and click 'Generate'
4. Wait while image is generated
5. alert: 'Error message occurred while generating.'

**Expected behavior**
Stable diffusion, in the browser!

**Stack Trace**
```
Error happened
image_done() got an unexpected keyword argument 'first_seed'
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51339)
Traceback (most recent call last):
  File "…\miniconda3\envs\ldm\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "…\miniconda3\envs\ldm\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "…\miniconda3\envs\ldm\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "…\miniconda3\envs\ldm\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "…\miniconda3\envs\ldm\lib\http\server.py", line 415, in handle_one_request
    method()
  File "…\downloads\stable-diffusion\ldm\dream\server.py", line 267, in do_POST
    raise e
  File "…\downloads\stable-diffusion\ldm\dream\server.py", line 241, in do_POST
    self.model.prompt2image(**vars(opt), step_callback=image_progress, image_callback=image_done)
  File "…\downloads\stable-diffusion\ldm\generate.py", line 411, in prompt2image
    results = generator.generate(
  File "…\downloads\stable-diffusion\ldm\dream\generator\base.py", line 75, in generate
    image_callback(image, seed, first_seed=first_seed)
TypeError: image_done() got an unexpected keyword argument 'first_seed'
----------------------------------------
```
**Additional context**
https://github.com/invoke-ai/InvokeAI/blob/f1d4862b132a3c604db9632862192f24fe01b3bd/ldm/dream/server.py#L164
called by 
https://github.com/invoke-ai/InvokeAI/blob/f1d4862b132a3c604db9632862192f24fe01b3bd/ldm/dream/generator/base.py#L75

**Comment by jspraul** [comment]
Dupe of [WebUI img2img got an unexpected keyword argument 'first_seed'](https://github.com/invoke-ai/InvokeAI/issues/747)
