### ISSUE TITLE
New server on dev branch won't run on macOS m1

### ISSUE THREAD

**Issue by sjmarshy** [invoke-ai/InvokeAI#753]
**Describe your environment**
- GPU: mps
- CPU arch: arm
- OS: macos (m1 pro)
- Python: Anaconda
- Branch:development
- Commit: Merge: 110c4f7 28f06c7

**Describe the bug**

Cannot run `python3 backend/server.py` without error. 

To be clear - `python3 scripts/dream.py` works just fine. The new web server command however results in the error message:

```
Traceback (most recent call last):
  File "/Users/sjm/repos/lstein-stable-diffusion/backend/server.py", line 6, in <module>
    import eventlet
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/eventlet/convenience.py", line 4, in <module>
    from eventlet import greenpool
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/eventlet/greenpool.py", line 4, in <module>
    from eventlet import queue
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/eventlet/queue.py", line 49, in <module>
    from eventlet.event import Event
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/eventlet/event.py", line 3, in <module>
    from eventlet import hubs
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/eventlet/hubs/__init__.py", line 7, in <module>
    from eventlet.support import greenlets as greenlet
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/eventlet/support/__init__.py", line 6, in <module>
    from eventlet.support import greenlets
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
  File "/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: dlopen(/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/greenlet/_greenlet.cpython-310-darwin.so, 0x0002): tried: '/Users/sjm/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/greenlet/_greenlet.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

I did set up the conda environment with the line `PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yaml` and as stated, everything else works fine - so I'm a little stumped.

**Comment by Any-Winter-4079** [comment]
To know the arch, you can run
```
import platform
platform.platform()
```
If you indeed have arm64, that message is weird indeed. Maybe the library you have installed is for x86?

**Comment by OrcsDev** [comment]
Getting this as well.  


running "uname -a" from command line I get:

Darwin MacBook-Pro 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

**Comment by OrcsDev** [comment]
So I was able to fix this by uninstalling tokenizers with pip and reinstalling it with conda.

Run:
pip uninstall tokenizers

wait for it to finish then:
conda install tokenizers

**Comment by sjmarshy** [comment]
I was able to solve this with similar to @OrcsDev - in my case it was 

```
pip uninstall greenlet
...
conda install greenlet
```
