### ISSUE TITLE
Running development branch with either conda or pew failing on Windows

### ISSUE THREAD

**Issue by PutUsernameHere** [invoke-ai/InvokeAI#757]
- GPU: cuda
- VRAM: 11GB
- CPU arch: x86
- OS: Windows 10
- Python: Anaconda
- Branch: development
- Commit: f1d4862b132a3c604db9632862192f24fe01b3bd

**Describe the bug**
When trying to run the development branch in either pew or conda, I get at similar points in the execution. I have tried both methods, but they both appear to have similar issues.

Conda error:
```
Traceback (most recent call last):
  File "D:\Stable_Diffusion\stable-diffusion-lsteinDEV\scripts\dream.py", line 454, in <module>
    main()
  File "D:\Stable_Diffusion\stable-diffusion-lsteinDEV\scripts\dream.py", line 107, in main
    gen.load_model()
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\generate.py", line 665, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\generate.py", line 804, in _load_model_from_config
    model = instantiate_from_config(c.model)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\models\diffusion\ddpm.py", line 657, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\models\diffusion\ddpm.py", line 768, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\modules\encoders\modules.py", line 245, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\site-packages\transformers\tokenization_utils_base.py", line 1768, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
```
Pew error:
```
Traceback (most recent call last):
  File "D:\Stable_Diffusion\stable-diffusion-lsteinDEV\scripts\dream.py", line 454, in <module>
    main()
  File "D:\Stable_Diffusion\stable-diffusion-lsteinDEV\scripts\dream.py", line 107, in main
    gen.load_model()
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\generate.py", line 665, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\generate.py", line 804, in _load_model_from_config
    model = instantiate_from_config(c.model)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\models\diffusion\ddpm.py", line 657, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\models\diffusion\ddpm.py", line 768, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\modules\encoders\modules.py", line 245, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(
  File "C:\Users\Andrew\.virtualenvs\stable-diffusion\lib\site-packages\transformers\tokenization_utils_base.py", line 1750, in from_pretrained
    commit_hash = extract_commit_hash(resolved_vocab_files[file_id], commit_hash)
  File "C:\Users\Andrew\.virtualenvs\stable-diffusion\lib\site-packages\transformers\utils\hub.py", line 225, in extract_commit_hash
    search = re.search(r"snapshots/([^/]+)/", resolved_file)
  File "C:\Python310\lib\re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

1. Install using either the standard Windows install instructions or the easy peasy installation method.
2. Use corresponding method to activate environment (conda or pew)
3. run `python scripts\dream.py --web` (on pew, `"C:\Program Files\Git\usr\bin\winpty.exe" python scripts\dream.py --web`)

I've been running the main release branch with no issues with installation or running the the script itself. I was using the standard installation method using conda as listed in the readme, but since it wasn't working for the development branch I thought that the easy peasy method might work, but it seems to have a similar issue.

**Comment by lstein** [comment]
You need to run `scripts/preload_models.py` before running the web or CLI scripts for the first time.

**Comment by PutUsernameHere** [comment]
I had already run preload_models.py but running it again seems to let me run `python scripts/dream.py --web`. Pew is still giving me the same error so I wonder if there's something different about how it works with pew.
Though now the web version (`dream.py --web`) fails after image generation with
```
Error happened
image_done() got an unexpected keyword argument 'first_seed'
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56141)
Traceback (most recent call last):
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\http\server.py", line 425, in handle
    self.handle_one_request()
  File "C:\Users\Andrew\anaconda3\envs\ldm\lib\http\server.py", line 413, in handle_one_request
    method()
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\dream\server.py", line 267, in do_POST
    raise e
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\dream\server.py", line 241, in do_POST
    self.model.prompt2image(**vars(opt), step_callback=image_progress, image_callback=image_done)
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\generate.py", line 411, in prompt2image
    results = generator.generate(
  File "d:\stable_diffusion\stable-diffusion-lsteindev\ldm\dream\generator\base.py", line 75, in generate
    image_callback(image, seed, first_seed=first_seed)
TypeError: image_done() got an unexpected keyword argument 'first_seed'
```
Running it in the CLI seems to work fine though. The webserver interface looks more like the old one than the screenshots I've seen of the new one though, is there something I'm doing wrong to activate it?

**Comment by jspraul** [comment]
The [first_seed issue in the old web UI](https://github.com/invoke-ai/InvokeAI/issues/747) has been resolved if you pull latest.

**Comment by PutUsernameHere** [comment]
Oh awesome that fixed the webserver thing thanks. The pew installation method is still giving me the same initial error as above but it appears to be working fine with conda

**Comment by tildebyte** [comment]
Either Huggingface's 'transformers' lib introduced a regression in v4.22, or we changed how we're using 'transformers' in such a way that we break when using v4.22.

I'll open a PR to pin 'transformers' to '4.21.*'

Meanwhile, either add `transformers==4.21.*` to 'requirements' manually and build a new venv, or try to fix existing installs with `pip install --upgrade "transformers==4.21.*"` (remember to run when the venv is activated).

**Comment by PutUsernameHere** [comment]
That did it thanks! Pew seems to be working fine now! If it matters, I think the reason why the conda version was working fine was that it was running version 4.19.2 of transformers for some reason.

**Comment by tildebyte** [comment]
> I think the reason why the conda version was working fine was that it was running version 4.19.2 of transformers for some reason.

Yeah, I noticed that it was pinned for conda installs, but we don't require a version as old as that
