### ISSUE TITLE
New webUI: generate fails when "Display in-progress images" is enabled

### ISSUE THREAD

**Issue by timdesrochers** [invoke-ai/InvokeAI#758]
**Describe your environment**
- GPU: cpu (I think)
- VRAM: 8 GB
- CPU arch: x86
- OS: Linux
- Python: Anaconda
- Branch: development
- Commit: `commit f1d4862b132a3c604db9632862192f24fe01b3bd (HEAD -> development, origin/development, d4fce6e)`  

**Describe the bug**
The new web ui works normally, but when the "Display in-progress images" checkbox is turned on via the Settings wheel in the top right, nothing is generated or output, and the following traceback is thrown:
```
Traceback (most recent call last):
  File "/home/InvokeAI/backend/server.py", line 744, in generate_images
    generate.prompt2image(
  File "/home/InvokeAI/ldm/generate.py", line 411, in prompt2image
    results = generator.generate(
  File "/home/InvokeAI/ldm/dream/generator/base.py", line 72, in generate
    image = make_image(x_T)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/InvokeAI/ldm/dream/generator/txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/InvokeAI/ldm/models/diffusion/ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/k_diffusion/sampling.py", line 64, in sample_euler
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigma_hat, 'denoised': denoised})
  File "/home/InvokeAI/ldm/models/diffusion/ksampler.py", line 66, in route_callback
    img_callback(k_callback_values['x'], k_callback_values['i'])
  File "/home/InvokeAI/backend/server.py", line 638, in image_progress
    image = generate.sample_to_image(sample)
  File "/home/InvokeAI/ldm/generate.py", line 748, in sample_to_image
    return self._sample_to_image(samples)
  File "/home/InvokeAI/ldm/generate.py", line 753, in _sample_to_image
    self.base_generator = Generator(self.model)
TypeError: __init__() missing 1 required positional argument: 'precision'
```

**To Reproduce**
1. Start the new web UI  ```$ python backend/server.py --host 0.0.0.0 --precision=float32```
2. Access the GUI from your browser
4. Enter any prompt and hit Generate with a step count >= 2 to verify normal operation
5. Enable "Display in-progress images" via the settings menu in the top-right
6. Hit Generate again for the same or differing prompt, step count >= 2
7. The GUI hangs and after some time, the error message is returned in the console where server.py was started.

**Expected behavior**
Progress images are displayed.

**Screenshots**
n/a

**Additional context**
Confirmed this is not working at least with k_euler, k_euler_a, and ddim; have not checked all samplers. 

I suspect something's not getting handed off somewhere... I'm going to keep poking around.

**Comment by lstein** [comment]
@mh-dm I believe this is another place that needs to be patched to handle the new precision handling.

**Comment by timdesrochers** [comment]
Getting a new error now, something related to path, it seems.

`

Traceback (most recent call last):
  File "/home/user/InvokeAI/backend/server.py", line 795, in generate_images
    image_callback=image_done,
  File "/home/user/InvokeAI/ldm/generate.py", line 413, in prompt2image
    results = generator.generate(
  File "/home/user/InvokeAI/ldm/dream/generator/base.py", line 73, in generate
    image = make_image(x_T)
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/InvokeAI/ldm/dream/generator/txt2img.py", line 34, in make_image
    samples, _ = sampler.sample(
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/InvokeAI/ldm/models/diffusion/ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/site-packages/k_diffusion/sampling.py", line 103, in sample_heun
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigma_hat, 'denoised': denoised})
  File "/home/user/InvokeAI/ldm/models/diffusion/ksampler.py", line 66, in route_callback
    img_callback(k_callback_values['x'], k_callback_values['i'])
  File "/home/user/InvokeAI/backend/server.py", line 678, in image_progress
  File "/home/user/InvokeAI/backend/server.py", line 577, in save_image
    prefix = pngwriter.unique_prefix()
  File "/home/user/InvokeAI/ldm/dream/pngwriter.py", line 20, in __init__
    os.makedirs(outdir, exist_ok=True)
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
`

Only when "display in-progress" is enabled. 

I'm on commit c09e81e21be8c77c2b473aa2ca816f97645923ad
