### ISSUE TITLE
Error downloading gfpgan model

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#766]
**Describe your environment**
- GPU: cpu
- CPU arch: x86_64
- OS: macOs
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)]
- Branch: development

**Describe the bug**
running python3 scripts/preload_models.py fails to download gfpgan model and print following error message:
```
downloading gfpgan model file...
Error loading GFPGAN:
Traceback (most recent call last):
  File "/Users/jakubkolcar/custom/InvokeAI/scripts/preload_models.py", line 95, in <module>
    urllib.request.urlretrieve(model_url,model_dest)
  File "/Users/jakubkolcar/miniconda3/envs/ldm/lib/python3.10/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'src/gfpgan/experiments/pretrained_models/GFPGANv1.3.pth'
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ioma8** [comment]
closing, it was by me having corrupted conda environment
