### ISSUE TITLE
GFPGAN facefix throws exception

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#797]
**Describe your environment**
- GPU: cpu
- VRAM: [if known]
- CPU arch: arm
- OS: macOs
- Python: Anaconda
- Branch: development
- Commit: 636c356aafdeceab646648bcb25ba38c16a49e32

**Describe the bug**
Using the new webUI, I selected image from gallery on right, clicked on Fix faces, and progress bar scrolls infinitely and in console I have this exception. Before it worked fine for me:
```
>> GFPGAN face fix requested for "outputs/img-samples/000381.3977462604.png": {'gfpgan_strength': 0.8}
Exception in thread Thread-435 (_handle_event_internal):
Traceback (most recent call last):
  File "/Users/jakubkolcar/miniconda3/envs/ldm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/jakubkolcar/miniconda3/envs/ldm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jakubkolcar/miniconda3/envs/ldm/lib/python3.10/site-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/jakubkolcar/miniconda3/envs/ldm/lib/python3.10/site-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Users/jakubkolcar/miniconda3/envs/ldm/lib/python3.10/site-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/Users/jakubkolcar/miniconda3/envs/ldm/lib/python3.10/site-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "/Users/jakubkolcar/custom/InvokeAI/backend/server.py", line 313, in handle_run_gfpgan_event
    image = gfpgan.process(
AttributeError: 'NoneType' object has no attribute 'process'
```

**Comment by blessedcoolant** [comment]
@psychedelicious Please update the WebUI script to match the new changes to the restoration module.

**Comment by ioma8** [comment]
@blessedcoolant hmm, I was already on the latest commit. After cleaning git & new preloading of models it works.

**Comment by KeystoneScience** [comment]
@ioma8 I am also running into this issue... could I ask what you meant by 'new preloading of models'?

besides that I ran `git clean -n` Thanks!

**Comment by KeystoneScience** [comment]
actually, for me it was doing the git clean and then turning off "Restore Face" in advanced options.

**Comment by psychedelicious** [comment]
@KeystoneScience you need to run  `scripts/preload_models.py` to download all of the additional models for face restoration and updating to work.

**Comment by KeystoneScience** [comment]
Ahh, i totally skipped over that. Thanks! @psychedelicious
