### ISSUE TITLE
[New UI] attribute error when click on the Fix Faces button

### ISSUE THREAD

**Issue by HugoSega** [invoke-ai/InvokeAI#816]
>> GFPGAN - Restoring Faces for image seed:unknown_seed
Exception in thread Thread-147 (_handle_event_internal):
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/ldm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/user/miniconda3/envs/ldm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user/miniconda3/envs/ldm/lib/python3.10/site-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/user/miniconda3/envs/ldm/lib/python3.10/site-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/Users/user/miniconda3/envs/ldm/lib/python3.10/site-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/Users/user/miniconda3/envs/ldm/lib/python3.10/site-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "/Users/user/InvokeAI-dev/backend/server.py", line 382, in handle_run_gfpgan_event
    "mtime": os.path.mtime(path),
AttributeError: module 'posixpath' has no attribute 'mtime'

**Comment by HugoSega** [comment]
fixed it by replacing code in server.py
 "gfpganResult",
```
        {
            "url": os.path.relpath(path),
            "mtime": os.path.mtime(path),
            "metadata": metadata,
        },
    )
```

with 
```
 "gfpganResult",
        {
            "url": os.path.relpath(path),
            "mtime": os.path.getmtime(path),
            "metadata": metadata,
        },
    )
```

**Comment by lstein** [comment]
This was fixed on Monday.
