### ISSUE TITLE
Error when running gfpgan on web server

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#818]
**Describe your environment**
- GPU: CUDA
- VRAM: 24 GB
- CPU x86
- OS: Linux
- Python: Anaconda, python 3.9
- Branch: development
- Commit: 14616f41786b2282e3686d86b2c79f9ddc95f479

**Describe the bug**
When fixing a face, the backend crashes with this backtrace:

~~~
>> GFPGAN face fix requested for "outputs/img-samples/000003.3697659031.png": {'gfpgan_strength': 0.8}
>> GFPGAN - Restoring Faces for image seed:unknown_seed
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/socketio/server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages/flask_socketio/__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "/u/lstein/projects/SD/InvokeAI/backend/server.py", line 382, in handle_run_gfpgan_event
    "mtime": os.path.mtime(path),
AttributeError: module 'posixpath' has no attribute 'mtime'
~~~

I have heard there are differences in the posixpath capabilities from one architecture to another. For a portable mtime, use `os.path.getmtime`

**Comment by lstein** [comment]
Changing `mtime` to `getmtime` fixed it on my system. I just committed this change as well, as it seems innocuous. Let me know if this is a problem.

**Comment by psychedelicious** [comment]
@lstein That was a typo and I must've not tested GFPGAN, sorry!
