### ISSUE TITLE
[New UI] Display in-progress results in TypeError [...] os.PathLike object

### ISSUE THREAD

**Issue by timdesrochers** [invoke-ai/InvokeAI#822]
Linux x86, Anaconda, CPU-only, on commit c09e81e21be8c77c2b473aa2ca816f97645923ad

Getting a new error now, something related to path, it seems.

```
[Traceback (most recent call last):
  File "/home/user/InvokeAI/backend/server.py", line 795, in generate_images
    image_callback=image_done,
  File "/home/user/InvokeAI/ldm/generate.py", line 413, in prompt2image
    results = generator.generate(
  File "/home/user/InvokeAI/ldm/dream/generator/base.py", line 73, in generate
    image = make_image(x_T)
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/InvokeAI/ldm/dream/generator/txt2img.py", line 34, in make_image
    samples, _ = sampler.sample(
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/InvokeAI/ldm/models/diffusion/ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/site-packages/k_diffusion/sampling.py", line 103, in sample_heun
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigma_hat, 'denoised': denoised})
  File "/home/user/InvokeAI/ldm/models/diffusion/ksampler.py", line 66, in route_callback
    img_callback(k_callback_values['x'], k_callback_values['i'])
  File "/home/user/InvokeAI/backend/server.py", line 678, in image_progress
  File "/home/user/InvokeAI/backend/server.py", line 577, in save_image
    prefix = pngwriter.unique_prefix()
  File "/home/user/InvokeAI/ldm/dream/pngwriter.py", line 20, in __init__
    os.makedirs(outdir, exist_ok=True)
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "/home/user/anaconda3/envs/ldm/lib/python3.9/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int](url)
```

Only when "display in-progress" is enabled. 

_Originally posted by @timdesrochers in https://github.com/invoke-ai/InvokeAI/issues/758#issuecomment-1258784677_

**Comment by psychedelicious** [comment]
Thanks, I neglected to test progress images during some recent changes. Fixed in PR #826.
