### ISSUE TITLE
New webUI not generating / 'Txt2Img' object has no attribute 'free_gpu_mem'

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#831]
**Describe your environment**
- GPU: cpu
- CPU arch: arm
- OS: macOs
- Python: Anaconda
- Branch: development
- Commit: cad237b4c803fe4e9559f8082d08451b8b1831ff

**Describe the bug**
I get this esception on new error:
```

>> Image generation requested: {'prompt': 'Harry Potter funny photography portrait', 'iterations': 1, 'steps': 20, 'cfg_scale': 6.5, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 4163929135, 'seamless': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
Generating:   0%|                                         | 0/1 [00:00<?, ?it/s]


Traceback (most recent call last):
  File "/Users/jakubkolcar/custom/InvokeAI/backend/server.py", line 793, in generate_images
    generate.prompt2image(
  File "/Users/jakubkolcar/custom/InvokeAI/ldm/generate.py", line 411, in prompt2image
    results = generator.generate(
  File "/Users/jakubkolcar/custom/InvokeAI/ldm/dream/generator/base.py", line 72, in generate
    image = make_image(x_T)
  File "/Users/jakubkolcar/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jakubkolcar/custom/InvokeAI/ldm/dream/generator/txt2img.py", line 31, in make_image
    if self.free_gpu_mem and self.model.model.device != self.model.device:
AttributeError: 'Txt2Img' object has no attribute 'free_gpu_mem'

```

**Comment by wbecher** [comment]
Hello, I think this issue is fine now. You can test the branch https://github.com/invoke-ai/InvokeAI/commits/improve-metadata-retrieval mentioned in https://github.com/invoke-ai/InvokeAI/issues/813
