### ISSUE TITLE
preload_models.py fails with on GFPGan with RuntimeError: unexpected EOF, expected 467321 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by georgzoeller** [invoke-ai/InvokeAI#856]
**Describe your environment**
- GPU: cuda/RTX3090
- VRAM: 24
- CPU arch: x86
- OS: Windows
- Python: miniconda
- Branch: main
- Commit: d87bd29a6862996d8a0980c1343b6f0d4eb718b4
- Directec internet connection, no proxy
- 
**Describe the bug**
preload_models fails with Runtime error reliably for me. Feels like some kind of caching issue but I see no way to force cache invalidation?

**To Reproduce**
1. python scripts\preload_models

**Expected behavior**
script to complete

**Screenshots**
See additional context

**Additional context**
```
(ldm) D:\_dev\ai\stable-diffusion-alts\InvokeAI>python scripts\preload_models.py
preloading bert tokenizer...
...success
preloading Kornia requirements (ignore the deprecation warnings)...
...success
preloading CLIP model (Ignore the deprecation warnings)...
...success

Loading models from RealESRGAN and facexlib
Error loading GFPGAN:
Traceback (most recent call last):
  File "scripts\preload_models.py", line 80, in <module>
    FaceRestoreHelper(1, det_model='retinaface_resnet50')
  File "C:\Users\gulbs\miniconda3\envs\ldm\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 99, in __init__
    self.face_det = init_detection_model(det_model, half=False, device=self.device, model_rootpath=model_rootpath)
  File "C:\Users\gulbs\miniconda3\envs\ldm\lib\site-packages\facexlib\detection\__init__.py", line 22, in init_detection_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "C:\Users\gulbs\miniconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\gulbs\miniconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 938, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 467321 more bytes. The file might be corrupted.
```

**Comment by georgzoeller** [comment]
To answer my own issue,

~\miniconda3\envs\ldm\Lib\site-packages\facexlib\weights\detection_Resnet50_Final.pth was corrupted, probably partially downloaded and manually deleting it and rerunning the script fixed it. May be nice though to pass through the ability to force redownload to the script.
