### ISSUE TITLE
Generating variations fails on macOS

### ISSUE THREAD

**Issue by BrentOzar** [invoke-ai/InvokeAI#877]
**Describe your environment**
- GPU: mps
- CPU arch: arm
- OS: macOS
- Python: miniconda
- Branch: development
- Commit: 2cbf1e6 (but started happening at 8c9f2ae or earlier)

**Describe the bug**
When I try to do variations, 

**To Reproduce**
Try to generate variations with the -v command line switch, like this:

`"jumbo shrimp" -S2669402800 -v0.05 -n3`

And I get an error message. Here's an example of where I generate "jumbo shrimp" by itself, but when I try to do variations, it fails:

```
* Initialization done! Awaiting your command (-h for help, 'q' to quit)
dream> "jumbo shrimp"
/Users/brentozar/LocalOnly/Github/InvokeAI/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484612588/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
100%|███████████████████████████████████████████| 50/50 [00:27<00:00,  1.85it/s]
DEBUG:upscaled=False, first_seed=2669402800, use_prefix=None27<00:00,  1.91it/s]
Generating: 100%|█████████████████████████████████| 1/1 [00:27<00:00, 27.59s/it]
>> Usage stats:
>>   1 image(s) generated in 27.81s
Outputs:
[1] outputs/img-samples/000007.2669402800.png: "jumbo shrimp" -s 50 -S 2669402800 -W 512 -H 512 -C 7.5 -A k_lms

dream> "jumbo shrimp" -S2669402800 -v0.05 -n3
100%|███████████████████████████████████████████| 50/50 [00:27<00:00,  1.83it/s]
DEBUG:upscaled=False, first_seed=2669402800, use_prefix=None27<00:00,  1.90it/s]
Generating:   0%|                                         | 0/3 [00:27<?, ?it/s]
Traceback (most recent call last):
  File "/Users/brentozar/LocalOnly/Github/InvokeAI/scripts/dream.py", line 530, in <module>
    main()
  File "/Users/brentozar/LocalOnly/Github/InvokeAI/scripts/dream.py", line 120, in main
    main_loop(gen, opt, infile)
  File "/Users/brentozar/LocalOnly/Github/InvokeAI/scripts/dream.py", line 330, in main_loop
    gen.prompt2image(
  File "/Users/brentozar/LocalOnly/Github/InvokeAI/ldm/generate.py", line 411, in prompt2image
    results = generator.generate(
  File "/Users/brentozar/LocalOnly/Github/InvokeAI/ldm/dream/generator/base.py", line 75, in generate
    image_callback(image, seed, first_seed=first_seed)
  File "/Users/brentozar/LocalOnly/Github/InvokeAI/scripts/dream.py", line 298, in image_writer
    filename, formatted_dream_prompt = prepare_image_metadata(
  File "/Users/brentozar/LocalOnly/Github/InvokeAI/scripts/dream.py", line 429, in prepare_image_metadata
    formatted_dream_prompt = opt.dream_prompt_str(seed=first_seed)
  File "/Users/brentozar/LocalOnly/Github/InvokeAI/ldm/dream/args.py", line 230, in dream_prompt_str
    formatted_variations = ','.join(f'{seed}:{weight}' for seed, weight in (a["variations"]))
KeyError: 'variations'
(ldm) brentozar@MacBook-Pro-16 InvokeAI % 

```
**Additional context**
I've been staying pretty current with the dev branch, and I think it happened around commit 8c9f2ae. It was happening to me on that commit yesterday for the first time, and I came back to it this morning, synced with the latest dev branch to see if it was fixed, and it's still there.

**Comment by psychedelicious** [comment]
Hi @BrentOzar , thanks for reporting. Fixed in https://github.com/invoke-ai/InvokeAI/pull/886

**Comment by BrentOzar** [comment]
Worked perfectly, thanks for the quick fix! Have a great week.
