### ISSUE TITLE
Was working until Sept 30th, now I get an error when I try to generate images

### ISSUE THREAD

**Issue by eadnams22** [invoke-ai/InvokeAI#885]
**Describe your environment**
- GPU: M1 Pro
- VRAM: 32g
- CPU arch: arm
- OS: macOS 12.6
- Python: Anaconda
- Branch: main
- Commit: commit 8e76bc2b5de7cb4b69f758518be38278f6d1099c (HEAD -> main, origin/main, origin/HEAD) # best I could find, there was no 'Merge'

**Describe the bug**
Following mac install guide, everything works (though I needed to use sudo often). It was working fine until yesterday, and It started to crash when generation was requested. Now even with several re-installs and rebuilding the environment I get this:

>> Request to generate with prompt: a rubber duck
>> Setting Sampler to ddim
/Users/evanadnams/opt/InvokeAI/ldm/modules/embedding_manager.py:153: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484612588/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
Traceback (most recent call last):
  File "/Users/evanadnams/opt/InvokeAI/ldm/generate.py", line 303, in prompt2image
    uc, c = get_uc_and_c(
  File "/Users/evanadnams/opt/InvokeAI/ldm/dream/conditioning.py", line 16, in get_uc_and_c
    uc = model.get_learned_conditioning([''])
  File "/Users/evanadnams/opt/InvokeAI/ldm/models/diffusion/ddpm.py", line 828, in get_learned_conditioning
    c = self.cond_stage_model.encode(
  File "/Users/evanadnams/opt/InvokeAI/ldm/modules/encoders/modules.py", line 455, in encode
    return self(text, **kwargs)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/evanadnams/opt/InvokeAI/ldm/modules/encoders/modules.py", line 450, in forward
    z = self.transformer(input_ids=tokens, **kwargs)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/evanadnams/opt/InvokeAI/ldm/modules/encoders/modules.py", line 420, in transformer_forward
    return self.text_model(
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/evanadnams/opt/InvokeAI/ldm/modules/encoders/modules.py", line 373, in text_encoder_forward
    hidden_states = self.embeddings(
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/evanadnams/opt/InvokeAI/ldm/modules/encoders/modules.py", line 276, in embedding_forward
    inputs_embeds = embedding_manager(input_ids, inputs_embeds)
  File "/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/evanadnams/opt/InvokeAI/ldm/modules/embedding_manager.py", line 156, in forward
    embedded_text[placeholder_idx] = placeholder_embedding
NotImplementedError: The operator 'aten::_index_put_impl_' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

Note: 
**To Reproduce**
Generate an image

**Comment by psychedelicious** [comment]
Hi @eadnams22 , based on the error, the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` is not set in your `ldm` environment. 

This variable tells the system to use your CPU for some operations which are not yet supported on M1 Macs. However, it should be automatically set when you activate the environment e.g. `conda activate ldm`. 

Can you please try:
- activate the environment e.g. `conda activate ldm`
- run this to explicitly set the variable `export PYTORCH_ENABLE_MPS_FALLBACK=1`
- run the script e.g. `python scripts/dream.py`
- try to generate an image normally

What do you get after that? 

PS: You shouldn't need to use `sudo` at any point - that's an indication that something went sideways at some point during setup.

**Comment by eadnams22** [comment]
It is activated. First thing I tried, as per the warnings.

(ldm) evanadnams@eta-m1bp-2021 InvokeAI % echo $PYTORCH_ENABLE_MPS_FALLBACK 
1
(ldm) evanadnams@eta-m1bp-2021 InvokeAI %

**Comment by eadnams22** [comment]
I've also uninstalled and removed everything including git and brew, and rebuild from scratch, same issue.

Thankfully my windows install works perfectly, even been adding new opjects successfully, but would be nice to have working on my mac as well.

**Comment by psychedelicious** [comment]
Thanks for trying all that. 

The only thing else I can think to try is to make a new user account and try there. If sudo is needed there, there must be something wonky deeper in your macOS installation, and I'd guess that's pointing to the same root cause. 

Sorry I can't be more helpful - maybe somebody else will have other ideas.

**Comment by eadnams22** [comment]
> Thanks for trying all that.
> 
> The only thing else I can think to try is to make a new user account and try there. If sudo is needed there, there must be something wonky deeper in your macOS installation, and I'd guess that's pointing to the same root cause.
> 
> Sorry I can't be more helpful - maybe somebody else will have other ideas.

Thanks! Yeah, was gonna try a new user next. Any advice on which folders to put things into?

**Comment by psychedelicious** [comment]
I've got everything organized in ~/Documents, if that's what you mean.

Also, while conda worked fine for me, mamba does things a bit quicker and didn't need an environment variable to prevent environment creation from stalling while installing pip dependencies. I installed it with `brew install --cask mambaforge`.

**Comment by lstein** [comment]
Have you tried `rm -rf /opt/anaconda3` and then reinitializing anaconda?

**Comment by lstein** [comment]
Any luck?

**Comment by eadnams22** [comment]
> Have you tried `rm -rf /opt/anaconda3` and then reinitializing anaconda?

I have tried that, for now I'm using it from my windows machine, will try again with the mac when I have some more time.

**Comment by psychedelicious** [comment]
Hi @eadnams22 , did you ever get this figured out?

**Comment by psychedelicious** [comment]
If you get back to this an still have issues on the latest release, please let us know. Closing as no activity in a while.
