### ISSUE TITLE
img2img missing 2 required positional arguments: 'width' and 'height' [macOS] [M1]

### ISSUE THREAD

**Issue by ppogorze** [invoke-ai/InvokeAI#935]
- GPU: M1
- CPU arch: arm
- OS: MacOS
- Python: miniconda
- Branch: development
- Commit: 4c482fe24ad6ea10f6ccdff0072d154927189e34

When trying to use img2img, via web ui or dream cli:

`loaded input image of size 512x768 from ./init-images/sample.jpg
Traceback (most recent call last):
  File "/Users/pp/Desktop/InvokeAI/scripts/dream.py", line 562, in <module>
    main()
  File "/Users/pp/Desktop/InvokeAI/scripts/dream.py", line 120, in main
    main_loop(gen, opt, infile)
  File "/Users/pp/Desktop/InvokeAI/scripts/dream.py", line 337, in main_loop
    gen.prompt2image(
  File "/Users/pp/Desktop/InvokeAI/ldm/generate.py", line 401, in prompt2image
    init_image,mask_image = self._make_images(
  File "/Users/pp/Desktop/InvokeAI/ldm/generate.py", line 629, in _make_images
    init_image   = self._create_init_image(image)                   # this returns a torch tensor
TypeError: Generate._create_init_image() missing 2 required positional arguments: 'width' and 'height'
(ldm) 
`

Same for 512x512.
Thanks.

**Comment by lstein** [comment]
Thank you for the bug report. This is fixed in the release candidate, which you can check out as `release-candidate-2`
