### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

### ISSUE THREAD

**Issue by robert-dm** [invoke-ai/InvokeAI#942]
I am using Mac M1 and followed all steps in the guide but getting this error

(ldm) robert@Robertos-MBP InvokeAI % python3 scripts/dream.py

Traceback (most recent call last):
  File "/Users/robert/Documents/workspace/InvokeAI/scripts/dream.py", line 12, in <module>
    import ldm.dream.readline
  File "/Users/robert/miniconda3/envs/ldm/lib/python3.9/site-packages/ldm.py", line 20
    print self.face_rec_model_path 
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?
(ldm) robert@Robertos-MBP InvokeAI %

**Comment by lstein** [comment]
The file `ldm.py` is actually not a part of the InvokeAI package. Have you installed other versions of Stable Diffusion? If so, could you please delete the `ldm` environment and start over?

If this doesn't work, then we have a really weird problem.

**Comment by robert-dm** [comment]
Hi @lstein thanks for your reply, you are correct, this is not my first installation of Stable Diffusion. 
I have removed previous installations and also miniconda3 folder, started from scratch the steps and worked.
Thank you
