### ISSUE TITLE
Data type issue

### ISSUE THREAD

**Issue by smashedProton** [invoke-ai/InvokeAI#944]
**Describe your environment**
- GPU: [amd/cpu]
- VRAM: 2GB 
- CPU arch: [x86/arm]
- OS: [Linux]
- Python: [Anaconda]
- Commit:  commit 8a8be92eac17e0ef699528157596b2336bdee532

**Describe the bug**
I am experiencing an issue upon running the program on a prompt.  I am using an AMD card with the --full_precision switch when launching.  It looks like it has an issue with data type that is different than the issue with half precision in amd cards.

dream> holy hand grenade of antioch
  0%|                                                                                                                                                            | 0/50 [00:18<?, ?it/s]
Generating:   0%|                                                                                                                                                 | 0/1 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "/home/garrett/repos/InvokeAI/ldm/generate.py", line 319, in prompt2image
    results = generator.generate(
  File "/home/garrett/repos/InvokeAI/ldm/dream/generator/base.py", line 70, in generate
    image = make_image(x_T)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/dream/generator/txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/models/diffusion/ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/garrett/repos/InvokeAI/src/k-diffusion/k_diffusion/sampling.py", line 251, in sample_lms
    x = _lms(model,x,sigmas,i,s_in,ds,callback,order=order,extra_args=extra_args)
  File "/home/garrett/repos/InvokeAI/src/k-diffusion/k_diffusion/sampling.py", line 267, in _lms
    denoised = model(x, sigmas[index] * s_in, **extra_args)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/models/diffusion/ksampler.py", line 16, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/garrett/repos/InvokeAI/src/k-diffusion/k_diffusion/external.py", line 100, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/home/garrett/repos/InvokeAI/src/k-diffusion/k_diffusion/external.py", line 126, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/models/diffusion/ddpm.py", line 1440, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/models/diffusion/ddpm.py", line 2148, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/modules/diffusionmodules/openaimodel.py", line 806, in forward
    h = module(h, emb, context)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/modules/diffusionmodules/openaimodel.py", line 88, in forward
    x = layer(x, context)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/modules/attention.py", line 346, in forward
    x = block(x, context=context)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/garrett/repos/InvokeAI/ldm/modules/attention.py", line 296, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/home/garrett/repos/InvokeAI/ldm/modules/diffusionmodules/util.py", line 157, in checkpoint
    return func(*inputs)
  File "/home/garrett/repos/InvokeAI/ldm/modules/attention.py", line 300, in _forward
    x = self.attn1(self.norm1(x)) + x
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/home/garrett/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type BFloat16 but found Float

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 18.27s
Outputs:

**Comment by mh-dm** [comment]
This is in main and since there were a lot of related changes in development, it might already be resolved. Could you please try the development branch? Specifically try the development branch without any flags, and if that fails try with `--precision=float32`.

**Comment by thj9332** [comment]
I also encounter the same issue,using the latest version

**Comment by mh-dm** [comment]
@thj9332 I see you opened #997 which is related but a different issue.

**Comment by psychedelicious** [comment]
No response, closing
