### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by thj9332** [invoke-ai/InvokeAI#997]
**Describe your environment**
- GPU: [NVIDIA GeForce RTX 3060 Ti]
- VRAM: [8050 MB]
- CPU arch: [ 12th Gen Intel(R) Core(TM) i7-12700 ]
- OS: [Windows]
- Python: [Anaconda]
- Branch: [main] 

**Describe the bug** 
enter text and draw,but fail with RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

**Expected behavior**
Expect to successfully draw pictures

**result**
dream> a fantastic alien landscape
Traceback (most recent call last):
  File "e:\stablediffusion\invokeai-main\ldm\generate.py", line 306, in prompt2image
    log_tokens=self.log_tokenization
  File "e:\stablediffusion\invokeai-main\ldm\dream\conditioning.py", line 16, in get_uc_and_c
    uc = model.get_learned_conditioning([''])
  File "e:\stablediffusion\invokeai-main\ldm\models\diffusion\ddpm.py", line 829, in get_learned_conditioning
    c, embedding_manager=self.embedding_manager
  File "e:\stablediffusion\invokeai-main\ldm\modules\encoders\modules.py", line 455, in encode
    return self(text, **kwargs)
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\stablediffusion\invokeai-main\ldm\modules\encoders\modules.py", line 450, in forward
    z = self.transformer(input_ids=tokens, **kwargs)
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\stablediffusion\invokeai-main\ldm\modules\encoders\modules.py", line 427, in transformer_forward
    embedding_manager=embedding_manager,
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\stablediffusion\invokeai-main\ldm\modules\encoders\modules.py", line 399, in text_encoder_forward
    return_dict=return_dict,
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\stablediffusion\invokeai-main\ldm\modules\encoders\modules.py", line 324, in encoder_forward
    output_attentions=output_attentions,
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\transformers\models\clip\modeling_clip.py", line 316, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\normalization.py", line 190, in forward
    input, self.normalized_shape, self.weight, self.bias, self.eps)
  File "C:\Users\陶洪钧\AppData\Roaming\Python\Python37\site-packages\torch\nn\functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 0.02s
Outputs:

**Comment by lstein** [comment]
@mh-dm Could you have a look at this? This sounds like a precision-setting issue.

**Comment by mh-dm** [comment]
@thj9332 As per the instructions in https://github.com/invoke-ai/InvokeAI#hardware-requirements could you please try with `--precision=float32` and report back?

Overall it's strange since I thought GeForce RTX 3060 Ti had Half / float16 support.

**Comment by lstein** [comment]
@thj9332 If the problem is still persistent, could you post the log of your output with `--precision=float32` ?

**Comment by psychedelicious** [comment]
No response, closing

**Comment by jk779** [comment]
just FYI: Had the same problem, changing from float16 to float32 resolved it :)
